### ISSUE TITLE
Create an API to send a request.

### ISSUE THREAD

**Issue by m-murad** [anitab-org/mentorship-backend#10]
## Description
Create an API so that a user can send another user a request mentor/mentee relationship request.

### Update
- [x] A user is able to send a request to any user who is not in a mentor/mentee relationship.
- [x] Define constraints before actually creating the data model

## Definition of Done
- [x] PR should be sent to the `gsoc18-code` branch
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
10 hours

**Comment by isabelcosta** [comment]
**Logic in mind**

**Initial fields:** `action_user_id`, `mentor_id`, `mentee_id`, `start_date`, `end_date` and `notes`.

**Constraints:**
- `action_user_id` has to match with `mentee_id` and `mentor_id`;
- `mentor_id` has to be different from `mentee_id`;
- `start_date` < `end_date`
- Set a minimum for this interval [`start_date`:`end_date`]?
- `start_date` after "date.now()"
- Check if `mentor_id` is available to mentor
- Check if `mentee_id` is available to be a mentee
- Check if the users are (1) blocked; (2) with unverified emails; (3) available for the roles that are requested of them

**Comment by isabelcosta** [comment]
**Updated constraints:**

- `user_id` has to match with `mentee_id` and `mentor_id`;
- `mentor_id` has to be different from `mentee_id`;
- `now` < `end_date`
- Minimum ralation duration: `end_date` - `now` > 4 weeks ~ 1 month
- Maximum ralation duration: `end_date` - `now` < 24 weeks ~ 6 months
- `start_date` = `creation_date`
- User with `mentor_id` has to be available to mentor
- User with `mentee_id` has to want to be mentored
- Users involved can't be involved in an accepted relation (active/on going)
