### ISSUE TITLE
Remove .github/ISSUE_TEMPLATE folder

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#1013]
## Description

As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Update [Required]
- [ ] Delete `.github/ISSUE_TEMPLATE`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by s4-2** [comment]
I have read the doc provided in the above link but I was unable to understand.
As I am new in contributing, so can you please help me out what I should do to contribute.

**Comment by Sejalcodes** [comment]
can i work on this issue?

**Comment by saurabh-shetty** [comment]
Can I work on this issue?

**Comment by epicadk** [comment]
Since @s4-2 commented first I will ask if they'd like to work on this. If there is no response I'll assign @Sejalcodes .

**Comment by saurabh-shetty** [comment]
Let @s4-2 and @Sejalcodes try fixing this. If they are not able to fix, I have already submitted a pull request you can review that.

**Comment by saurabh-shetty** [comment]
Okay no problem. If they are not able to solve the issue try considering my
PR.

**Comment by s4-2** [comment]
Thank you @epicadk  for giving me this chance to fix it. But can anyone guide me as this is my first contribution. I really want to do, but little confuse where from start. 
Thank you

**Comment by epicadk** [comment]
> Thank you @epicadk for giving me this chance to fix it. But can anyone guide me as this is my first contribution. I really want to do, but little confuse where from start.
> Thank you

@s4-2 That's okay we all have to start somewhere. You can ask doubts here or on zulip . We have a great community that is always willing to help. : ) I'll assign it to you I'm sure you can figure it out or ask for some help . Goodluck : )

**Comment by s4-2** [comment]
Thank you @epicadk. I will definitely try my best. I want to know what I have to do or learn to fix it, I just want to start that is why need some help.

**Comment by s4-2** [comment]
Thank You @epicadk .

**Comment by epicadk** [comment]
> Thank you @epicadk. I will definitely try my best. I want to know what I have to do or learn to fix it, I just want to start that is why need some help.

You don't have to learn anything. You can setup the project using the instructions given in the readme and then you just have to delete the specified folder. If you are facing problems feel free to ask on zulip or over here.

**Comment by s4-2** [comment]
Please check @epicadk  I have created a PR . Please guide me if I need to do some correction.
Thank You

**Comment by epicadk** [comment]
> Please check @epicadk I have created a PR . Please guide me if I need to do some correction.
> Thank You

You haven't created a PR on this repository but instead on your fork. Please create a pull request on this repo.

**Comment by s4-2** [comment]
Okay.

**Comment by s4-2** [comment]
Please check @epicadk if  I have successfully created PR or not . I have also merged it because it was showing me the option to merge. Please guide me if now also I haven't created a PR.

**Comment by isabelcosta** [comment]
@s4-2 when creating a PR you have to make sure the **"base repository" mentions "anitab-org" repo**, take a look at this, which showed up when I went to your fork and tried to create a pull request there:

![image](https://user-images.githubusercontent.com/11148726/109393635-cbc92600-791a-11eb-8d5f-30a1f97b4b9e.png)

Is it clearer now?

**Comment by s4-2** [comment]
Yes I understood. Thank you for your guidance

**Comment by s4-2** [comment]
Thank You @isabelcosta . I have created a PR according to your guidance. Its now asking for Review is required.

**Comment by epicadk** [comment]
> Please check @epicadk if I have successfully created PR or not . I have also merged it because it was showing me the option to merge. Please guide me if now also I haven't created a PR.

Hey sorry I have my tests so I couldn't respond. Glad everything worked out. Good work : ).

**Comment by isabelcosta** [comment]
> Hey sorry I have my tests so I couldn't respond. Glad everything worked out. Good work : ).

Totally ok @epicadk that is why we are in a community so that multiple people can help ;) hope tests went well 💪🏾

**Comment by s4-2** [comment]
Sorry for the late response, I have fixes the description with issue no. #1013.
Thank you  @vj-codes for your help :)

**Comment by epicadk** [comment]
Closing as #1021 was merged.

**Comment by devkapilbansal** [comment]
Reopening as ISSUE_TEMPLATE file is available in `.github` folder.

We need to remove this [file](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE.md) as well.

Cc:- @epicadk @isabelcosta

**Comment by vj-codes** [comment]
@devkapilbansal also the link needs to be updated under bug_report in contributing.md 
it returns a 404 error right now due to the merging of the previous PR .

**Comment by Sejalcodes** [comment]
Can I work on this issue?

**Comment by devkapilbansal** [comment]
@Sejalcodes have you contributed before in the project??

**Comment by Sejalcodes** [comment]
@devkapilbansal No, I haven't. I am a beginner. This will be my first PR.

**Comment by vj-codes** [comment]
Assigning you @Sejalcodes 
Happy documenting!
Make sure to remove the templates from .github folder and update the link in contributing.md as mentioned in comments above :)

**Comment by Sejalcodes** [comment]
I have removed the ISSUE_TEMPLATE file from the .github folder and made a PR for the same. Could you please check and inform if it's fine? Also, I wanted to know that the link in contributing.md needs to be updated to which new link?

**Comment by epicadk** [comment]
Can you please link this issue to the pr?

**Comment by Sejalcodes** [comment]
@epicadk Oh okay, I linked it. Is it fine now?

**Comment by vj-codes** [comment]
@Sejalcodes in contributing.md , under last point update bug_report  to this link https://github.com/anitab-org/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Sejalcodes** [comment]
I "THINK" I have completed the task. Can someone please confirm? :)

**Comment by vj-codes** [comment]
@Sejalcodes yes you have 🎉 
Although you've created 2 PRs for the same issue, it's advisable to do it in one only.
It's okay for now but remember while working on future issues :)

**Comment by Sejalcodes** [comment]
Oh my god, thankyou so much for all the help, everyone!
@vj-codes Right, I didn't know how that, will make sure not to repeat this in the future, thankyou!
