### ISSUE TITLE
Doc: Add the "bit" branch to the "Branches" section on README.md

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#1027]
### Is your feature request related to a problem? Please describe.
There is a newly created branch `bit` for ms-backend version specific to BridgeInTech project (https://github.com/anitab-org/mentorship-backend/tree/bit). The contributors need to be made aware of this so they can contribute to the BIT-MS integration related issues.

### Describe the solution you'd like
The `bit` branch needs to be mentioned on the Readme.md under `Branches` [section](https://github.com/anitab-org/mentorship-backend/tree/bit#branches) to make contributors aware that there are more issues specific to BIT-MS integrations that they work on.
<img width="748" alt="Screen Shot 2021-03-03 at 9 46 33 am" src="https://user-images.githubusercontent.com/29667122/109726863-7f763280-7c07-11eb-9068-30e737c643ef.png">

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by Aayush-hub** [comment]
@mtreacy002 Can I take up this issue??

**Comment by epicadk** [comment]
> @mtreacy002 Can I take up this issue??

You are already assigned a different first timer issue : ).

**Comment by Aayush-hub** [comment]
@epicadk @vj-codes Yes, but I have solved that and made a PR. Hope I could work on it now.

**Comment by vj-codes** [comment]
@Aayush-hub you can't be assigned to this as you have made your first contribution through #1034 
Do go through other available issues :)

**Comment by keshavagarwal17** [comment]
@mtreacy002 I would like to work on this issue.

**Comment by epicadk** [comment]
@The-Keshav-Agarwal assigning you. Good luck 👍: )
