### ISSUE TITLE
Feat : Create Makefile

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#1040]
### Is your feature request related to a problem? Please describe.
 
As a developer having a [Makefile](https://makefiletutorial.com/) will make it easier to run different commands.

### Describe the solution you'd like

Create a Makefile containing the commands to builds and test the application. 

### Additional context

You could also include additional ones such as format and running the app with docker

**Comment by isabelcosta** [comment]
Which are the commands you would like to have there?
How compatible is this with contributors who have Windows file?

Is this an alternative https://flask.palletsprojects.com/en/1.1.x/cli/?

Example:
- run tests
- run flake8
- etc


Anddd thank you so much for bringing this conversation to today's Mentorship System sync up session 🙏🏾

**Comment by epicadk** [comment]
@isabelcosta Yes this would help with the examples you mentioned. The alternative you mentioned doesn't seem to allow running black and running tests so I guess a Makefile would be a better alternative. I think any c/c++ compiler would be sufficient to run make so it should be possible in linux and macos without much hassel however windows contributors would need to install mingw or other such software.
