### ISSUE TITLE
Tests: Add tests for User file

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#1049]
## Description
Coverage ensures that the code we have in our project is tested and working fine. But `app/api/dao/user.py` has least coverage percentage, i.e. 85% till now dropping overall coverage to 93 %

We need to ensure that code changes done are covered by test cases correctly.

### Update [Required]
- [ ] Ensure all cases are covered and get 100% on codecov for this particular file.
See codecov reports [here](https://codecov.io/gh/anitab-org/mentorship-backend/src/develop/app/api/dao/user.py)

### Enhancement to Update [Optional]
- [ ] Find other test cases that can be helpful to cover to ensure app is working fine.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by 17sushmita** [comment]
May I work on this issue?

**Comment by epicadk** [comment]
Good luck 😄 @17sushmita .

**Comment by vj-codes** [comment]
@17sushmita any updates?

**Comment by 17sushmita** [comment]
> @17sushmita any updates?

I'm working on it

**Comment by devkapilbansal** [comment]
@17sushmita are you working on this?

**Comment by 17sushmita** [comment]
> @17sushmita are you working on this?

I'm sorry, I was busy with some other commitments. I can work on it in next week. Meanwhile, If anyone is interested to work on it. feel free to assign them.

**Comment by devkapilbansal** [comment]
Any updates on this?

**Comment by vj-codes** [comment]
@17sushmita unassigning you due to inactivity, let us know if you would like to continue again :)

**Comment by Aryamanz29** [comment]
@devkapilbansal  Should I work on this?

**Comment by KushalBeniwal** [comment]
@devkapilbansal @vj-codes I would like to work on this issue.

**Comment by vj-codes** [comment]
Assigning you @KushalBeniwal 
Happy coding!
