### ISSUE TITLE
Add Docusaurs link to README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#1062]
## Description

Add https://anitab-org.github.io/mentorship-backend to link README.
Perhaps add a badge for this, along with adding this to the documentation section.

### Update [Required]
- [ ] Add https://anitab-org.github.io/mentorship-backend to README

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 min

**Comment by Bhavani-Somanchi** [comment]
Hi Isabel! This link is already available in the documentation section(The first line). If a badge is needed can you assign it to me. Thank you.

**Comment by Bhavani-Somanchi** [comment]
@isabelcosta  Hi Isabel! This link is already available in the documentation section(The first line). If a badge is needed can you assign it to me. Thank you.

**Comment by isabelcosta** [comment]
@Bhavani-Somanchi thank you for confirming it 🤗 I think adding a badge for docusaurus/documentation would be amazing :) I will assign this to you.
I will remove the first timers only label, as this will be good for newcomers

**Comment by vj-codes** [comment]
@isabelcosta this was the first-timers issue and @Bhavani-Somanchi has already contributed to the repository before
Ideally, the assignment is removed but a PR has already been made now should it be made available again or not
@anitab-org/mentorship-maintainers thoughts?

**Comment by isabelcosta** [comment]
@vj-codes I knew about it, I decided here to make it an exception since this can help newcomers finding documentation faster. And no one else had claimed it before. That is what I meant here https://github.com/anitab-org/mentorship-backend/issues/1062#issuecomment-817306864

How does it sound?
