### ISSUE TITLE
Update steps in how to test a PR doc

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#1072]
## Description
As a developer,
I need the quality assurance doc of how to test a PR with correct steps,
so that it'll help everyone in testing PRs locally.
We shouldn't be cloning and checking out the author's fork we can directly use

` git fetch origin pull/ID/head:BRANCHNAME`

Read [this reference doc](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) for more info

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10mins

**Comment by vj-codes** [comment]
@epicadk @devkapilbansal thoughts?

**Comment by devkapilbansal** [comment]
@vj-codes this seems valid to me

**Comment by keshavgbpecdelhi** [comment]
Sir pls assign this to me🙏

**Comment by epicadk** [comment]
@keshavgbpecdelhi assigning you. Good luck. No need to say sir.

**Comment by keshavgbpecdelhi** [comment]
I am unable to understand what to do and where to do :/
Better Question frame :
Where I have to do the changes in README.md !?
What to do in that ?

Asking this after reading these docs and issue :
https://github.com/anitab-org/mentorship-backend/issues/1072
https://github.com/anitab-org/mentorship-backend/blob/develop/docs/test-pr-guide.md
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Comment by devkapilbansal** [comment]
HI @keshavgbpecdelhi 
You need to update point 5 for pulling repository locally in test-pr-guide doc you mentioned above.

**Comment by keshavgbpecdelhi** [comment]
Any Improvement related suggestion?
