### ISSUE TITLE
Use python 3.9 in GitHub actions.

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#1078]
### Is your feature request related to a problem? Please describe.

Currently we run github actions on python 3.6.

### Describe the solution you'd like

Use a build matrix to run on version 3.7 , 3.9 (maybe `python:latest` for future releases?)

### Additional context

https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

**Comment by epicadk** [comment]
@vj-codes related to issues you have been working on ,would you like to work on this?

**Comment by vj-codes** [comment]
@epicadk sure
