### ISSUE TITLE
Registration happens when name is a combination of numeric characters

### ISSUE THREAD

**Issue by r00pal** [anitab-org/mentorship-backend#108]
**Describe the bug**
The program sents a confirmation email even when the name is given as a combination of numeric characters.

Related to #86 

**To Reproduce**
1. Go to 'Register'
2. Set 'name' to any combination of digits greater than the minimum length, i.e 1

**Expected behavior**
There should be an error saying that name is invalid

**Screenshots**

![image](https://user-images.githubusercontent.com/19304435/43196863-113299a4-9027-11e8-9f49-fa2298666ed9.png)

![image](https://user-images.githubusercontent.com/19304435/43196880-1d4dee5a-9027-11e8-8487-fd5c2d4fd6d2.png)

**Additional context**
Not Required

**Comment by isabelcosta** [comment]
@sys-bot approve
