### ISSUE TITLE
Use UUID as userID.

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#1082]
### Is your feature request related to a problem? Please describe.

Currently we use an autoincrement id as the userid. 

### Describe the solution you'd like

Change this to UUID. Migrate existing userids to UUID as well.

### Additional Context 

> UUID values do not expose the information about your data so they are safer to use in a URL. For example, if a customer with id 10 accesses his account via http://www.example.com/customers/10/ URL, it is easy to guess that there is a customer 11, 12, etc., and this could be a target for an attack.

from https://www.mysqltutorial.org/mysql-uuid/

**Comment by epicadk** [comment]
On hold as it needs @isabelcosta's approval.

**Comment by isabelcosta** [comment]
@epicadk if you could add to the ticket the why, that would be awesome. I kind of know this is a better approach, but for a newcomer to learn in case they don't know. Thank you for raising this 🚀 
Also, so this will require migration right 🤔  ... such a big change to the database. How can we do this, with pre existing data? Perhaps we should initiate all again 🤔  Also, this is for user id, do you also want to do this for any kind of ID? mentorship ID, task? let me know what you think

**Comment by epicadk** [comment]
> @epicadk if you could add to the ticket the why, that would be awesome. I kind of know this is a better approach, but for a newcomer to learn in case they don't know. Thank you for raising this 🚀

Sure. 
> Also, so this will require migration right 🤔 ... such a big change to the database. How can we do this, with pre existing data? Perhaps we should initiate all again 🤔 Also, this is for user id, do you also want to do this for any kind of ID? mentorship ID, task? let me know what you think

We can generate a random uuid for each existing user.I think we can have separate issues for those.

**Comment by epicadk** [comment]
Also can I work on this?

**Comment by epicadk** [comment]
I'd like to work on this.

**Comment by epicadk** [comment]
We don't really need this. Kind of an overkill. If we have proper rate limiting we should be good.

**Comment by isabelcosta** [comment]
@epicadk you're so thoughtful. I feel like it could be a good change, but I also agree that at this point we don't need this. So should be good. I just looked at your PR, and it's kind of interesting. Thank you so much for handling this 🤗
