### ISSUE TITLE
Create an API get a list of all relationship requests

### ISSUE THREAD

**Issue by m-murad** [anitab-org/mentorship-backend#11]
## Description
A user should be able to get a list of all the relationship requests. This should be specific to a user.

### Update [Required]
- [x] Get a list of all previous relationships.
- [x] Get the current relationship.
- [x] Get a list of relationship requests. (All three should be different APIs)

## Definition of Done
- [x] PR should be sent to the `gsoc18-code` branch
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
10 hours

**Comment by isabelcosta** [comment]
**As discussed in project weekly meeting:**

- Get a list of all previous relationships.
All states and `end_date` has passed

- Get the current relationship.
`ACCEPTED` state

- Get a list of relationship requests. (All three should be different APIs).
`PENDING` and the `end_date` has not passed yet

These are all auth protected and specific of the authenticated user
