### ISSUE TITLE
Mentorship Relation Reject a request Quality Assurance 

### ISSUE THREAD

**Issue by Dilu9218** [anitab-org/mentorship-backend#110]
## Description
This issue is to test all the test cases in the Mentorship Relation Reject Request in the Quality Assurance document below. This issue can be worked by many contributors. Refer this issue when you find a bug in the following test cases.

## Test Cases

You can check the following document for test cases: [Quality Assurance Google Docs](https://docs.google.com/document/d/1kStdMWK9K93zlsjIFbU2fODE98NK3a4nJGtYtBEyrlo/)

**Service:**  PUT /mentorship_relation/{request_id}/reject

| Test Case     | Outcome |
| ------------- | ------------- |
| Having User1 sending a request to User2, User2 rejects this request | Success |
| Having User1 sending a request to User2, User1 rejects this request | Fail |
| User1 rejects a mentorship relation which the User1 is not involved with | Fail |

## Definition of Done
- [ ] At least one test case tested.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes for test case (approximation)

**Comment by isabelcosta** [comment]
@sys-bot approve
