### ISSUE TITLE
Mentorship Relation Cancel a Relation Quality Assurance

### ISSUE THREAD

**Issue by Dilu9218** [anitab-org/mentorship-backend#111]
## Description
This issue is to test all the test cases in the Mentorship Relation Cancel a Relation in the Quality Assurance document below. This issue can be worked by many contributors. Refer this issue when you find a bug in the following test cases.

## Test Cases

You can check the following document for test cases: [Quality Assurance Google Docs](https://docs.google.com/document/d/1kStdMWK9K93zlsjIFbU2fODE98NK3a4nJGtYtBEyrlo/)

**Service:** PUT /mentorship_relation/{request_id}/cancel

| Test Case     | Outcome |
| ------------- | ------------- |
| User1 (sent the request) cancels a mentorship relation that it is currently involved with User2 (the relation is in an ACCEPTED state) | Success |
| User2 (received the request) cancels a mentorship relation that it is currently involved with User1 (the relation is in an ACCEPTED state)  | Success |
| User1 cancel a mentorship relation which the User1 is not involved with | Fail |

## Definition of Done
- [ ] At least one test case tested.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes for test case (approximation)

**Comment by isabelcosta** [comment]
@sys-bot approve

**Comment by isabelcosta** [comment]
@sys-bot approve
