### ISSUE TITLE
Change the Comments API to provide the user details along with the comments

### ISSUE THREAD

**Issue by justdvnsh** [anitab-org/mentorship-backend#1110]
### Is your feature request related to a problem? Please describe.
The comment API right now provides the userID as a parameter in the response. It needs to change to provide the user details such as username and email along with the comment response. A complete discussion can be found here. https://github.com/anitab-org/mentorship-android/pull/1129

### Describe the solution you'd like
User details come along with the comments response

### Additional context
A complete discussion can be found here. https://github.com/anitab-org/mentorship-android/pull/1129

**Comment by epicadk** [comment]
@justdvnsh do you want to work on this?

**Comment by justdvnsh** [comment]
@epicadk I don't think I'd be able to work on this. Would not be able to give in the time for this issue.

**Comment by RiddhiAthreya** [comment]
@epicadk can I try working on this?

**Comment by RiddhiAthreya** [comment]
@justdvnsh can you tell me the exact endpoint you want changed?

**Comment by RiddhiAthreya** [comment]
@justdvnsh @epicadk 
About the structure of the response : 

- So do I include both the users in the task - the mentor and the mentee details in the response JSON? 

- Right now it's a list of comment objects being returned. I'm thinking of having a list with 2 key value pairs :-
         
          - comments :- value will contain a list of comment objects

          - users :-  value will contain a list with 2 key-value pairs -  user_id being the key and value being the details of the user

**Comment by epicadk** [comment]
Sure that works or you could change the comment response to include the corresponding user within the comment. I think this way makes more sense.

**Comment by RiddhiAthreya** [comment]
@epicadk but wouldn't that be sending a lot of redundant information? Since there are only 2 users involved, I'd be sending the same info over and over again. Response might become unnecessarily big.

**Comment by devkapilbansal** [comment]
Duplicate issue #685
