### ISSUE TITLE
Mentorship Relation Delete Request Quality Assurance 

### ISSUE THREAD

**Issue by Dilu9218** [anitab-org/mentorship-backend#112]
## Description
This issue is to test all the test cases in the Mentorship Relation Delete Request in the Quality Assurance document below. This issue can be worked by many contributors. Refer this issue when you find a bug in the following test cases.

## Test Cases
You can check the following document for test cases: [Quality Assurance Google Docs](https://docs.google.com/document/d/1kStdMWK9K93zlsjIFbU2fODE98NK3a4nJGtYtBEyrlo/)

**Service:** DELETE /mentorship_relation/{request_id}

| Test Case     | Outcome |
| ------------- | ------------- |
| A user that creates a mentorship request X deletes this mentorship request X | Success |
| A user that creates a mentorship request X deletes this mentorship request X (without token being sent in Authorization Header)  | Fail |
| A user that did not create mentorship request X tries to deletes mentorship request X | Fail |
| A user that tries to delete mentorship request X that does not exist (i.e., request_id does not exist in the system) | Fail |

## Definition of Done
- [ ] At least one test case tested.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes for test case (approximation)

**Comment by isabelcosta** [comment]
@sys-bot approve
