### ISSUE TITLE
Name should only contain alphabetic characters

### ISSUE THREAD

**Issue by r00pal** [anitab-org/mentorship-backend#113]
## Description
As a developer,
I need to restrict names of users to alphabetic characters,
so that I can avoid invalid users.

Currently, numeric or special characters alone can be used to substitute for the name field, which increases anonymity. Name field should only be allowed to have alphabetic characters

Related to bug #108 

### Update [Required]
- [ ] Add a name regex and create a simple function to check this on [app/utils/validation_utils.py](https://github.com/systers/mentorship-backend/blob/gsoc18-code/app/utils/validation_utils.py)
- [ ] Add validation on both register and update profile validation functions: `validate_user_registration_request_data()` and `validate_update_profile_request_data()`
- [ ] Return valid error message like "Name field is invalid". Example: https://github.com/systers/mentorship-backend/blob/gsoc18-code/app/api/validations/user.py#L94
- [ ] Add tests for this

These are some suggestions ^^

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by r00pal** [comment]
@sys-bot approve

**Comment by isabelcosta** [comment]
@sys-bot approve

**Comment by isabelcosta** [comment]
@roopalJazz is this issue to solve the #108 bug? can you follow this template -> https://github.com/systers/mentorship-backend/issues/97, with some more description? or I can create one with more implementation detail

**Comment by GeVic** [comment]
@sys-bot claim

**Comment by GeVic** [comment]
Hey @isabelcosta, can you assign it to me?

**Comment by isabelcosta** [comment]
@GeVic yes, I will just fix the description and assign this to you

**Comment by isabelcosta** [comment]
@GeVic Do you belong to systers open source on Github? because I cannot assign you until you are. you can do it so by doing on slack ith /sysbot_invite

**Comment by isabelcosta** [comment]
You can start working on the issue but it would be great to officially assign this to you. But its totally possible for you to send the PR so go for it ;) @GeVic

**Comment by GeVic** [comment]
Yeah, I do belong to systers-opensource @isabelcosta

**Comment by GeVic** [comment]
@isabelcosta Should I create separate file itself for testing name validations? As it is done for username validation.

**Comment by isabelcosta** [comment]
@GeVic for the function with the name regex yes, to have in one file different combinations for a name, and all related to that util function. Regarding the community, you are in the slack, but you're not a member of the Systers Github community. You can join by asking an admin or a member with capabilities to do so, but you can also type `/sysbot_invite` on Slack and you'll receive an email to join the organization on GitHub

**Comment by GeVic** [comment]
@isabelcosta I would have to ask may then? Actually /sysbot_invite is not processing the request as of now.

**Comment by isabelcosta** [comment]
@GeVic I think @mayburgos could take care of that, yes, but have you reported that potential bug to @sammy1997 ? @sammy1997 the command `/sysbot_invite` is not working? Either way, you can start working on this issue, you don't need to be assigned to send the PR ;)

**Comment by sammy1997** [comment]
Actually it's not working because the bot account requires a higher level of permission. It was being discussed in this weekly meeting @isabelcosta . You were present then! Prachi will be discussing it in the Admin meet.

**Comment by isabelcosta** [comment]
@sammy1997 yes I was :P I must have forgotten. No problem! @GeVic you can still work on this
