### ISSUE TITLE
Document how to register a new user with temporary email

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#114]
## Description
As a tester,
I need to register new users using the deployed server,
so that I can use the API.

This can be a step by step tutorial like [Using Swagger UI @ Wiki](https://github.com/systers/mentorship-backend/wiki/Using-Swagger-UI).

### Update [Required]
- [x] Create a step by step guide with visual components, images and/or a GIF showing how to register a new User into Mentorship System
- [x] Present a wiki page on your fork repo with this new tutorial page (for mentors to approve)

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30-40 minutes

**Comment by isabelcosta** [comment]
@sammy1997 can you tell me what is wrong in this template? is the hours that I turned into minutes? Is the `[Required]` keyword?

**Comment by Dilu9218** [comment]
*@sys-bot approve*

**Comment by sammy1997** [comment]
@isabelcosta It's the [Required] Keyword

**Comment by isabelcosta** [comment]
I added the [Required] keyword and the label wasn't removed, should that be? Does @sys-bot understand when an issue is edited? @sammy1997

**Comment by isabelcosta** [comment]
@Dilu9218 can you please do sys-bot approve without the markdown for italic?

**Comment by mayburgos** [comment]
@sys-bot approve

**Comment by ejbryant28** [comment]
Is this issue still available? If so I think I could take it on. It'd be my second open source contribution

**Comment by isabelcosta** [comment]
Hey @ejbryant28 👋 yes it is, but this is not related to code, is more related to the wiki. We want something like this [Using Swagger UI @ Wiki](https://github.com/systers/mentorship-backend/wiki/Using-Swagger-UI) to put on the GitHub Wiki. This wouldn't involve PR exactly, we could give you access to the wiki (@mayburgos right?), after you show us how you want that new Wiki page to look like, and then you can create that new page on our Wiki. You can test doing the page on the Wiki of your fork. What do you think?

**Comment by ejbryant28** [comment]
@isabelcosta sure I can do that! It might take me a little while to do it though because I have some big interviews I'm studying for and I really want to prioritize coding. So if time is a factor, you might want to assign it to someone else. But otherwise I'll definitely work on it in my free time and get it up and going fairly soon.

**Comment by isabelcosta** [comment]
@ejbryant28 I totally understand, I'm in processes like that right now as well ;) and I see other students that had their exams. So I think there isn't a problem. Since no one has shown interest in this issue before. Take your time and prioritize things however works best for you ;) Once you start actively working on this just leave an update here on the issue. Good luck with your interviews :)

**Comment by isabelcosta** [comment]
I did this because I saw a newcomer facing issues understanding how to register a new user. Here it is: https://github.com/systers/mentorship-backend/wiki/Register-a-new-user-using-Swagger
