### ISSUE TITLE
Add Docusaurus badge on readme

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#1142]
### Is your feature request related to a problem? Please describe.
The project's documentation is using Docusaurus, add its badge on top of the readme with other badges present similar to what is done on [stem-diverse-tv's repo](https://github.com/anitab-org/stem-diverse-tv)

### Describe the solution you'd like
Add badge on readme

**Comment by vj-codes** [comment]
@isabelcosta do you approve this?

**Comment by isabelcosta** [comment]
which badge you would like to add, only the docusaurus one with the version of it? @vj-codes

**Comment by vj-codes** [comment]
Yes and hyperlink it to the deployed website @isabelcosta

**Comment by isabelcosta** [comment]
ah, I think we have it here already, with the "documentation". Let me know if I understood this wrong @vj-codes

![image](https://user-images.githubusercontent.com/11148726/133309944-9132204f-0174-4a80-b661-9307a3624c43.png)

**Comment by vj-codes** [comment]
opps wrong repo 🤦 
I meant to create it on mentorship android since the PR to move documentation to Docusaurus is in the review process
What say to add it on android?

**Comment by isabelcosta** [comment]
Yes, I did think maybe you were using the wrong repository 😅 
Agree with this for mentorship-android for sure @vj-codes feel free to create the issue there 🤗 and close this issue here
