### ISSUE TITLE
Add link with icon to our AnitaB.org Open Source Medium

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#1145]
## Description

As an admin,
I need our Medium blog to be in the social media links on Docusaurus,
so that I can promote our blog to our contributors.

We want to see the medium link to our AnitaB.org Open Source on the Docusaurs page footer.
Our Medium publication: https://medium.com/anitab-org-open-source
Our Docusaurus documentation: https://anitab-org.github.io/mentorship-backend

## Mocks

You can find this in the footer:
![docusaurus page footer](https://user-images.githubusercontent.com/11148726/136611075-679c93b8-6763-4056-afad-1c9a7bd1a902.png)

### Update [Required]
- [ ] Add Medium icon with link to our blog on Docusaurus page footer.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

30 min

**Comment by sharonibose** [comment]
@isabelcosta, could you kindly assign me this task?

**Comment by isabelcosta** [comment]
@sharonibose sure! I will assign it to you :)

**Comment by sharonibose** [comment]
Thank you for assigning me. I will make the necessary changes soon.

**Comment by msaini28r** [comment]
can you assign me to this issue ?

**Comment by msaini28r** [comment]
the GitHub link is not changed yet.

**Comment by isabelcosta** [comment]
@msaini0r , @sharonibose started working on this. PR is linked above. If we don't get updates to PR within 3 days we can then reassign. Until then, it's up to @sharonibose to solve

**Comment by msaini28r** [comment]
I have made the necessary changes please check the pull request and review it. @isabelcosta

**Comment by isabelcosta** [comment]
@sharonibose are you still working on this ticket? Please let us know, since i added a comment to your PR, otherwise I'll have to close and potentially re assign

**Comment by sharonibose** [comment]
> @sharonibose are you still working on this ticket? Please let us know, since i added a comment to your PR, otherwise I'll have to close and potentially re assign

Yeah, I'm updating the required changes.

**Comment by sharonibose** [comment]
The required changes have been made

**Comment by devkapilbansal** [comment]
This issue is closed in #1146 

Thanks @sharonibose for your contribution :clap: :clap: :clap:
