### ISSUE TITLE
Remove unverified users after some time has passed since registration

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#115]
## Description
As a developer,
I need avoid test or invalid users on the database,
so that I can save up storage space.

We need to develop a scheduler/ cron job to delete user with unverified email for some period of time.
**The period still needs to be discussed** with the community and admins.

### Update [Required]
- [ ] Cron job to delete unverified users after a certain period of time

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by isabelcosta** [comment]
@systers/mentorship can any of you approve this please, with the Sysbot command

**Comment by mayburgos** [comment]
@sys-bot approve

**Comment by GeVic** [comment]
@isabelcosta If this is not your GSoC work can I work on the issue?

**Comment by isabelcosta** [comment]
@GeVic This will not be developed during gsoc since I'm focused on the android app, but this still needs some discussion, on how much time we'll wait until removing the users, so its on hold. Thank you for your interest in helping! And since you're "assigned" to another issue, its better if you solve that one first and then look for others. unless you don't want to solve that one?
