### ISSUE TITLE
Fix broken links in Getting-Started.md

### ISSUE THREAD

**Issue by ghost** [anitab-org/mentorship-backend#1155]
### Describe the bug
Several links in the `Getting-Started.md` file are broken. Broken links 2-5 are likely due to the comma in the `Fork,-Clone-&-Remote.md` file name. The last link is likely broken because it is missing the `.md` extension.

### To Reproduce
1. Go to [Getting-Started.md](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/docs/Getting-Started.md)
2. Click on the links highlighted in the screenshot below
3. See 404 error

### Expected behavior
All links should work.

### Screenshots
![broken_links](https://user-images.githubusercontent.com/35678644/178603384-fff25455-e483-460d-879d-45ff2190a00a.png)
![chrome_screenshot](https://user-images.githubusercontent.com/35678644/178605053-bd02d792-009d-43a5-b273-ebd3b6a82d8b.png)

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 103.0.5060.114

**Comment by devkapilbansal** [comment]
Thanks @jasminjohal for this issue. Would you like to work on it?

**Comment by SrijanShovit** [comment]
I would like to work on this issue.
Kindly assign it to me!

**Comment by mariagabrielacs123** [comment]
Hello! I am a first-time user and I can do this for you.

**Comment by amanda-mcmullin** [comment]
I would like to work on this issue!

**Comment by devkapilbansal** [comment]
The links are working as they should. See here:-
https://anitab-org.github.io/mentorship-backend/docs/Getting-Started
