### ISSUE TITLE
Create Quality Assurance Issue Template

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#119]
## Description
As a contributor,
I need Quality Assurance issue template,
so that I can create issues dedicated to quality assurance tasks.

### Update [Required]
- [x] Create issue template for Quality Assurance tasks

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Dilu9218** [comment]
@sys-bot approve
