### ISSUE TITLE
Send Name in GET /mentorship_relations response

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#121]
## Description
As a developer on the frontend,
I need to send the Name along with the response of Mentorship relation list API ,
so that I can show the name of the user.

This is necessary for issues https://github.com/systers/mentorship-android/issues/9 and  https://github.com/systers/mentorship-android/issues/21

```
user: {
    Id,
    name
}
```

### Update [Required]
- [x] Modify the response of the APIs related to Mentorship Relation listing

## Definition of Done
- [x] All of the required items are completed.
- [ ] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by isabelcosta** [comment]
@systers/maintainers-mentorship-android need approval on this, since I'll be working on this ASAP

**Comment by isabelcosta** [comment]
@m-murad and @roopalJazz I just need you to comment here: @sys-bot approve

**Comment by m-murad** [comment]
@sys-bot approve

**Comment by isabelcosta** [comment]
Thank you @m-murad !
