### ISSUE TITLE
Prepare gsoc18-code branch for develop branch

### ISSUE THREAD

**Issue by m-murad** [anitab-org/mentorship-backend#133]
## Description
As a maintainer,
I need prepare gsoc18-code branch for merging in develop,
so that GSoC work can be merged.

### Update [Required]
- [ ] PR is merged

## Definition of Done
- [ ] PR is merged
- [ ] Approval by 2 mentor.

## Estimation
1 hours

**Comment by m-murad** [comment]
@isabelcosta @Dilu9218 @roopalJazz 
please approve the issue

**Comment by isabelcosta** [comment]
@sys-bot approve

**Comment by isabelcosta** [comment]
@m-murad done!
