### ISSUE TITLE
Add Environment Variables link to README.md

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#134]
## Description
As a developer,
I need to understand the environment variables used in the backend,
so that I can properly use them.

### Update [Required]
- [ ] Link Environment Variables Wiki page to the README.md

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by isabelcosta** [comment]
@m-murad @roopalJazz @Dilu9218 please approve this so I can send a PR for this issue

**Comment by m-murad** [comment]
@sys-bot approve
