### ISSUE TITLE
Add feature specific branch creation when sending PRs to CONTRIBUTING.md

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#135]
## Description

As a contributor,
I need clear Contributing Guidelines,
so that I can properly contribute to this project.

Explain that a contributor has to create a new branch per issue instead of sending PRs from their base branch (same as this repo base branch `develop`).

### Update [Required]
- [ ] Update CONTRIBUTING.md

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by isabelcosta** [comment]
@m-murad @Dilu9218 @roopalJazz can you please approve this issue

**Comment by m-murad** [comment]
@sys-bot approve
