### ISSUE TITLE
Add Contact section to README.md

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#136]
## Description

As a new contributor,
I need know whom to contact and how,
so that I can discuss anything related to this project.

The content will be the same as https://github.com/systers/mentorship-android/blob/develop/README.md

But instead of having @systers/maintainers-mentorship-android you'll have for this repository, @systers/maintainers-mentorship-backend

## Mocks

Contact section on systers/mentorship-android repository

![image](https://user-images.githubusercontent.com/11148726/44312222-a9223200-a3ec-11e8-8a7e-8bf3fc0d8446.png)

### Update [Required]
- [ ] Add Contact information just like on Android repo, but with a different tag for maintainers

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by isabelcosta** [comment]
@systers/maintainers-mentorship-backend can you please approve this using @sys-bot

**Comment by m-murad** [comment]
@sys-bot approve

**Comment by preeti98** [comment]
Hello everyone! May I please work on this issue in case no one is working on this?
Thanks in advance!

**Comment by isabelcosta** [comment]
@preeti98 yes you can :)

**Comment by preeti98** [comment]
Here, do I need to hyperlink @systers/maintainers-mentorship-backend to the website mentioned in the comments? The mock website does not have any hyperlinking at @systers/maintainers-mentorship-android .

**Comment by isabelcosta** [comment]
just for the record, we continued this discussion on slack
