### ISSUE TITLE
Filter Users list to hide the current logged in user

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#143]
## Description
As an API consumer,
I need to have the current user hidden from the users' list,
so that I can show a correct users listing the frontend client (e.g.: Android).

Task: Hide current user from the users' list
API: 
- GET /users
- GET /users/verified

### Update [Required]
- [ ] API must show all users except for the current logged in user

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by fnshemerirwe** [comment]
@sys-bot claim

**Comment by fnshemerirwe** [comment]
@isabelcosta, can I please claim this issue.

**Comment by isabelcosta** [comment]
Hey @flacode yes you can :) If you have any doubts about this issue feel free to ask questions ;)
