### ISSUE TITLE
Add seek mentorship and availability to mentor fields to Register API

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#144]
## Description
As an API consumer,
I need availability to mentor or mentee fields on registration API,
so that I can give the option to the end user.

**Fields:**
- availability_to_mentor
- need_mentoring

### Update [Required]
- [ ] Add fields to the request body as optional to be a mentor or a mentee
- [ ] Make tests to confirm this functionality
## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by fnshemerirwe** [comment]
@isabelcosta, can I please claim this issue.

**Comment by isabelcosta** [comment]
@flacode yes sure :)
