### ISSUE TITLE
Create doc strings

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#149]
**Is your feature request related to a problem? Please describe.**
Backend code does not have proper in code documentation. New contributors may find difficult to understand the code without this documentation.

**Describe the solution you'd like**
Create doc strings everywhere in the code, where its needes (example: classes, methods, ...). I've seen this [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

After agreeing on this, we can create an example for others to follow.

**Describe alternatives you've considered**
There are other ways of doing doc strings, so this is totally open for discussion!

**Additional context**
This is an awesome opportunity to create newcomer/first-timers-only issues to learn about open source workflow and code logic.

**Comment by alexanderwlee** [comment]
Hi, is this still open? I would love to work on this :)

**Comment by isabelcosta** [comment]
@alexlee311 yes it is, although this is an Epic, we tend to create issues specific to a file that needs doc strings. Right now, I'm focused on reviewing work from Google Code-in participants, so I might not review your work right away but feel free to see what classes/files that need doc strings and contribute to them :)

**Comment by alexanderwlee** [comment]
okay, thanks for the clarification! :) @isabelcosta

**Comment by radhikasethi2011** [comment]
I wish to work on this issue. Please assign it to me.

**Comment by isabelcosta** [comment]
@radhikasethi2011 I think this is a quite broad issue, can you select a file or module where doc strings are missing and you can contribute to? You can then create an issue for it to work on it.

**Comment by vj-codes** [comment]
@isabelcosta I looked through the code and can see that docstrings is used, although I don't see any merged PRs 
Can this be closed then?

**Comment by isabelcosta** [comment]
@vj-codes is it used everywhere? I guess we can close :) Thank you for the triage 🙏🏾
