### ISSUE TITLE
Add base tests for first features

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#15]
## Description
As a developer,
I need to test my code,
so that I can check my code for bugs.

There should be some tests at least so that a developer can have an idea of how to test the separate modules.

### Update [Required]
- [ ] tests folder

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Dilu9218** [comment]
@isabelcosta you can work on this...

**Comment by isabelcosta** [comment]
@Dilu9218 Thank you! I'll send a PR right away.

**Comment by isabelcosta** [comment]
@Dilu9218 I'm checking [this possible solution](https://qxf2.com/blog/dont-hardcode-usernames-and-passwords-in-your-test-scripts/) that you sent me
