### ISSUE TITLE
Add HTTPS support to backend elastic beanstalk server

### ISSUE THREAD

**Issue by haroldadmin** [anitab-org/mentorship-backend#150]
**Is your feature request related to a problem? Please describe.**

This issue is related to the Android app for the mentorship system. Here's the issue I'm referencing: https://github.com/systers/mentorship-android/issues/94

The backend server on Elastic Beanstalk currently does not support HTTPS. All the debug-build Android app communication with the server currently happens over this URL: `http://systers-mentorship-dev.eu-central-1.elasticbeanstalk.com/`. However, Android P defaults to TLS connections for all communication, so all requests to a non-https server results in this error:
```
HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to systers-mentorship-dev.eu-central-1.elasticbeanstalk.com not permitted by network security policy
```
When the base URL is changed to `https://systers-mentorship-dev.eu-central-1.elasticbeanstalk.com/` then all requests fail with a timeout error.

**Describe the solution you'd like**
The server should support communication over HTTPS .

**Describe alternatives you've considered**
We can allow cleartext communication on a per-app basis through some workarounds, but that would defeat the point of this security feature.

**Additional context**
No HTTPS also presents a security issue. When a user signs up through the app, their credentials are transferred in plain text over the network.

**Comment by isabelcosta** [comment]
**Update:** As discussed on Community Open Session this has to be done by who has access to the AWS.

**Comment by vj-codes** [comment]
Closing since backend has https support and is no longer deployed on elastic beanstalk server
