### ISSUE TITLE
Create doc strings for AdminDao class and its functions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#153]
## Description
As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for AdminDao class and its functions**. You can find this file [app/api/dao/admin.py](https://github.com/systers/mentorship-backend/blob/develop/app/api/dao/admin.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

### Update [Required]
- [ ] Create doc strings for AdminDao class and its functions (file: app/api/dao/admin.py).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by isabelcosta** [comment]
@sarnava1 in this community we prefer that contributors ask for approval to work on the issue before sending a PR, or at least mention that they're working [(see more here)](https://github.com/systers/mentorship-backend/wiki/Getting-Started#choose-a-working-item). This helps the maintainers managing the issues that are being worked on. In this case its ok, because no one else showed previous interest, and also this being your first time with this repo you qualify for "First Timers Only".

**Comment by sarnava1** [comment]
@isabelcosta I am extremely sorry for not asking before starting to work with this issue. I will keep this in mind from the next time.

**Comment by isabelcosta** [comment]
No problem @sarnava1. Now you know for the next time :)
