### ISSUE TITLE
Create doc strings for UserDao class and its functions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#154]
## Description
As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for UserDao class and its functions**. You can find this file [app/api/dao/user.py](https://github.com/systers/mentorship-backend/blob/develop/app/api/dao/user.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

### Update [Required]
- [ ] Create doc strings for UserDao class and its functions (file: app/api/dao/user.py).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by isabelcosta** [comment]
@Isfaaq in this community we prefer that contributors ask for approval to work on the issue before sending a PR, or at least mention that they're working [(see more here)](https://github.com/systers/mentorship-backend/wiki/Getting-Started#choose-a-working-item). This helps the maintainers managing the issues that are being worked on. 

In this case its ok, because no one else showed previous interest, and also this being your first time with this repo you qualify for "First Timers Only". When I'll review your PR, when I get some time.

**Comment by 0x15F9** [comment]
Okay. Thanks for the information.

**Comment by mustaqmustu** [comment]
can I work on this?

**Comment by isabelcosta** [comment]
@mustaqmustu are you still interested in working on this?

**Comment by mustaqmustu** [comment]
Nope

**Comment by amnoweb** [comment]
Do you still need someone to work on this?

**Comment by isabelcosta** [comment]
@amnoweb yes, this is available. You can work on this if you want.
