### ISSUE TITLE
Create doc strings for MentorshipRelationDAO class and its functions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#155]
## Description
As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for MentorshipRelationDAO class and its functions**. You can find this file [app/api/dao/mentorship_relation.py](https://github.com/systers/mentorship-backend/blob/develop/app/api/dao/mentorship_relation.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

### Update [Required]
- [ ] Create doc strings for MentorshipRelationDAO class and its functions (file: app/api/dao/mentorship_relation.py).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by UmarAuhammud** [comment]
I'm working on it :smile:

**Comment by isabelcosta** [comment]
@UmarAuhammud ok, go ahead. Since no one else showed previous interest in this issue, its totally fine that you work on it ;)

**Comment by isabelcosta** [comment]
Closed PR #159 due to lack of response from the contributor. This PR was almost finished. The only thing missing was changes according to my review.

**Comment by agarwalrounak** [comment]
@isabelcosta I will work on it.

**Comment by isabelcosta** [comment]
@agarwalrounak yes you can work on this :) Since no one claimed it so far after I made this again and because you're a first timer to this repository.
