### ISSUE TITLE
Implement refresh tokens feature

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#160]
## Description
As a user of the system,
I need refresh tokens,
so that I can refresh my access token to contribue using the backend services.

Read [this for more information on the need for refresh tokens.](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/)
This came up because of this issue on the Android client issue tracker (https://github.com/systers/mentorship-android/issues/113)

Isabel's suggestion: This can be done with the already used [flask-jwt-extended](https://flask-jwt-extended.readthedocs.io/en/latest/) library.

### Update [Required]
- [ ] Implement refresh token feature

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 hours

**Comment by iulianav** [comment]
Hi! I would like to attempt this issue! Is that ok?

**Comment by isabelcosta** [comment]
@iulianav sure you can :) Right now I have no idea of a complete implementation, but I let some comments on the description that can help you out!

**Comment by iulianav** [comment]
Honestly, @isabelcosta I have no clue either. But I thought I might give it a try and learn if that is ok!

**Comment by isabelcosta** [comment]
Do give it a try! It's totally fine if you're clueless, thank you for your honesty here!
If you need any help feel free to ask questions so that I can help you :) @iulianav
