### ISSUE TITLE
Create doc strings for validation_utils.py file

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#161]
## Description

As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for Validation Utils file**. You can find this file [app/utils/validation_utils.py](https://github.com/systers/mentorship-backend/blob/develop/app/utils/validation_utils.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

### Update [Required]
- [ ] Create doc strings for Validation Utils file functions (file: app/utils/validation_utils.py).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by iulianav** [comment]
I would like to take this issue. Is that ok? :)

**Comment by LSariel** [comment]
Is this issue still available? :)

**Comment by isabelcosta** [comment]
@LSariel sorry for the late reply, but yes it is available if you're still interested ;)

**Comment by LSariel** [comment]
Yes! Only I don't have time to work on it this week. But starting Friday I
would love to! :)

Den sön 12 maj 2019 kl 02:35 skrev Isabel Costa <notifications@github.com>:

**Comment by isabelcosta** [comment]
Ok no problem @LSariel , I'll leave this open and if you're still interested at that time, just leave a comment here and I'll assign it to you

**Comment by LSariel** [comment]
Thank you!

Den tors 16 maj 2019 kl 01:02 skrev Isabel Costa <notifications@github.com>:

**Comment by LSariel** [comment]
I can do it this week! :)

**Comment by silentechoes** [comment]
@isabelcosta Can I work on this?

**Comment by roshni-b** [comment]
@isabelcosta can I work on this?

**Comment by mtreacy002** [comment]
@isabelcosta, is this issue still available? Can I work on it?
