### ISSUE TITLE
Create doc strings for app/api/email_utils.py file

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#162]
## Description

As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for Email utils file**. You can find this file [app/api/email_utils.py](https://github.com/systers/mentorship-backend/blob/develop/app/api/email_utils.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

### Update [Required]
- [ ] Create doc strings for Email Utils file functions (file: app/api/email_utils.py).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by iulianav** [comment]
I would like to take this issue. Is that ok? :)

**Comment by isabelcosta** [comment]
Sure @iulianav work on this ;) the other issue will still be available for others ;)

**Comment by iulianav** [comment]
@isabelcosta thanks alot!
