### ISSUE TITLE
Create doc strings for TaskDao class and its functions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#166]
## Description

As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for TaskDao class and its functions**. You can find this file [app/api/dao/task.py](https://github.com/systers/mentorship-backend/blob/develop/app/api/dao/task.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

### Update [Required]
- [ ] Create doc strings for TaskDao class and its functions (file: app/api/dao/task.py).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by jaerjaerbin** [comment]
Hey @isabelcosta, I would like to attempt this.

**Comment by isabelcosta** [comment]
Sure you can @jaerjaerbin  :) Go ahead. Feel free to ask any doubts you have

**Comment by jaerjaerbin** [comment]
@isabelcosta Cool! working at it! 

I only have one doubt, when I run:

`python run.py` the page in the web browser only says **No spec provided** is it normal?

**Comment by jaerjaerbin** [comment]
Hey @isabelcosta I have a doubt.

What should I run after adding and commiting.

`$ git push origin <my-docstring-branch>` 
or
`$ git push upstream <my-docstring-branch>`

**Comment by isabelcosta** [comment]
> `python run.py` the page in the web browser only says **No spec provided** is it normal?

Its normal if it shows only for some seconds. If that's all it shows then its not normal.
Do you have the environment variables set up?

> `$ git push origin <my-docstring-branch>`
> or
> `$ git push upstream <my-docstring-branch>`

you should push to origin, therefore is: `$ git push origin <my-docstring-branch>`

@jaerjaerbin hope that answers it all :) If you have more questions just keep them coming ;)

**Comment by jaerjaerbin** [comment]
Thanks for your answers @isabelcosta 

The push doubt is clear now. The bad news for me is that it shows **No spec provided** all the time.

About the environment variables I followed the steps in [Environments Variables wiki](https://github.com/systers/mentorship-backend/wiki/Environment-Variables) but to be honest, the security section was not so clear for me. All those key values were made out by me, so I don't know if I did wrong.

Any guidance will be appreciated.

**Comment by isabelcosta** [comment]
@jaerjaerbin Thank so much you for pointing what you did not understand from the documentation! 🙌 That's really important so that I can improve the documentation for newcomers to this project. You can use the examples I provided in that section, they are used for email verification and access tokens for login. you can just give them random strings, since it runs on your local machine.

When have you cloned this project? Because there was a small bug introduced by a PR I approved, and then I solved it in the same day. Can you tell me the last commit you have? You can know that by doing:
```
git log --oneline
```

The first commit will be the most recent you have.

**Comment by jaerjaerbin** [comment]
Sure! 
This is a screenshot of what I got:

![logsnap](https://user-images.githubusercontent.com/17935632/51503324-6c49d500-1da8-11e9-9b9f-a6a4a34a14fa.JPG)

**Comment by jaerjaerbin** [comment]
About the Environment Variables I did type random strings for both security keys. 

I was trying to check those variables in this way (opening python CLI with venv activated):

`import os`
`os.environ.get('SECURITY_PASSWORD_SALT')`

returning empty string. It seems like it wasn't export those variables or something.

**Comment by jaerjaerbin** [comment]
It's solved. I exported the environment variables again and now it's working fine!

**Comment by isabelcosta** [comment]
@jaerjaerbin yes!!! I'm so so glad you figured that out on your own 🎉 now you can test the live app and debug better :D
