### ISSUE TITLE
Create doc strings for TasksListModel class and its functions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#167]
## Description
As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for TasksListModel class and its functions**. You can find this file [app/database/models/tasks_list.py](https://github.com/systers/mentorship-backend/blob/develop/app/database/models/tasks_list.py).
You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

_To do this you have to understand the classes and the functions, make sure you read the code and understand what they are doing_

### Update [Required]
- [ ] Create doc strings for TasksListModel class and its functions (file: app/database/models/tasks_list.py).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by agarwalrounak** [comment]
I will work on it.

**Comment by isabelcosta** [comment]
@agarwalrounak I'm sorry, but it starts to become difficult to manage all the issues, both this and #155 are "First Timers Only" issues, so you can only work on one of them, in this way we can give an opportunity for more people to contribute to this project, which one of the issues, #155 or #167, do you want to work on so I can close one of the PRs?

**Comment by isabelcosta** [comment]
I will close the latest issue since it was the last you submitted @agarwalrounak and this still has the available status.

**Comment by agarwalrounak** [comment]
Sys-bot had closed PR #182 so I had begun to work on this issue. I guess an exception can be made here.

**Comment by isabelcosta** [comment]
@agarwalrounak I understand :) is just that your almost done with the pr, you just need to address my change requests and then I can approve it and merge it. I try to have as many first timers only issues as possible, so that everyone can have a chance to work on open source through this repo and make a valuable contribution. So your work won't go unnoticed it is there in the pr, it can help others and is a valuable contribution.

**Comment by 5anjana** [comment]
Hii @isabelcosta 
I would like to work on this issue. Can I take it up?

**Comment by 5anjana** [comment]
Hii @isabelcosta
Please assign me this issue?

**Comment by agarwalrounak** [comment]
Hi @sanjana11147, I guess you can take it up since there's no one else working on it(or expressed the desire to do so)

**Comment by 5anjana** [comment]
Okay thanks @agarwalrounak  :)

**Comment by isabelcosta** [comment]
You can work on it @sanjana11147
