### ISSUE TITLE
Create doc strings for MentorshipRelationModel class, attributes and functions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#168]
## Description

As a developer,
I need to have in code documentation,
so that I can understand better the code.

Related to #149 

We need to have **doc strings for MentorshipRelationModel class, attributes and functions**. You can find this file [app/database/models/mentorship_relation.py](https://github.com/systers/mentorship-backend/blob/develop/app/database/models/mentorship_relation.py).

You can follow these conventions: [style guide for doc strings in python by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings).

_To do this you have to understand the classes and the functions, make sure you read the code and understand what they are doing_

### Update [Required]
- [ ] Create doc strings for MentorshipRelationModel class and its functions (file: app/database/models/mentorship_relation.py).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by AyahRamahi** [comment]
Can I work on this ?

**Comment by isabelcosta** [comment]
Sure go ahead @AyahRamahi 😄
