### ISSUE TITLE
Add missing description to APIs on Swagger

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#171]
## Description
As an API consumer who sees Swagger UI,
I need to have Swagger Documentation on point,
so that I can understand the API.

At least 2 APIs don't have a simple description:

![two apis undocumented](https://user-images.githubusercontent.com/11148726/50543596-96a6d900-0bd4-11e9-9455-ad27e26b7b3a.png)

This is done with a simple doc string comment below the API Resource definition.

### Update [Required]
- [ ] Add 2 simple doc string comments for resend and confirm email API

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

(< 5 min if you already know where to add the doc strings ;) )

**Comment by iulianav** [comment]
@isabelcosta can I take this for now? :)

**Comment by isabelcosta** [comment]
Go ahead @iulianav !
