### ISSUE TITLE
Refactor codebase according to PEP8 standards

### ISSUE THREAD

**Issue by iulianav** [anitab-org/mentorship-backend#178]
## Description
As a developer,
I need the codebase to follow PEP8 standards,
so that I can read and maintain it with less effort.

### Update [Required]
- [ ] Refactor entire codebase to pass flake8 checks

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by Tlazypanda** [comment]
@isabelcosta @iulianav can I take up this issue?

**Comment by vj-codes** [comment]
Closing as the codebase is refactored by black
