### ISSUE TITLE
Running pylint for Code quality checks

### ISSUE THREAD

**Issue by ramitsawhney27** [anitab-org/mentorship-backend#187]
## Description
This issue is to test all the test cases of features in the project.
Add pylint to the configuration in the deploying script, and return an exit code of 0 only if all files exceed the score of 7.0

## Test Cases
Sample output for pylint:
C: 61, 0: Function name "dumpErrors" doesn't conform to snake_case naming style (invalid-name)
C: 61, 0: Missing function docstring (missing-docstring)
C: 67, 0: Missing function docstring (missing-docstring)

------------------------------------------------------------------
Your code has been rated at 3.75/10 (previous run: 5.22/10, -1.47)
The code rating should be > 7.0 for each python script in the repository.

## Definition of Done
- [ ] At least one test case tested.
- [x] Approval by 1 mentor.

## Estimation
10 hours

**Comment by devbihari** [comment]
Let me make this enhancement if it has not been done already :fire:

**Comment by NidhiKJha** [comment]
Pylint can be run over an entire directory to give a cumulative score for all the code, 
why should we have to find the score for each file separately?

**Comment by ananyaarun** [comment]
@NidhiKJha , to ensure that each file follows a particular coding standard and rating rather than the whole repo on an average. Also personally i feel it is easier and gives clarity to fix errors detected by pylint individually on files.

**Comment by NidhiKJha** [comment]
So how would you suggest we implement this? Should a developer test each file individually while working, this way you get small messages to improve the code, while running pylint over all files individually will still generate large error messages that will get ignored in bulk.
It is possible to run a bash script to extract scores from each file and get an exit 0 code.
But I would suggest not to do this.
It should just be suggested to developer to use pylint on their own to check each file they're working with.

**Comment by ramitsawhney27** [comment]
Suggesting something isn't the same as enforcing it. We've had enough PRs that don't match up to quality standards, and as we continue to scale mentorship system, it is ideal to start enforcing strong quality standards at this stage. A lower rating will be kept, but the change is well valid.

**Comment by CleverFool77** [comment]
@NidhiKJha Please let us know if you were planning to work on this issue as I already started working on it and saw your opened PR. Please continue with the issue as you opened PR but letting everyone know beforehand prevents redundant work on issue.

**Comment by NidhiKJha** [comment]
@CleverFool77 You hadn't commented here that you were working on this issue either. I'm currently working upon this issue and in future, I'll make sure to comment beforehand.

**Comment by NidhiKJha** [comment]
@ramitsawhney27 @isabelcosta in PR #194 I have submitted a solution using Bash by invoking Pylint through the terminal and parsing the output. The bash code is not easily readable. So, Should I submit another PR using a python script and invoking it through bash?

**Comment by ramitsawhney27** [comment]
No, the PR looks fine.

**Comment by CleverFool77** [comment]
@NidhiKJha I asked about this issue in slack but its okay ✌️.

**Comment by CleverFool77** [comment]
@NidhiKJha I asked about this issue in slack but its okay ✌️. 
You are doing great job with PR. Keep contributing :tada:

**Comment by Tlazypanda** [comment]
@isabelcosta Is this issue still available?

**Comment by vj-codes** [comment]
Closing since we use black and it's gh action now
