### ISSUE TITLE
 In edit profile section,if user removes his/her details like bio,user name..they are not removed ,instead they are showing the older details again

### ISSUE THREAD

**Issue by mustaqmustu** [anitab-org/mentorship-backend#189]
**Describe the bug**
In edit profile section,if user removes his/her details like bio,user name..they are not removed ,instead they are showing the older details again

**To Reproduce**
1. Go to 'update user'
2. remove any details
3.save and see error

I want to work on this issue

**Comment by isabelcosta** [comment]
@sys-bot approve

**Comment by isabelcosta** [comment]
I tested it on the [Backend API](http://systers-mentorship-dev.eu-central-1.elasticbeanstalk.com/), and it seems this is a bug from the backend.

**Comment by LordGameleo** [comment]
Is it available!? I would like to work on it. @isabelcosta

**Comment by mustaqmustu** [comment]
> Is it available!? I would like to work on it. @isabelcosta

Im already working on it @LordGameleo

**Comment by LordGameleo** [comment]
@isabelcosta  please remove Available Status..... @mustaqmustu  is working on it.

**Comment by mustaqmustu** [comment]
@LordGameleo seems this issue is not only occurs when we update bio but even while updating username and everything .

**Comment by LordGameleo** [comment]
@mustaqmustu try figuring out what may be the cause at one place..... other places will be similar.

**Comment by sumit-badsara** [comment]
Is this issue available? @isabelcosta @mustaqmustu.
I would like to work on this.

**Comment by isabelcosta** [comment]
@BadduCoder I think it is, I don't see updates from @mustaqmustu .
@mustaqmustu are you still interested in this issue?

**Comment by sumit-badsara** [comment]
@isabelcosta as there is no response from @mustaqmustu , could you assign this to me.

**Comment by isabelcosta** [comment]
Done! You can start working on this :) @BadduCoder

**Comment by sumit-badsara** [comment]
I have a pending PR, so how should i isolate both of these? @isabelcosta 
Should i create a new branch? Or any other workaround.

**Comment by isabelcosta** [comment]
@BadduCoder yes please create another branch, push it to your fork and then create a new PR.
This is important to keep an PR with a limited scope, so that maintainers can do specific tests and perform a code review specific to the PR's context.

You can revert the past commit on the branch you just pushed the commit and create a new branch just like I mentioned.

Can you look into that?

**Comment by sumit-badsara** [comment]
Sure @isabelcosta... on it!

**Comment by isabelcosta** [comment]
Thank you @BadduCoder !

**Comment by sumit-badsara** [comment]
@isabelcosta Created the PR from new branch, please have a look.
