### ISSUE TITLE
Its possible to be in two mentorship relations at the same time and it shouldn't be

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#191]
**Describe the bug**

I noticed through using the Swagger UI and testing the mobile app around, that it is possible to be in 2 mentorship relations at the same time. According to the project initial requirements, a user can only be in one mentorship relation at a time, so this should not be possible.

I don't know the solution since I did not investigate this yet...

**To Reproduce**

1. Go to Backend Swagger UI
2. Login with user: isabel
3. Call GET /mentorship-relations
4. See 2 mentorship relations with code 2 for ACCEPTED, which means ongoing relation.

**Expected behavior**

This should not be possible to happen.

**Screenshots**

![swagger ui with 2 accepted relations for isabel](https://user-images.githubusercontent.com/11148726/52237060-77c8f000-28c0-11e9-83f3-f67fdbe3caea.png)

**Additional context**
 
This should be investigated ... For whoever is solving this issue, try to create relations for a same user and accept it from both sides, try to replicate this.

**Comment by LordGameleo** [comment]
Is it available!?.... Can I work on this!?

**Comment by CleverFool77** [comment]
@LordGameleo Did you get yourself assigned to this issue or Are you working on Flask script one ?

**Comment by LordGameleo** [comment]
I am not working on this one @CleverFool77

**Comment by CleverFool77** [comment]
@isabelcosta I tried reproducing the steps
* trying mentee in two relation
* mentor in two relation
* a user in two relation with role as mentee in one and mentor as another.

But the answer I got was correct. In all these steps,  It denied to form a second relation as first one is already existing. And i didn't get the bug present in issue.

**Comment by isabelcosta** [comment]
@CleverFool77 thank you for testing this. That's interesting 🤔 
Can you or anyone check the timings? Maybe the end date has already passed and the cron job did not complete the 1º relation.

**Comment by CleverFool77** [comment]
@isabelcosta I have never used cron job scheduler before, but I'll try to explore and see.

**Comment by BadduCoder** [comment]
@sys-bot assign

**Comment by sumit-badsara** [comment]
@isabelcosta I would like to work on this issue, if it is available.
