### ISSUE TITLE
Replace hardcoded HTTP codes with constants/enum

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#193]
## Description
As a developer,
I need have abstractions on HTTP code,
so that I can have a code easier to understand.

HTTP codes (e.g.: 404, 403, ...) are used throughout the code hardcoded. Putting this into constant can make the code more descriptive and easy to understand, by having a descriptive name such as `NOT_FOUND` instead of `404`.

For example, have constants that map HTTP codes like this:
```
@unique
class HttpCode(IntEnum):
    NOT_FOUND = 404
    UNAUTHORIZED = 403
```
Like it is for MentorshipRelationState enum [(you can see this here)](https://github.com/systers/mentorship-backend/blob/develop/app/utils/enum_utils.py).

### Update [Required]
- [ ] Create constants for each HTTP code used through out the code
- [ ] Replace hardcoded HTTP codes with these new constants

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by isabelcosta** [comment]
@ramitsawhney27 @m-murad I think this make sense, right?

**Comment by ramitsawhney27** [comment]
I’m not exactly sure why this would be needed. The HTTP status response codes are fairly standard, and adding an abstraction over these doesn’t make sense. We can add comments/docstrings that explain this rather.

**Comment by isabelcosta** [comment]
@ramitsawhney27 it just reminds me of magic numbers on the code. At the beginning of development, I was just getting a lot of codes wrong and using them in the wrong contexts because I didn't understand them at that time 🤔 How could we put on the comments or docstrings?

**Comment by ramitsawhney27** [comment]
We should either add this in the documentation itself, or just simple one line comments where the codes are being used.

**Comment by isabelcosta** [comment]
Ok I think I will create a wiki page for common things to know about Backend dev, and include a section to explain this codes. Does that sound ok? @ramitsawhney27

**Comment by isabelcosta** [comment]
Started this documentation https://github.com/systers/mentorship-backend/wiki/Backend-Dev
