### ISSUE TITLE
As a user does not need to update his username always during updating his/her profile,its better to remove uniqueness of username in update profile section

### ISSUE THREAD

**Issue by mustaqmustu** [anitab-org/mentorship-backend#195]
**Describe the bug**
As a user does not need to update his username always during updating his/her profile,its better to remove uniqueness of username in update profile section

**To Reproduce**
1. Go to 'update user'
2. edit any details
3. execute it and again click on update user.
4. edit anything by keeping the same username as before
5.Execute it.
6.See the error 

**Expected behavior**
No need to change username everytime

**Screenshots**
after the 1st update:
![screenshot from 2019-02-14 18-47-06](https://user-images.githubusercontent.com/43813438/52789938-4653df80-308b-11e9-92d3-4f7b602032dc.png)
after the 2nd update:
![screenshot from 2019-02-14 18-47-19](https://user-images.githubusercontent.com/43813438/52789981-697e8f00-308b-11e9-951f-be2dd93ea122.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser:mozilla

I want to work on this issue

**Comment by iulianav** [comment]
May i attempt this issue?

**Comment by mustaqmustu** [comment]
> May i attempt this issue?

I already mentioned that I am working on the issue @iulianav

**Comment by iulianav** [comment]
Oh sorry, i did not see!

**Comment by mustaqmustu** [comment]
@isabelcosta what is ur opinion on this

**Comment by jaerjaerbin** [comment]
@mustaqmustu Did you make a PR of this issue?

**Comment by mustaqmustu** [comment]
@jaerjaerbin no..this issue is still not approved

**Comment by devkapilbansal** [comment]
Closing as it is a duplicate of #596
