### ISSUE TITLE
Support SQLAlchemy Schema Migration using Alembic

### ISSUE THREAD

**Issue by iulianav** [anitab-org/mentorship-backend#198]
**Is your feature request related to a problem? Please describe.**
A database/schema migration refers to the management of incremental, reversible changes to relational database schemas. A schema migration is performed on a database whenever it is necessary to update or revert that database's schema to some newer or older version.

A database migration usually changes the schema of a database, such as adding a column or a constraint, adding a table or updating a table. It's often performed using raw SQL wrapped in a transaction so that it can be rolled back if something went wrong during the migration. 

**Describe the solution you'd like**
Migrations can be performed programmatically by using a `schema migration tool` (e.g. Alembic). When invoked with a specified desired schema version, the tool automates the successive application or reversal of an appropriate sequence of schema changes until it is brought to the desired state. Most schema migration tools aim to minimize the impact of schema changes on any existing data in the database.

Instead of changing the schema directly and then recreate the database from scratch, we can choose to migrate the database using alembic. Alembic is a lightweight database migration tool for SQLAlchemy. It is created by the author of SQLAlchemy and it has become the de-facto standard tool to perform migrations on SQLAlchemy backed databases.

**Describe alternatives you've considered**
[Flask-migrate](https://flask-migrate.readthedocs.io/en/latest/) is an extension that handles SQLAlchemy database migrations for Flask applications using Alembic. The database operations are made available through the Flask command-line interface or through the Flask-Script extension. Using this might also be helpful.

**Additional context**
https://en.wikipedia.org/wiki/Schema_migration
https://www.pythoncentral.io/migrate-sqlalchemy-databases-alembic/

**Comment by iulianav** [comment]
@isabelcosta what do you think? :)

**Comment by isabelcosta** [comment]
@iulianav thank you for suggesting this! This seems very important. now that we're using sqlite database, changing schema won't affect much, because every time we merge a new commit, the database is reset. But when we start using a persistent database on Amazon this will be very critical, having a way to manage migrations.

I just didn't understand how this will work. We'll have to run something on the command line to migrate without issues, or programmatically by adding the migrate extension, things will be done under the hood?

**Comment by isabelcosta** [comment]
@sys-bot approve

**Comment by iulianav** [comment]
@isabelcosta have a look at this https://github.com/inspirehep/inspire-next/blob/master/docs/alembic.rst.
I have never implemented it (so i have to learn a bit first if that is ok), but I used it during my internship at CERN for the inspire-next project.

**Comment by isabelcosta** [comment]
I haven't got time to take a deeper look into this. But it seems that @ramitsawhney27 agrees with this as well, so I think if you want to start working on this, or taking a look at this, feel free to do so. @iulianav

**Comment by iulianav** [comment]
@isabelcosta thank you! I will give it a try, I hope it works out nicely!

**Comment by ApheleiaS** [comment]
Hey can I start working on this?

**Comment by isabelcosta** [comment]
@ApheleiaS yes you can :)
