### ISSUE TITLE
Refactor codebase to correct all comparisons

### ISSUE THREAD

**Issue by ramitsawhney27** [anitab-org/mentorship-backend#201]
**Describe the bug**
There are multiple incorrect comparisons in the code, these include:

1. Comparing booleans with 'is', 'is not', '==' and '!='
2. Comparing None with '==' or '!='
3. Comparing objects in terms of identities and not values

**To Reproduce**
-

**Expected behavior**
Correct comparisons everywhere
**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by agarwalrounak** [comment]
I will work on it

**Comment by isabelcosta** [comment]
I think this better be a first timers only issue @agarwalrounak since it's easy to do.

**Comment by LordGameleo** [comment]
I have done this part to the scripts I touched

**Comment by HSR05** [comment]
@isabelcosta  I will work on it. Can you just guide me a little? Thankyou. :)

**Comment by LordGameleo** [comment]
@HSR05 this issue revolves around the use of `is` and `==` operators. Please read about it first a little at https://stackoverflow.com/questions/2209755/python-operation-vs-is-not 

If you have any doubt ask here or on Slack

**Comment by isabelcosta** [comment]
@HSR05 I hope @LordGameleo answered your doubt.
Thank you for the help @LordGameleo 🎉 

@HSR05 do you still want to work on this?

**Comment by LordGameleo** [comment]
@HSR05 Are you still working?

**Comment by HSR05** [comment]
@LordGameleo Currently i have exams so i am busy with those. Will look at it in few weeks. Sorry for the delay.

**Comment by LordGameleo** [comment]
No Issues :)

**Comment by LSariel** [comment]
Is this issue available? :) 
I would like to find an issue to start with, so I'd love to do it if it's free.

**Comment by isabelcosta** [comment]
@LSariel yes this is taken for now. @HSR05 you're still interested in this right?

**Comment by LSariel** [comment]
Okay! Thank you. :)

**Comment by HSR05** [comment]
It's okay if @LSariel wants to make a PR, I'll be free in 3 days and will be able to work on this after that only. Really sorry for the delay.

**Comment by LSariel** [comment]
It's fine for me! :) If you want to do it, you should!

Den tors 2 maj 2019 kl 18:46 skrev HSR05 <notifications@github.com>:

**Comment by efitzpatrick** [comment]
Is this issue available to work on right now?

**Comment by Tsukaiyo** [comment]
Can I do it?

**Comment by isabelcosta** [comment]
Unfortunately, I lost track of who was working on this.
@efitzpatrick I'm sorry I missed your message. I just saw your message now, let us know if you're still interested.

@Tsukaiyo if within 2 days there's no one showing interest for this than you can take on this issue.

**Comment by clemkoh** [comment]
Can I work on this?

**Comment by isabelcosta** [comment]
@clemencetbk yes you can! since there aren't any updates from previous contributors.
