### ISSUE TITLE
Add support for using environment variables

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#21]
## Description
As a developer,
I need load environment variables,
so that I can protect sensitive app data and load app configuration.

In this way, we can avoid hardcoded app configurations.

### Update [Required]
- [x] Remove configuration selection inside of run.py file
- [x] Define environment file and base variables (e.g.: APP_SETTINGS, SECRET_KEY, ...)

## Definition of Done
- [x] All of the required items are completed.
- [x] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by isabelcosta** [comment]
@Dilu9218 @m-murad can you approve this? And if I got something wrong please mention that

**Comment by m-murad** [comment]
Send a PR please

**Comment by isabelcosta** [comment]
@m-murad @Dilu9218 submitted the PR #51 for this issue, if you see that I'm using the setup for environment variables wrong please suggest changes.

I'm assuming that a developer will have the `.env` and to export these variables of the app. I saw this library - [python-dotenv](https://github.com/theskumar/python-dotenv) - that allows exporting these with code within the app, but I'm not using it.

**Comment by Dilu9218** [comment]
It looks ok to me. @m-murad any suggestion?

**Comment by m-murad** [comment]
@Dilu9218 
I have asked for some changes
