### ISSUE TITLE
Activating virtual environment on Windows 

### ISSUE THREAD

**Issue by gowriprathap** [anitab-org/mentorship-backend#211]
**The issue**
In the README file for Mentorship System (backend) of Systers, where run.py is to be executed, the commands for activating the virtual environment (Step 2 under 'Run app') may not work on Windows computers.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have python 3 installed on a windows machine
2. Go to git bash (on windows) or Windows CMD
3. Create a virtual environment venv
5. If creating a virtual environment was successful, run `source ./venv/bin/activate`
4. See error saying no such directory

**Why it did not work**
On Windows machines, virtual environments do not have the bin folder under venv. That is the reason the error shows up.

**Solution**
For git bash users on windows:
Run the command `source ./venv/Scripts/activate` instead.
For windows cmd users:
`.\env\Scripts\activate`

**Screenshots**
![image](https://user-images.githubusercontent.com/47261886/65375891-062f8d80-dc68-11e9-8e5e-fe3935f52ff7.png)

Then complete the steps as provided in the README.

**Comment by isabelcosta** [comment]
@gowriprathap thank you for such a well described issue! Your issue is super valid, do you wish to improve README speaking about the windows-specific setup? That contribution is super welcome!

**Comment by gowriprathap** [comment]
Hi @isabelcosta  Thank you! I will be honoured to update the README and do my best to contribute to this!

**Comment by sumit-badsara** [comment]
@gowriprathap is that git bash? 
Because if I remember correctly, we don't mention even keyword `source` in cmd.
Correct me if I am wrong somewhere!
We just do `.\env\Scripts\activate` for a normal windows cmd.

**Comment by gowriprathap** [comment]
Hi @BadduCoder, I did use git bash for running the application. On the windows cmd, the command might be slightly different. I think Git bash uses linux commands?

**Comment by sumit-badsara** [comment]
Yes @gowriprathap that's what I am pointing out, If you are adding documentation for windows then assume the user can go for any option be it cmd or git bash. So, I was just suggesting that you can add the above mentioned command under CMD commands for windows.

**Comment by gowriprathap** [comment]
@BadduCoder , I understand what you mean now, thank you so much for the suggestion :) I'll add it in. I've already done a PR after updating the README, should I update this in the PR? The PR is still under review.

**Comment by megha070** [comment]
@BadduCoder is this issue still open?

**Comment by sumit-badsara** [comment]
@megha070 This is still to be reviewed. So, you can find another issue for now.

**Comment by megha070** [comment]
@BadduCoder can you please assign me a beginner issue?

**Comment by sumit-badsara** [comment]
@megha070 I am contributer to this repository. 
So, it's better if you can find an issue from the list which has tag of "first-issue" or maybe "First Timers Only" and check if it is available, join the slack channel for better communication with the project owners and admins. 
You can tag @isabelcosta if you want to take up some issue.
You can request to assign an issue to yourself through comments also but slack would be a better choice.

**Comment by Ruchika06** [comment]
Hey @BadduCoder is this issue available?

**Comment by isabelcosta** [comment]
@Ruchika06 it is not available, I updated the assignee now.
If you want to contribute you can look to the available issues, there are plenty I'm sure :)
