### ISSUE TITLE
No module flask error commands

### ISSUE THREAD

**Issue by gowriprathap** [anitab-org/mentorship-backend#212]
**Importing modules**
While running python run.py on the command line (I use git bash), it shows NoModuleFoundError many times. 

**Solution**
Including the import commands for these modules in the README file would be easy for users who are trying to run the program.
These are the commands to run before running `python run.py`
1. `pip install flask`
2. `pip install flask_sqlalchemy`
3. `pip install flask_jwt_extended`
4. `pip install flask_restplus`
5. `pip install flask_mail`
6. `pip install apscheduler`

After running these, it should say 'Running on http://127.0.0.1:5000'.

**Comment by sara-02** [comment]
Hey, @gowriprathap shouldn't `pip install -r requirements.txt` be already doing that, there should not be any need to install them after running the `requirements.txt`

**Comment by PrashanthPuneriya** [comment]
This issue has been fixed by #713. So, I am closing it :)
