### ISSUE TITLE
Add password security checks

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#22]
## Description
As a user,
I need password security validation,
so that I can be sure that my password is secure.

Add validations that make the user choose strong passwords instead of insecure ones. This validation can be done here and on the frontend.

### Update
- [ ] Add password check to Change Password API
- [ ] Add password check to Register API
- [ ] Create password security validation function

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by m-murad** [comment]
+1

**Comment by anshulahuja98** [comment]
https://github.com/systers/mentorship-backend/blob/71e5ff92c378baea92f8c163f27c15b140724819/app/api/validations/user.py#L168

Isn't this already done?

Or is the issue talking about something else?

**Comment by isabelcosta** [comment]
@anshulahuja98 This issue is different, its to make sure that a user chooses a good password, like with characters and such. But now that I'm thinking, maybe this should be put on hold because its an enhancement that can wait. When we test this backend, on Swagger or through frontend, this would take us more time from testing, to create strong passwords and then remembering them. What I use usually to test the backend is "12345678", if we were to do this than the password would be more complex :/

**Comment by anshulahuja98** [comment]
@isabelcosta  Ohk, got it
I haven't give through the whole code yet, for testing purposes, is there any debug variable, like there is in Django.

I generally include the password validators in my Django projects in production only, they are disabled in testing/debug mode which addresses the concern you were talking about.

**Comment by isabelcosta** [comment]
@anshulahuja98 we currently just use this in the development environment. Yes we have a Debug mode if that's what you're thinking. But still, since we're not using production, maybe this can be delayed.

**Comment by KING-SID** [comment]
Hey @isabelcosta is this issue still open? If so, I'd like to begin working on it immediately!

**Comment by ilyamaier** [comment]
@isabelcosta @m-murad I've created an issue on the android repository. It would be better to check the password's security on the android app as we might use password encryption, therefore this issue could be closed. Have a good day! :)

**Comment by chahat99** [comment]
@isabelcosta I have made a pull request regarding this issue.Can you please review it?

**Comment by devkapilbansal** [comment]
@isabelcosta this issue is closed by a PR from mentorship-android. Does similar types of checks exist on this repository too? If not this issue can be reopened and checks can be applied.

**Comment by isabelcosta** [comment]
@devkapilbansal in this repository there are no security checks on the password, currently.
This isn't a huge priority, that is why I haven't done anything about this yet 🤔
