### ISSUE TITLE
[Test issue] for Sysbot

### ISSUE THREAD

**Issue by sara-02** [anitab-org/mentorship-backend#220]
**Describe the bug**
Dummy issue to create a dummy PR against, for testing sysbot against the assumption
1. Double messgaing(happening due to 2 repos on same channel)
2. Not listing PRs if they are not reviewed with 7 days,(but once reviewed they are not checked again)

**To Reproduce**

**Expected behavior**
If the first problem is what we think it is then adding the repo name againt the PR message will be more helpful.

**Screenshots**
![Screenshot from 2019-10-25 12-35-41](https://user-images.githubusercontent.com/7047079/67550424-18e42900-f724-11e9-9207-aa8c35c4fa65.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Problem 1 is not observed in the vms project.
Problem 2 looks similar to https://github.com/systers/sysbot/issues/182

**Comment by sara-02** [comment]
@isabelcosta Can you approve this issue and assign it to me.

**Comment by m-murad** [comment]
@sys-bot approve
