### ISSUE TITLE
TypeError: can't concat NoneType to bytes on /register 

### ISSUE THREAD

**Issue by Anjalizi** [anitab-org/mentorship-backend#224]
**Describe the bug**
TypeError: can't concat NoneType to bytes shows on submitting a POST request on /register on the mentorship system API backend.

500Undocumented | Error: INTERNAL SERVER ERROR gets thrown

**To Reproduce**

1. Go to http://localhost:5000/register, when running the backend locally

The error description can be found [here](https://drive.google.com/file/d/1boEExk-ZCYt733yDm8j4vApnAnn_mn8P/view?usp=sharing)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome

**Comment by sara-02** [comment]
Hey @Anjalizi the localhost link you shared will not available to others.

**Comment by isabelcosta** [comment]
@sara-02 I understand that what @Anjalizi means by localhost link, is for when someone is running the app locally. Maybe @Anjalizi could mention in the description. I will edit the description to make it clear :)

**Comment by isabelcosta** [comment]
@Anjalizi thank you for reporting this potential bug 🎉 

Can you be more clear about how did you submit the POST /register service? Did you just `curl` or when to the browser with  http://localhost:5000/register? Did you send a specific request, any post data? Can you provide more information about it on the issue description please?

**Comment by Anjalizi** [comment]
I'm unable to reproduce the error now when I have setup the repository again locally. If you say, I can close the issue for now.

**Comment by sara-02** [comment]
@Anjalizi sure, you can close this issue for the time being, if the issue surfaces again, just reopen the issue, share the error log/screenshot and tag us :)
