### ISSUE TITLE
Mention in the README in which URL the backend will be exposed once you run it

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#229]
## Description
As a contributor,
I need the README to explain what link can I use to see the project running,
so that I can test the backend api locally.

The README, may be missing the link where the 
Right now, the default URL (ip and port) is setup to http://localhost:5000 as it says on the console log when you run the app.

So the idea is to add an extra step between step 5 and 6 of "Run app" section on README.md, to direct contributors to http://localhost:5000 once the app is running.

### Update [Required]
- [ ] Add an extra step between step 5 and 6 of [Run app section on README.md](https://github.com/systers/mentorship-backend#run-app)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by meenakshi-dhanani** [comment]
Hi @isabelcosta ,
Could you please assign me to this issue?

**Comment by isabelcosta** [comment]
Done :) I managed to assign the issue to you, but if I couldn't you could work on this anyway ;)
You can submit a pull request for it @meenakshi-dhanani
