### ISSUE TITLE
Validate email regex

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#23]
## Description
As a developer,
I need email validation,
so that I can avoid users with invalid emails.

### Update
- [x] Validate email before inserting new user
- [x] Return proper error message, if email is invalid

## Definition of Done
- [x] All of the required items are completed.
- [x] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by m-murad** [comment]
+1
