### ISSUE TITLE
Include links/instructions for local development in README

### ISSUE THREAD

**Issue by PaulaPaul** [anitab-org/mentorship-backend#230]
## Description
As a Developer,
I need to work with and test the mentorship-backend on my local machine,
so that I can better understand the application and do exploratory testing.

## Acceptance Criteria
- A new developer should be able to clone, build and run the mentorship-backend using only content and links in the README, including:
-- Testing APIs using the Postman collection and/or Swagger (OpenAPI) document
-- POST to the Registration API, to add a new user to the locally running backend
-- Use the API to log in as an administrator, and obtaining an Authorization token to execute other APIs via Postman or Swagger
-- Running commands to explore the backend database
-- Setting up the local environment so that new users can be added, with email verification (described in this wiki page [Register a New User](https://github.com/systers/mentorship-backend/wiki/Register-a-new-user-using-Swagger)

### Update [Required]
- Update README to include headings and links to relevant information that will allow backend developers to run and test the mentorship-backend APIs and database in their local environment

## Definition of Done
- [ ] All of the required items are completed.
- [ ] The README instructions are successfully tested by another contributor or tester starting from a clean 'clone and build', demonstrating that:
-- backend APIs can be executed locally via Postman or Swagger, and 
-- the local database can be queried
using only the information and links found in the README.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

**Comment by isabelcosta** [comment]
@PaulaPaul I really like this issue! thank you for reporting this 🎉

I just have a couple of comments:
- why not split this into multiple issues, one per section of the README: 1 for the "test with swagger and Postman" section, another 1 for "querying the local database" section, another 1 for improving the "Setup and Run" section
- to avoid having a really really long README, for example the section that shows how to test the API with swagger does not need to be too extensive on the README. There could be the very basics on the README, and if we want to be more extensive, we could create separate markdown files on the `/docs` folder on the repo.

I posted this here as well (a part from Slack) for documentation purposes.

Let me know what do you think?

**Comment by vaibhavarora102** [comment]
@PaulaPaul @isabelcosta  is this still open and can I try my hands on it
thanks!

**Comment by SanketDG** [comment]
@vaibhavarora102 This is largely a meta issue which itself can be broken into several issues, I'd like to take @isabelcosta's thoughts on this before assigning anyone

**Comment by isabelcosta** [comment]
@vaibhavarora102 @SanketDG Oh I remember this from GCI 🤔 Though right now I don't understand. I think this should be broken into multiple issues indeed! An issue for each sub-bullet of the acceptance criteria. cc @anitab-org/mentorship-backend-maintainers

**Comment by vj-codes** [comment]
Clsoing as readme has these parts included now
