### ISSUE TITLE
Show if user is currently on a relation on the GET /users API for each user

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#232]
## Description

As a developer consuming the backend api,
I need to know if the user is already occupied (in a current relation),
so that I can provide a better experience on the backend, showing the user is not currently available.

The idea is to return for each user entry from GET /users API response, a new value indicating if the user is available for new mentorship relations. For example, if the user is already enrolled in a current mentorship relation then the value should be `false`.

The value returned could had the following JSON key `is_available`.

To do this, the logic will be probably contained on the UserDAO class, and you won't have to add anything to the User API code.

_this issue is intended for the Google Code-in participants, it can be released after the program ends on January 23rd_

## Mocks

The GET /users should have an additional returning value, like this:
```
{
    (...),
    "is_available": true,
    (...)
}
```

### Update [Required]
- [ ] Return a new value on the GET /users API
### Enhancement to Update [Optional]
- [ ] Create at least one test for this new feature

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by bartekpacia** [comment]
I'd like to work on this thing. Is it going to be made into a task or can I start now?
