### ISSUE TITLE
Fix lint errors.

### ISSUE THREAD

**Issue by namrata-jha** [anitab-org/mentorship-backend#234]
## Description
Maintainers need to remove lint errors in code to improve code structure and application performance.

## Acceptance Criteria
One category of lint error has to be removed.

## Definition of Done
- [ ] At least one lint error category is removed.
- [ ] Approval by 1 mentor.

**Comment by sara-02** [comment]
@namrata-jha Can you please run the code against a standard Python Linter and repo the set of errors in a gist.

**Comment by sara-02** [comment]
Possible duplicate of https://github.com/systers/mentorship-backend/issues/178

**Comment by namrata-jha** [comment]
I intended to make this a task in mentorship-android for GCI, my bad. Will delete it.

**Comment by isabelcosta** [comment]
@namrata-jha you can still create this task on the GCI board :)
