### ISSUE TITLE
Improve Environment Variables guide

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#235]
**Is your feature request related to a problem? Please describe.**
I just think it'd be helpful for all of us to have a full description on how to setup dev environment for this project. 

**Describe the solution you'd like**
I'd like to see something like this (below) included in [the guide](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md) at `/docs/environment-variables.md`

> To properly set up `dev` environment, an **email address is required**. We recommend creating a temporary email (e.g.: Gmail, Mail.com, etc)

Also, I think that the current description of `MAIL_DEFAULT_SENDER` and `APP_MAIL_USERNAME` is insufficient. I'd change it to:

> `MAIL_DEFAULT_SENDER` Email used to send email verification emails. This has to be a real email address that you've got access to. This is in string format.

> `APP_MAIL_USERNAME` Username of the email account used to send verification emails. It must be equal to part of the email address before the `@` sign. For example, if your email address is `johnclark@gmail.com`, this will be `johnclark`. This is in string format.

**Additional context**

Conversation from which this info comes: https://systers-opensource.zulipchat.com/#narrow/stream/212722-gci/topic/Mentorship.20Backend.20Setup

**Comment by sara-02** [comment]
@bartekpacia I would suggest using pointing to the https://myaccount.google.com/lesssecureapps link instead. And adding a point that similar features will be available for respective email services as well.

**Comment by bartekpacia** [comment]
Yeah, official docs would be better, indeed.

**Comment by gaurivn** [comment]
I added the Status: On Hold since I thought of including this issue for the upcoming Open Source Hack.

**Comment by isabelcosta** [comment]
@gaurivn just as a note, this issue description could be updated, because, now with the MOCK_EMAIL env var we don't need someone to have an email, so that is not needed for example.

**Comment by gaurivn** [comment]
> @gaurivn just as a note, this issue description could be updated, because, now with the MOCK_EMAIL env var we don't need someone to have an email, so that is not needed for example.

@isabelcosta, I'm unable to edit the issue title or description, please tell what to do

**Comment by isabelcosta** [comment]
@gaurivn I just improved the description :) So now I think its good! Thank you so much for helping this.

**Comment by vj-codes** [comment]
I would like to work on this for OSH @gaurivn

**Comment by gaurivn** [comment]
Hi @vj-codes, since OSH starts on Sept 1st, 2020, pls do come back and comment here on that day, will assign you :)

**Comment by vj-codes** [comment]
@anna4j  @gaurivn @PrashanthPuneriya I would like to work on this

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by anna4j** [comment]
> @anna4j @gaurivn @PrashanthPuneriya I would like to work on this

Go ahead :)

**Comment by Anmollenka** [comment]
I will like to work on this issue as a part of OSH.Can you please assign this issue to me?Thank You.

**Comment by anna4j** [comment]
@Anmollenka this issue has already been assigned. The status available tag wasn't removed by mistake 😅
Please look for another issue :)

**Comment by soumyjain14** [comment]
HI, is there any task which can be assigned to me?

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same
