### ISSUE TITLE
[Typos][Set2]Fix Minor typos in models/user.py

### ISSUE THREAD

**Issue by sara-02** [anitab-org/mentorship-backend#249]
**Describe the bug**
The `models/user.py` has 2 typos that need fixing.
* https://github.com/systers/mentorship-backend/blob/develop/app/database/models/user.py#L60 `extra `"` in the docstring should be 3, not 4
* https://github.com/systers/mentorship-backend/blob/develop/app/database/models/user.py#L112 `should be `user name is` not` id`

**Expected result**
All the above typos to be fixed in the `user.py` as a single commit.

**Estimated time**
1/2 hour

**Comment by mdterrenal** [comment]
Hi! Is this issue available? I would love to work on it if it hasn't been resolved already!

**Comment by sara-02** [comment]
Hello, @mdterrenal as you can see the task is currently labelled Program: GCI which means it can be used during the contest by the participants. If you are participating in GCI feel free to work on it. Else you will have to wait until 21st Jan to work on this task. I suggest you can pick some tasks not labelled GCI for the time being.

**Comment by mdterrenal** [comment]
My apologies @sara-02 , I didn't realize that that was what the label was used for. This is my first time contributing to open source so I got a bit too excited. I'll be sure to look at another task to work on for now. Thank you!
