### ISSUE TITLE
Fix typos in messages.py

### ISSUE THREAD

**Issue by sara-02** [anitab-org/mentorship-backend#250]
**Describe the bug**
The `messages.py` has a few typos/misplaced words.  We want to bring some consistency in the messages we report to the user, by fixing these.

**Add space**
* Add a space after `profile` https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L77 similar to how it is for other multi-line messages.

**Put the word username first**
The message should be `Username field is missing.` and not `The field username is missing.` This will be more consistent with the messages around it.  
https://github.com/systers/mentorship-backend/blob/develop/app/messages.py#L31

**Expected result**
All the above typos to be fixed in the `messages.py` as a single commit.

**Estimated time**
1/2 hour

**Comment by isabelcosta** [comment]
I think this is fixed already with a GCI task, byt checking the file mentioned, so I will close the issue now
