### ISSUE TITLE
Remove pycodestyle warnings from app/api

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#261]
**Describe the bug**
The codebase doesn't conform to the rules of [pycodestyle](http://pycodestyle.pycqa.org/en/latest)

**To Reproduce**
1. Open command line in project's root directory
2. Run `pycodestyle app/api`
3. See lots of code style warnings being reported

**Expected behavior**
Output of `pycodestyle app/api` should return no output.

**Comment by vj-codes** [comment]
Closing as the code is refactored using black
