### ISSUE TITLE
Remove pycodestyle warnings in app/database

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#262]
**Describe the bug**
The codebase doesn't follow code style recommended by [pycodestyle](http://pycodestyle.pycqa.org/en/latest)

**To Reproduce**
1. Open terminal in project's root directory
2. Run `pycodestyle app/database`
3. See lots of code style warnings being reported

**Expected behavior**
Output of `pycodestyle app/database` should return no output.

**Comment by mdterrenal** [comment]
Hi! Has this issue been resolved? I'm new to contributing to open source and I would love to work on this as my first issue if it hasn't been resolved yet!

**Comment by bartekpacia** [comment]
@mdterrenal Hi. According to my knowledge, it wasn't.

BTW Are you participating in [Google Code-in](https://codein.withgoogle.com) or *just want to contribute*?

**Comment by mdterrenal** [comment]
@bartekpacia Awesome, I'll start working on this issue then.

I'm not participating in Google Code-in, but I am interested in working with the organization for Google Summer of Code this upcoming summer. Regardless, I'd like to contribute to gain more experience in working with open source.

**Comment by bartekpacia** [comment]
Sure, good luck:)
If you have some problems/questions, you may want to visit [Systers Slack](http://systers.io/slack-systers-opensource/) as it is where all project maintainers are.
