### ISSUE TITLE
Use python_dotenv to load environment variables

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#281]
This is a small feature suggestion, one of those that require minimal effort but greatly increase out productivity and happinees :)

### Currently
In `requirements.txt` we already have `python-dotenv` listed, but...we're not using it. Environmental variables have to be exported manually from `.env` file.

### What I suggest?
Adding a few lines of code (look #282) and make life easier

Together with this issue I'm submitting a PR (look below)
If it gets merged, it will let us all benefit from it :)

**Comment by isabelcosta** [comment]
I don't quite understand if this is really needed.
From what I know when I run the flask app the variables are automatically imported. I only use `.env` to import the variables. @bartekpacia 

Maybe I am not aware of something about my configuration that allows that 🤔

**Comment by bartekpacia** [comment]
Hmm...
From what I remember, thorough the whole GCI I kept pasting this 2 lines to every new branch when I needed to access env variables. I guess it didn't work for me in the same way it works for you.
If you think everything's fine, feel free to close it.

**Comment by vj-codes** [comment]
Closing as python_dotenv works as explected no errors
