### ISSUE TITLE
Dependabot integration 

### ISSUE THREAD

**Issue by daksha-aeer** [anitab-org/mentorship-backend#284]
**Is your feature request related to a problem? Please describe.**
The backend python project uses **requirements.txt** file to install dependencies in virtual environment. Currently the dependency versions are set as fixed in the file using == sign
```
aniso8601==3.0.0
APScheduler==3.5.1
awsebcli==3.14.1
blessed==1.15.0
blinker==1.4
botocore==1.10.48
cached-property==1.4.3
cement==2.8.2
```
The issue is that the dependencies may become outdated with time. We may also miss out on new features and security updates as well.

**Describe the solution you'd like**
I've seen some github projects use **Dependabot**. According to the description it automates dependency updates. This way the project will always have latest working packages. 
![image](https://user-images.githubusercontent.com/50169911/70891487-5458f080-200d-11ea-8d1c-de79c62a6796.png)

**Describe alternatives you've considered**
Not considered

**Additional context**
I think this will be an awesome addition to the backend. I'm ready to work on this part.

**Comment by bartekpacia** [comment]
This would be really cool, I use PyCharm and 3/4 of all dependencies are outdated.

**Comment by vj-codes** [comment]
Closing since Dependabot is integrated now.

**Comment by SanketDG** [comment]
I don't see the updates anymore, @isabelcosta was it switched off?

**Comment by isabelcosta** [comment]
@SanketDG nop. I have definitely not switch it off 🤔
