### ISSUE TITLE
fix: add missing variable message on line 177 mentorship-relation.py

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#286]
### Description

As a developer of the backend,
I need to avoid misspelling,
so that I can make sure everyone has a good experience reading the code.

This issue is about the missing "messages" on line 177 of mentorship-relation.py (before "CANT_ACCEPT_UNINVOLVED_MENTOR_RELATION")

### Acceptance Criteria

**Update [Required]**
- [x] Add "messages" to line 177

**Definition of Done**
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Estimation**

- [x] 15 min

**Comment by isabelcosta** [comment]
@mtreacy002 thank you for creating the issue and linking the Pull Request to the appropriate issue.
This is a great issue for you to start contributing to this repo :)

I just want to ask to follow one of our issue templates. Some maybe appropriate would be either [bug report](https://github.com/systers/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) or [user story](https://github.com/systers/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/user-story.md). Let me know if you need any help with updating the issue (with the action or filling user story, ...). This is a nice to have, but that can help you keep this in mind for future issues.

**Comment by mtreacy002** [comment]
Thanks, for the advice, @isabelcosta. I'll update it now.

**Comment by isabelcosta** [comment]
@mtreacy002 great work! thank you for updating the issue :D I marked the approval by mentor ;)
