### ISSUE TITLE
Create .env.template file

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#288]
## Description
As a developer,
I need `.env.template` file,
so that I can minimize work while setting up the project environment variables.

The idea is to create a `.env.template` file to make developer's life easier while setting up the environment variables of the project, by having a template ready to use and place the variables.

### Update [Required]
- [ ] Create `.env.template` file with placeholders for environment variables
- [ ] Update README to indicate that the template exists to be used

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation

1 hour

**Comment by mtreacy002** [comment]
Hi @isabelcosta, can I work on this one? Am I still allowed to take on "First Timers Only" issues or I should move on to non-first-timers now? :-D

**Comment by isabelcosta** [comment]
@mtreacy002 You already contributed to a First timers only, and I'm actually going to merge it as soon as I can. So yes moving to a non first timers would be better. Also this can eventually be used to the contest we're going through now - GCI. Thank you for taking the label into consideration!
I can forward you to other ones:
- https://github.com/systers/mentorship-backend/issues/266 (creating a docker file)
- https://github.com/systers/mentorship-backend/issues/141 (tests for assigning admin api)
- https://github.com/systers/mentorship-backend/issues/178 (there is a PR open, but needs changes, you could take this one and continue the other contributor work)
- you can also come up with your own ideas that could improve the project, look to the code and see what can be improved in this project (we're always open to ideas)!

**Comment by mtreacy002** [comment]
Cool... I'll look at the other issues then. Thanks again, @isabelcosta .

**Comment by PratibhaShrivastav** [comment]
Can I work on this ?
