### ISSUE TITLE
Deprecation warnings when running tests

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#290]
**Describe the bug**
When I type `python -m unittest discover tests`, I see following warnings being printed". Everything works fine, but well, this informs us that in the future, some problems may arise and we should update to newer versions of `sqlalchemy`.
```
/Users/bartekpacia/dev/python/mentorship-backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:374: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  args = inspect.formatargspec(*spec)
/Users/bartekpacia/dev/python/mentorship-backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:384: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  spec[2], None, spec[4])
/Users/bartekpacia/dev/python/mentorship-backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:405: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  formatvalue=lambda x: '=' + x)
```

**To Reproduce**
`$ python -m unittest discover tests`

**Expected behavior**
No warnings should be displayed.

**Screenshots**
<img width="776" alt="Zrzut ekranu 2019-12-17 o 09 52 58" src="https://user-images.githubusercontent.com/40357511/70980142-17473980-20b3-11ea-9e2f-b546cde67ffc.png">

**Comment by daksha-aeer** [comment]
I've noticed this warning as well. As an interim measure we could update the dependencies and perform tests to ensure everything works. But I think for long term we should work on dependabot integration (issue #284 )

**Comment by bartekpacia** [comment]
I agree @daksha-aeer.

If you integrate dependabot, that'd be a great benefit for everyone - we could do more interesting things instead of worrying about dependencies versions.

As of now, I'll submit a quick PR to have a ready solution, let's hope there won't be much issues.

**Comment by vj-codes** [comment]
CLosing as no warnings are generated now and dependabot is integrated
