### ISSUE TITLE
Use GraphQL API for backend

### ISSUE THREAD

**Issue by daksha-aeer** [anitab-org/mentorship-backend#296]
**Is your feature request related to a problem? Please describe.**
Mentorship backend has currently over 25+ endpoints. I feel this will be more complex to maintain as the app grows. Many of the enpoints are also doing similar tasks
```
GET users
GET users/{user_id}

GET /mentorship_relations
GET /mentorship_relations/current
GET /mentorship_relations/past
GET /mentorship_relations/pending
```

**Describe the solution you'd like**
While working on a task to research about REST APIs, I came to know about a new technology called GraphQL. Supposedly 1 GraphQL endpoint do the job of multiple REST endpoints. This can greatly simplify development and maintenance of mentorship system app. I'm aware that this will be like re-inventing the wheel, but this could be implemented in the long term.

![image](https://user-images.githubusercontent.com/50169911/71179285-dd825880-2295-11ea-89d7-6f266f0d3285.png)

### Advantages
1. Single endpoint
2. No need of API versions
3. Better for poor internet because fewer calls have to be made

Source: https://graphql.org/

**Describe alternatives you've considered**
There's something called **SOAP API** as well. But it is not very popular due to its complexity.

**Additional context**
None

**Comment by isabelcosta** [comment]
@daksha-aeer this is a great idea! I've heard about this GraphQL for some time, but I haven't still figured out how this is used. So thank you for creating this issue 🎉

**Comment by prachi1210** [comment]
GraphQL is mainly for consolidating multiple frontends with different payloads. I strongly feel that we shouldn't use technology for the sake of using it. My vote is a no.

**Comment by isabelcosta** [comment]
Thank you so much @prachi1210 for voicing your opinion here in the issue!
I understand now this might be an over engineering situation.

Although I recognise that these APIs could be simplified:
```
GET /mentorship_relations
GET /mentorship_relations/current
GET /mentorship_relations/past
GET /mentorship_relations/pending
```

Thats why I created issue #329, that can solve this particular situation mentioned above, and eventually deprecate those endpoints.

@daksha-aeer what do you think?

**Comment by daksha-aeer** [comment]
@isabelcosta consolidating some of the endpoints is cool

**Comment by abhishekmishragithub** [comment]
Hello Folks,
This seems interesting. I can help in the migration REST API to GraphQL.
Would like to know, how urgent is this issue?
Migration might take a little longer as ita backend change.

**Comment by isabelcosta** [comment]
@abhishekmishragithub I will close this issue as this is not really a priority nor a desired feature for the project at the moment :) Thank you for voicing your opinion though! 🙏

**Comment by abhishekmishragithub** [comment]
> @abhishekmishragithub I will close this issue as this is not really a priority nor a desired feature for the project at the moment :) Thank you for voicing your opinion though! 🙏 

Okay. Thanks 😊
