### ISSUE TITLE
Add a gitignore file to repo.

### ISSUE THREAD

**Issue by m-murad** [anitab-org/mentorship-backend#3]
## Description
Add the `.gitignore` file. The latest version of the file can be found [here](https://github.com/github/gitignore/blob/master/Python.gitignore)

### Update [Required]
- [x] `.gitignore` file is added to the repo

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by m-murad** [comment]
@isabelcosta 
Before you start working please complete this. We don't want unnecessary files to be added to the repo.

**Comment by isabelcosta** [comment]
@m-murad yes!

**Comment by isabelcosta** [comment]
@m-murad besides this can I add ".idea" to it as well, to avoid this folder being added when I use PyCharm?

**Comment by m-murad** [comment]
Fixed in #13
