### ISSUE TITLE
Create an API Endpoint to Count Pending Mentorship Relations

### ISSUE THREAD

**Issue by Anjalizi** [anitab-org/mentorship-backend#320]
**Describe the solution you'd like**
Create a new API Endpoint at GET/mentorship_relations/count_pending which counts the number of pending mentorship relations of the current user. Return a dictionary response with key "count" and value as the number of pending mentorship relations.

**Additional context**
This issue has been created for students participating in GCI'19.

**Comment by isabelcosta** [comment]
I will close this issue, since this is not a desirable issue for the app, and it was only used for Google Code-in contest.
