### ISSUE TITLE
Fetch GRAVATAR for User profile using email

### ISSUE THREAD

**Issue by xprilion** [anitab-org/mentorship-backend#326]
**Is your feature request related to a problem? Please describe.**
Currently, the users have an option to set a URL for their profile pictures. Another PR is underway for using AWS for the same, by uploading the images first. However, for a quicker option, it will be good to fetch the profile pictures from GRAVATAR.

Instead of fetching and saving the image, one just needs to grab the URL from GRAVATAR and store it into the profile picture field on the database.

**Describe the solution you'd like**
Fetch GRAVATAR URL using user email and save into database.

**Comment by bartekpacia** [comment]
I think these changes will require: 
- adding new field `gravatar_url` to UserModel. 
- updating API endpoints (`GET /user`, `PUT /user`, `GET /users`)
- updating related API docs

@xprilion Anything more?

**Comment by xprilion** [comment]
No @bartekpacia, you do not need to add another field to the UserModel. Please use the `photo_url` field to store the GRAVATAR URL. You'll then not have to modify any of the endpoints, only the way they are handled.

**Comment by bartekpacia** [comment]
@xprilion This makes sense. I'll fix it ASAP.

**Comment by vj-codes** [comment]
Closing as other approaches also need to be discussed and aws cannot be used right now
