### ISSUE TITLE
Alternative signing options

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#341]
## Description
As a user,
I need to be able to sign in through Google,
so that I don't have to remember yet another password.

Google Cloud Platform seems like the go-to solution.

I also think [Firebase](https://firebase.google.com/docs/auth/admin) has APIs for accomplishing such task, but I'm not sure. I'll be googling this topic and will be grateful if you have any suggestions.

## Mocks
This PR targets backend, so no mocks.

## Acceptance Criteria
User is able to sign in by clicking `Sign in with Google`.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## ETA
4 hours

**Comment by isabelcosta** [comment]
What is ETA @bartekpacia ?
Thank you for creating this issue!
This was indeed part of the future idea for the app, having third party authentication, I'm just not sure of how to go about this right now 🤔 
This specific issue is related with Google Sign in option right? Can you update the issue title to reflect that please?

**Comment by bartekpacia** [comment]
@isabelcosta  Estimated Time Arrival (it's a military term). I accidentaly removed this section and forgot how it was named😂.

And yes, as of now I mean only Google. In the future, when we will have some fundaments set up and more experience, we can add other auth providers like Facebook, Twitter, LinkedIn or GitHub. Or Apple - it's highly recommended by Apple to provide their sign-in method on iOS (and I think there are some plans to release iOS version in the future).

Regarding implementation, I'm reading about all this stuff currently. I'll try to send some early PRs in the upcoming days.

**Comment by alapan-sau** [comment]
I would like to work on this for OSH.

**Comment by alapan-sau** [comment]
Can this issue be assigned to me for OSH ?

**Comment by Anmollenka** [comment]
I would like to work on this issue for OSH.Can you assign it to me??Thank You.

**Comment by codesankalp** [comment]
@bartekpacia I have integrated many third party sites login like google, Facebook in many sites. So I want to work on this issue. Please assign this issue to me.

**Comment by priyanshuone6** [comment]
Hey, can you please assign this issue to me

**Comment by ankit-saraf** [comment]
@bartekpacia Please assign it to me.

**Comment by bartekpacia** [comment]
I don't have permission.

**Comment by ankit-saraf** [comment]
@vj-codes Please assign it to me or we can raise a fresh issue regarding this.

**Comment by ankit-saraf** [comment]
> I don't have permission.

Oh! No problem

**Comment by vj-codes** [comment]
@anna4j since you have labelled it as OSH issue , is this available? Also how is #761 different from this?

**Comment by vj-codes** [comment]
> I don't have permission.

@bartekpacia is this the only issue that you didn't work on during GCI just kidding 😆

**Comment by bartekpacia** [comment]
Hahah @vj-codes. I had many ideas but not enough time
