### ISSUE TITLE
Improve Admin API doc string to improve Swagger documentation

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#344]
## Description
As a developer that uses the Swagger UI,
I need good API documentation on Swagger,
so that I can understand how to properly use the backend API.

The Admin API resources don't have enough doc strings to reflect their usage or purpose on Swagger UI. By adding doc strings under the respective REST methods, you'll be updating the Swagger UI at the same time. E.g.: POST /login has a full description on Swagger.

Improve doc strings for every resource/endpoint of Admin API.
**Hint:** the file where you might have to do these changes is [app/api/resources/admin.py](https://github.com/systers/mentorship-backend/blob/develop/app/api/resources/admin.py) file. Be mindful to explain important parts of the logic behind the APIs, for example if an endpoint is only available to an existing admin.

### Update [Required]
- [ ] Improve doc strings for every resource/endpoint of Admin API. 

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by lorryaze** [comment]
Can I work on this?

**Comment by isabelcosta** [comment]
@lorryaze I am noticing now that i think this was solved with PR #405 , I can leave this open for you to improve even more. Is there anything you think could be added to the file mentioned in the issue?

**Comment by lorryaze** [comment]
> @lorryaze I am noticing now that i think this was solved with PR #405 , I can leave this open for you to improve even more. Is there anything you think could be added to the file mentioned in the issue?

No problem, I will take a look and if I find something that can be included I will let you know! :)

**Comment by pallavisavant** [comment]
I have participated for OSH....if this is still available can i take up this one... as i haven't been assigned any under documentation...Thanks.

**Comment by vj-codes** [comment]
Closing as PR #405 fixed this and there was no response for improvements to be added
