### ISSUE TITLE
Improve email verification html style

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#346]
## Description

This task was suggested by @annabauza

This is a creative task to make verification e-mail more elegant. Please use your creativity and aesthetics skills. Be original!

The file you should update is `/templates/email_confirmation.html`

Suggestions:
* Add some styling to make it feel more colourful 
* Use some icons with links to social media with more elegant footer
* Change text of link to `click here`
* The prettier, the better, please feel free to use own words. Be creative and original!

### Update [Required]
- [ ] Improve the email template style

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Prakash-sa** [comment]
@isabelcosta can i work on it?

**Comment by alapan-sau** [comment]
Can I work on this issue?

**Comment by SanketDG** [comment]
@alapan-sau Sorry for the delay, I have assigned you

**Comment by yash2189** [comment]
@SanketDG   Is this available as a part of OSH?

**Comment by SanketDG** [comment]
@yash2189 It sure can be, do you know what needs to be done in this issue? This could very much be changed to have a UI mock first and then coding it.

**Comment by yash2189** [comment]
I can try creating a mockup of the page using Figma and then code accordingly after it has been reviewed by you :)

**Comment by yash2189** [comment]
@SanketDG I have created a mockup in figma should I share the link of the same?

**Comment by SanketDG** [comment]
@yash2189 Sure absolutely!

**Comment by yash2189** [comment]
@SanketDG  Please check this [Figma](https://www.figma.com/file/97H3GWpFWBiCbZWJOYTw1C/Email_verification?node-id=0%3A1)  link for the mockup :)
I have added icons in footer that redirects to respective social media links for communication.
Do suggest changes if any.

**Comment by SanketDG** [comment]
This looks really good @yash2189 

I apologize for sort of derailing you here, but I should have mentioned that there are existing issues #768 #769 #770 that you can take as inspiration.

We may want to stick to some standard designs as mentioned in those issues, feel free to just start coding if it's simple enough :slightly_smiling_face: 

Pinging @isabelcosta for some pointers.

**Comment by yash2189** [comment]
So if I make a PR for the same will it be accepted @SanketDG ?
Should I start coding the same design if it's complies to the branding guidelines?
Where should I add the CSS file for this particular issue?

**Comment by SanketDG** [comment]
> Should I start coding the same design if it's complies to the branding guidelines?

Yes ofcourse, if it complies though.

> Where should I add the CSS file for this particular issue?

In the same place as the html, that's fine.

**Comment by isabelcosta** [comment]
+1 to @SanketDG

**Comment by vj-codes** [comment]
Closing as it's same as #768
