### ISSUE TITLE
Internal Server Error when sending relationship request

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#383]
**Describe the bug**
I encountered a strange and possibly unintended behavior while developing Mentorship Client. I accidentaly multiplied timestamp by 1000 (I actually wanted to divide it by 1000).

**To Reproduce**
1. Go to http://systers-mentorship-dev.eu-central-1.elasticbeanstalk.com/
2. Open Mentorship Relation tab
3. Expand first endpoint – `POST /mentorship_relation/send_request`
4. Enter valid mentor_id and mentee_id, pass valid JWT and valid notes.
5. Pass too big value as end_date.
6. Admire undocumented status code 500.

**Expected behavior**
`400 Bad Request` should be returned with helpful message e.g "end_date too big".

**Screenshots**
![internal server error](https://user-images.githubusercontent.com/40357511/71788324-77316000-3021-11ea-84eb-95bd80d200bb.png)

**Comment by isabelcosta** [comment]
Very good issue description! The steps to reproduce are very clear 👏 
Thank you for reporting this bug @bartekpacia !
