### ISSUE TITLE
Recent achievements retrieving the first three achievements.

### ISSUE THREAD

**Issue by rudrakshjhalanii07** [anitab-org/mentorship-backend#393]
**Describe the bug**
The achievements retrieved from `/home` endpoint retrieves the first three achievements of a user. Instead it should retrieve the lastest three achievements of the user, i.e the recent ones.

**To Reproduce**
1. Go to '/home'
2. Enter the auth token and execute the call.
3. Scroll down to 'achievement section'

**Expected behavior**
The achievements section should contain the recent three achievements and not the first three.

**Screenshots**

**Comment by sankha555** [comment]
@Hardik0403 @isabelcosta If this issue is still open, can I please work on it? Thanks!

**Comment by sankha555** [comment]
I am facing a problem in this issue. Although I have figured out where the bug in the code lies, I am unable to test it as I cannot gain access to the account of any of the test users (user1, user2, etc). I tried logging in using use1 as username and user1_pwd as password, but it shows wrong username and password. Any help on this??

**Comment by SanketDG** [comment]
I am not sure what test users mean here but you can just create a new user and work with that. It also gives you enough some experience to work with the existing APIs.

**Comment by sankha555** [comment]
@SanketDG  I have made a PR regarding the issue. Could you kindly review it and let me know if some changes are required? Thanks!

**Comment by devkapilbansal** [comment]
Adding `first timers only` as it is relatively easy

**Comment by devkapilbansal** [comment]
Some tests are needed too to ensure the changes done here are correct.

**Comment by diananova** [comment]
can I work on this?

**Comment by devkapilbansal** [comment]
Sure @diananova 
Good luck 😃
