### ISSUE TITLE
Return user's creation time from GET /users endpoints

### ISSUE THREAD

**Issue by bartekpacia** [anitab-org/mentorship-backend#395]
**Is your feature request related to a problem? Please describe.**
I think that the API should include the user's creation date. The List of users returned now is already sorted by creation date in descending order, so why not include that information with the response?

**Describe the solution you'd like**
I'd like every `User` JSON objects returned from `GET /users` and `GET /users/verified` to have `creation_time` property, represented as timestamp integer.

**Describe alternatives you've considered**
I'm not aware of any viable alternatives.

**Additional context**
Encountered while doing [this task](https://codein.withgoogle.com/dashboard/task-instances/5998011734294528/).

**Comment by arpitjadiya** [comment]
I am a first timer .Can I take up this issue?

**Comment by isabelcosta** [comment]
@arpitjadiya go ahead :)

**Comment by theOpetunde** [comment]
@arpitjadiya have you issued a PR yet for this issue? I'd also like to take on a "first-timers-only" issue.

**Comment by arpitjadiya** [comment]
@theOpetunde I haven't issued PR till now

**Comment by arpitjadiya** [comment]
@bartekpacia can you please tell how creation time is different from registration_time  ?

**Comment by isabelcosta** [comment]
@arpitjadiya its the same value :) you can assume that

**Comment by isabelcosta** [comment]
@theOpetunde there is more first timers only issue :) what do you think of #419 ? We can help you with any doubt you might have :)

**Comment by arpitjadiya** [comment]
@isabelcosta I created Pull Request, can you please see it?

**Comment by Ruchika06** [comment]
@isabelcosta Is this issue available?

**Comment by isabelcosta** [comment]
@Ruchika06 I forgot to update the assignee, this is assigned to @arpitjadiya :)

**Comment by Anmollenka** [comment]
I would like to work on this issue as a part of OSH.Can you assign it to me?Thank You.

**Comment by RiaDhanani** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by arjungarg07** [comment]
@isabelcosta Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by justdvnsh** [comment]
@vj-codes I'd like to take this issue up !!

**Comment by vj-codes** [comment]
@justdvnsh are you contributing for the first time to this repo? If yes ,then  only I can assign you

**Comment by justdvnsh** [comment]
@vj-codes Yeah. This is my first time in this repo.

**Comment by isabelcosta** [comment]
@Anmollenka @RiaDhanani are you still interested in contributing to this issue?
If no response in 3 days, @justdvnsh you can send a PR to this if you still want.
cc @vj-codes

**Comment by RiaDhanani** [comment]
@isabelcosta Yes. I just wanted to understand in a little more detail what the issue was about.

**Comment by isabelcosta** [comment]
@RiaDhanani no problem, so the idea is to return along with user data, the user creation timestamp, which is part of the `UserModel`.
Here's an example of the user response data from `GET /users` API:

![image](https://user-images.githubusercontent.com/11148726/102898449-6d3a8400-4461-11eb-9773-5b515c5c4f05.png)

Does it make sense?

**Comment by diananova** [comment]
If @RiaDhanani doesn't respond, I can work on this!

**Comment by vj-codes** [comment]
@RiaDhanani hey are you interested to work on this ? Otherwise the issue will be assigned to the contributor who claimed in next:)

**Comment by vj-codes** [comment]
@diananova hey welcome to the community! 
According to the community guidelines a contributor cannot create an PR for an issue until that specific issue is assigned to you. 
I will be closing the PR for now but if @RiaDhanani doesn't respond within a day or two this issue will be assigned to you and the PR you've created will be reopened . 
How's that? If you have any more questions do update;)

**Comment by diananova** [comment]
@vj-codes oh sorry! Sounds great, thank you 😊

**Comment by vj-codes** [comment]
Assigning you @diananova 
Happy coding!
