### ISSUE TITLE
Create an API to register a new user.

### ISSUE THREAD

**Issue by m-murad** [anitab-org/mentorship-backend#4]
## Description
Create an API using which the user can register on the platform.

- Required fields: email, username, password, name, security question, security answer, terms and conditions check
- Error message specifying what is wrong with the POST data. E.g.: if the users do not check terms and conditions, an error message must be returned indicating that the user must have this checked
- Endpoint: POST /register
- Password must be saved as a hash, and NOT in plain text

### Update [Required]
- [ ] A new user is able to register on the system.

## Definition of Done
- [ ] PR should be sent to the `gsoc18-code` branch
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

**Comment by isabelcosta** [comment]
I'm using these  [security functions](http://werkzeug.pocoo.org/docs/0.14/utils/#module-werkzeug.security), I found from [this snippet](http://flask.pocoo.org/snippets/54/) to save the hash of the password

**Comment by m-murad** [comment]
Fixed in #14
