### ISSUE TITLE
Update README with project description

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#40]
## Description
As a new contributor,
I need to see a README with project's mission and description,
so that I can learn about the Mentorship System project.

### Update
- [x] Updated README with Mentorship System project description (what is all about, the motivation, ...)
- [x] Link to Systers #mentorship-system channel for further details
- [x] Define proper text to describe the project

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by isabelcosta** [comment]
@Dilu9218 @m-murad created this as a low priority item, to do when I'm free of other more important action items

**Comment by riddhik84** [comment]
Hi @isabelcosta Can I work on this issue?

**Comment by isabelcosta** [comment]
I'm sorry @riddhik84  but this issue is already solved since README already contains the information required in the issue. I forgot to close this issue. Can you take a look at other issues? I'll make some available on the Android project if you're interested in it :)

**Comment by isabelcosta** [comment]
Solved with PR #140
