### ISSUE TITLE
Implement Algolia for search functionality

### ISSUE THREAD

**Issue by daksha-aeer** [anitab-org/mentorship-backend#401]
**Is your feature request related to a problem? Please describe.**
In a previous task I added search functionality to GET /users endpoint. This was done using Python ```whoosh``` library. However there are more powerful search tools available which should be implemented in the near future. For example, searching will be required for usernames, tasks and comments.

**Describe the solution you'd like**
Algolia is a cloud based search-as-a-service provider. With Algolia we do not have to worry about maintaining the search infrastructure. Instead it provides APIs and SDKs for uploading and querying data from their server. It has many cool features like keyword suggestion and analytics. Whoosh on the other hand is just a python library and is not very powerful.

**Describe alternatives you've considered**
ElasticSearch is an open sourcesearch engine software. It is also very feature rich and popular. However unlike Algolia we need to maintain our own elasticsearch server. It is more complicated to use.

**Additional context**
I added search functionality using **whoosh** in [this PR](https://github.com/systers/mentorship-backend/pull/397).

**Comment by vj-codes** [comment]
Closing since search feature is already implemented.

**Comment by SanketDG** [comment]
This is an aspect which can always be improved, but I agree, since we already implemented full text search, there is no point of using a cloud service. But this can always be improved, cloud or not.
