### ISSUE TITLE
Admin cannot revoke own admin status (not the sole admin)

### ISSUE THREAD

**Issue by daksha-aeer** [anitab-org/mentorship-backend#411]
**Describe the bug**
According to the test case page on Mentorship backend wiki, a user can revoke her own admin status when she's not the sole admin. However this is not supported by the backend.

**To Reproduce**
1. Run mentorship backend locally and assign two users as admin.
2. Make an admin user call POST /admin/remove to revoke her own admin status.
3. See error

**Expected behavior**
Either the backend code should be updated to reflect this feature. Otherwise the wiki should be edited and this item should be removed.

**Screenshots**
1. Wiki
![image](https://user-images.githubusercontent.com/50169911/72828693-308b6900-3ca3-11ea-891a-6229728ac53d.png)

2. More than one admin
![image](https://user-images.githubusercontent.com/50169911/72828720-3f721b80-3ca3-11ea-9fa7-4c001c1271cd.png)

3. Cannot revoke own status
![image](https://user-images.githubusercontent.com/50169911/72828722-44cf6600-3ca3-11ea-941c-aae2e874484e.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by isabelcosta** [comment]
Very good catch 👏👏👏  @daksha-aeer 
Thank you so much for reporting this bug!

**Comment by lmcicat** [comment]
Hey @isabelcosta ! Can @brainguo98 and I work on this while we wait for our other PRs to be reviewed?

**Comment by chahat99** [comment]
@isabelcosta Can I work on this issue?

**Comment by isabelcosta** [comment]
@lmcicat do you still wish to work on this? Or can I leave it to @chahat99 ?

**Comment by lmcicat** [comment]
@isabelcosta I'd love to do it :)

**Comment by isabelcosta** [comment]
Assigned to you @lmcicat :)
