### ISSUE TITLE
Create new GET /admins endpoint accessible to admins only

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#419]
## Description

As a admin of the app,
I need to have a List Admins endpoint,
so that I can get the list of fellow admins.

Admins should have quick access to other admins. E.g.: in case they wish to remove an admin.

Create a new endpoint `GET /admins`, only accessible to Admin users, that lists all users who are admin (excluding the user accessing the API). This should appear under the Admins namespace on Swagger UI.

Please, commit your change using our [Commit message Style Guide](https://github.com/systers/mentorship-backend/wiki/Commit-Message-Style-Guide).

### Update [Required]
- [ ] Create a new endpoint GET /admins
- [ ] Write at least one test showing your changes are working.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by naveennvrgup** [comment]
@isabelcosta  Is this issue still open? I would like to work on this (I am a first timer)

**Comment by isabelcosta** [comment]
@naveennvrgup Yes, you can work on this :) I'm glad you notice the `First Timers Only` label and understand what it is about :)
I will review your PR, once I have the chance
