### ISSUE TITLE
Change any reference from systers organization to anitab-org on README links

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#428]
## Description

Change any reference from `systers` to `anitab-org` on README links.
Places you might find this: TravisCI and commit style guide link

Please follow out [Commit Message Style Guide](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide)

### Update [Required]
- [ ] Change references from `systers` to `anitab-org`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 min

**Comment by theanjalisharmaaa** [comment]
Hey @isabelcosta, as I am starting off my open-source contribution journey, can you assign this task to me?

**Comment by isabelcosta** [comment]
Feel free to work on this @AnjaliSharma1234  :) Consider it assigned to you :)

**Comment by lorryaze** [comment]
Hi @isabelcosta can I take up this issue?

**Comment by lorryaze** [comment]
Hi @isabelcosta  can I take up this issue?

**Comment by isabelcosta** [comment]
@lorryaze sure you can work and submit a pull request

**Comment by lorryaze** [comment]
> @lorryaze sure you can work and submit a pull request

Isabel, as I can't open a pull request for the mentorship-backend wiki and I'm not allowed to change it on the master, I thought about making the wiki changes in another repository and then merge it. Do you think this is a good idea? I'm asking this because I belive that I need change the [Fork, Clone & Remote
](https://github.com/anitab-org/mentorship-backend/wiki/Fork,-Clone-&-Remote) for example and this file is on the wiki.

**Comment by isabelcosta** [comment]
No need to worry about the Wiki, for this issue :) You can just edit the README.md for now and send a Pull Request for it @lorryaze 
Thank you for clarifying your doubts 🙌

**Comment by yukienomiya** [comment]
Hi, is this issue still taken? Can I work on it?

**Comment by isabelcosta** [comment]
@lorryaze do you have any update about your work? Have you started already?
@yukienomiya lets see if we get an answer, and if not, then you can work on it

**Comment by lorryaze** [comment]
I'm sorry for the delay Isabel, I will submit my PR today.

Em seg, 2 de mar de 2020 17:44, Isabel Costa <notifications@github.com>
escreveu:

**Comment by isabelcosta** [comment]
No problem @lorryaze , just wanted to know if you were still interested. If you were not, I just would need you to let me know, but I would find no problem with that :)
