### ISSUE TITLE
fix: TypeError: can't concat Nonetype to bytes when you request for sign up.

### ISSUE THREAD

**Issue by Prakash-sa** [anitab-org/mentorship-backend#458]
**Describe the bug**
When you request for sign up you get  TypeError: can't concat Nonetype to bytes .

**To Reproduce**
1. Run server locally.
2. Request from mobile app in Sign up activity.
3. Click on Signup button

**Expected behavior**
Response code should be 200.

**Screenshots**

![IMG_20200225_100806](https://user-images.githubusercontent.com/35262074/75245917-bfd0f280-57f4-11ea-8ef1-7f34a744e09f.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Run server on local host. Connect your moblie and laptop on same wifi. Get an ip from ipconfig or ifconfig by typing into the terminal. Run server from laptop from that IP and modify the url in Android project. URl will be like http://192.168.xx.xx:<port>/ .

**Comment by isabelcosta** [comment]
@Prakash-sa for another contributor to be able to reproduce your bug, they will need to use the same request body you used to sign up a user and mimic the same conditions. can you please provide more context?

**Comment by Prakash-sa** [comment]
@isabelcosta done.

**Comment by isabelcosta** [comment]
@Prakash-sa what I meant by request body is the payload:
```
{
  "name": "string",
  "username": "string",
  "password": "string",
  "email": "string",
  "terms_and_conditions_checked": true,
  "need_mentoring": true,
  "available_to_mentor": true
}
```
So what are the values of this request body. I know you did this through the android application, so so if you could let us know about the input you've given to the Register screen, that would be great :)
As of now, I don't know how to reproduce your bug right now, since I want to test with the same exact data you did.

**Comment by Prakash-sa** [comment]
@isabelcosta  my bad.
This is the request code :- 
{
   "email":"prakashuu@gmail.com",
   "terms_and_conditions_checked":true,
   "available_to_mentor":true,
   "name":"Prakash Saini",
   "need_mentoring":false,
   "password":"123456789",
   "username":"sainiit"
}

**Comment by isabelcosta** [comment]
that info should be on the issue description ;)
I just tested `develop` branch code locally, with your data and I have not got an error 🤔 
You must have received an email recently, pointing to localhost:5000.

![image](https://user-images.githubusercontent.com/11148726/75279000-c0708580-5802-11ea-8545-20fa27537367.png)

**Comment by Prakash-sa** [comment]
@isabelcosta I am trying to figure out why i am geting error with the same response code.
![Screenshot from 2020-02-26 00-51-36](https://user-images.githubusercontent.com/35262074/75280046-b9fa0200-5832-11ea-93ab-eab876c743a9.png)

**Comment by isabelcosta** [comment]
I suspect that you may have your environment variables wrongly set. Here's the documentation:https://github.com/anitab-org/mentorship-backend/wiki/Environment-Variables @Prakash-sa

**Comment by sumit-badsara** [comment]
Yes @isabelcosta @Prakash-sa this is definitely issue due to empty value of env variables.
@Prakash-sa Just create .env from the .env.template provided and assign them the values otherwise export them in the environment. Documentation link is provided by @isabelcosta. Check that out!

**Comment by Prakash-sa** [comment]
@isabelcosta @BadduCoder thanks I got he error. My email password is wrong. Thanks for figure this out.

**Comment by isabelcosta** [comment]
Glad you solved the issue here on GitHub! This can be very useful for future contributors 🤗

**Comment by Prakash-sa** [comment]
😊 Thanks.
