### ISSUE TITLE
Add Black to help simplify code refactoring to PEP8 standard

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#464]
**Is your feature request related to a problem? Please describe.**
I'm wondering if we could implement a reformatting tool to help refactor code to comply with pycodestyle (aka PEP8) standard. This will help save time and make us more productive in our app development.

**Describe the solution you'd like**
We could try adopting [black](https://github.com/psf/black) that not only can help us check our code against PEP8 standard but also reformat the code for us using only one single command line. The coverage can be from just a single file up to the whole project. 

**Describe alternatives you've considered**
I haven't look for alternative yet 😊. 

PS: I'm aware that code refactoring to PEP8 standard has been discussed in a couple of previous issues and relevant PRs and they all are great. We could still apply the solution offered here in integration with 'black':

- PR #174 for issue #173 
- PR #197, #417 for issue #187 
- PR #253, #255 
- PR #260, issue #261
- PR #414, #416, #421, #422, #433, issue #178

I have no intention to disregard the efforts and contribution that others have made. My intention is only to offer an alternative solution. I will gladly follow any solution that @mentors/@maintainers decide to be adopted 😉. If this does not follow the common acceptable practice, I apologise beforehand and appreciate the patience as I'm a newbie who's still in learning 😊    

**Additional context**

- checking codes in the whole project against pycodestyle with black:

> <root dir> $ black . --check

<img width="888" alt="Screen Shot 2020-02-28 at 11 12 40 pm" src="https://user-images.githubusercontent.com/29667122/75549414-b7dab200-5a83-11ea-9b71-d02b54eb46a8.png">

- reviewing the 'before/after' code changes prior to reformatting:

> <root dir> $ black . --diff

<img width="816" alt="Screen Shot 2020-02-28 at 11 13 52 pm" src="https://user-images.githubusercontent.com/29667122/75549729-74347800-5a84-11ea-8b58-a3d2bfadd3eb.png">

- reformatting codes with black using one line command:

> <root dir> $ black .

<img width="614" alt="Screen Shot 2020-02-28 at 11 43 17 pm" src="https://user-images.githubusercontent.com/29667122/75549619-33d4fa00-5a84-11ea-8869-cd3c247d3a91.png">

**Comment by mtreacy002** [comment]
I have tested and created PR with codes refactored using black.

- codacy - number of issued before refactoring:

<img width="807" alt="Screen Shot 2020-02-29 at 1 16 45 am" src="https://user-images.githubusercontent.com/29667122/75556674-bfee1e00-5a92-11ea-8309-bb5d6a183934.png">


- codacy - number of issues after refactoring:

<img width="814" alt="Screen Shot 2020-02-29 at 1 06 26 am" src="https://user-images.githubusercontent.com/29667122/75556516-7d2c4600-5a92-11ea-9dca-d07d9b845883.png">

PS: not sure if this is the right representation though, coz on develop branch only shows last 8 commits whereas on branch shows last 7 or 31 days. Not sure how to change this 😊

**Comment by mtreacy002** [comment]
@isabelcosta, can you please share your thoughts on this? Thanks.

**Comment by isabelcosta** [comment]
I agree with anything that makes the code better to read and according to best practices.
I am currenlty testing the PR. @mtreacy002

**Comment by isabelcosta** [comment]
I had no idea about this `black` tool. I totally learned something new here :D @mtreacy002
