### ISSUE TITLE
Remove unecessary comments

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#468]
## Description

There is some unnecessary comment in `app/schedulers/complete_mentorship_cron_job.py` file.
These should be removed

### Update [Required]
- [ ] Remove uncessary comments from `app/schedulers/complete_mentorship_cron_job.py`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by sayashraaj** [comment]
I am interested

**Comment by isabelcosta** [comment]
Go ahead @sayashraaj :)
