### ISSUE TITLE
Create Quality Assurance table for Create Task API

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#472]
## Description

As a developer,
I need to know what are the test cases for a certain API,
so that I can write new unit tests.

As a tester,
I need to know what are the test cases for a certain API,
so that I can perform manual tests on the API.

The task is to come up and add a quality assurance table to the docs in the `/docs` folder.

### Update [Required]
- [ ] Add test cases for Create Task API

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by AjayThakur12** [comment]
@isabelcosta please assign it to me

**Comment by isabelcosta** [comment]
Sure @AjayThakur12 :)

**Comment by bera5186** [comment]
@AjayThakur12 are you working on it

**Comment by AjayThakur12** [comment]
yes @bera5186  
today will share screenshot of table before committing changes

**Comment by AjayThakur12** [comment]
@isabelcosta  I created this table need your review 
![Creat table ](https://user-images.githubusercontent.com/29337604/76704640-69bee300-6700-11ea-8b9e-49529f5f5e44.png)

**Comment by isabelcosta** [comment]
@AjayThakur12 can you please send a PR with this table there so I can properly review your work?
