### ISSUE TITLE
Create Quality Assurance table for Refresh token API

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#475]
## Description

As a developer,
I need to know what are the test cases for a certain API,
so that I can write new unit tests.

As a tester,
I need to know what are the test cases for a certain API,
so that I can perform manual tests on the API.

The task is to come up and add a quality assurance table to the docs in the `/docs` folder.

### Update [Required]
- [ ] Add test cases for Refresh token API

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by jotharman** [comment]
@isabelcosta I would like to work on this as a first-timer issue.

**Comment by isabelcosta** [comment]
@jotharman go ahead :) let me know if you have any doubt about this

**Comment by jotharman** [comment]
6c261cd26300cee550df841f39c85f94c91209b0 @isabelcosta Please let me know if anything else is required.

**Comment by isabelcosta** [comment]
@jotharman the commit you are showing sounds good in terms of structuring and where you placed the information. Thank you for updating us about your progress :) Regarding the content, can you please submit a pull request so I can properly review it?

**Comment by jotharman** [comment]
I have generated the pull request #492. Could you please review it?
