### ISSUE TITLE
Create Quality Assurance table for Delete task API

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#476]
## Description

As a developer,
I need to know what are the test cases for a certain API,
so that I can write new unit tests.

As a tester,
I need to know what are the test cases for a certain API,
so that I can perform manual tests on the API.

The task is to come up and add a quality assurance table to the docs in the `/docs` folder.

### Update [Required]
- [ ] Add test cases for Delete task API

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by m-murad** [comment]
Closing this.
Refer to [this](https://github.com/anitab-org/mentorship-android/issues/212#issuecomment-595430447) for more info.
