### ISSUE TITLE
Bug: mismatch mentor/mentee availability on My Profile and Send Request

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#477]
**Describe the bug**
When user A is mentee and want to send request to user B who is a mentor, an error message will appear and states that the request is not possible as both users are a mentor.

Related to issue [#614 Android](https://github.com/anitab-org/mentorship-android/issues/614)
**To Reproduce**
1. Create 2 users, A available to mentee only the B available to mentor only
2. Login as A and try send request to B to be mentor
3. You'll get an error saying both of you are only available as mentor

**Expected behavior**
It should not be a problem as A is not available to Mentor

**Screenshots**
> user A profile

<img width="362" alt="Screen Shot 2020-03-03 at 11 46 08 am" src="https://user-images.githubusercontent.com/29667122/75732476-b1c82800-5d46-11ea-8062-9d61970c96ed.png">

> error message when sending request to B
<img width="432" alt="Screen Shot 2020-03-03 at 11 45 39 am" src="https://user-images.githubusercontent.com/29667122/75732518-c99fac00-5d46-11ea-8251-84fa9dc831ee.png">

**Desktop (please complete the following information):**
 - OS: IOS 
 - Browser: Safari
 - Version MacOS Mojave 10.14.6

**Smartphone (please complete the following information):**
 - Device: Pixel 2 API 27
 - OS: IOS Mojave 10.14.6
 - Version ??

**Additional context**
None

**Comment by mtreacy002** [comment]
Hi @isabelcosta , while waiting for you or other mentors to review my PR #511 , can I please work on this issue now? 😀

**Comment by mtreacy002** [comment]
The issue is actually caused by a bug in the Android UI. Here's a video  made on the existing code showing user testone logged-in and tried to send request to user testthree. But on the debug mode, the btnSendRequest shows that only user testthree is the one got recognised as both logged-in user and member that the request is addressed to. I'll try to trace where this bug is originated from.

![MSissue614Android](https://user-images.githubusercontent.com/29667122/78131488-dfe47900-7466-11ea-9e6f-2aed52fe032f.gif)

The expected behaviour would be:
- memberProfileViewModel.userProfile == user testthree,  
- userProfile == user testone => this isn't the case.

For now, I think we should close this issue and move the discussion to [#614 Android](https://github.com/anitab-org/mentorship-android/issues/614). What do you think @isabelcosta

**Comment by isabelcosta** [comment]
I just read this now, I will close the issue then :) Thank you for letting me know about this, I am now reviewing the android PR :) @mtreacy002
