### ISSUE TITLE
Save registration date as a UNIX timestamp

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#48]
## Description
As a developer,
I need receive in the API response the registration date as a UNIX timestamp,
so that I can properly parse the registration date.

Currently, the registration date of a user is saved as a `DateTime`.
Save it as a `Float`.

### Update
- [ ] Change the registration date data type from `DateTime` to `Float`.
- [ ] Add or Update tests for this
- [ ] Return UNIX timestamp in List Users API response (and others)
 
## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by bhawesh96** [comment]
@isabelcosta  
Can I work on this issue?

**Comment by isabelcosta** [comment]
Status update: this is implemented on PR #148, I'm just waiting for more PRs to be merged on backend to do them all at once (resetting the BD at that time)
