### ISSUE TITLE
Create document for troubleshooting problems, starting with email setup of backend

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#480]
## Description

As a developer,
I need to be aware of common issues faced with setting up the project,
so that I can quickly troubleshoot these issues.

This #233 currently documents common issue developers face when setting up the email for the backend to email users.

There could be a file called `troubleshoot.md` under `/docs` folder.

### Update [Required]
- [ ] Create `troubleshoot.md` file inside `/docs` folder
- [ ] Provide clear steps that show how a contributor can setup a Gmail account with necessary settings to be used by the backend running on localhost

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sumit-badsara** [comment]
I can add the section, which troubleshoots the signin attempt blocked by google.
and provide alternate options for it maybe.

**Comment by isabelcosta** [comment]
Sure @BadduCoder I will assign this to you :) Looking forward to seeing this troubleshoot documentation that can help future contributors 🎉

**Comment by sumit-badsara** [comment]
I am a bit busy for time being, So adding back the available tag.

**Comment by isabelcosta** [comment]
Thank you @BadduCoder for the update 🙌 , I was intending on doing that, but then I just forgot.

**Comment by mtreacy002** [comment]
Hi @isabelcosta, if this issue is still available, may I work on it?

**Comment by isabelcosta** [comment]
I would say yes, in case you are waiting for the review on your PRs :)

**Comment by mtreacy002** [comment]
Thanks, for assigning this issue to me, @isabelcosta. I'll work on it today. 😉

**Comment by mtreacy002** [comment]
Hi @isabelcosta, I have created and pushed the troubleshoots.md doc in PR#546. Please check when you have time. Thanks 😉

PS: It would be great if we could upload images on the doc as well but since I don't have permission to upload files on AnitaB repo, so, just the written steps provided. 😆

**Comment by mtreacy002** [comment]
@mayburgos and @isabelcosta, maybe admins can open permission access to contributors to one particular folder where we contributors can upload our images or relevant things. So when contributors working on .md we can make it a bit more attractive by inserting these images. 
This (using images) would also be a better and more informative way in the case of troubleshoots.md doc. 
Just a suggestion... 😉

**Comment by isabelcosta** [comment]
You can upload images in a comment on GitHub, and then you can the link from the image hosted :) That is what I usually do. You can also see that in this PR #543. When you upload you can see the link. @mtreacy002 what do you think?

![image](https://user-images.githubusercontent.com/11148726/79809001-51795e00-8367-11ea-8f2c-fee2ded96122.png)

**Comment by mtreacy002** [comment]
mmm... interesting. Let me try uploading them to my PR branch. Maybe it wasn't allowed coz I tried to upload on develop branch before. 😂

**Comment by mtreacy002** [comment]
Done. I squashed commit the changes to now using permalink of images uploaded to [PR#546](https://github.com/anitab-org/mentorship-backend/pull/546) branch. Hope this works. Please let me know if it doesn't. 😉
