### ISSUE TITLE
Improve the description of the app on the Swagger UI docs

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#482]
## Description

As a contributor,
I need some more description on Swagger docs,
so that I can easily understand what the app is about.

Maybe you could add the link to the wiki, and the full description of the app, link to Android app.
These are just ideas.. I'm not sure what is the best, but I know this can definitely contain some more information.

## Mocks

I tried this out myself, staying something like:
![image](https://user-images.githubusercontent.com/11148726/76032284-73429100-5f31-11ea-967c-b19fa884e8ef.png)

### Update [Required]
- [ ] Improve Swagger Docs description

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by EfthymiaKostaki** [comment]
Hello, this is my first time contributing to a project, can I work on this issue as a beginning?

**Comment by isabelcosta** [comment]
@EfthymiaKostaki sure, go ahead :)

**Comment by EfthymiaKostaki** [comment]
Thank you! I will try to work on this as soon as possible and to have finished by next week!

**Comment by Adarsh-NP** [comment]
Can I work on this?

**Comment by isabelcosta** [comment]
@EfthymiaKostaki is working on it. (right?)
I already assigned you another issue :)

**Comment by EfthymiaKostaki** [comment]
Yes I am currently working on that!

**Comment by EfthymiaKostaki** [comment]
@isabelcosta Hey, I will submit a pull request regarding this issue during the day. I wanted to ask even though it's not included in this issue is the "default Default namespace" API category needed on the initial page? Because I don't see any content in it. If it is not maybe this should be altered?

**Comment by isabelcosta** [comment]
@EfthymiaKostaki the default namespace is not needed, I just don't know how to take it out from the Swagger UI. Do you know how to do it? If so can you please create an issue, and then I can approve and assign it to you?

**Comment by EfthymiaKostaki** [comment]
Okay, I have updated my pull request regarding this issue and I think I resolved the default Namespace issue. Here's a preview of how it turns out:
![default namespace](https://user-images.githubusercontent.com/43841219/77851471-03e35880-71e2-11ea-8d2e-d63029bcf990.png)

**Comment by isabelcosta** [comment]
@EfthymiaKostaki i just quickly checked your PR and it does not have any new commit that would fix what you mentioned

**Comment by EfthymiaKostaki** [comment]
I haven't included it in the original pull request. I thought you mentioned it should be in a different one solving a different issue. If you want I can add it to the existing pull request

**Comment by isabelcosta** [comment]
Once you showed you could do it... this can be done in the same PR :) It is part of improving the Swagger docs :) @EfthymiaKostaki

**Comment by EfthymiaKostaki** [comment]
@isabelcosta I have updated the pull request adding the commit for the default namespace issue.
