### ISSUE TITLE
http 500 when sending an request without containing the logged user

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#487]
**Describe the bug**

When I tried sending a mentorship request, where the user was not involved not as a mentor nor as a mentee, I got the error 500.

**To Reproduce**

Have at least 3 users signed in.
Make User 1 send request with mentor and mentee id, of User 2 and User 3 (not including User 1)

1. Log in as User 1
2. Send request using IDs from existing users (except User 1)
3. See "Internal Server Error" error (error log below)

**Expected behavior**

Error should be returned with a message, saying the user was not involved in the request.

**Screenshots**

Error thrown:
```
172.17.0.1 - - [09/Mar/2020 00:37:33] "POST /mentorship_relation/send_request HTTP/1.1" 500 -
[2020-03-09 00:38:16,892] ERROR in app: Exception on /mentorship_relation/send_request [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 101, in wrapper
    return fn(*args, **kwargs)
  File "/dockerBuild/app/api/resources/mentorship_relation.py", line 106, in post
    send_email_new_request(user_sender, user_recipient, notes, sender_role)
  File "/dockerBuild/app/api/email_utils.py", line 145, in send_email_new_request
    user_recipient_name=user_recipient.name,
AttributeError: 'tuple' object has no attribute 'name'
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

I used Docker to run the program.
The error seems to come from [this line in the code](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/email_utils.py#L122), although the problem must come from previous lines in [this function](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/resources/mentorship_relation.py#L103).

**Comment by naveennvrgup** [comment]
I would like to work on this issue

**Comment by isabelcosta** [comment]
sure @naveennvrgup go ahead :)

**Comment by naveennvrgup** [comment]
@isabelcosta I have tried to reproduce the bug by creating 3 users and doing the request as u have described in the issue. But everthing seems to work fine. 

**I got the exact same error message  when i tried to make the request with a user that doesnot exist in the database.**  I feel like the description and what I have found doesn't match. Please correct me if I am wrong. :)

**Comment by naveennvrgup** [comment]
I have added a check to find wheather the user_id actually exists in the database. This fixes the above error. Also no testcases are available for the **/mentorship_relation/send_request** API. So, I will write write the test cases for that also.

**Comment by naveennvrgup** [comment]
I think I found the root cause please check my PR. @isabelcosta @mayburgos

**Comment by isabelcosta** [comment]
the tests thing was a really nice catch 🎉 Thank you so much for mentioning it. I will review/run/test your PR once I have some time. Thank you for looking thoroughly into this :)
