### ISSUE TITLE
Add documentation about database environment variables

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#493]
## Description

As a developer,
I need to understand the environment variables I need to set,
so that I can successfully run and test the backend API.

Environment Variables markdown file is missing information regarding the Database environment variables that you have to set to connect the backend to a remote database. There are at least 5 
You may have to mention that these are used only when the environment configuration is set to `dev` or `prod`.

For each mention an example of the value and the description of the variable.

The Environment Variables document is located under `/docs` folder.

### Update [Required]
- [ ] Add documentation about Database environment variables

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by bera5186** [comment]
@isabelcosta can I work on this issue !!

**Comment by isabelcosta** [comment]
@bera5186 yes you can work on this issue. I will assign this to you.

**Comment by bera5186** [comment]
@isabelcosta I have sent a pull request 😊 can you please review it.

**Comment by isabelcosta** [comment]
This PR #500 was quite close to solving this issue, I welcome anyone who wishes to contribute here

**Comment by vanshikagoell** [comment]
Please assign me this issue, I wish to contribute this is my first time!

**Comment by SanketDG** [comment]
@vanshikagoell There you go!

**Comment by vanshikagoell** [comment]
Sorry I am not able to do it!

**Comment by divyanshugit** [comment]
Hey, I would like to work on this issue. Can you suggest me ways to get started ?

**Comment by isabelcosta** [comment]
@divyanshugit this PR https://github.com/anitab-org/mentorship-backend/pull/500 was almost finished, so you can just follow this :)
