### ISSUE TITLE
Change link to Environment Variables documentation on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#494]
## Description
As a developer,
I need to have the updated version of environment variables documentation,
so that I can be up to date on how to run the project.

Change on README the links to Environment Variables on Wiki, to the Environment Variables file stored in the repository.

### Update [Required]
- [ ] Change links to Environment Variables on README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by bera5186** [comment]
@isabelcosta can you review my [pull request](https://github.com/anitab-org/mentorship-backend/pull/496)

**Comment by isabelcosta** [comment]
I closed the PR since you did not wait to get assigned to it. I assigned you another issue you claimed.

**Comment by Adarsh-NP** [comment]
@isabelcosta so is this closed because @bera5186  did it already?
If not can I work on this?

**Comment by isabelcosta** [comment]
@Adarsh-NP the PR is closed because of the reason I mentioned above. @bera5186 did not wait to be assigned to work on the issue and additionally was already assigned a first timers only issue.
You can work on it. I will assign it to you.

**Comment by Adarsh-NP** [comment]
Hello @isabelcosta ma'am, I updated readme.md kindly have a look at the aforementioned link to the pull request.
Thanks
