### ISSUE TITLE
Show proper error message when user fails to send access token

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#50]
## Description

As a consumer of the API,
I need receive a proper error message when failing to send JWT,
so that I can be aware of how to use the authenticated API.

Currently, when we try to use a restricted API without sending the token, we receive a `500 Internal Server Error` and the app throws an exception. The proper message should be something like:
```
{
      "message": "This resource requires an Authorization header field: JWT <token>."
}
```

### Update
- [x] Overide JWT error handler to return proper error message instead of showing `500 internal server error`

## Definition of Done
- [x] PR should be sent to the `gsoc18-code` branch
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 hours

**Comment by m-murad** [comment]
@isabelcosta 

`401 Unauthorized`

**Comment by isabelcosta** [comment]
Ok @m-murad noted! Thanks!
