### ISSUE TITLE
Add necessary files to allow deployment on Heroku?

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#501]
## Description
As a developer,
I need a couple of configurations,
so that I can deploy the app to Heroku.

I want to empower anyone who wished to deploy the project on heroku to do so. To do this I needed 2 files to be added, here are the [2 latest commits I did in my repository](https://github.com/isabelcosta/mentorship-backend/commits/heroku) `heroku` branch.

I am in doubt if this is something that is done on backend projects in open source, so if anyone could give your opinion on this, I would highly appreciate!

### Update [Required]
- [ ] Add support to deploy on Heroku

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by isabelcosta** [comment]
@m-murad @sara-02 @ramitsawhney27 do these files being added to the repository make sense? I needed them to deploy the project into Heroku

**Comment by m-murad** [comment]
I guess heruko is a temporary solution. Does CD on a temporary server make sense/do we need it?
If yes then files should be pushed else we don't need those files.

Maybe May can give clarity on the time it will take to deploy the project back in AWS

**Comment by isabelcosta** [comment]
@m-murad it is temporary and I have no idea about when AWS issue will be resolved (cc @mayburgos ). These files do not change anything on the production code. My idea was that instead of just me having these files configured on my fork, everyone else could benefit from this if they wanted to do the same setup as me on heroku. Either way I am fine.

**Comment by isabelcosta** [comment]
2 files I commits I did for this to work was:
https://github.com/isabelcosta/mentorship-backend/commit/9904252dad53e4a72e62e7f90d6b1bd8cee05024

cc @mtreacy002 is this what you mentioned on Zulip? I had to install gunicorn package and add the .profile file
