### ISSUE TITLE
Error in packages installation for first time project setup

### ISSUE THREAD

**Issue by ashokrayal** [anitab-org/mentorship-backend#503]
While installing packages to work on the project. Package installation is failing on the windows system.

Step 3 of run app.
below command is resulting in error for pypiwin32==200
`pip install -r requirements.txt`

![image](https://user-images.githubusercontent.com/26453959/76865373-a4538780-6888-11ea-938f-dc8034ee1526.png)

**Comment by StergiosSozos** [comment]
Hey @Ashokrayal , try removing all the lines that have "docker" in them ( in the txt) , and run the command again.

**Comment by ashokrayal** [comment]
Thanks @StergiosSozos.

I also had to remove below line from requirement file.
PyYAML==3.13

I have made some code changes and now I want to test the API. Can you please also help me to find out how I can get the Bearer access token?

**Comment by ashokrayal** [comment]
> Thanks @StergiosSozos.
> 
> I also had to remove below line from requirement file.
> PyYAML==3.13
> 
> I have made some code changes and now I want to test the API. Can you please also help me to find out how I can get the Bearer access token?

I can get the access token using swagger.  Thanks. Closing the issue.

**Comment by isabelcosta** [comment]
Cool! problem solved!
