### ISSUE TITLE
Update Environment Variables documentation to mention local config setting

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#506]
## Description

As a developer,
I need to understand the environment variables I need to set,
so that I can successfully run and test the backend API.

So the [docs/environment-variables.md](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md) file needs to be updated to reflect that one should set the `FLASK_ENVIRONMENT_CONFIG ` as `local` if they do not want to set a remote database connection and want to use a sqlite database locally. This is an easy setting to play around with the app locally.

You can take a look at the `README.md` which is updated regarding the local setting.

### Update [Required]
- [ ] Add information about local configuration

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 min

**Comment by rahulshah456** [comment]
@isabelcosta 
Can I work on this issue? Assignee to me, please...

**Comment by isabelcosta** [comment]
Sure @rahulshah456 :) I will assign this to you
