### ISSUE TITLE
Internal Server Error in localhost 

### ISSUE THREAD

**Issue by rahulshah456** [anitab-org/mentorship-backend#510]
**Describe the bug**
Internal Server error when registering a new user in the localhost server for 1st time. after clicking the execute button again error shows the message **A user with that email already exists**.
No confirmation mail is received and I have tried to resend confirmation mail but it also shows **Internal Server Error**.
I'm using FLASK_ENVIRONMENT_CONFIG=local

**To Reproduce**
1. Go to 'http://127.0.0.1:5000/'
2. Click on '/register Creates a new user'
3. Fill dummy data
4. Execute

**Expected behavior**
A new user should be created with a confirmation email.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/41780639/77233572-6202b100-6bce-11ea-856c-533c895a9e22.JPG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version:  80.0.3987.149

**Comment by isabelcosta** [comment]
@rahulshah456 it would be great if you could put the error logs here. Just the Swagger UI with the 500 error does not provide me enough context to understand what might be happening.
Also, you could provide the exact dummy data you provided, it's hard to understand just from the message.

**Comment by rahulshah456** [comment]
Dummy data I'm using:
{
  "name": "hello",
  "username": "hello123",
  "password": "12345678",
  "email": "hello123@gmail.com",
  "terms_and_conditions_checked": true,
  "need_mentoring": true,
  "available_to_mentor": true
}

Console Error: 

![Capture2](https://user-images.githubusercontent.com/41780639/77243571-817ef580-6c31-11ea-9179-bacd6d5349b7.JPG)

Console Logs: And after executing the error logs i.e.  http://127.0.0.1:5000/register the response is below. 

Response:
{"message": "The method is not allowed for the requested URL."}

**Comment by isabelcosta** [comment]
@rahulshah456 the error log would be more verbose than that. Like what really appears on the terminal after you run the project.
I see the response you show in the comment is different than the one showed on the PR description, so you may be showing me 2 different test scenarios.

I would like to see a log similar to this structure:
![image](https://user-images.githubusercontent.com/11148726/76807340-f7bbcc00-67db-11ea-881a-b37d3f029a82.png)

**Comment by rahulshah456** [comment]
Is this is the log you asked for...

![Capture](https://user-images.githubusercontent.com/41780639/77247934-b43de380-6c5b-11ea-9106-0e6573ab2780.JPG)

**Comment by isabelcosta** [comment]
Yes @rahulshah456 that is actually very helpful :) So I think that you did not set the SECRET_KEY environment variable. This can be a random string. Here's it is the guide for [exporting environment variables](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md)

**Comment by rahulshah456** [comment]
This is my .env template and still getting the same error, how to generate working SECRET_KEY and
SECURITY_PASSWORD_SALT 

FLASK_ENVIRONMENT_CONFIG = test
SECRET_KEY = '38AF0B8DC326F180BD1822B86F61CA95C6A82F28A0946ED755EDC8D9BFF891D9'
SECURITY_PASSWORD_SALT = '11629f3c3243c120d8c2b0e0fcf5c89298efc0a2cea7d4d3'
MAIL_DEFAULT_SENDER = droid2developers@gmail.com
MAIL_SERVER = smtp.gmail.com
APP_MAIL_USERNAME = droid2developers@gmail.com
APP_MAIL_PASSWORD = **************

**Comment by isabelcosta** [comment]
No need to be working secret key, you can put a simple string there @rahulshah456 🤔 but I see you have the `FLASK_ENVIRONMENT_CONFIG` to test. Can you set it to `local`?

**Comment by rahulshah456** [comment]
I was just experimenting on changing the `FLASK_ENVIRONMENT_CONFIG` to test. While It is local already and this is my updated .env template.
And Still facing same error :disappointed:

```
FLASK_ENVIRONMENT_CONFIG = local
SECRET_KEY = 'hsagdasigdfbksfjcfiu'
SECURITY_PASSWORD_SALT = 'sdfuyhewkfhgdifgpfk'
MAIL_DEFAULT_SENDER = droid2developers@gmail.com
MAIL_SERVER = smtp.gmail.com
APP_MAIL_USERNAME = droid2developers@gmail.com
APP_MAIL_PASSWORD = **************
```

**Comment by mtreacy002** [comment]
@rahulshah456. Is that a real email address? What is the security settings of the email? I'm asking because last time this happened to me was because the 2 steps verification and allow less app settings of gmail. [Here](https://github.com/anitab-org/mentorship-backend/issues/233#issuecomment-594054365)'s the discussion we had that time. Give it a try, let us know what happened. 😉

**Comment by mtreacy002** [comment]
Also, if it says the email already exist, try to delete the user from the database. You said you're using the local database. If you use sqlite, then try the steps I posted on [Zulip](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/Troubleshoot/near/191570789).

**Comment by rahulshah456** [comment]
> @rahulshah456. Is that a real email address? What is the security settings of the email? I'm asking because last time this happened to me was because the 2 steps verification and allow less app settings of gmail. [Here](https://github.com/anitab-org/mentorship-backend/issues/233#issuecomment-594054365)'s the discussion we had that time. Give it a try, let us know what happened. 😉

Yes, it is a real email address and I have enabled 2 step auth because SMTP message not sending due to some updated google security. But I have followed the instructions to generate an app-specific password from Gmail and it is working in sending an SMTP message because I have tested it already.
The problem is different I think. But for now, I am going to manually test the SQL database in every query and I have already seen your messages in #troubleshoot.
BTW thanks 😄
