### ISSUE TITLE
Use HTTPStatus instead of hard coded HTTP status code

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#519]
## Description

As a developer,
I need explicit HTTP status codes,
so that I can improve coding experience.

The idea is to use http.HTTPStatus values instead hardcoded values in the whole app

https://docs.python.org/3/library/http.html#http.HTTPStatus

This values without a clear description, can be easily overlooked. With `HTTPStatus.CREATED` we can easily understand that we are using the right code.

### Update [Required]
- [ ] Use HTTPStatus values instead of 200, 400, etc values

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by nandini45** [comment]
can i work on this issue?

**Comment by isabelcosta** [comment]
Yes you can @nandini45

**Comment by nandini45** [comment]
i am working on the issue. but i am new to github and facing some issues can you help me out?

**Comment by nandini45** [comment]
i am working on the issue. but i am new to github and facing some issues can you help me out?

@isabelcosta

**Comment by isabelcosta** [comment]
@nandini45 sure! What is your problem?

**Comment by nandini45** [comment]
actually i had some basic questions can i mail them to u?

**Comment by nandini45** [comment]
@isabelcosta

**Comment by nandini45** [comment]
@isabelcosta 
i am not able to read any values in the swagger.json file

**Comment by isabelcosta** [comment]
@nandini45 please use GitHub or Zulip public forum for questions regarding our open source projects. In our open source community, we practice as much as transparency as we can, so that we can open discussions and questions and answers to other contributors.

I think I [already answered on Zulip](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/Troubleshoot/near/192971335), I will paste it here:
> the idea is to wherever in the code there is a HTTP code hardcoded as 201, is should be replaced in the code with HTTPStatus.CREATED. This is in the whole code inside app folder, the swagger.json file is generated automatically so no need to change it there. So you only have to import the module that is mentioned in the issue and no need to create the enums that already exist in the HTTPStatus module

**Comment by isabelcosta** [comment]
Can you please send a PR just with code for this issue? @nandini45 I can guide you on the PR by reviewing it :) I noticed in the other PR that the implementation did not fulfill the requirements of this issue, so I really want to help you get it right :)

**Comment by nandini45** [comment]
ok @isabelcosta i am trying to pull open a new request. i am facing some network issues. sorry!

**Comment by isabelcosta** [comment]
No worries @nandini45 :) you have plenty of time, send when you can

**Comment by vj-codes** [comment]
@isabelcosta Closing since HTTPStatus is currently being used.Hope it's alright:)
