### ISSUE TITLE
docs: Typos in documentations

### ISSUE THREAD

**Issue by hk-mp5a3** [anitab-org/mentorship-backend#522]
**Describe the bug**
There are a few typos in `docs/environment-variables.md` and `docs/quality-assurance-test-cases.md`.

Details can be found in:
https://github.com/anitab-org/mentorship-backend/pull/521

**To Reproduce**
Not Applicable

**Expected behavior**
Not Applicable

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
Not Applicable

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Not Applicable

**Comment by isabelcosta** [comment]
@yzhu01 step 1 done :) Step 2 was following one of our issue templates 🙃 That would make this perfect!
You can send a PR again to fix this issue @yzhu01 :)

**Comment by hk-mp5a3** [comment]
@isabelcosta Thank you for your review. I have made a modification to the issue description. Would this be better? The new PR is at https://github.com/anitab-org/mentorship-backend/pull/529. Thank you for your time and consideration.

**Comment by isabelcosta** [comment]
@yzhu01 its good as it is, and it was good as it was, I know this is a very very small tiny issue. I will review shortly

**Comment by isabelcosta** [comment]
Solved with #529
