### ISSUE TITLE
Mock sending email for developers 

### ISSUE THREAD

**Issue by naveennvrgup** [anitab-org/mentorship-backend#524]
**Is your feature request related to a problem? Please describe.**
New developers to the mentorship backend often have trouble with setting up the email server settings right. (Mainly due to 2 factor authentication). Also it is nice to have the feature to mock email sending.

**Describe the solution you'd like**
Create a environment variable MOCK_EMAIL which if set to true will print the **email purpose** and **email body** in the terminal instead of sending the actual email.

**Comment by naveennvrgup** [comment]
I would like to contribute to this issue

**Comment by isabelcosta** [comment]
This is very very interesting 🤔 thank you for proposing this.
The email feature active can actually complicate the local development right? I agree with this. I just need a second opinion. And the default value (in case the variable is not set) could be false? What do you think @naveennvrgup ?

cc @m-murad

**Comment by isabelcosta** [comment]
I will assign this to you, so you can start woking on this :)

**Comment by naveennvrgup** [comment]
> the default value (in case the variable is not set) could be false? What do you think @naveennvrgup ?

Yes, that is a great addition. Will add that too.
