### ISSUE TITLE
[Production Bug] Migration script is missing 

### ISSUE THREAD

**Issue by vkWeb** [anitab-org/mentorship-backend#526]
**Describe the bug**
Recently @isabelcosta and team talked about developing the mentorship project ready for production. The most critical problem I see as of now is, we don't have scripts for database migrations. Without scripts, we won't be able to migrate new models to the database in production.

Also, GSoC students might bring in some new models this year which should be carefully migrated to the database with the help of flask-migrate's migration scripts. 

**Proposed solution**
Flask-Migrate can generate migration scripts with `flask db migrate` command. @isabelcosta I'm ready to send a PR once I get a green light from you or from any other maintainer.

**Estimated time for fix**
5 - 10 minutes.

**Comment by thesauravkarmakar** [comment]
@vkWeb Could you assign it to me? I want to try to solve this issue.

**Comment by vkWeb** [comment]
@thesauravkarmakar Thanks for your interest. Actually, I have been inactive on this project for a while. I am not aware how things are getting shaped up so I'll leave this decision to @isabelcosta.

**Comment by isabelcosta** [comment]
@vkWeb thank you so much for coming back to update the community about this 🤗 I really appreciate it!
@thesauravkarmakar from what you understand, do you think this issue is valid? Have you tried to setup the project locally? I feel this is needed with new code that comes with new data models. I am not sure what you can do as a standalone fix.

**Comment by thesauravkarmakar** [comment]
> @vkWeb thank you so much for coming back to update the community about this 🤗 I really appreciate it!
> @thesauravkarmakar from what you understand, do you think this issue is valid? Have you tried to setup the project locally? I feel this is needed with new code that comes with new data models. I am not sure what you can do as a standalone fix.

I don't understand that much. No, I didn't setup it locally. I am new to Open Source, so if you could help me regarding this issue, I would like to contribute.
