### ISSUE TITLE
Create a bulleted list of features the app has on the README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#528]
## Description
As a contributor,
I need to know the app's features,
so that I can know more about the app before working on it.

The README has practical information on how to contribute to the app and a small description of the app, but misses some information about the features it has, like see members of the app, send mentorship request.

### Update [Required]
- [ ] Add a bullet list of high-level features to the README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by nandini45** [comment]
@isabelcosta  
can i try and work on it?

**Comment by isabelcosta** [comment]
sure @nandini45 :) will assign it to you

**Comment by isabelcosta** [comment]
@nandini45 sorry I had to unassign you here, since you as a first-timer you are already working on issue #519 . I missed this detail when I assigned this to you. We only allow contributors to be working on an issue at a time (if not waiting for reviews). Can you please send a PR just for the first issue you were working on?

**Comment by nandini45** [comment]
i send the PR already on my first issue and i made the commit for this issue too
@isabelcosta

**Comment by developer22-university** [comment]
you can assign it to me @isabelcosta

**Comment by isabelcosta** [comment]
Sure :) @developer22-university

**Comment by developer22-university** [comment]
hi, @isabelcosta  i am facing some problems in setting the environment variables , i will keep you updated with the work, i hope to finish it soon

**Comment by isabelcosta** [comment]
Thank you so much for your update @developer22-university please let us know if we can help you :) Usually the problem comes from using the FLASK_CONFIGURATION as `dev` instead of `local`. Are you using local?

**Comment by developer22-university** [comment]
actually , i think i will work tommorow i have early morning classes,  yes i am using local , by

**Comment by developer22-university** [comment]
@isabelcosta  yes we can discuss can u share some link i m using ubuntu

**Comment by isabelcosta** [comment]
@developer22-university which link do you need?

**Comment by vj-codes** [comment]
Unassigning @developer22-university due to inactivity.

**Comment by yash2189** [comment]
Can I try working on this  as a first timer , I'm currently setting up the application.

**Comment by vj-codes** [comment]
@yash2189 you are assigned#343 and this a first timers only issue , so no longer eligible for you. Please comment on other available issues.

**Comment by Kunal1198** [comment]
Hi, can I work on this?

**Comment by madhhuurrii** [comment]
Hii , can i work on this issue?

**Comment by vj-codes** [comment]
@Kunal1198 assigning you 
Happy documenting!

**Comment by Anmollenka** [comment]
@vj-codes  Can I work on this issue as a part of OSH?Thank You.

**Comment by vj-codes** [comment]
@Anmollenka hey this issue is already assigned, please look out for other available issues and comment :)

**Comment by Anmollenka** [comment]
@vj-codes what is the maximum time for solving each issue??

**Comment by vj-codes** [comment]
@Anmollenka the PR should be submitted before 30th September and if it's taking long there should be updates about your progress after every 3 days.

**Comment by vj-codes** [comment]
@Anmollenka but just remember that this issue is already assigned to someone else :)

**Comment by Anmollenka** [comment]
@vj-codes Thanks for the answer.

**Comment by Kunal1198** [comment]
@vj-codes please review my PR.

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by isabelcosta** [comment]
@sujal111 are you interested in this issue still? we can assign this to you, if you are interested
cc @vj-codes

**Comment by sujal111** [comment]
No,m not interested

**Comment by isabelcosta** [comment]
That's ok, thank you for your response @sujal111

**Comment by sujal111** [comment]
You're welcome!

**Comment by madhhuurrii** [comment]
@isabelcosta @vj-codes Can I take this issue?

**Comment by isabelcosta** [comment]
sure @madhhuurrii :) assigning it to you

**Comment by madhhuurrii** [comment]
Hii!! @isabelcosta Please review my PR :)

**Comment by madhhuurrii** [comment]
Hii @isabelcosta I have done appropriate changes Please review them

**Comment by Jasmine9003** [comment]
Hi @isabelcosta Can I work on this issue?

**Comment by isabelcosta** [comment]
Sure @Jasmine9003 :) i will assign this to you. Feel free to continue the previous PRs that had some useful code for this already.

**Comment by Jasmine9003** [comment]
@isabelcosta I have created a PR with list of features in read me file, kindly review.

**Comment by epicadk** [comment]
> @isabelcosta I have created a PR with list of features in read me file, kindly review.

Hey just a suggestion instead of tagging a maintainer individually you can tag the testers at anitab-org/testers for a quicker response.

**Comment by isabelcosta** [comment]
yes and also @anitab-org/mentorship-maintainers :) I will also properly setup this.
