### ISSUE TITLE
Add misplaced values to error message

### ISSUE THREAD

**Issue by sihhub** [anitab-org/mentorship-backend#533]
**Describe the bug**
If I put values other than "prod", "test", "dev", "local", and "stag" in the FLASK_ENVIRONMENT_CONFIG environment variable, the error message excluding local and stag are printed.

**Screenshots**
![image](https://user-images.githubusercontent.com/59594931/78647916-2f5af700-78f6-11ea-8be2-d577b6307cb9.png)

**Comment by isabelcosta** [comment]
@hongsungin92 very nice catch :)
Although, according to our CONTRIBUTING.md guidelines, you have to wait until approval and assignment before sending a PR @hongsungin92 . Are you interested in working on this issue?

**Comment by sihhub** [comment]
@isabelcosta thanks.  I'll try to remember that from now on.
Yes, I'd like to be in charge of this.

**Comment by isabelcosta** [comment]
oki :) I will assign this to you and re open your PR @hongsungin92
