### ISSUE TITLE
Create guide on how to test PRs and backend with Swagger UI

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#542]
## Description

As a contributor for testing,
I need a guide to help me understand how Swagger UI works and how to use multiple APIs from the project,
so that I can properly test pull requests from contributors that solve issues for the project.

Idea is to create a Markdown-based guide on the repository to help guide testers. [Conversation started here on Zulip](https://anitab-org.zulipchat.com/#narrow/stream/216325-quality-assurance/topic/PR.20that.20needs.20Testing/near/194472739).

_this has already an assignee_

### Update [Required]
- [ ] Create guide on docs folder

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by rpattath** [comment]
@isabelcosta can you assign this to me?

**Comment by rpattath** [comment]
![Screenshot from 2020-04-17 12-32-42](https://user-images.githubusercontent.com/26095715/79673496-488e5e00-81a8-11ea-8daf-714949e111f2.png)
![Screenshot from 2020-04-17 12-32-33](https://user-images.githubusercontent.com/26095715/79673497-488e5e00-81a8-11ea-852d-e361e422b3aa.png)
![Screenshot from 2020-04-17 12-31-39](https://user-images.githubusercontent.com/26095715/79673498-4926f480-81a8-11ea-8e95-a7cd3ea24e56.png)
![Screenshot from 2020-04-17 12-21-40](https://user-images.githubusercontent.com/26095715/79673499-4926f480-81a8-11ea-8641-79749fdc89ab.png)
![Screenshot from 2020-04-17 12-21-01](https://user-images.githubusercontent.com/26095715/79673500-4926f480-81a8-11ea-9c97-bac8cc800f85.png)
![Screenshot from 2020-04-17 12-16-11](https://user-images.githubusercontent.com/26095715/79673501-4926f480-81a8-11ea-9d78-25704487ce28.png)
![Screenshot from 2020-04-17 12-16-05](https://user-images.githubusercontent.com/26095715/79673502-4926f480-81a8-11ea-8695-882117830657.png)
![Screenshot from 2020-04-17 12-55-21](https://user-images.githubusercontent.com/26095715/79673504-49bf8b00-81a8-11ea-9a1e-c136cb345440.png)
![Screenshot from 2020-04-17 12-14-40](https://user-images.githubusercontent.com/26095715/79673505-49bf8b00-81a8-11ea-89f2-687913a238fe.png)
![Screenshot from 2020-04-17 12-14-35](https://user-images.githubusercontent.com/26095715/79673506-49bf8b00-81a8-11ea-8bf3-0dffd8b269f5.png)
![Screenshot from 2020-04-17 12-02-09](https://user-images.githubusercontent.com/26095715/79673507-4a582180-81a8-11ea-96ff-2268733e9673.png)
![Screenshot from 2020-04-17 11-55-50](https://user-images.githubusercontent.com/26095715/79673508-4a582180-81a8-11ea-87ce-fe0bfda82fea.png)
![Screenshot from 2020-04-17 12-31-43](https://user-images.githubusercontent.com/26095715/79673509-4a582180-81a8-11ea-9e76-fb931eaa3aeb.png)
![Screenshot from 2020-04-17 11-57-38](https://user-images.githubusercontent.com/26095715/79673510-4a582180-81a8-11ea-8259-532718f76b65.png)
