### ISSUE TITLE
API: typo present in task.py

### ISSUE THREAD

**Issue by snitin315** [anitab-org/mentorship-backend#559]
**Describe the bug**

presence of some typos.

**To Reproduce**
1. Go to https://github.com/anitab-org/mentorship-backend/blob/dfecaec198db134bed32b7d3232b9c62791d84c6/app/api/dao/task.py#L28

https://github.com/anitab-org/mentorship-backend/blob/dfecaec198db134bed32b7d3232b9c62791d84c6/app/api/dao/task.py#L95

https://github.com/anitab-org/mentorship-backend/blob/dfecaec198db134bed32b7d3232b9c62791d84c6/app/api/dao/task.py#L129

4. See error [succesful]

**Expected behavior**

It should be `successful`.

**Screenshots**

NA

**Desktop (please complete the following information):**
 
Any

**Smartphone (please complete the following information):**
 Any

**Additional context**
I would like to work on this.

**Comment by isabelcosta** [comment]
Could we leave this PR for another first-timer and you would do the PR template one? @snitin315

**Comment by snitin315** [comment]
Let's leave this for the First timer. I will go ahead with the PR template one.

**Comment by isabelcosta** [comment]
Thank you @snitin315 :) Its a great catch and thank you for following the bug report template

**Comment by sankha555** [comment]
Hello @isabelcosta !
Hope you are in the best of health. I was going through the repository and have found it to a really great one and I wish to contribute to it in future. If no one else is working on it, can I take up this issue and fix it as a starting issue? 

I am new to the repository and if there is any pre-requirements to be fulfilled before working, can you please guide me a bit on them. Thanks!

**Comment by snitin315** [comment]
@sankha555 Yes you can take this up :tada:

> I am new to the repository and if there are any pre-requirements to be fulfilled before working, can you please guide me a bit on them. Thanks!

You can go through the `README` file and our [contributing guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).

**Comment by snitin315** [comment]
@sankha555 I have assigned you this issue. 

Let us know if you need any help and thank you for working on this.

**Comment by sankha555** [comment]
Thanks a lot ! I will go through the guidelines and will let you know in case I need any help in the task.
