### ISSUE TITLE
400 Responses does not list "Terms and conditions is false" message

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#561]
When registering a new user , if Terms and conditions is set to false then we see the expected error message "Terms and conditions are not checked." but this message is not listed under the list of 400 responses.

1. Go to 'Users- register'
2. {
  "name": "testua",
  "username": "testua",
  "password": "testua123",
  "email": "voxij69223@mailop7.com",
  "terms_and_conditions_checked": false,
  "need_mentoring": true,
  "available_to_mentor": true
}
3. Click on 'Execute'
4. Scroll down to 'Responses' 
5. ![Screenshot (3)](https://user-images.githubusercontent.com/50888936/80868541-fcb7da80-8cb8-11ea-86bc-656d7f18effe.png)

**Expected behavior**

All the error messages should be listed under the 400 error messages

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by isabelcosta** [comment]
this is amazing @faznan3nazer thank you so much for creating this bug report!

**Comment by sankha555** [comment]
Hello @isabelcosta and @faznan3nazer,
I am interested in working on this issue. If no one else is working on it, could you please assign it to me? Thanks!

**Comment by isabelcosta** [comment]
@sankha555 can you leave this up for a first timer / newcomer (as it is labeled with "First Timers Only")? This is a really simple issue (1 - 2 lines of code) that someone could use to get acquainted with our open source workflow. I can redirect you to other issues if you would like

**Comment by sankha555** [comment]
Sure @isabelcosta , I can leave this issue for a first timer then. Yes, I would be grateful to you if you could kindly redirect to some other issues. Thanks again :)

**Comment by isabelcosta** [comment]
@sankha555 would this be interesting for you https://github.com/anitab-org/mentorship-backend/issues/505?
I have no idea about the size of work here, it would be great if this could be split into modules. But I had no time to do that.

**Comment by sankha555** [comment]
@isabelcosta Thanks for mentioning this issue to me. I am interested to work on it and will take a look at it. Could you assign this to me then? And if I need any help, I hope I can reach out on this thread for any assistance? Thank You :)

**Comment by CharityKithaka** [comment]
Hey can I work on this?

**Comment by isabelcosta** [comment]
Yes, go ahead :) @CharityKithaka

**Comment by vj-codes** [comment]
Unassigning @CharityKithaka due to inactivity.

**Comment by Bhavani-Somanchi** [comment]
@isabelcosta  @vj-codes Can I work on this issue?

**Comment by isabelcosta** [comment]
Sure @Bhavani-Somanchi go ahead and get started!
