### ISSUE TITLE
error message for missing required fields under user registration

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#563]
If ne of the required field is missing in the input an appropriate error message should be showned and listed under the 400 Responses.

1. Go to 'User-Register'
2. {
  "name": "testua",
  "username": "testua",
  "password": "testua123",
  "email": "voxij69223@mailop7.com",
  "need_mentoring": true,
  "available_to_mentor": true
}
3. Click on 'Execute'
4. Scroll down to 'Response'
5. 
![Screenshot (5)](https://user-images.githubusercontent.com/50888936/80870263-f62e6080-8cc2-11ea-84a5-defa08eafb62.png)

**Expected behavior**
The ideal error message should be
{’message’: ''terms_and_conditions_checked' is a required property".’}

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  Chrome

**Additional context**
This is showing the same error message for missing name, username, password, email adress.

**Comment by isabelcosta** [comment]
This issue I am in doubt if we should put that on the swagger docs, if we can get that in a way that is not hardcoded (using a function from Flask-RESTPlus) or if we should rewrite that in the backend, and send the message formatted the way we want like, HTTP Status 400 and the following JSON response:
```
{
    "message": "terms and conditions property cannot be missing"
}
```

**Comment by rashikaqureshi** [comment]
Hi is this open. can i take this up ?

**Comment by nickinack** [comment]
Hey, can I take this one up?

**Comment by faznan3nazer** [comment]
Hey...I would like to work on this issue..can you please assign me this?

**Comment by b-thebest** [comment]
Can I work on issue, I have worked on login and refresh API earlier, so I find myself best fit.
thank you

**Comment by keshavgbpecdelhi** [comment]
Thanks to you all 4 for showing interest in this issue. We will soon assign you at the right time.

Thankyou
Regards

**Comment by epicadk** [comment]
@isabelcosta closing this. If you think it is valid please reopen it.
