### ISSUE TITLE
Wiki(Fork, Clone & Remote): outdated links and screenshots

### ISSUE THREAD

**Issue by snitin315** [anitab-org/mentorship-backend#565]
**Describe the bug**

In the wiki, the reference links and screenshots are still for `systers`. Which new contributors may find confusing.

**To Reproduce**

1. Go to [Fork, Clone & Remote](https://github.com/anitab-org/mentorship-backend/wiki/Fork,-Clone-&-Remote)
2. See error

**Expected behavior**

The links and Screenshots should be updated to reflect the latest org name.

**Screenshots**

![Screenshot at 2020-05-03 09-46-21](https://user-images.githubusercontent.com/46647141/80898602-fa8a6600-8d22-11ea-8ced-af04b7c307aa.png)

![Screenshot at 2020-05-03 09-43-01](https://user-images.githubusercontent.com/46647141/80898582-b008e980-8d22-11ea-9c6b-f7d40d637e31.png)

**Desktop (please complete the following information):**

Any

**Smartphone (please complete the following information):**
Any
**Additional context**

**Comment by sankha555** [comment]
Hello @snitin315 , 
I am interested in working on this issue. If there is no one else working on it, could you please assign it to me? Thanks

**Comment by snitin315** [comment]
@sankha555 Thank you for showing interest, but I guess only those with `write access` to the repository can edit the wiki.

/cc @isabelcosta

**Comment by sankha555** [comment]
Oh, I see. I'll look for another issue to work then. Thanks for pointing it out all the same :)

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by isabelcosta** [comment]
@gaurivn to change wiki I would have to give you write access which is almost maintainer's level. I would suggest here to move this to the docs folder instead and move it with correct values.
Once you finish other tasks you are assigned, I an assign you here.

**Comment by vj-codes** [comment]
@PrashanthPuneriya only the screenshot needs to be updated.This can be a good issue for OSH.What say?

**Comment by PrashanthPuneriya** [comment]
@vj-codes Yes! this would be a good issue for OSH. But, we need to consider what @isabelcosta said and decide further on what/how to do.

**Comment by SanketDG** [comment]
Moving to Docusaurus is something we did at Portal. We can do that for `mentorship-backend` where each task is a separate issue as seen in https://github.com/anitab-org/portal/pull/657

**Comment by PrashanthPuneriya** [comment]
Woww! That's cool @SanketDG. Can we take such decisions like moving to Docusaurus?

**Comment by gaurivn** [comment]
> Moving to Docusaurus is something we did at Portal. We can do that for `mentorship-backend` where each task is a separate issue as seen in [anitab-org/portal#657](https://github.com/anitab-org/portal/pull/657)

I created an issue for the same: Issue #747, pls do review it.

**Comment by SanketDG** [comment]
> Woww! That's cool @SanketDG. Can we take such decisions like moving to Docusaurus?

Great question! We have to ask @isabelcosta then!

**Comment by Hyper-Matrix** [comment]
I would like to work on this for OSH. Can someone assign it to me on 1st september?

**Comment by Hyper-Matrix** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by gaurivn** [comment]
> I would like to work on this issue as a part of OSH. Can you assign me this issue?

@Hyper-Matrix, this issue is not intended for OSH, and as per the discussion here, I don't think it's available (as of now). I suggest to look out for issues labeled Open Source Hack.

**Comment by vj-codes** [comment]
Will close this and open a new one for updating links and screenshots in docusaurus
