### ISSUE TITLE
Error message for field 'username' is not filled.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#574]
If the field 'username' is not filled in input an appropriate error message should be showned and listed under the 400 Response.

**To Reproduce**

1. Go to 'User-Register'
2.   {
             "name": "testua",
             "username": "",
             "password": "testua123",
             "email": "voxij69223@mailop7.com",
             "terms_and_conditions_checked": true ,
             "need_mentoring": true ,
             "available_to_mentor":true 
            }
3. Click on 'Execute'.
4. Scroll down to 'Response'.
5. 
![Screenshot (18)](https://user-images.githubusercontent.com/50888936/81111690-16685480-8f3b-11ea-95e2-916051d14370.png)

**Expected behavior**
The error message should be listed under 400 error messages

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by abha224** [comment]
@isabelcosta Can i take up this issue?

**Comment by isabelcosta** [comment]
Sure @abha224 :) go ahead!

**Comment by abha224** [comment]
@isabelcosta could you pls unassign me from this issue? I may not be able to complete it on time, as Im occupied with some college work. I want to leave it for other first-timers for now. :see_no_evil:

**Comment by EllieMwangi** [comment]
@isabelcosta Can I take up this issue?

**Comment by meenakshi-dhanani** [comment]
@EllieMwangi I have unassigned the previous assignee. Assigned it to you  :)

**Comment by EllieMwangi** [comment]
Thanks @meenakshi-dhanani

**Comment by isabelcosta** [comment]
@EllieMwangi feel free to let us know if you need any help :)

**Comment by EllieMwangi** [comment]
@isabelcosta I have submitted a pull request, awaiting review.

**Comment by TrojanTarun** [comment]
@isabelcosta 
hii is this issue still open.this is my first time open source contribution if you give me the permission for working on this issue.

**Comment by isabelcosta** [comment]
@TrojanTarun this issue was already solve by PR #604 . Could you please look into another one? I can point your to some, which may not have the first timers only label, but they are very easy to pick and similar to this one :)
- https://github.com/anitab-org/mentorship-backend/issues/616
- https://github.com/anitab-org/mentorship-backend/issues/633
- https://github.com/anitab-org/mentorship-backend/issues/631
