### ISSUE TITLE
Error message for field 'password' is not filled.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#575]
If the field 'password' is not filled in input an appropriate error message should be showned and listed under the 400 Response.

**To Reproduce**

1. Go to 'User-Register'
2.   {
              "name": "testua",
              "username": "testua",
              "password": "",
              "email": "voxij69223@mailop7.com",
              "terms_and_conditions_checked": true ,
              "need_mentoring": true ,
              "available_to_mentor":true 
      }

3.Click on 'Execute'.
4.  Scroll down to 'Response'.
5. 
![Screenshot (20)](https://user-images.githubusercontent.com/50888936/81113375-bf17b380-8f3d-11ea-9480-d02fd139e29d.png)

**Expected behavior**
The error message should be listed under 400 error messages

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by Vuyanzi** [comment]
I would like to be assigned this please

**Comment by SanketDG** [comment]
@Vuyanzi There you go, let us know if you have any questions!

**Comment by Vuyanzi** [comment]
ok, thank you

**Comment by Vuyanzi** [comment]
Hello am still working on this and will push soon. Sorry for any inconvenience caused.
