### ISSUE TITLE
Fix description messages on Backend Server

### ISSUE THREAD

**Issue by StergiosSozos** [anitab-org/mentorship-backend#577]
## Description
As a developer, i need to see the same way for displaying messages on the backend server. so that i can follow the same pattern on the messages im writing.

### Update 
The following methods should include:  
![image](https://user-images.githubusercontent.com/44146773/81184653-52da9580-8fb9-11ea-9287-5ad911cfbfb2.png) before the message itself. 

Users
- [ ] GET / dashboard
- [ ] PUT /user
- [ ] POST user/send email
- [ ] GET /users
- [ ] GET /users/verified

Admins
- [ ]  GET /admins

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by StergiosSozos** [comment]
Since I'm working with @EfthymiaKostaki and she is interested in this issue can she be assigned to this issue?

**Comment by siddhipandare** [comment]
I tried finding her @ in the assignees but couldn't find her as she's not a member of the organization on GitHub

**Comment by siddhipandare** [comment]
@StergiosSozos I tried finding her @ in the assignees but couldn't find her. Is she a member of the org on GitHub? Let me know.

**Comment by StergiosSozos** [comment]
She hasn't be assigned yet in this issue but she has worked on this project, for example PR #545

**Comment by SanketDG** [comment]
@StergiosSozos Given that it's publicly documented that you guys want to work on this issue, please feel free and start work on this. Even though you are not _oficially_ assigned, it should be fine to go ahead with fixing this.

**Comment by isabelcosta** [comment]
@EfthymiaKostaki you have to express interest in this issue, for us to be able to use the username when assigning. Can you please leave a comment here?

**Comment by EfthymiaKostaki** [comment]
@isabelcosta Heyy, I didn't do that because we are working together with @StergiosSozos and we wanted to have similar difficulty in issues. I am interested in this issue!

**Comment by isabelcosta** [comment]
Cool @EfthymiaKostaki :) I couldn't assign you because GitHub would not allow me unless you would participate in this discussion.

**Comment by Aayush-hub** [comment]
@isabelcosta Can you please assign me this?

**Comment by epicadk** [comment]
@Aayush-hub Assigning you good luck : ).

**Comment by Aayush-hub** [comment]
@epicadk Can you please tell the steps how to get to this part?

**Comment by epicadk** [comment]
> @epicadk Can you please tell the steps how to get to this part?

I think it is just a change to swagger ui. You can take a look at the pr by @EfthymiaKostaki sent above I think it almost solves the issue.

**Comment by Aayush-hub** [comment]
@epicadk Sir, can you please help me after trying very hard I am still coming with error `sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:None` after running `run.py`. I have made .env file and setted  FLASK_ENVIRONMENT_CONFIG=local .

**Comment by Aayush-hub** [comment]
@isabelcosta Can you please help me after trying very hard I am still coming with error
`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:None` after running `run.py`.
I have made .env file and setted FLASK_ENVIRONMENT_CONFIG=local .
