### ISSUE TITLE
Remove cffi from dependencies

### ISSUE THREAD

**Issue by SanketDG** [anitab-org/mentorship-backend#578]
**Describe the bug**

When installing dependencies `pip install -r requirements.txt`, it fails on Python 3.8.2

**To Reproduce**

- Try to setup the project on Python version 3.8.2
- `pip install -r requirements.txt` fails on installing `cffi`

**Expected fix**
Remove cffi from dependencies and make sure our tests work.

**Additional context**
https://bitbucket.org/cffi/cffi/issues/403/build-fails-on-38-dev-pyinterpreterstate

**Comment by isabelcosta** [comment]
Thank you for creating this @SanketDG !

**Comment by nickinack** [comment]
Can I take this one up?

**Comment by SanketDG** [comment]
This issue may be obsolete as we don't use `cffi` at all (it's a transitive dependency), so maybe we should remove `cffi`?

@isabelcosta

**Comment by isabelcosta** [comment]
@SanketDG remove `cffi` as an dependency? sure, if its not needed.

**Comment by SanketDG** [comment]
@nickinack You still interested in this?

**Comment by nickinack** [comment]
@SanketDG yes I'm still interested!
