### ISSUE TITLE
Upgrade to flask-restx

### ISSUE THREAD

**Issue by SanketDG** [anitab-org/mentorship-backend#579]
**Describe the bug**

`flask-restplus` is not maintained anymore, it's best we move to [flask-restx](https://github.com/python-restx/flask-restx)

A lot of modules break on newer Python versions because of `flask-restplus` staying unmaintained.

This is a big change, but it's a change in the right direction.

Relevant links:
https://github.com/noirbizarre/flask-restplus/issues/593

**Comment by isabelcosta** [comment]
Wow I had no idea about this 😱 I was aware of the issue you mentioned, but I did not know about this at all. This is awesome, how a group of people joined to continue the project and keep it alive ❤️ 
@SanketDG thank you so much for bringing this to our attention.

**Comment by isabelcosta** [comment]
@SanketDG can you estimate the time?! the complexity of doing this? I am asking because since this is a fork, maybe it's not that complex?

**Comment by SanketDG** [comment]
@isabelcosta 

I did take a rough look at the estimation, and it seems like they have tried and maintained 100% compatilibity as much as they can. The only change that seems immediate is the package name i.e. `flask_restplus` -> `flask_restx`. There can be other small changes, but I am hoping there won't be any major breaking changes.

I will be taking this up and doing this over the weekend, but since this is a large refactor, it will require some discussion. When this is merged, a lot of existing PRs will have large merge conflicts because of the changes. We can obviously choose to merge this change when the PRs are at a minimum.

What do you think?

**Comment by vkWeb** [comment]
@SanketDG I think let's get this in as soon as we can. There won't be a lot of conflicts I believe if flask-restx is compatible with flask-restplus. 

What do you all think?
