### ISSUE TITLE
Upgrade psycopg2-binary to the latest version

### ISSUE THREAD

**Issue by Ritika5901234** [anitab-org/mentorship-backend#586]
**Describe the bug**

When installing dependencies pip install -r requirements.txt, it fails on Python 3.8.2

**To Reproduce**

Steps to reproduce the behaviour:

Try to setup the project on Python version 3.8.2
`pip install -r requirements.txt` fails on installing `psycopg2-binary`

**Expected behavior**
Upgrade `psycopg2-binary` to the latest version and make sure our tests work.

**Screenshots**

![image](https://user-images.githubusercontent.com/9658378/81730064-9dbd4700-94aa-11ea-99c7-5126ee8546d9.png)

**Additional context**
https://github.com/psycopg/psycopg2/issues/990

**Comment by Ritika5901234** [comment]
Hi, I have created an issue here for first time, can I be assigned this issue? I plan to upgrade the version from 2.8.3 to 2.8.5 which eliminates the error, please let me know your suggestions.

**Comment by vkWeb** [comment]
@Ritika5901234 Welcome to the community. 

I have assigned you this issue. You can start working on this :)

**Comment by Ritika5901234** [comment]
@vkWeb - thanks for assigning the issue (P.S. - I have worked on one existing issue but I have created an issue for the first time)
