### ISSUE TITLE
Add only Python3 support in tests

### ISSUE THREAD

**Issue by EfthymiaKostaki** [anitab-org/mentorship-backend#595]
## Description
I was working on an issue to alter the test structure of the project and discussing with a maintainer we found out that the project should only support python 3 but in some tests, this is not achieved. For example, in tasks_base_setup this is happening:
![image](https://user-images.githubusercontent.com/43841219/82122417-4cf46980-979c-11ea-9660-e98f777e6192.png)
The setup method should be written like this
<code>
super.setUp()
</code>

## Acceptance Criteria
- [ ] Refactor all the test bases which support Python2 to Python3 as presented
- [ ] All local testing passing
### Update [Required]
- [ ] tests/tasks/tasks_base_setup 
- [ ] tests/mentorship_relation/relations_base_setup 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by muskanvk** [comment]
Please assign this to me. I'd like to work on this issue !

**Comment by Abjcodes** [comment]
I would like to work on this issue. Can assign it to me if its available? Thank you.

**Comment by Aaishpra** [comment]
Hey, @vj-codes can I get assigned here.

**Comment by vj-codes** [comment]
Assigning you @Aaishpra 
Happy coding!

**Comment by Aaishpra** [comment]
> Assigning you @Aaishpra
> Happy coding!

Thanks for the quick response @vj-codes
