### ISSUE TITLE
Error message for missing all fields under update user profile.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#597]
When we delete all fields in input, an appropriate error message should be showned and listed under Responses.
**To Reproduce**

1. Go to 'User-update user profile'.
2. Provide authorization access token.
3.  Input playload:
 {
  }
4.  Click on 'Execute'
5. Scroll down to 'Respense.'
6. 
![Screenshot (72)](https://user-images.githubusercontent.com/50888936/82156969-3af9f000-989c-11ea-887f-d0b5185c0660.png)

**Expected behavior**
That error message should be listed in the responses.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by Maheejaiswal** [comment]
hello, I am a first-timer and participated in OSH. Can you please help me through this?

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by faznan3nazer** [comment]
I would like to work on this issue.. Can you please assign this to me for Open-Source Hack?

**Comment by HeroicHitesh** [comment]
I would like to work on this issue under OSH. Please assign me this issue when it's free.

**Comment by Anmollenka** [comment]
I would like to work on this issue under OSH.I am a first timer .Can you please assign this to me??Thank You.

**Comment by Abjcodes** [comment]
Can you assign this issue to me if its available? Thank You.

**Comment by Bhavani-Somanchi** [comment]
I would like to work on this issue as part of the Open Source Hack. Can you please assign it to me? Thank you!

**Comment by pallavisavant** [comment]
I have participated for OSH....if this is still available can i take up this one... as i haven't been assigned any under documentation...Thanks.

**Comment by alivabasa** [comment]
I want to take up this issue for OSH.

**Comment by Anmollenka** [comment]
@isabelcosta @vj-codes @gaurivn Can you please give me this issue to solve as I have already solved an issue of this type and hence can be able to solve this one.Thank You.

**Comment by vj-codes** [comment]
Assigning you @Anmollenka 
Happy coding!

**Comment by Anmollenka** [comment]
@vj-codes What would be the authorization acess token??

**Comment by vj-codes** [comment]
@Anmollenka in `User/login` you have to enter username and password of your mentorship system acc and then after clicking on execute the access token will be generated . Copy that token and paste in `User/update`

**Comment by Anmollenka** [comment]
> @Anmollenka in `User/login` you have to enter username and password of your mentorship system acc and then after clicking on execute the access token will be generated . Copy that token and paste in `User/update`

Thank you @vj-codes

**Comment by Anmollenka** [comment]
Another doubt what is the category of this issue??

**Comment by vj-codes** [comment]
I would say the main category is coding

**Comment by Anmollenka** [comment]
@vj-codes I followed the steps just as you said.

> > @Anmollenka in `User/login` you have to enter username and password of your mentorship system acc and then after clicking on execute the access token will be generated . Copy that token and paste in `User/update`
> 
> Thank you @vj-codes

**Comment by Anmollenka** [comment]
But still I am getting invalid token error.

**Comment by vj-codes** [comment]
@Anmollenka the syntax  is `Bearer <token>` 
You might have not added the word bearer in the text input before your token. Try this out it , if it doesn't work do update your error and I could help :)

**Comment by Anmollenka** [comment]
@vj-codes I am still receiving the same error.

**Comment by Anmollenka** [comment]
Shall I attach the screenshot of the access token and the error??

**Comment by vj-codes** [comment]
Ya that would help , you can share it here or on zulip @Anmollenka

**Comment by vj-codes** [comment]
@Anmollenka any updates?

**Comment by Anmollenka** [comment]
@vj-codes I have worked on the issue but I am unable to create the ouput in the local database.The main problem is that it is showing the username or password is wrong and I am unable to register as a new user it is showing some forbidden error.
I will try once again today and ask on Zulip if I face any issue.Thank You.

**Comment by alivabasa** [comment]
I want to work on this, if it's available.

**Comment by devkapilbansal** [comment]
@Anmollenka are you still working on this? It's being a long time and this issue has no pull request linked to it

**Comment by Anmollenka** [comment]
@devkapilbansal I am still uanble to create the output in the local database.It will be okay if someone else is assigned.

**Comment by devkapilbansal** [comment]
Okay @faznan3nazer I will look into this issue

**Comment by devkapilbansal** [comment]
@PrashanthPuneriya assign this to me
