### ISSUE TITLE
Error message mismatch under update user profile.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#606]
When we enter numericals instead of characters for name, the error message mismatches.
 
**To Reproduce**

1. Go to 'user-update user profile'.
2. Provide authorization access token.
3. {
  "name": "1234567",
  "username": "1234567",
  "bio": "string",
  "occupation": "string",
  "organization": "string",
  "slack_username": "string",
  "social_media_links": "string",
  "skills": "string",
  "interests": "string",
  "resume_url": "string",
  "photo_url": "string",
  "need_mentoring": false,
  "available_to_mentor": false,
  "location": "string"
}

4. Click on 'Execute'.
5. Scroll down to 'Response'.
6. 
![Screenshot (83)](https://user-images.githubusercontent.com/50888936/82572787-836a2400-9ba2-11ea-90aa-fd2fa5841a62.png)
 

**Expected behavior**
Error message should be same in both server response and responses.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  Chrome

**Comment by faznan3nazer** [comment]
When we enter special characters instead of characters, it is showing same error as above.

**Comment by faznan3nazer** [comment]
I would like to work on this PR. Can I take this up?

**Comment by vj-codes** [comment]
Sure assigning you @faznan3nazer 
Happy coding!

**Comment by faznan3nazer** [comment]
This issue was assigned to me a few days back...can you unassign me and assign back on September 1st. I would like to work on this issue as a part of OSH.

**Comment by vj-codes** [comment]
@faznan3nazer how's the PR going?

**Comment by faznan3nazer** [comment]
Can you please grant me 2 more days to create PR for this issue?
I would like to work on this issue as a part of OSH. Can you please add OSH label for this issue?

**Comment by faznan3nazer** [comment]
When I tried to set up the project locally...I am getting some error... That is why I couldn't create PR for this issue...  
![Screenshot (347)](https://user-images.githubusercontent.com/50888936/92940547-e2fb8080-f46c-11ea-919c-4634080f9014.png)

**Comment by vj-codes** [comment]
@faznan3nazer can you share your .env file?

**Comment by faznan3nazer** [comment]
> @faznan3nazer can you share your .env file?

 cat .env
FLASK_ENVIRONMENT_CONFIG = local
SECRET_KEY = fazna123
SECURITY_PASSWORD_SALT = 7907
MAIL_DEFAULT_SENDER = xxxxx@gmail.com
MAIL_SERVER = smtp.gmail.com
APP_MAIL_USERNAME = xxxxx@gmail.com
APP_MAIL_PASSWORD = xxxxxxxx
(venv)

**Comment by vj-codes** [comment]
APP_mail_username is the part before '@' in your gmail id , in this case it'll be` xxxxx`
And add MOCK_EMAIL = `True`
@faznan3nazer and see if there's any change

**Comment by faznan3nazer** [comment]
> APP_mail_username is the part before '@' in your gmail id , in this case it'll be` xxxxx`
> And add MOCK_EMAIL = `True`
> @faznan3nazer and see if there's any change

Actually I used the same...my mail id...but haven't added MOCK_EMAIL...Let me try this one...

**Comment by faznan3nazer** [comment]
@vj-codes I am getting the same error.

**Comment by rpattath** [comment]
@faznan3nazer any updates?

**Comment by faznan3nazer** [comment]
> @faznan3nazer any updates?

@rpattath  I will complete it by Tomorrow...

**Comment by alivabasa** [comment]
Can I be assigned this issue? I don't have any documentation issue so far.
