### ISSUE TITLE
Delete the error message "The authorization token is missing" from the response.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#607]
When we click execute without providing any token, it doesn't execute. Which is a correct behaviour. But if that's the case you have to remove that response from the response list.

**To Reproduce**

1. Go to 'user-update user profile'.
2. Authorization access token is not provided.
3. Click on 'Execute'.
4. 
![Screenshot (88)](https://user-images.githubusercontent.com/50888936/82598434-4c0e6e00-9bc8-11ea-9a24-20a29addc1aa.png)

**Expected behavior**
Error message listed under the response, "The authorization token is missing" should remove from list.

![Screenshot (89)](https://user-images.githubusercontent.com/50888936/82598784-c808b600-9bc8-11ea-9e28-8445041d880c.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser chrome

**Comment by sahil9001** [comment]
Can I take up this issue?

**Comment by SanketDG** [comment]
There you go, Sahil!

**Comment by SanketDG** [comment]
@faznan3nazer Could you explain me this issue? I am not able to understand from the description.

**Comment by sahil9001** [comment]
She was saying that in the POSTMAN UI the user has to put the Authorization token before accessing the GET request, so the message "The authorization token is missing" makes no sense because you have to enter that first before accessing the GET request.

**Comment by SanketDG** [comment]
@sahil9001 Well, one can send the request without the authorization token, and then the right error mesage appears

```
➜ http PUT http://localhost:5000/user/
HTTP/1.0 401 UNAUTHORIZED
Content-Length: 57
Content-Type: application/json
Date: Sun, 24 May 2020 19:14:10 GMT
Server: Werkzeug/0.15.3 Python/3.7.7

{
    "message": "The authorization token is missing!"
}
```

**Comment by isabelcosta** [comment]
Ah I think @rpattath mentioned this issue to me previously. It's true that you can use a different client than Swagger UI and eventually get that response. So I think this issue is not valid.
Thank you @SanketDG for the explanation

**Comment by isabelcosta** [comment]
I am closing this issue because of the previous comments ^^
@sahil9001 feel free to pick another issue that is available, we have plenty ;)

**Comment by sahil9001** [comment]
okay
