### ISSUE TITLE
Add flutter client to API Swagger description

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#610]
## Description
As a contributor,
I need information accessible in the Swagger UI,
so that I can get to know more about mentorship system projects.

The idea is to add an extra line mentioning the flutter client and its URL

## Mocks

This is how the description looks like at the moment:

![image](https://user-images.githubusercontent.com/11148726/82814944-0daad480-9e90-11ea-8a69-7f3d5b2250ab.png)

### Update [Required]
- [ ] Add flutter client text on Swagger UI description

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by vj-codes** [comment]
Closing since this part is merged into #724
