### ISSUE TITLE
Mention on Swagger UI the default values regarding pagination

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#612]
## Description

As a developer/tester,
I need to know what I should expect as default values of pagination,
so that I can properly test is or understand the values used if I don't give any.

## Mocks

Here's an example of how the default values could appear there:

![image](https://user-images.githubusercontent.com/11148726/82818641-eefc0c00-9e96-11ea-8b88-4d3b72c1b655.png)

### Update [Required]
- [ ] Adds default values used for pagination to the Swagger UI.
- [ ] Update API description to mention that when the listing reached the end, the API simply returns an empty list.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by nickinack** [comment]
@isabelcosta, I would like to work on this, can you please assign this to me

**Comment by isabelcosta** [comment]
Sure @nickinack ;)

**Comment by vj-codes** [comment]
@nickinack Hows the PR going?

**Comment by isabelcosta** [comment]
@nickinack I removed the assignment and label since more than 3 days passed without a response.
@vj-codes This is in the Contribution Guidelines, so feel free to do this if you don't get a response for too long.

**Comment by livrbecca** [comment]
Can i be assigned to this please?

**Comment by livrbecca** [comment]
Hi @isabelcosta, I’ve made the changes, also messaged you

**Comment by isabelcosta** [comment]
Can you create the Pull Request, please? So I can review your changes :) @livrbecca 
Also, feel free to join our Zulip community here https://anitab-org.zulipchat.com/ 🤗
