### ISSUE TITLE
Responses does not list "Notes field is missing." error message.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#613]
When we update an user profile, if the filed notes is removed from the inputs then we see the expected error  "Notes field is missing." but this not listed under responses.

**To Reproduce**

1. Go to 'Mentorship relation- send request'.
2. Provide authorization access token.
3.   {
     "mentor_id": 271,
     "mentee_id": 272,
     "end_date": 1598400000
      }

4.  Click on 'Execute'.
5. Scroll down to 'Responses'
6. 
![Screenshot (109)](https://user-images.githubusercontent.com/50888936/83188523-7377b480-a14d-11ea-98f7-81f0c12e38e4.png)

**Expected behavior**
All the error messages should be listed under the 400 error messages

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by UdokaVrede** [comment]
any more detail on this please

**Comment by isabelcosta** [comment]
@UdokaVrede what detail you feel is missing? This is about adding a new message to the responses displayed on swagger UI which is accessible through http://localhost:5000 when you run the app or here https://mentorship-backend-temp.herokuapp.com/ Is this clearer?

**Comment by Bhavani-Somanchi** [comment]
@faznan3nazer  @isabelcosta  Can I work on this issue?

**Comment by isabelcosta** [comment]
@Bhavani-Somanchi I will leave this issue unassigned since I already assigned this https://github.com/anitab-org/mentorship-backend/issues/561 to you :)

**Comment by UdokaVrede** [comment]
@isabelcosta  yes I guess so

**Comment by isabelcosta** [comment]
@UdokaVrede so do you want me to assign this to you? let me know and I'll do it :)

**Comment by UdokaVrede** [comment]
yeah sure

**Comment by faznan3nazer** [comment]
I would like to work on this issue...can you please assign this to me

**Comment by pallavisavant** [comment]
if its still available i would like to work on this

**Comment by Anmollenka** [comment]
@vj-codes and @isabelcosta I would like to work on this issue.Can you I work on this issue if it is available?Thank You.

**Comment by vj-codes** [comment]
@Anmollenka  hey, this is a first timers issue and you have created #838 thus no more eligible
Please go through other available issues and comment on any one to start working. Thanks:)

**Comment by Anmollenka** [comment]
@vj-codes can I work on issue #597 as it is not a first timer issue.Thank you?

**Comment by alivabasa** [comment]
Hi, I would like to work on this issue, if available.

**Comment by ravi5175** [comment]
@vj-codes @isabelcosta @SanketDG @PrashanthPuneriya please assign me this issue, i have completed my previous one

**Comment by vj-codes** [comment]
@ravi5175 this is a `first timers only` issue thus you aren't eligible to be assigned .
Please look out for other available issues :)

**Comment by faznan3nazer** [comment]
@isabelcosta  Hey...I would like to work on this issue..can you please assign this to me?

**Comment by pallavisavant** [comment]
if this is available can i claim this???

**Comment by vj-codes** [comment]
@faznan3nazer @pallavisavant sorry this is a first timers only issue ,please go through other available issues:)

**Comment by amritada** [comment]
Hi I am a first time open source contributor. Can you please assign this issue to me if it is still available?

**Comment by isabelcosta** [comment]
@amritada I will assign this to you :) happy coding!
