### ISSUE TITLE
Responses does not list "Mentee ID field is missing." error message.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#615]
When we update an user profile, if the filed notes is removed from the inputs then we see the expected error  "Mentee ID field is missing." but this not listed under responses.
**To Reproduce**

1. Go to 'Mentorship relation- send request'.
2. Provide authorization access token.
3.  {
     "mentor_id": "271",
     "end_date": 1598400000,
     "notes": "string"
     }
4. Click on 'Execute'.
5. Scroll down to 'Responses'.
6. 
![Screenshot (122)](https://user-images.githubusercontent.com/50888936/83192111-b7b98380-a152-11ea-93c6-01827f655a6b.png)

**Expected behavior**
All the error messages should be listed under the 400 error messages

**Desktop (please complete the following information):**
 - OS:  windows 10
 - Browser  chrome

**Comment by nickinack** [comment]
I would like to work on this, can someone assign this to me?

**Comment by vermastuti** [comment]
@isabelcosta Can I work on this issue?

**Comment by isabelcosta** [comment]
@nickinack since you are not a first timer anymore 🎉 I will assign to @vermastuti :)
@vermastuti I hope you are still interested 🤗

**Comment by vj-codes** [comment]
@vermastuti hey how's the PR going?

**Comment by vermastuti** [comment]
Need help with environment variables. Where can I get these values?

**Comment by SanketDG** [comment]
Could you show us the `.env` file @vermastuti ?

**Comment by vj-codes** [comment]
@vermastuti hey are you still working on this issue?

**Comment by vermastuti** [comment]
Yes I'm working on it. Wanted some help on this to move forward.

**Comment by vermastuti** [comment]
@vj-codes yes, wanted some help on setting up the project in my machine. I have setup the GitHub repo but some issue is coming up.

**Comment by vj-codes** [comment]
@vermastuti can you explain the issues here or on zulip , then I  or someone else can help you setting the repo successfully:)

**Comment by vermastuti** [comment]
I have setup the repo successfully. Also, I found that "Mentee ID field is missing." error message is already added in the app/api/resources/mentorship_relation.py/SendRequest function. Could anyone test if the issue still persists? Also, if possible, please provide authorization access token to test the issue.

**Comment by vermastuti** [comment]
@isabelcosta @SanketDG @vj-codes I have made the changes and raised a PR. Please review the PR and let me know if there are any more changes to this.
