### ISSUE TITLE
Responses does not list "End date field is missing." error message.

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#616]
When we update an user profile, if the filed notes is removed from the inputs then we see the expected error "End date field is missing." but this not listed under responses.

**To Reproduce**

1 .Go to 'Mentorship relation- send request'.
2. Provide authorization access token.
3. 
```
{
      "mentor_id": "271",
      "mentee_id": "272",
      "notes": "string"
}
```
4. Click on 'Execute'.
5. Scroll down to 'Responses'.
6. 
![Screenshot (123)](https://user-images.githubusercontent.com/50888936/83233781-dba9b300-a1ac-11ea-809a-497297801361.png)

**Expected behavior**
All the error messages should be listed under the 400 error messages

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by 19-pragya** [comment]
Can i work on this issue?

**Comment by titiksha01** [comment]
@faznan3nazer Hello, As OSH has begin, i would like to work on this issue. Can this be assigned to me? I am new to open source so please guide me.

**Comment by faznan3nazer** [comment]
I would like to work on this issue... Can you please assign this to me for Open-Source Hack?

**Comment by Anmollenka** [comment]
I would like to work on this issue as a part of OSH.Can you please assign it to me?Thank You

**Comment by arjungarg07** [comment]
Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by sreelekha901** [comment]
Can you assign this to me
I'm participating in OSH

**Comment by codesankalp** [comment]
I want to work on this issue. I want to contribute  @darecoder

**Comment by darecoder** [comment]
@faznan3nazer as you are already been assigned to some of the issues, I'm assigning this to @Anmollenka.

**Comment by Anmollenka** [comment]
#836

**Comment by Anmollenka** [comment]
@darecoder  I have opened one pull request but it is not passing 2 out of 3 cases.Should I close that one??

**Comment by Anmollenka** [comment]
And also I am not able to understand why am I failing in that case can you please help me out.

**Comment by darecoder** [comment]
@Anmollenka Didn't you link the PR to this issue?

**Comment by Anmollenka** [comment]
I first created draft pull request to check if it is passing all the cases.

**Comment by Anmollenka** [comment]
Shall I add the review part and link it here???

**Comment by darecoder** [comment]
@Anmollenka I just saw your PR, always try to give a meaningful title to your PR and add words like fixes, closes along with issue hash. You have mentioned fixes # 616, the space between # and issue no. wasn't required. I'll review the PR soon, till then explore some other issues:)

**Comment by Anmollenka** [comment]
> @Anmollenka I just saw your PR, always try to give a meaningful title to your PR and add words like fixes, closes along with issue hash. You have mentioned fixes # 616, the space between # and issue no. wasn't required. I'll review the PR soon, till then explore some other issues:)

@darecoder Ok mam,I will always try to give a meaningful title to my PR henceforth.

**Comment by Anmollenka** [comment]
> @Anmollenka I just saw your PR, always try to give a meaningful title to your PR and add words like fixes, closes along with issue hash. You have mentioned fixes # 616, the space between # and issue no. wasn't required. I'll review the PR soon, till then explore some other issues:)

Please review it and tell me if any changes are required.

**Comment by faznan3nazer** [comment]
Is this issue still available? can I claim this ?

**Comment by amritada** [comment]
Can I claim this issue if it is still available?

**Comment by isabelcosta** [comment]
@faznan3nazer @amritada I asked for a change on the PR sent by @Anmollenka . If we get no answers soon, I can re assign this :)
