### ISSUE TITLE
Fix: refactor HTTP error codes POST /register for Users service

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#619]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to POST /register request,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 201: Created need to be returned instead of 200: OK if the process is successful 
- [ ] 409: Conflict need to be returned instead of 400: Bad Request if the username or email already exist

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by meenakshi-dhanani** [comment]
Isn't there also a 404 being returned that should be 401? Is that a separate issue?

**Comment by mtreacy002** [comment]
Yeah. That will be on separate issue (POST /login) 😉 
<img width="580" alt="Screen Shot 2020-06-03 at 7 25 24 pm" src="https://user-images.githubusercontent.com/29667122/83619998-068e6f80-a5d0-11ea-9485-f0c8d1b7535d.png">

**Comment by nandini45** [comment]
@mtreacy002  are you working on this issue or i can work on it?
btw i think this can be a first timer issue .. its quite easy right?

**Comment by nandini45** [comment]
btw i think this can be a first timer issue if you want?

**Comment by mtreacy002** [comment]
Hi @nandini45 . You are most welcome to work on it. Please feel free to ask me anything if you have unclear off.... 😉

**Comment by nandini45** [comment]
yeah sure.!! 
i had a question i have to update the 200 httpcodes with 201 but can you elaborate a bit more under what criteria? or i just have to update all the 200 httpcodes?

**Comment by mtreacy002** [comment]
so, since we're sending a POST /register request, which means we ask a user to be created by the system, the system then should return HTTPStatus.CREATED to confirm that the user has been created. HTTPStatus.OK only means a process requested is successful, but not specific to what process itself. So, this is why we need the 201 instead of 200 (it's much closer in reflecting to what the process is). Does this makes sense, @nandini45?

**Comment by mtreacy002** [comment]
The same as 409: Conflict. Since the user trying to register with using an existing user data in the database, the system should notify the user that trying to register that the action they requested has raised a `conflict` with existing data.

**Comment by mtreacy002** [comment]
> @mtreacy002 are you working on this issue or i can work on it?
> btw i think this can be a first timer issue .. its quite easy right?

We actually want someone to work on this issue asap as this issue is blocking the bridge-in-tech progress for GSoC. That's why we don't label it first-timer issue, coz we need someone to do it `reasonably` quickly 👌 😃

**Comment by nandini45** [comment]
yeah i understand i will do it asap

**Comment by mtreacy002** [comment]
Thank you soooooo much for your help, @nandini45 ❤️ . You're the BEST!!! 🤗 😘

**Comment by nandini45** [comment]
@mtreacy002 @isabelcosta  During updating the values in app/api/dao/task there is a httpcode for whose code value is returned instead of the httpcode
![image](https://user-images.githubusercontent.com/62046625/83653075-f7f88600-a5d8-11ea-8e42-0e4bd5711ee7.png)

so should i change it or a separate issue can be created???

**Comment by nandini45** [comment]
although i have replaced all the 200 and 400 codes. do tell me if i can change 403 also!!
