### ISSUE TITLE
Fix: refactor HTTP error codes GET/users/{user_id}

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#623]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to GET /users/{user_id},
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA
### Update [Required]
- [ ] 200: OK needs to be returned instead of 201: Created if the process is successful
- [ ] 403: Forbidden needs to be returned instead of 400: Bad Request if the user_id who sends the request is not valid the operation.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by satya7289** [comment]
I want to work on the issue. @anitab-org/mentorship-managers

**Comment by mtreacy002** [comment]
Thanks, @satya7289 for helping with this issue 🙂
