### ISSUE TITLE
Fix: refactor HTTP error codes POST /user/resend_email for Users service

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#625]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to POST /user/resend_email request,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 409: Conflict need to be returned instead of 403: Forbidden if the email already confirmed

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by satya7289** [comment]
I want to work on this issue. @anitab-org/mentorship-managers

**Comment by vj-codes** [comment]
Assigning you @satya7289 
Happy coding!

**Comment by harshakhmk** [comment]
I would like to work on this @isabelcosta @devkapilbansal

**Comment by devkapilbansal** [comment]
Assigning you @harshakhmk
