### ISSUE TITLE
Fix: refactor HTTP error codes POST /mentorship_relation/send_request

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#626]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to POST /mentorship_relation/send_request,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 201: Created need to be returned instead of 200: OK if the process is successful

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by satya7289** [comment]
I want to work on this. @anitab-org/mentorship-managers
