### ISSUE TITLE
Fix: refactor HTTP error codes PUT / mentorship_relation/{request_id}/accept

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#627]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to PUT / mentorship_relation/{request_id}/accept,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 403: Forbidden need to be returned instead of 400: Bad Request if the request state is not pending state, the request is sent to themselves, the request is for uninvolved mentor relation, user is involved in another mentorship relation.

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ApheleiaS** [comment]
@isabelcosta can I work on this issue?

**Comment by isabelcosta** [comment]
@ApheleiaS yes for sure :) I just assigned it to you

**Comment by isabelcosta** [comment]
@ApheleiaS I will unassign you this issue due to inactivity. If you are still interested please let me know and I will assign it to you again :)

**Comment by rashikaqureshi** [comment]
Hi can I start working on this ?

**Comment by rashikaqureshi** [comment]
Hi @isabelcosta can I work on this.

**Comment by vj-codes** [comment]
@rashikaqureshi Hey assigning you 
Happy coding!

**Comment by rashikaqureshi** [comment]
Hi @vj-codes Please check and let me know if you need any changes.
https://github.com/anitab-org/mentorship-backend/pull/699/commits

**Comment by rashikaqureshi** [comment]
Hi @vj-codes Please check and let me know if you need any changes.
#699
