### ISSUE TITLE
Fix: refactor HTTP error codes PUT /mentorship_relation/{request_id}/task/{task_id}/complete

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#632]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to PUT /mentorship_relation/{request_id}/task/{task_id}/complete,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 409: Conflict need to be returned instead of 400: Bad Request if the task was already achieved

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by nandini45** [comment]
can i work on it?

**Comment by vj-codes** [comment]
@nandini45 Are you available to work on this?

**Comment by nandini45** [comment]
yes @vj-codes  sorry for the late comment

**Comment by vj-codes** [comment]
Assigning you @nandini45 
Happy coding!

**Comment by nandini45** [comment]
@vj-codes  i am working on it.
need some time..a little caught with  my other work

**Comment by vj-codes** [comment]
@nandini45 hows the PR  going?

**Comment by nandini45** [comment]
my laptop broke down 
i need time to assemble back.
you can assign it to someone else

**Comment by PrashanthPuneriya** [comment]
@divyanshugit Do you want to work on this issue? This issue gives you an overview of the project flow.

**Comment by divyanshugit** [comment]
Yes, I would love to work on this issue.

**Comment by divyanshugit** [comment]
@PrashanthPuneriya Yes, I would love to work on this issue !!

**Comment by PrashanthPuneriya** [comment]
Assigned you this issue @divyanshugit . Looking forward for your PR :)

**Comment by vj-codes** [comment]
@divyanshugit hey how's the PR going?

**Comment by divyanshugit** [comment]
@vj-codes , @PrashanthPuneriya  Now the task API is changed to HTTPstatus.FORBIDDEN (in #682). Do I still need to change it to 403:FORBIDDEN  to 409:CONFLICT?

**Comment by PrashanthPuneriya** [comment]
@divyanshugit To my knowledge #682 has no impact on this issue. You still need to refactor the status code to 409:Conflict. May be I am wrong. What's the reasoning behind this question?

**Comment by divyanshugit** [comment]
@PrashanthPuneriya I mean in file app/api/dao/task.py:  
![Screenshot (192)](https://user-images.githubusercontent.com/53843818/91648228-676bfd80-ea82-11ea-9252-197c2c6b85b8.png)
Do I need to change the HTTPstatus.FORBIDDEN to HTTPstatus.CONFLICT?

**Comment by PrashanthPuneriya** [comment]
Yes! You need to change every related piece of code. Since, you got this doubt I would suggest you to read [this wiki](https://github.com/anitab-org/mentorship-backend/wiki/Code-Organization) to understand more about the codebase.

**Comment by vj-codes** [comment]
@PrashanthPuneriya is this an OSH issue?

**Comment by PrashanthPuneriya** [comment]
No! I don't think so @vj-codes

**Comment by vj-codes** [comment]
I would like to work on this :)

**Comment by vj-codes** [comment]
Update changes done will send a PR tomr
