### ISSUE TITLE
Fix: refactor HTTP error codes GET /mentorship_relation/{request_id}/task/{task_id}/comments

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#636]
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to GET /mentorship_relation/{request_id}/task/{task_id}/comments, 
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 403: Forbidden needs to be returned instead of 400: Bad Request if it has unaccepted state relation

### Enhancement to Update [Optional]
NA
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Ritika5901234** [comment]
Hi @mtreacy002 - I am interested, can you assign this to me :-)

**Comment by mtreacy002** [comment]
I'd be glad to if I have authority to assign you (unfortunately I don't). But, I'll pass this on to @anitab-org/coding-team and @anitab-org/bridgeintech-maintainers . Can anyone in the team please assign this issue to @Ritika5901234? Thanks, heaps.

**Comment by Ritika5901234** [comment]
Thanks @meenakshi-dhanani and @mtreacy002 !

**Comment by vj-codes** [comment]
@Ritika5901234 Hey how's the PR work going?

**Comment by Ritika5901234** [comment]
@vj-codes - thanks for commenting, I missed to push changes and raise PR here earlier.

**Comment by b-thebest** [comment]
Can I take up this issue

**Comment by vj-codes** [comment]
Assigning you @b-thebest 
Happy coding!

**Comment by b-thebest** [comment]
@vj-codes @mtreacy002  Could you please review my PR
