### ISSUE TITLE
Change __repr__ strings format to f-strings

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#639]
## Description
As a developer,
I need to have code using f-strings,
so that I can promote coding style consistency.

Coding standards 👉 https://github.com/anitab-org/mentorship-backend/wiki/Coding-Standards

## Mocks

Some of the places to change are:
- https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/user.py#L115
- https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/tasks_list.py#L158
- https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/mentorship_relation.py#L99 (uncomment and change for f-strings)

### Update [Required]
- [ ] Change every place that is not using f-strings, at least in the places already talked about.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by vj-codes** [comment]
@isabelcosta I would like to work on this

**Comment by evangelisilva** [comment]
@vj-codes You are assigned 😊

**Comment by vj-codes** [comment]
@EvangeliSilva I have changed the strings mentioned in the mocks , do I have to change only those or I have to look for more in the code and change them too?

**Comment by isabelcosta** [comment]
@vj-codes if you find more which could use f-strings its fine :) But for this specific issue i would keep the PR specific to this issue, so if you are thinking about f-strings in other parts of the code as API resources, I would say to create an issue for you to focus on those. Where did you see you could do more?

Also feel free to submit the PR already regarding this issue so we can give you feedback asap :)

**Comment by vj-codes** [comment]
@isabelcosta thanks.I'll submit the PR soon!

**Comment by vj-codes** [comment]
Update on my PR:
Was facing a few issues which is solved now and will send a PR tomorrow.
