### ISSUE TITLE
XMLHttp Request Error

### ISSUE THREAD

**Issue by techno-disaster** [anitab-org/mentorship-backend#641]
**Is your feature request related to a problem? Please describe.**
For the flutter web mentorship client, i keep getting a XMLHTTP Error. This is the exact error.
``` Access to XMLHttpRequest at 'https://mentorship-backend-temp.herokuapp.com/login' from origin '<myurl>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Describe the solution you'd like**
 A solution for this would be enabling CORS. This should be pretty easy. You may refer [this]( https://flask-cors.readthedocs.io/en/latest/)

**Comment by Techno-Disaster** [comment]
> **Is your feature request related to a problem? Please describe.**
> For the flutter web mentorship client, i keep getting a XMLHTTP Error. This is the exact error.
> ` Access to XMLHttpRequest at 'https://mentorship-backend-temp.herokuapp.com/login' from origin '<myurl>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
> 
> **Describe the solution you'd like**
> A solution for this would be enabling CORS. This should be pretty easy. You may refer [this](https://flask-cors.readthedocs.io/en/latest/)

after reading the error again i found out that cors was already enabled and thats why I'm getting the error smh. 

So the solution would be to remove Access-Control-Allow-Origin to * from server. 
cc @isabelcosta @anitab-org/coding-team  Am i correct?

**Comment by satya7289** [comment]
I want to work on this. @Techno-Disaster

**Comment by snitin315** [comment]
Go ahead.

**Comment by epicadk** [comment]
Not sure why this happens. Does flutter library you are using make some sort of pre-flight request as well?

**Comment by techno-disaster** [comment]
The flutter client is no longer in development, closing this issue now
