### ISSUE TITLE
Search users function with pagination does not work as expected

### ISSUE THREAD

**Issue by techno-disaster** [anitab-org/mentorship-backend#644]
**Describe the bug**

Currently when we try and search a user and if he/she is not on the first page, we get an empty list. A proper search function should search the whole db and give the result without being dependent on the page number

**To Reproduce**
 Search the following in the search field
```urs``` or ```tech```  (ursula and technouser exist so they should be listed) 
![image](https://user-images.githubusercontent.com/52817235/83561796-1194c180-a536-11ea-9476-62f726d418c2.png)

```isa```
![image](https://user-images.githubusercontent.com/52817235/83561926-4d2f8b80-a536-11ea-8724-8c64f7f818e0.png)

**Comment by rpattath** [comment]
For more clarity adding a few more screenshots:

technodisaster4 user exists but seeing the following
![Screenshot from 2020-06-16 14-42-11](https://user-images.githubusercontent.com/26095715/84814671-cf608b00-afdf-11ea-9867-2cddac277b2e.png)

And if we try with page number
![Screenshot from 2020-06-16 14-42-31](https://user-images.githubusercontent.com/26095715/84814785-f919b200-afdf-11ea-9b6e-a010e919d3ee.png)
![Screenshot from 2020-06-16 14-42-36](https://user-images.githubusercontent.com/26095715/84814795-fc14a280-afdf-11ea-9e8e-a55973ae3b9b.png)

@Techno-Disaster would you mind editing the title of this issue to "Search users function with pagination does not work as expected"

**Comment by adi-001** [comment]
Hey @anitab-org/coding-team , anyone up for this?

**Comment by isabelcosta** [comment]
@rpattath thank you for testing this and helping making the issue more clear

**Comment by PrashanthPuneriya** [comment]
@isabelcosta @adi-001 @Techno-Disaster I would like to work on this issue.

**Comment by PrashanthPuneriya** [comment]
@isabelcosta @Techno-Disaster @rpattath 
The search feature is working as expected. Internally, the search function queries for the **Name** but, not for the **username**. So, to find a user you must search by **Name** but not by **username**.
#### Explanation for the above given example in the [comment](https://github.com/anitab-org/mentorship-backend/issues/644#issuecomment-644947055):-
The user with username `technodisaster4` exists. But, when you searched for `techno` the user isn't showing up because, the function searches for the user with **Name** as `techno`. But, here arises the problem; the **Name** of the user with username `technodisaster4` is `Jayesh Nirve`. Hence, he would show up only if you search for `jayesh` but not for `techno`.

So, @isabelcosta we can close this issue.

**Comment by techno-disaster** [comment]
@PrashanthPuneriya @isabelcosta shouldn't the feature search depend on the username and not the name? because names can be same usernames are unique?

**Comment by PrashanthPuneriya** [comment]
@Techno-Disaster Yes! I too thought of that. Anyway if we want to search by username then we should raise a feature request.

**Comment by techno-disaster** [comment]
Anyways a PR for this is up [here](https://github.com/anitab-org/mentorship-flutter/pull/114) on the flutter repo and even if you change it from names to usernames it will still work without requiring any additional changes. cc: @isabelcosta

**Comment by vj-codes** [comment]
@PrashanthPuneriya hows the PR going?

**Comment by PrashanthPuneriya** [comment]
I think we can close this issue now @vj-codes. What do you think @Techno-Disaster? Are we on the same page or am I missing something.?

**Comment by vj-codes** [comment]
> I think we can close this issue now @vj-codes. What do you think @Techno-Disaster? Are we on the same page or am I missing something.?

@PrashanthPuneriya the search function still doesn't work on android apk, any idea why?

**Comment by PrashanthPuneriya** [comment]
I mentioned in this [comment](https://github.com/anitab-org/mentorship-backend/issues/644#issuecomment-661748664) @vj-codes that it queries by name not username :)

**Comment by vj-codes** [comment]
Tried both ways no result, if you can successfully search , could you please upload a gif then we can close this as well as the issue in android repo. @PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
@vj-codes I will upload a gif soon. Meanwhile can you please describe the issue? Even [this PR](https://github.com/anitab-org/mentorship-flutter/pull/114) was approved as working and merged right?

**Comment by vj-codes** [comment]
@PrashanthPuneriya I just downloaded the recent apk again but still no results , the issue here is you try by anyway the search simply doesnt work:(

**Comment by techno-disaster** [comment]
> I think we can close this issue now @vj-codes. What do you think @Techno-Disaster? Are we on the same page or am I missing something.?

yep I agree, I did see a issue for searching both using names and usernames #745 . So this issue is deprecated now :)

**Comment by SanketDG** [comment]
Can we close this then?

**Comment by vj-codes** [comment]
Closing as discussed in comments.
