### ISSUE TITLE
Update TravisCI badge and Development server link on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#652]
## Description
As a contributor,
I need README updated with the project deployment status,
so that I can be up to date.

Some links are not up to date, which can lead to confusion, like the Travis CI badge for develop branch, and the Development server link.

### Update [Required]
- [ ] Change Travis CI develop badge link to https://travis-ci.org/anitab-org/mentorship-backend.svg?branch=develop
- [ ] Change development server link to https://mentorship-backend-temp.herokuapp.com/ 

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by Neilblaze** [comment]
@isabelcosta Can you assign me this?
