### ISSUE TITLE
Bug: HTTPStatus CONFLICT is returned instead of BAD_REQUEST for invalid input POST /register

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#653]
**Describe the bug**

HTTPStatus.CONFLICT is returned for invalid input instead of HTTPStatus.BAD_REQUEST

**To Reproduce**

1. Run `python run.py` command
2. Go to Swagger UI and try to register new user with invalid input
3. You will see error message with 409 CONFLICT instead of BAD_REQUEST 400 being returned.
You can also see the expected response on Swagger UI that have invalid input returned as HTTPStatus.CONFLICT (409)

**Expected behavior**
The error return on invalid inputs need to be HTTPStatus.BAD_REQUEST (400) instead of CONFLICT  (409)

**Screenshots**
<img width="970" alt="Screen Shot 2020-06-28 at 2 03 47 pm" src="https://user-images.githubusercontent.com/29667122/85937643-e771cc00-b948-11ea-9c6c-8f6ac7a2f8e5.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version ??

**Additional context**
This is caused by the recent [PR#650](https://github.com/anitab-org/mentorship-backend/pull/650) that got merged to develop.

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers and @anitab-org/coding-team . Just want to report a bug that is raised by the recent merged PR #650 . The PR was supposed to refactor 400 response to 409 on the events where user inserted existing username or email only.
Despite the code being refactored correctly on the app/api/dao/user.py,

<img width="1448" alt="Screen Shot 2020-06-28 at 2 17 14 pm" src="https://user-images.githubusercontent.com/29667122/85937806-46841080-b94a-11ea-8dce-20b2aa995086.png">

The responses shown on the Swagger UI got some unwanted changes. The invalid token or invalid input should be kept as HTTPStatus.BAD_REQUEST (2 bottom red boxes)

<img width="1680" alt="Screen Shot 2020-06-28 at 2 17 18 pm" src="https://user-images.githubusercontent.com/29667122/85937858-c9a56680-b94a-11ea-96ec-5ed4f2652f1b.png">

HTTPStatus.CONFLICT is supposed to be used only for the event when username or email already exist as clearly explained in issue #619. So, line 261-268 on original code need to be separated into 2 responses, HTTPStatus.BAD_REQUEST for line 267-268 (on original) and HTTPStatus.CONFLICT for line 265-266 (on original).

<img width="608" alt="Screen Shot 2020-06-28 at 2 24 33 pm" src="https://user-images.githubusercontent.com/29667122/85937917-7aac0100-b94b-11ea-8812-38847386c521.png">

**Comment by nandini45** [comment]
@mtreacy002  testcases have to be added can i do the work?

**Comment by mtreacy002** [comment]
Sure, @nandini45 . You can add the test cases in this same issue instead of having them separately. Let me know if you are unclear of the task required here. 😉

**Comment by mtreacy002** [comment]
Before working on the test cases. Make sure you make the relevant changes mentioned in the issue description and my comment above.

**Comment by nandini45** [comment]
@mtreacy002  i will update my work asap.. sorry for the delay..i am working on it

**Comment by mtreacy002** [comment]
No worries, @nandini45 , take your time. Let me know if there's anything you're not sure of.

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/87246910-05255200-c46e-11ea-8469-7e0a32a0369c.png)

  i was trying to test the code after making the changes but an error raised. what am i doing wrong? 
@satya7289

**Comment by NenadPantelic** [comment]
@mtreacy002  Is this still active? I could work on this :smile:

**Comment by mtreacy002** [comment]
@nandini45, can you let us know if you're still working on this issue or is it ok if @NenadPantelic pick it up now?

**Comment by nandini45** [comment]
I am not working.
Sorry for the inconvenience
U can assign it to nenand

**Comment by vj-codes** [comment]
Assigning you @NenadPantelic 
Happy coding!

**Comment by NenadPantelic** [comment]
@mtreacy002 @vjcodes Hi, I made a PR regarding this issue. Can you please review it? Thanks :slightly_smiling_face:
