### ISSUE TITLE
Add a missing environment config value to .env.template

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#663]
[environment-variables.md](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md) doc specifies that the run configuration has 4 options: `dev`, `local`, `test` and `prod` values to be loaded. But, **FLASK_ENVIRONMENT_CONFIG** variable under [.env.template](https://github.com/anitab-org/mentorship-backend/blob/develop/.env.template) file doesn't include `local` value as an option.

**Comment by PrashanthPuneriya** [comment]
I would like to fix this issue if this is approved by mentors.

**Comment by vj-codes** [comment]
Assigning you @PrashanthPuneriya 
Happy coding!

**Comment by isabelcosta** [comment]
@PrashanthPuneriya this is a great issue 🎉 Next time could you please follow one of the templates suggested? You can use perhaps "User Story" :)
