### ISSUE TITLE
Bug: Fix inconsistent format of comments present in task_comment.py file

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#669]
**Describe the bug**

The comments of TaskCommentModel present in [task_comment.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/task_comment.py#L8) file are not formatted correctly.

**To Reproduce**

1. Go to [task_comment.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/task_comment.py) file
2. Scroll down to line no. 8
3. See the inconsistent format present from line no. 8 to line no. 17

**Expected behavior**

Line no. 10 to 17 should not have those extra 4 spaces as indentation.

**Comment by vj-codes** [comment]
@PrashanthPuneriya the issue should be first approved , then assigned and then the PR is sent.Please don't send PRs unless a specific issue is assigned to you.Will be closing that PR for now, if this issue is approved you may reopen it:)

**Comment by vj-codes** [comment]
@PrashanthPuneriya follow the issue template please and add some solution , alternative and resources for the right format.

**Comment by PrashanthPuneriya** [comment]
@vj-codes Sorry! Won't happen again. I thought that the formatting won't require alternatives, resources and other things so I removed them. Can you please tell me what kind of templates and what should I fill in that template in cases similar to this?

**Comment by vj-codes** [comment]
No problem! @PrashanthPuneriya 
I would suggest following the feature template,adding solutions/advantages in such cases and providing resources like the correct format to follow in this case and if applicable attaching a screenshot.
It's easy for others to understand and review then as compared to just mentioning the problem in short.

**Comment by PrashanthPuneriya** [comment]
@vj-codes As you have guided me I have edited this issue to follow the issue template. I have used the bug template as it made sense to me. Please review it. 
If it is good then assign me this issue so I could reopen the PR.

**Comment by vj-codes** [comment]
Thanks for changing, its so good now @PrashanthPuneriya .
I see that you are assigned another issue currently and this seems good for  a first timers issue.
I'll ask other managers and if no one responds in 2 days ,it'll be assigned to you.

**Comment by vj-codes** [comment]
@anitab-org/mentorship-managers Is this a good first timer's issue?Please confirm.Thanks!

**Comment by PrashanthPuneriya** [comment]
@vj-codes Okay! No problem

**Comment by PrashanthPuneriya** [comment]
@vj-codes Can I reopen the PR now?

**Comment by vj-codes** [comment]
yeah sure , I'll assign you too. @PrashanthPuneriya
