### ISSUE TITLE
Stop exposing expiry timestamp

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#679]
## Description
As a developer,
I need to deprecate `expiry` timestamp,
so that I can remove misleading information fro API definition.

I confirmed that the `expiry` field is not being used

## Mocks

![image](https://user-images.githubusercontent.com/11148726/87850999-7d679980-c8ec-11ea-9c91-50201ebd85a0.png)

### Update [Required]
- [ ] Remoove references to `expiry` timestamp field from POST /login

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by isabelcosta** [comment]
@divyanshugit want to try this one? It's about deprecating a field being returned on Login API

**Comment by divyanshugit** [comment]
Okay I will try to solve this issue ! Thanks for suggesting @isabelcosta

**Comment by isabelcosta** [comment]
@divyanshugit are you working on this issue? Do you need any help?

**Comment by divyanshugit** [comment]
@isabelcosta  Do I need to remove the expiry field or modify the expiry field from mentorship-backend/app/messages.py / ?

**Comment by isabelcosta** [comment]
Remove it @divyanshugit , so it does not get returned anymore :)

**Comment by divyanshugit** [comment]
@isabelcosta  I have removed the expiry field from message.py .But the run failed. Do I need to remove all the lines related to expiry field from every file available on the repo ?

**Comment by isabelcosta** [comment]
> @isabelcosta I have removed the expiry field from message.py .But the run failed. Do I need to remove all the lines related to expiry field from every file available on the repo ?

@divyanshugit yes :)
