### ISSUE TITLE
Create a user journey test from sending a mentorship request until the mentee completes a task

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#680]
## Description

As a developer,
I need to test a specific user path,
so that I can make sure a specific path can be executed usefully in a deterministic way.

This test should be located in a specific folder for separation concerns, it could be called `tests/user_journey`.
Next, I'll define a very broad scenario, but simple enough for you to start.

**Scenario:** User A (mentor) and User B (mentee)
1. User B (mentee) sends a request to User A (mentor)
2. User A (mentor) accepts request
3. User A (mentor) or User B (mentee) creates a task
4. User B (mentee) completes the task

### Update [Required]
- [ ] Create 1 user journey test that follows the scenario described above
- [ ] Document the test result on Test Quality (@anitab-org/qa-team can help)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by isabelcosta** [comment]
@rpattath first steps into more automated tests 😄

**Comment by PrashanthPuneriya** [comment]
@isabelcosta I have no experience in testing. So, I would like to learn about them by taking up this issue if that's okay with you.

**Comment by rpattath** [comment]
Sure @PrashanthPuneriya I will closely assist you with this. Also there are a few other QA practices that you need to get familiar with before starting test automation. I will give more information on Zulip. Thank you !

**Comment by PrashanthPuneriya** [comment]
@rpattath Thanks a lot :)

**Comment by PrashanthPuneriya** [comment]
@rpattath I am unassigning myself from this issue. I would like to work on other issue. Sorry, for that. Please, feel free to assign others to this issue.

**Comment by isabelcosta** [comment]
No inconvenience was caused @PrashanthPuneriya :) we can reassign this to someone else, meanwhile, there are plenty other issues you can request to work on.

**Comment by GobindB** [comment]
@isabelcosta I'm familiar with writing tests but new to automated testing. If nobody has taken this on I'd love to tackle it!

**Comment by isabelcosta** [comment]
@GobindB this is just a longer test. If you know how to write tests then you are good with this :)
Although I was thinking of trying this one in hopes to make an example to then share with the community next week. 
If you wish to give it a try I am ok with it. If you wish to do other tests I can also recommend some. What do you prefer :)

**Comment by GobindB** [comment]
@isabelcosta I'm hoping to get familiar with the codebase so I can get more involved with contributions. If you were to recommend me issues I would be happy to work on those :)
