### ISSUE TITLE
Fix wrong usage of f-strings in a test

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#681]
## Description
As a developer,
I need to have code consistent with standards,
so that I can have better readability.

Some parts of the code are not using f-strings in a consistent way to the standard.

Example:
```
        actual_response = self.client.post(
            f"mentorship_relation/{self.relation_id}/task/{self.task_id}" f"/comment",
            follow_redirects=True,
```

There should be 1 f-string instead of 2, so instead of `f"mentorship_relation/{self.relation_id}/task/{self.task_id}" f"/comment"` it should be `f"mentorship_relation/{self.relation_id}/task/{self.task_id}/comment"`

Example of file which contains this: https://github.com/anitab-org/mentorship-backend/blob/develop/tests/task_comments/test_api_create_task_comment.py

### Update [Required]
- [ ] Fix f-strings usage on `tests/task_comments/test_api_create_task_comment.py` file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by divyanshugit** [comment]
I would like to work on this issue. Can you suggest me ways to get started on this issue  ?

**Comment by isabelcosta** [comment]
@divyanshugit can you please choose another :) I just recently merged a PR of yours, and this is for first timers only contributors. I can forward you other issues while we leave this one for new contributors to this project

**Comment by isabelcosta** [comment]
@divyanshugit https://github.com/anitab-org/mentorship-backend/issues/679#issuecomment-660660621

**Comment by divyanshugit** [comment]
No problem, @isabelcosta I will choose another issue :)

**Comment by GobindB** [comment]
Hey, @isabelcosta I am a first-time contributor and would love to solve this if possible!

**Comment by isabelcosta** [comment]
@GobindB before sending a PR you have to wait until you are assigned to the issue. Please read our [Contribution Guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md) and let me know if you understand this.

**Comment by GobindB** [comment]
@isabelcosta sorry I hadn't taken a look at the contribution guidelines. I've gone through them now and am clear on the contents. Should I look for another open issue?

**Comment by isabelcosta** [comment]
No problem, I'll assign this to you and review your PR @GobindB :)
