### ISSUE TITLE
Integrate black and black's github action

### ISSUE THREAD

**Issue by SanketDG** [anitab-org/mentorship-backend#701]
## Description
As a developer, I need to have good, structured, readable code to be able to read through it painlessly and efforlessly.

Previously #465 used black to re-format the code, but because there is no way to check whether our code is according to Black's standards or not, there has been a lot of code that is not formatted.

The idea is to run Black through a single pass, and then integrate the [official github action](https://github.com/psf/black#github-actions) so that we make it a habit for every developer to run black before committing their code.

**Comment by isabelcosta** [comment]
@SanketDG sounds good! Can't wait to get the coding lint improved 🤗 🤗 🤗 🤗

**Comment by isabelcosta** [comment]
@SanketDG are you working on this still? Do you need any help from admins?
