### ISSUE TITLE
BUG: GET/users/{user_id} returns list of null users for id that doesn't exist

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#702]
**Describe the bug**
When a user trying to view other user's details by sending GET /users/{user_id} with user_id that does not exist, the system returns a list of null users instead of HTTP error 404 (Not Found)

**To Reproduce**

1. Login as a user
2. Go to GET users/{user_id} and enter a random id that does not exist in the Users table (check the database to do this)
3. See the response with list of empty users with null ids

**Expected behavior**
Must return http eerror 404 Not Found and message that user does not exist

**Screenshots**
<img width="1458" alt="Screen Shot 2020-07-29 at 5 10 27 pm" src="https://user-images.githubusercontent.com/29667122/88768436-711def00-d1be-11ea-84bc-fd6cb2c6792a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version ?

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers . I come across this bug when I was working on the GET /users/{useer_id} api endpoint on BIT [PR#99](https://github.com/anitab-org/bridge-in-tech-backend/pull/99). This is a cross-project issue as BIT response will also affected on this issue.

**Comment by mtreacy002** [comment]
PS to @anitab-org/coding-team. This issue is open to anyone. I personally don't have the bandwith to work on this issue atm. Just want to raise the issue. 😉

**Comment by isabelcosta** [comment]
@mtreacy002 this is an amazing catch 👏  I just tried it and it really happens 🤦‍♀️  And the fix should come with a test to cover this bug

![image](https://user-images.githubusercontent.com/11148726/89325910-631a1380-d681-11ea-82d8-cc3ffd456d01.png)

**Comment by saikirankv** [comment]
@isabelcosta  can you assign this to me?

**Comment by AprameyaGupta** [comment]
@isabelcosta  I would like to contribute in this as a part of OSH. Can you assign this issue to me?

**Comment by pallavisavant** [comment]
If available i would like to take this up...Thanks.

**Comment by isabelcosta** [comment]
@saikirankv would you still like to contribute to this? Let me know and I can assign to you.

@AprameyaGupta @pallavisavant I am going off "first come first served", if I get no response I'll assign to one of you. 

Be mindful that this issue is not labeled with OSH, so it's not part of it as of now.

**Comment by saikirankv** [comment]
Yes, I'm interested in this.

**Comment by pallavisavant** [comment]
Yes I want to take this up... thanks

**Comment by vj-codes** [comment]
Assigning you @saikirankv 
Happy coding!

**Comment by vj-codes** [comment]
@saikirankv how's the PR going?

**Comment by saikirankv** [comment]
Worked on it, some setup issue will raise PR today.

**Comment by saikirankv** [comment]
@vj-codes I have made the necessary changes, but the coverage report is failing.

The decorator email_verification_required is causing the issue, do we need that email_verification decorator for get_user, can we keep it a login.
Please review my PR, if that decorator is necessary I'll do another commit.

**Comment by saikirankv** [comment]
@vj-codes  I have raised PR, please review.

**Comment by NenadPantelic** [comment]
@mtreacy002  @vj-codes  What's going on with this?
