### ISSUE TITLE
Tests are failing in the "Run Tests" check

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#705]
**Describe the bug**

The tests are failing 😱 
This is the first time it failed: https://github.com/anitab-org/mentorship-backend/runs/935862710

**To Reproduce**

1. Go to https://github.com/anitab-org/mentorship-backend/runs/935862710
2. Click on 'Run Tests' build
3. Scroll down to tests failing
4. See errors

Run tests locally, and see if they work.

**Expected behavior**

Tests should not be failing.

**Comment by nickinack** [comment]
I would like to work on this issue. Can someone suggest ways to do so?

**Comment by SanketDG** [comment]
Oh there was a new test file that did not have the changes, I overlooked this!

@nickinack Let me assign you, you do not have to add back as we moved from `restplus` #579 to `flask-restx`, you just need to update the import in `https://github.com/anitab-org/mentorship-backend/blob/develop/tests/users/test_api_get_other_user.py`

**Comment by nickinack** [comment]
Please CR the PR

**Comment by isabelcosta** [comment]
@nickinack thank you for taking this issue. I will look at the PR as soon as I can :)

**Comment by isabelcosta** [comment]
@SanketDG @nickinack the problem was fixed! thank you so much for your help 🤗
