### ISSUE TITLE
Add badge with Python 3.6 version on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#714]
## Description

Add badge with Python 3.6 version in the README

### Update [Required]
- [ ] Add badge with Python 3.6 version in the README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by dwvicy** [comment]
@isabelcosta can I work on this?

**Comment by vj-codes** [comment]
Assigning you @dwvicy 
Happy coding!
