### ISSUE TITLE
Create the config.yml file for the Welcome Bot.

### ISSUE THREAD

**Issue by mayburgos** [anitab-org/mentorship-backend#717]
## Description
As a first time contributor,
I need a bot to help guide my first contribution, 
so that I can follow this org's contribution guidelines.

## Mocks
![Screen Shot 2020-08-06 at 10 26 14 AM](https://user-images.githubusercontent.com/2440938/89543720-44299780-d7cf-11ea-82a0-bd81664f0d8e.png)

### Update [Required]
- [ ] newIssueWelcomeComment is complete with the correct links to this repo.
- [ ] newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
- [ ] firstPRMergeComment is complete.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Aaishpra** [comment]
@isabelcosta @mayburgos  can i take this up if no one is currently working on it?

**Comment by isabelcosta** [comment]
@Aaishpra this issue is being worked on by @mayburgos for now.
Can you please look up other issues? We'll make sure to have more issues available

**Comment by Aayush-hub** [comment]
@isabelcosta @epicadk Can I work on this issue, if still not solved?

**Comment by Aayush-hub** [comment]
@isabelcosta @epicadk @vj-codes Can I work on this issue, if still not solved?
