### ISSUE TITLE
Error message for entering Email id  which was not registered a user under "Sends the user a new verification email"

### ISSUE THREAD

**Issue by faznan3nazer** [anitab-org/mentorship-backend#721]
**Describe the bug**

When we enter mail id which is not registered any user, an appropriate error message should be shown and listed under the Responses.

**To Reproduce**

1. Go to 'user-Sends the user a new verification email'
2. Provide the email id
3. {
    "email": "soyiv65617@corsj.net"
    }
4. Click on 'Execute'.
5. Scroll down to 'Responses'.
6.  
![Screenshot (280)](https://user-images.githubusercontent.com/50888936/89920504-18b50b80-dc1a-11ea-93d0-a43be7c8c965.png)

**Expected behavior**
That error message should be listed in the responses.

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome

**Comment by ashwinijha6** [comment]
@faznan3nazer I would like to work on this issue

**Comment by ashwinijha6** [comment]
@faznan3nazer  I would like to work on this issue as an OSH participant

**Comment by ashwinijha6** [comment]
@anna4j  & @isabelcosta  could u pls assign me this issue

**Comment by anna4j** [comment]
Sure assigning you! @ashwinijha6

**Comment by faznan3nazer** [comment]
I would like to work on this issue.. Can you please assign this to me for Open-Source Hack?

**Comment by anna4j** [comment]
Aren't you assigned to an issue on Android repo already @faznan3nazer

**Comment by eternal-dreamer** [comment]
I would like to work on this issue .

**Comment by faznan3nazer** [comment]
> Aren't you assigned to an issue on Android repo already @faznan3nazer

Yes... After completing that I would like to work on this issue...!

**Comment by vj-codes** [comment]
@ashwinijha6 how's the PR going?

**Comment by ashwinijha6** [comment]
@anna4j I'm getting the error
![mentorship](https://user-images.githubusercontent.com/45794450/92399616-348fcc80-f148-11ea-984d-15eed60313b7.JPG)

**Comment by ashwinijha6** [comment]
An appropriate error message should be shown under the responses so what should be I message like do u mean to say 
HTTPStatus.OK.description gives the message **Request fulfilled, document follows**
So this should be the case with each of the Http status or I'm getting it wrong?

**Comment by ashwinijha6** [comment]
Does it refer the ERROR:NOT FOUND?

**Comment by pallavisavant** [comment]
If this is available i would like to work on this..Thanks.

**Comment by vj-codes** [comment]
@ashwinijha6 how about `404 : ' Please register as a user first to get a verification email '`

**Comment by vj-codes** [comment]
> @ashwinijha6 how about `404 : ' Please register as a user first to get a verification email '`

@ashwinijha6 @faznan3nazer what do you say

**Comment by ashwinijha6** [comment]
> @ashwinijha6 how about `404 : ' Please register as a user first to get a verification email '`

ok ya I got it so that must be added to the responses section that is along with HttpStatus Not found or in place of that?

**Comment by ashwinijha6** [comment]
@vj-codes I have made the changes in #851
Should this message **USER_IS_NOT_REGISTERED_IN_THE_SYSTEM** be used as it is also used in the later part of the code ?
![use](https://user-images.githubusercontent.com/45794450/92528505-81f26380-f246-11ea-9d10-14a6bafc1231.JPG)

**Comment by ashwinijha6** [comment]
> @vj-codes I have made the changes in #851
> Should this message **USER_IS_NOT_REGISTERED_IN_THE_SYSTEM** be used as it is also used in the later part of the code ?
> ![use](https://user-images.githubusercontent.com/45794450/92528505-81f26380-f246-11ea-9d10-14a6bafc1231.JPG)

**USER_IS_NOT_REGISTERED_IN_THE_SYSTEM** as in messages.py is **You are not registered in the system**

**Comment by vj-codes** [comment]
@ashwinijha6 honestly I have no idea, this issue still doesn't make much sense to me unlike all other issues where I was sure what was to be done 
Maybe @PrashanthPuneriya @SanketDG could help

**Comment by ashwinijha6** [comment]
> @ashwinijha6 honestly I have no idea, this issue still doesn't make much sense to me unlike all other issues where I was sure what was to be done
> Maybe @PrashanthPuneriya @SanketDG could help

ok no issues @vj-codes thanx for the help I will ask @PrashanthPuneriya or @SanketDG

**Comment by ashwinijha6** [comment]
@SanketDG & @PrashanthPuneriya I had certain queries related to this issue as stated above & I have also sent a pull request #851 regarding this could u'll please review it & tell me the necessary changes to be made.

**Comment by vj-codes** [comment]
@ashwinijha6 I'm not a OSH mentor, but backend and android repo project manager best is to ask from mentors:) 
If I know what is to be done when you'll be working on next issues, I will definitely help

**Comment by ashwinijha6** [comment]
> @ashwinijha6 I'm not a OSH mentor, but backend and android repo project manager best is to ask from mentors:)
> If I know what is to be done when you'll be working on next issues, I will definitely help

No problem @vj-codes u helped me a lot I have written to @SanketDG & @PrashanthPuneriya I'm sure I will get answers to my query
Looking forward to solving new issues & ur guidance.

**Comment by faznan3nazer** [comment]
Is this issue still available? can I claim this issue?
