### ISSUE TITLE
Create a code_of_conduct.md file

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#722]
**Is your feature request related to a problem? Please describe.**
As a developer ,
I need to update the repository with all proper links and documents.
1)Create a  new code_of_conduct.md file that has the same content as http://systers.io/code-of-conduct
2) And then update the code of conduct link in **Readme.md**>>Contributing section as well as in **Contributing.md**  .

### Acceptance Criteria

- [ ]  Update [Required]

### Definition of Done

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

### Estimation
30 min

**Comment by 19-pragya** [comment]
Can i work on this

**Comment by vj-codes** [comment]
@19-pragya sorry this is a 'first timers only' issue and I see that you're assigned for #724. Do checkout other available issues and claim any one of them!

**Comment by 19-pragya** [comment]
I have actually completed i guess u have approved.

**Comment by vj-codes** [comment]
@19-pragya  First timers only means that users who have never contributed to backend repo can only work on this.

**Comment by 19-pragya** [comment]
Okay😅

**Comment by sanchibansal340** [comment]
Can I work on this?

**Comment by vj-codes** [comment]
Sure assigning you @sanchibansal340 
Happy coding!

**Comment by sanchibansal340** [comment]
@vj-codes The code_of_conduct.md needs to be created in the .github like the previous one was, right?

**Comment by sanchibansal340** [comment]
Hey I am done. I just have confusion about the folder it needs to go in and if previous code_of_conduct has to be deleted.

**Comment by PrashanthPuneriya** [comment]
@vj-codes What's the difference between [Systers code-of-conduct](http://systers.io/code-of-conduct) and [code_of_conduct.md](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/code_of_conduct.md) content? I don't see any major difference. Am I missing out something?
Task-2 seems valid to me.

**Comment by sanchibansal340** [comment]
I modified a link and deleted 4-5 lines.

**Comment by vj-codes** [comment]
@sanchibansal340 keep the file in docs folder by the name as code_of_conduct.md and delete the previous one

**Comment by vj-codes** [comment]
> @vj-codes What's the difference between [Systers code-of-conduct](http://systers.io/code-of-conduct) and [code_of_conduct.md](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/code_of_conduct.md) content? I don't see any major difference. Am I missing out something?
> Task-2 seems valid to me.

Earlier everything here was under Systers and now its under/changed to AnitaB Open Source . So everything that says Systers has to be changed to AnitaB , if you find anything related with this please feel free to create issues!

**Comment by sanchibansal340** [comment]
@vj-codes In the Code of Conduct Systers needs to be replaced to AnitaB?

**Comment by vj-codes** [comment]
yes and contact info too [here's](https://github.com/anitab-org/stem-diverse-tv/blob/master/docs/code_of_conduct.md) an example of updated one

**Comment by sanchibansal340** [comment]
Okay thanks. Can you please tell me about the folder it needs to go in as well?

**Comment by vj-codes** [comment]
docs folder @sanchibansal340

**Comment by sanchibansal340** [comment]
Okay thanks. I will make a pull request in 5-7 minutes.
