### ISSUE TITLE
Add mentorship: flutter and ios client to API Swagger description

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#724]
### Description
As a contributor,
I need information accessible in the Swagger UI,
so that I can get to know more about mentorship system projects.

The idea is to add an extra line mentioning the mentorship : flutter client and ios-client and its URL for both

### Mocks
This is how the description looks like at the moment:

![image](https://user-images.githubusercontent.com/60894542/90111917-f089f180-dd6c-11ea-83bf-d286b712f7f0.png)

### Acceptance Criteria

- [ ] Update [Required]
- [ ]  Add ios client text on Swagger UI description
- [ ] Add flutter client text on Swagger UI description

### Definition of Done

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

### Estimation
30 min

**Comment by 19-pragya** [comment]
can i get assigned in this if this is still available

**Comment by vj-codes** [comment]
Sure assigning you @19-pragya 
Happy coding!

**Comment by 19-pragya** [comment]
hey... @vj-codes  
actually, i am unable to find the page for editing this..and as i am doing it for the very first time to can u explain what exactly i have to do.. i will be very thankful to you

**Comment by vj-codes** [comment]
@19-pragya Sure and welcome to the community!
Here's the file page that needs changes https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/api_extension.py 
You have to add one line for Flutter client and one line for ios client in the same format in line 10 of the link mentioned.
Hope this helps:)

**Comment by 19-pragya** [comment]
Thankyou so much @vj-codes please check i have sent a request. and please tell me if it is appropriate.

**Comment by vj-codes** [comment]
@19-pragya I don't get you, do you mean a pull request coz I don't see any? And if yes sending a PR while you are assigned is 100% appropriate:)

**Comment by 19-pragya** [comment]
Thankyou so much mam😊

**Comment by 19-pragya** [comment]
Please let me know about the other projects i can work on..

**Comment by vj-codes** [comment]
@19-pragya checkout other repositories, all are interesting and first timer issues are a great start! 
Don't call be ma'am, just another open source enthusiast like you!

**Comment by 19-pragya** [comment]
Okay thanks

**Comment by vj-codes** [comment]
@19-pragya  did you commit your changes and then create a pull request? Lemme know if there's any problem in setting up project locally or making changes for this PR:)

**Comment by 19-pragya** [comment]
please check... i have commit my changes and created pull request. is it visible

**Comment by 19-pragya** [comment]
https://github.com/19-pragya/mentorship-backend/pull/1/commits
please tell if anything went wrong

**Comment by vj-codes** [comment]
@19-pragya Do you want to still work on this?I see you've removed your assignment?
The pull request should be added to the main repo here and not your fork, just do the same process here again then I can review:)

**Comment by 19-pragya** [comment]
https://github.com/anitab-org/mentorship-backend/pull/725
is this ok??

**Comment by 19-pragya** [comment]
@vj-codes  can you please check the file i committed. please tell me if further changes required

**Comment by vj-codes** [comment]
Closing as flutter and ios have been added currently
