### ISSUE TITLE
Replace {request_id} with {relation_id} in the Swagger UI and its related parameters

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#726]
**Describe the bug**
After a relationship has been formed between mentor and mentee, whenever a task is either created, edited, deleted or listed the Swagger UI should display the relationship between them as `{relation_id}` instead of `{request_id}`.

**Expected behavior**
`{relation_id}` should be displayed instead of `{request_id}`

**Screenshots**
![image](https://user-images.githubusercontent.com/42068010/90337622-4b3b7b80-e001-11ea-807c-c520b3b59174.png)

**Additional context**
In addition to the Swagger UI the function parameters and its corresponding variable names needs to be modified.

**Comment by vj-codes** [comment]
@isabelcosta Can you have a look at this?
I believe that it'll require a huge change in files of resources, dao, and tests
cc: @PrashanthPuneriya

**Comment by isabelcosta** [comment]
@vj-codes @PrashanthPuneriya I think its a valid change :) Yes, it will require some big changes, but not complex ones :) Whoever takes this, can ask for help, this does not seem to change logic, just naming variables. Makes sense?

**Comment by gitpurva** [comment]
I would like to work on this . Can you assign me this issue?

**Comment by vj-codes** [comment]
Assigning you @gitpurva 
Happy coding!

**Comment by vaibhavarora102** [comment]
hi i would like to work on this can i

**Comment by vj-codes** [comment]
@gitpurva it's been 5 days and no update from your side , thus unassigning you from this issue.

**Comment by vj-codes** [comment]
Assigning you @vaibhavarora102 
Happy coding!

**Comment by gitpurva** [comment]
@vj-codes I have already sent a PR solving the issue and it has passed all the unit test cases also. The PR is under review.

**Comment by vj-codes** [comment]
@gitpurva sorry my bad , you haven't linked this issue in `fixes` part of your PR , show it didn't show up here .
Assigning you back 🎉

**Comment by gitpurva** [comment]
@vj-codes Sorry about that. I did not know about the fixing part:(

**Comment by codesankalp** [comment]
@gitpurva 
If you are not able to link then you can unassign you from this issue.
and i will make a linked pull request.
@PrashanthPuneriya you can assign me this issue.

**Comment by codesankalp** [comment]
It's been a long i.e. 18days and the pull request is not linked. 
That's why i want to work on this issue.

**Comment by PrashanthPuneriya** [comment]
Not linking the PR doesn't mean that the work hasn't been done. @gitpurva has almost completed the work. I was busy with my exams so I had forgotten this issue and I apologize for that @codesankalp :)

**Comment by codesankalp** [comment]
No problem @PrashanthPuneriya . I commented because the assignee didn't respond since 18 days. :smile:

**Comment by vj-codes** [comment]
I would like to work on this @devkapilbansal  :)

**Comment by isabelcosta** [comment]
yours @vj-codes 🤗

**Comment by devkapilbansal** [comment]
Didn't see that issue is already assigned :grimacing:
