### ISSUE TITLE
Change email confirmation signature to AnitaB.org Open Source

### ISSUE THREAD

**Issue by anna4j** [anitab-org/mentorship-backend#728]
**Describe the bug**

Since we have migrated our apps from Systers account to AnitaB.org when a new user creates an account for the Mentorship System the email confirmation signature should show **AnitaB.org Open Source** instead of Systers Open Source.

**To Reproduce**

1. Go to '/templates/email_confirmation.html'
2. Scroll down to line 11 or the email signature
3. See error
[Edit this file](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_confirmation.html)

**Expected behavior**

1. Change 'Systers Open Source' to 'AnitaB.org Open Source'
2. Change link in anchor tag to "https://anitab-org.github.io/"

**Screenshots**

![image](https://user-images.githubusercontent.com/43845261/90343316-f31a6e80-e02c-11ea-9920-03f9042cf2bb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anna4j** [comment]
@isabelcosta Do we need to replace "In Systerhood" by something else too?

**Comment by vj-codes** [comment]
@himanshuraj18 you can first comment on an issue you would like to work on, then it'll be assigned to you and then send a PR.
This issue is on hold and when it'll be available , if you wish to be assigned, your PR will be reopened again:)

**Comment by himanshuraj18** [comment]
@vj-codes I would like to work on this. Kindly reopen the PR and assign it to me.

**Comment by anna4j** [comment]
@vj-codes hey! I know this is a really small issue but I was hoping that we could save it for "Open Source Hack" that starts on September 1st, for newcomers participating in it. Please let me know what you think

**Comment by vj-codes** [comment]
@anna4j hey ,I agree its a good idea!

**Comment by vj-codes** [comment]
@himanshuraj18 sorry this is on hold. [Here's](https://github.com/anitab-org/mentorship-backend/issues?q=is%3Aopen+is%3Aissue+label%3A%22First+Timers+Only%22+label%3A%22Status%3A+Available%22) a list of 'first timers only 'available issues. Just comment on any one you wish to work on .Good luck:)

**Comment by yogeshr59** [comment]
@anna4j @vj-codes I would like to work on this as I am a beginner and want to learn open source contributing. If this issue is going to be available in open source hack, can you please guide me what it is and how do I participate?

**Comment by anna4j** [comment]
Open Source Hack starts on 1st September and ends on 31st September. It's an event for encouraging everyone who's new to Open Source and wants to contribute to some of our projects. Here's the website for reference:

Open Source Hack Website: https://anitab-org.github.io/events/open-source-hack/

Please make sure you send in your Pull Requests after September 1st or they won't be counted.
@raisinghanii

**Comment by isabelcosta** [comment]
@anna4j as per the program, can we put the label now? Do you have any trouble with it? I can create it for you. If you could let me know about the color of it, that would be great :)

**Comment by anna4j** [comment]
> @anna4j as per the program, can we put the label now? Do you have any trouble with it? I can create it for you. If you could let me know about the color of it, that would be great :)

Yes, I think it would be great if you could just create it for us now! It'll be very easy to differentiate between issues then. We haven't decided on a color though. I think something that really catches one's eye (like red?) would do since we're targeting new members!

**Comment by vj-codes** [comment]
@isabelcosta if the label is created then will the issues with label be available or all of them for open source hack?If only ones with label are there then we need to prioritize imp ones coz there are huge number of issues on backend.

**Comment by isabelcosta** [comment]
@vj-codes @anna4j I will create the label and let you know.
I didn't quite understand what you meant @vj-codes .
The idea here is to give you the ability to start marking issues such as this one for OSH :)

**Comment by vj-codes** [comment]
@isabelcosta What I meant was currently there are 172 issues open , so will the label be applicable to all of them or just specific ones?

**Comment by anna4j** [comment]
@vj-codes The label will be applied to specific issues that the OSH team is currently working on. Some of these issues could also overlap with the 172 issues you mentioned. You're right the huge number of issues will hopefully be lesser after OSH. We'll also have to keep in mind the fact, that the OSH participants might be new to Open Source. So at first "OSH Label" will be applied to issues such as this one, and if we see experienced Open Source contributors we'll apply OSH Label to complex issues too. I hope that answers your question!

**Comment by yogeshr59** [comment]
Hey @anna4j I would like to work on this under OSH if it has not been claimed yet. Thanks.

**Comment by anna4j** [comment]
@raisinghanii Ya sure we'll assign you on 1st. Please set up the project till then :)

**Comment by utkzas** [comment]
I am new to open source and can't understand one thing,

what happens if we make a PR merge request if there is no issue created first?
can non maintainers create issues on repo?

please help

**Comment by anna4j** [comment]
@utkzas Yes, if you find an issue that isn't already mentioned, you can create one! Once, the mentors review and approve it, you can be assigned to it and you can then open a PR fixing that issue.

**Comment by vanditkhurana** [comment]
I would like to work on this. Please assign me this issue.

**Comment by anna4j** [comment]
Done @vanditkhurana go ahead :)

**Comment by yogeshr59** [comment]
@anna4j I have created a PR. Please Review.

**Comment by yogeshr59** [comment]
Hey @anna4j @vj-codes @isabelcosta Shouldn't we change the signature of Systers Open Source to AnitaB Open Source in all 3 files of templates. If it is required please assign me and I'll create a PR.

**Comment by vj-codes** [comment]
@raisinghanii yes but there are issues of redesigning the email templates for OSH

**Comment by PriyanshuAgarwal27** [comment]
I wish to work on this issue. Please assign it to me.
