### ISSUE TITLE
Update swagger.json doc file status codes

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#732]
## Description
As a contributor,
I need an up-to-date status codes in swagger.json docs,
so that I can keep track of the URLs, responses and status codes.

## Mocks
Current [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file:-
![image](https://user-images.githubusercontent.com/42068010/90504151-43e5b080-e16e-11ea-954b-5d9c16b0e952.png)
The corresponding responses we receive in the deployed site:-
![image](https://user-images.githubusercontent.com/42068010/90504289-7e4f4d80-e16e-11ea-9e85-e9429a58b0a2.png)

### Update [Required]
- [ ] All the URL responses and their status codes must be updated accordingly to the deployed site.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by SanketDG** [comment]
Can we automate this? The swagger UI is the documentation, so I am not sure I need this.

**Comment by PrashanthPuneriya** [comment]
@SanketDG I too don't need it. I thought someone found it useful but, forgot to update it. Hence, I raised the issue.

**Comment by divyanshugit** [comment]
Can I work on this issue  @PrashanthPuneriya ?

**Comment by vj-codes** [comment]
@PrashanthPuneriya I would suggest that the new issues created be put on hold and make it available 2-3 days before Open Source Hack.What say?

**Comment by PrashanthPuneriya** [comment]
@vj-codes That sounds good.
@divyanshugit If you are participating in Open Source Hack(OSH) then for sure I will assign this issue to you. Please free to fix other issues in the meantime.

**Comment by divyanshugit** [comment]
@PrashanthPuneriya Can you give me some details about the Open Source hack(OSH) ? I don't have any idea about it .

**Comment by PrashanthPuneriya** [comment]
@divyanshugit It is an open source program aimed to help the participants contribute to open source projects. Refer [this link](https://anitab-org.github.io/events/open-source-hack/) to know more about it. I suggest you to participate in it :)

**Comment by divyanshugit** [comment]
@PrashanthPuneriya I would love to participate in the OSH. Can you assign me on this ??

**Comment by PrashanthPuneriya** [comment]
@divyanshugit There is no need of assigning someone to participate in OSH. Anyone can participate in it.

**Comment by PrashanthPuneriya** [comment]
Hey @divyanshugit! I am assigning this issue to you since, you are participating in OSH. But, remember that the PR for OSH program will be valid only if you raised it during the OSH timeline.

**Comment by vj-codes** [comment]
Hey @PrashanthPuneriya on the Android repo no contributors are being assigned till 1st September for OSH. It'll be great if same is followed to avoid further confusion:)

**Comment by SanketDG** [comment]
Again, if we can't automate this, I truly think there is no point doing this if it's always going to be out of date.

**Comment by PrashanthPuneriya** [comment]
@vj-codes Okay! I won't assign the OSH issues from now on then.

**Comment by PrashanthPuneriya** [comment]
> Again, if we can't automate this, I truly think there is no point doing this if it's always going to be out of date.

Is the automation possible? What should we do with this issue now? Shall we let @divyanshugit work on this for now?

**Comment by SanketDG** [comment]
I am not sure @PrashanthPuneriya, I would have already suggested something if I knew :slightly_smiling_face: 

Also do you mean that the codes on the left hand side of the preview `HTTPStatus....` is what the swagger.json should contain?

Because it's actually a bug when we moved to flask-restx #605, previously the actual status codes used to appear.

**Comment by SanketDG** [comment]
Also, if you go to http://mentorship-backend-temp.herokuapp.com/swagger.json, you will also see the same status codes as the display.

**Comment by PrashanthPuneriya** [comment]
> Also do you mean that the codes on the left hand side of the preview HTTPStatus.... is what the swagger.json should contain?

Yes! I meant the status codes.
> Also, if you go to http://mentorship-backend-temp.herokuapp.com/swagger.json, you will also see the same status codes as the display.

Ohh! Then, we don't even need this file right? The deployed version link itself serves the purpose.

**Comment by PrashanthPuneriya** [comment]
@SanketDG I opened #764. Can we close this issue now? If yes, what about the assignee?

**Comment by SanketDG** [comment]
@divyanshugit Apologies, you will have find some other issue now, there are lot of them right now!

Feel free to close this
