### ISSUE TITLE
Remove unrequired Optional import from typing package

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#733]
**Describe the bug**

There is no usage of `typing.Optional` import in [user.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/user.py) file.

**Expected behavior**
There shouldn't be any unnecessary imports.

**Screenshots**
![image](https://user-images.githubusercontent.com/42068010/90507225-2b2bc980-e173-11ea-8607-b1db3cac880b.png)

**Additional context**
Remove the unnecessary import from the mentioned file and also search for any other unnecessary imports and remove them.

**Comment by SanketDG** [comment]
Also can be reported in CI with https://github.com/anitab-org/mentorship-backend/issues/173

**Comment by PrashanthPuneriya** [comment]
Cool 😎. But, I think this issue would be quite beneficial for the beginners (Open Source Hack) as it pushes them to setup the project and learn about git. What do you think?

**Comment by atharwa-24** [comment]
Can I work on this issue?

**Comment by PrashanthPuneriya** [comment]
Hey @atharwa-24 ! This issue is reserved for Open Source Hack (OSH) participants. If you are participating in it then, for sure I will assign you this issue :)

**Comment by vaibhavarora102** [comment]
hi @PareenKarpe can you pls assign this issue to me for open-source hack 
thanks!

**Comment by faznan3nazer** [comment]
I would like to work on this issue.. Can you please assign this to me for Open-Source Hack?

**Comment by niyati-n** [comment]
I would like to work on this issue for open source hack

**Comment by yogeshr59** [comment]
Hey @PrashanthPuneriya I would like to work on this issue under OSH if it has not been claimed yet. Thanks.

**Comment by vaibhavarora102** [comment]
Hi, can you pls assign this issue to me as its already 1st of September and I guess OSH has started
Thanks

**Comment by priyanshuone6** [comment]
Hey can you assign this issue to me, I would like to work on it

**Comment by PrashanthPuneriya** [comment]
Assigning you this issue @vaibhavarora102  :)

**Comment by vaibhavarora102** [comment]
thanks 
@PrashanthPuneriya

**Comment by vaibhavarora102** [comment]
hi @PrashanthPuneriya 
i got some error from bot can you pls tell that what i had did wrong as i am bit new to open source
thanks
