### ISSUE TITLE
Server response : registration_date in GET/user is float

### ISSUE THREAD

**Issue by Shivansh2407** [anitab-org/mentorship-backend#736]
**Describe the bug**

The registration_date field on retrieving the user details gives a float value which is not an appropriate option for displaying the date.

**To Reproduce**

1. Go to 'https://mentorship-backend-temp.herokuapp.com/'
2. Click on 'Users' -> 'POST/login' -> Get the Token
3. Scroll down to 'GET/user' -> Enter : Bearer <access_token> 
4. See error in the registration_date

**Expected behavior**
 It should return the date in the specified date format as the email_verification_date does.

**Screenshots**
![image](https://user-images.githubusercontent.com/42182955/90761972-d8344c80-e301-11ea-9d33-07889cefde03.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [ Chrome ]

**Comment by UdokaVrede** [comment]
way to go on this @Shivansh2407

**Comment by Sommie09** [comment]
I would love to work on this, I am participating in OSH @Shivansh2407  I'm a first-timer

**Comment by Shivansh2407** [comment]
@UdokaVrede @Sommie09 glad to see you interest in this issue. This issue is reserved for Open Source Hack which starts on 1st September. If you are participating in OSH, I will surely assign it to you . Please fix the other issues in the meantime. For more information about OSH take a look at [this link](https://anitab-org.github.io/events/open-source-hack/)

**Comment by UdokaVrede** [comment]
Thanks for the reply, I'd like to know if applications to participate in
the Open Source Hack are still open, as I would love to participate in this
exercise.
A link to the application is still available would be appreciated.

**Comment by PrashanthPuneriya** [comment]
Hey @UdokaVrede! There is no need of applying to OSH program. We will consider you as a participant in the OSH program if you open PRs in the month of September. Please follow [this link](https://anitab-org.github.io/events/open-source-hack/) to know more about OSH program. Happy coding :)

**Comment by priyanshuone6** [comment]
Hey can you assign this issue to me, I would like to work on it

**Comment by PrashanthPuneriya** [comment]
Assigning you @priyanshuone6. Happy coding :)

**Comment by priyanshuone6** [comment]
What should be the username, password in POST/login to get token?

**Comment by Shivansh2407** [comment]
Hi @priyanshuone6, you can register, then use the credentials for login everytime you need the token for access.

**Comment by UdokaVrede** [comment]
I am Udokaku Ugochukwu, a python developer, technical writer and Free open
source contributor from Nigeria. I am currently learning Data Science. I am
enthusiastic about introducing more women and underrepresented people into
tech and open source contributions. For Anita organization, I would like to
be part of the mentoring committee, as this would be a platform to bringing
more women into technology and encourage diversity and inclusion in tech.

I hope to get a response from you soonest.

Thanks

Udokaku Ugochukwu

**Comment by diananova** [comment]
Hi I'd love to work on this!

**Comment by devkapilbansal** [comment]
@isabelcosta @vj-codes  please mark this issue as available

**Comment by harshakhmk** [comment]
I would like to work on this, I am first time contributor @Shivansh2407  @isabelcosta @devkapilbansal

**Comment by devkapilbansal** [comment]
@harshakhmk assigning you.

**Comment by harshakhmk** [comment]
![register-error](https://user-images.githubusercontent.com/56113657/121361204-b10f4000-c952-11eb-95eb-420115cfcd24.png)

Getting 500 error on registering a new user
Also by changing ``` registered_at``` field to ```DateTime``` field, I am getting error that It accepts only float object
But I changed the field everywhere in entire repo

**Comment by harshakhmk** [comment]
I have made code changes but from the bottom level, every operation involving in registration_date is been done using float values, so if we try to change it to the DateTime field, the code is breaking

**Comment by epicadk** [comment]
I don't think this change is required. We should return a float value to that we can display the epoch timestamp in the appropriate/local timezone of the user.
 cc @isabelcosta
