### ISSUE TITLE
Categorise mentorship_relation, tasks and comments

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#738]
## Description
As a contributor,
I need better categorization of files and its related code logic,
so that I can easily find the related code and wrap up my head around the project.
### Currently the following are under one category
![image](https://user-images.githubusercontent.com/42068010/90953439-3f303d80-e489-11ea-9870-335441c039de.png)

[resources/mentorship_relation.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/resources/mentorship_relation.py) and many other files can be further split into different files.
### We can categorise them as
- mentorship relation --> send, accept, delete, cancel, reject, current, past, pending
- tasks --> list, create, update, delete
- comments --> list, create, update, delete.

### Update [Required]
- [ ] Come with a solution to categorise them.
- [ ] Discuss all the required things we need to change and the existing code which might break after this change.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
[Can't estimate] hours

**Comment by pavani-17** [comment]
I am participating in Open Source Hack... May I work on this?

**Comment by PrashanthPuneriya** [comment]
@pavani-17 Sure! I can assign this issue to you as soon as the program starts. Also, since this issue comes under outreach/research I think it requires approval from the core contributors. Meanwhile please feel free to work on other issues :)

**Comment by faznan3nazer** [comment]
I would like to work on this Issue...can you please assign this to me for Open-Source Hack?

**Comment by saideepesh000** [comment]
#OSH, can I work on this.

**Comment by saideepesh000** [comment]
#OSH, can I work on this.

**Comment by pavani-17** [comment]
Can I be assigned as the program starts today?

**Comment by PrashanthPuneriya** [comment]
Hey everyone! This issue needs approval as this is a large issue and can create several files and break the project. Can you please review this issue @isabelcosta @SanketDG ?

**Comment by codesankalp** [comment]
@PrashanthPuneriya i want to work on this issue.

**Comment by isabelcosta** [comment]
@PrashanthPuneriya I think this is a very goood issue! Even though the task and comments are related to mentorship relation, it would make the Swagger UI much easier to inspect I think. Feel free to assign it @PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
Does anyone want to work on this? I will assign this issue on the basis of First-Come-First-Serve.

**Comment by faznan3nazer** [comment]
I would like to work on this issue... currently, I am assigned to  [issue](https://github.com/anitab-org/mentorship-android/issues/779) but I cannot create a PR, because of the required folder (docs/ui) is still not created by the repo admins. That is why I cannot create a PR for that, I am blocked there. Can I work on this issue?

**Comment by PrashanthPuneriya** [comment]
@faznan3nazer What about #596 ?

**Comment by vj-codes** [comment]
@PrashanthPuneriya hey I would like to work on this

**Comment by vj-codes** [comment]
> I would like to work on this issue... currently, I am assigned to [issue](https://github.com/anitab-org/mentorship-android/issues/779) but I cannot create a PR, because of the required folder (docs/ui) is still not created by the repo admins. That is why I cannot create a PR for that, I am blocked there. Can I work on this issue?

@faznan3nazer As far as I know , contributors have to create the folder and then add the changes , 
this is being done in android and backend repo.

**Comment by PrashanthPuneriya** [comment]
Assigning you @vj-codes :)

**Comment by vj-codes** [comment]
@PrashanthPuneriya since swagger.json is deleted , where am I supposed to make the changes?
Also do you want me to rearrange as well as split the files?

**Comment by PrashanthPuneriya** [comment]
@vj-codes To my knowledge `swagger.json` has nothing to do with this issue. Once you rearrange and split the code into different files the frontend for this project a.k.a swagger automatically changes.
> Also do you want me to rearrange as well as split the files?

Yes! It would be more convienient :)

**Comment by vj-codes** [comment]
@PrashanthPuneriya I still can't get it totally , like do I have to split in form of send_request.py , delete_request.py etc ?
What I thought about this issue was to edit [this](http://mentorship-backend-temp.herokuapp.com/swagger.json) and the UI will get categorised. 
If you could  ellaborate a bit more , thanks!

**Comment by PrashanthPuneriya** [comment]
> What I thought about this issue was to edit this and the UI will get categorised.

This issue is not related to docs. It is related to coding. As far as I know you can't edit swagger.json it is automatically generated by swagger ui.
> I still can't get it totally , like do I have to split in form of send_request.py , delete_request.py etc ?

Currently all the logic related to comments, tasks, relations are under single file. So, I need you to split the code as follows or even better:-
![image](https://user-images.githubusercontent.com/42068010/92448619-7d8e6200-f1d6-11ea-86bc-e3fb28ae158c.png)
At the end you will have mentorship_relation.py, tasks.py, comments.py files and any other files you intend to split.
If you still don't understand please feel free to shoot all the questions you have @vj-codes :)

**Comment by vj-codes** [comment]
okay so what ever code is related to tasks in mentorship_relation.py should be remvoved and shifted to tasks.py? @PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
Yes @vj-codes! You got it right. Not just tasks.py you also need to create comments.py and any other file which you think is reasonable to have its own file.

**Comment by vj-codes** [comment]
Is this what is expected for mentorship relation? @PrashanthPuneriya 
Also what should be the description of tasks and comments like mentorship has "operations related to... users "?

![image](https://user-images.githubusercontent.com/60894542/92453521-fdb7c600-f1dc-11ea-8078-121233c7627b.png)

**Comment by PrashanthPuneriya** [comment]
@vj-codes Exactly!! Looks good :)
> Also what should be the description of tasks and comments like mentorship has "operations related to... users "?

"Operations related to comments between users" is fine by me. What do you think?

**Comment by vj-codes** [comment]
@PrashanthPuneriya @isabelcosta @SanketDG 
After mentorship relation , I created a tasks.py file in resources but got an error that there's no tasks.py in models .
So, I created tasks.py in models and took the body from mentorship_relation.py dealing with tasks part .
After I tried to run it I get this 
```
{
    "error": "Unable to render schema" and Failed to load API definition
}
```
What to do next? or should I categorise tasks and comments below relations on swagger as the same error thing is going to happen when I create comments.py in resources

**Comment by PrashanthPuneriya** [comment]
I need to invest a lot of time to help you on this @vj-codes. But, I am quite busy with my examinations and other stuff. I will try my best to help anyone fixing this issue whenver I am free. I hope you understand :)

**Comment by vj-codes** [comment]
Making it available as I'm quite busy with school too

**Comment by pallavisavant** [comment]
@PrashanthPuneriya was just looking into this....i can see that we already have 3 respective files each for mentorship_relation,tasks and tasks_comment and code has been precisely distributed also across these 3 files....if u can check...idk if am right but we already have this in existing project....Thanks.

**Comment by PrashanthPuneriya** [comment]
Yes we do have separate files for api/dao but not for api/resources and api/models @pallavisavant

**Comment by aditya2499** [comment]
I would like to work over this

**Comment by pallavisavant** [comment]
> @PrashanthPuneriya was just looking into this....i can see that we already have 3 respective files each for mentorship_relation,tasks and tasks_comment and code has been precisely distributed also across these 3 files....if u can check...idk if am right but we already have this in existing project....Thanks.

oh okay got it.....if this is still available i would like to work on this....Thanks.

**Comment by PrashanthPuneriya** [comment]
> I would like to work over this

Assigning you :)

**Comment by Anmollenka** [comment]
I am interested to work on this if it is available.Thank You

**Comment by PrashanthPuneriya** [comment]
@aditya2499 Any update?

**Comment by aditya2499** [comment]
@PrashanthPuneriya  I am in the midway. I got my university mid sem exams and may not be able to continue to work for some days. If you say I can unassign myself and open this issue for another contributors.

**Comment by vj-codes** [comment]
@PrashanthPuneriya if it's available later I would like to work on this again! I understood my mistake later but by that time it was assigned to another contributor. 
I would like to give another try here:)

**Comment by PrashanthPuneriya** [comment]
> @PrashanthPuneriya I am in the midway. I got my university mid sem exams and may not be able to continue to work for some days. If you say I can unassign myself and open this issue for another contributors.

No worries! I will be happy to assign you if others fail to deliver a PR until then I think it's better to make this issue available to others.

**Comment by PrashanthPuneriya** [comment]
Assigning you @vj-codes :)

**Comment by PrashanthPuneriya** [comment]
@vj-codes Any progress?

**Comment by vj-codes** [comment]
@PrashanthPuneriya yes I had some doubts , will ask Isabel in today's mentorship session

**Comment by khushishikhu** [comment]
may i work on this issue?

**Comment by PrashanthPuneriya** [comment]
@vj-codes How's the PR going on? Can you please update the progress?

**Comment by vj-codes** [comment]
> @vj-codes How's the PR going on? Can you please update the progress?

@PrashanthPuneriya I commited the changes yest , made the PR right now

**Comment by NenadPantelic** [comment]
@vj-codes @PrashanthPuneriya Can I take this?

**Comment by vj-codes** [comment]
Assigning you @NenadPantelic 
Happy refactoring!

**Comment by NenadPantelic** [comment]
> Assigning you @NenadPantelic
> Happy refactoring!

Thanks @vj-codes :slightly_smiling_face:

**Comment by NenadPantelic** [comment]
Hi @PrashanthPuneriya @isabelcosta  @vj-codes. I have opened a PR. Please, take a look and review it. Thanks :blush:
