### ISSUE TITLE
Use f-strings on User Resources file

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#739]
## Description
As a developer,
I need change strings interpolation in User Resources file,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `app/api/resources/user.py` file.

## Mocks

As an example, here:

https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/app/api/resources/user.py#L171-L172

We can use f-strings such as:

```
@users_ns.response(HTTPStatus.CREATED, f"{messages.PASSWORD_SUCCESSFULLY_UPDATED})
```

### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for `app/api/resources/user.py` file

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by anupriya-goyal** [comment]
I would like to work on this.

**Comment by SanketDG** [comment]
Let us know if you need any help!

**Comment by isabelcosta** [comment]
@PrashanthPuneriya we have to take the open source hack label right? because it has not started yet? I am asking because I am not sure.

**Comment by PrashanthPuneriya** [comment]
@isabelcosta We asked @mayburgos but, there was no response. So, we decided to assign the issues only for Open Source Hack participants else there will be very less no. of issues for the program.
If a contributor asks you to assign the OSH labelled issues please make them aware of OSH program and ask them to create a PR during the OSH timeline.

**Comment by isabelcosta** [comment]
@PrashanthPuneriya I see, that is a good compromise 🤔  As long as we are not gatekeeping issues. We can always come with more issues :P I have always a lot of ideas! Ok, so the hack starts next week right?

**Comment by PrashanthPuneriya** [comment]
@isabelcosta I am struggling to find issues :P Yes! OSH begins next week. Pretty excited to begin my journey as a mentor officially :D

**Comment by anupriya-goyal** [comment]
Hi everyone,

I was trying to setup this project on my windows machine. I have installed Python3.8 on my machine and when I tried to run the command given in the readme for setup: Create a virtual environment: virtualenv venv --python=python3 is not working. I got an error that virtualenv is not recognized. This command is for windows machine ? Can you please let me know where I am doing wrong in setup.

**Comment by SanketDG** [comment]
Hey @anupriya-goyal, here's a couple of things I can suggest:

- Make sure that `python3` is in your PATH, it's highly possible that your python installation may not have added the `python` executable to your `%PATH%`
- You could just try `virtualenv venv`, because I assume you would have installed only `Python 3`, and hence, there is no need to explicitly mention `Python 3` in the command.
- Look into using WSL, let's you use Linux from within Windows!

**Comment by SanketDG** [comment]
> If a contributor asks you to assign the OSH labelled issues please make them aware of OSH program and ask them to create a PR during the OSH timeline.

I wasn't aware, apologies. If it's possible, we can remove the OSH label from this issue.

**Comment by anupriya-goyal** [comment]
@SanketDG  thanks, I have followed your advice over using wsl. 
Currently I am using Ubuntu distribution WSL. I have forked the repo and have followed the steps to setup the remote upstream. 
I am able to create a virtual environment through WSlL. 
I am facing issues at pip install requirement.txt command. Error I am getting when it is installing cliff, blinker packages. 

![Error_in_requirement](https://user-images.githubusercontent.com/13662453/91380345-be5ba380-e7f2-11ea-82ed-610d8c8dc21b.png)

![2](https://user-images.githubusercontent.com/13662453/91380325-b4d23b80-e7f2-11ea-8c6d-0e80574c2b6a.png)

Any suggestions about this issue.

**Comment by SanketDG** [comment]
This is what googling turned up https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

**Comment by anupriya-goyal** [comment]
Hi,
Thanks @SanketDG. I tried the fixes given at this link. Unfortunately, they didn't work. Actually I tried to see by installing the cffi package. In the log I saw it is already installed but with different version and when it is trying to install the cffi version that is given in requirement.txt it is throwing an error of setup.py file not able to install that. 
I am not able to spend more time on this project , would try in future if I can manage it with my schedule. You can open this task for others to pick up if you want.

**Comment by Sanchit-Trivedi** [comment]
@SanketDG @PrashanthPuneriya @isabelcosta  as the previous assignee Anupriya is unable to work on the issue, I request you to assign me this issue as I would like to work on it as a part of OSH. Thanks

**Comment by SanketDG** [comment]
@anupriya-goyal No worries, that is understandable. Feel free to ask on Zulip about any issues you are facing.

**Comment by Sanchit-Trivedi** [comment]
@SanketDG I have made the required changes. Please review my Pull Request. As I am a first-time contributor and new to open source I request you to tell me if I have made any errors in putting the pull request regards to the format, commit message or the code itself. Thanks in advance.

**Comment by surbhigoel191** [comment]
@vj-codes May I work on this issue? :)

**Comment by vj-codes** [comment]
@surbhigoel191 this issue is not available , it's assigned to another contributor and a PR has been created too.
You can go through issue with the label `Status: Available` and comment :)

**Comment by KushalBeniwal** [comment]
@isabelcosta @devkapilbansal I would like to work on this issue. Can you please assign it to me?

**Comment by devkapilbansal** [comment]
@KushalBeniwal all yours good luck

**Comment by devkapilbansal** [comment]
You can take help from #837 if needed

**Comment by KushalBeniwal** [comment]
Sure, thanks :)

**Comment by KushalBeniwal** [comment]
I made the required changes. My PR is ready for review.
