### ISSUE TITLE
Use f-strings on Admin Resources file

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#741]
## Description
As a developer,
I need change strings interpolation in Admin Resources file,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `app/api/resources/admin.py` file.

## Mocks

As an example, here:

https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/app/api/resources/admin.py#L16

We can use f-strings such as:

```
@admin_ns.response(HTTPStatus.FORBIDDEN, f"{messages.USER_IS_NOW_AN_ADMIN})
```

### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for `app/api/resources/admin.py` file

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by LivesInRoom29** [comment]
Hi there! It doesn't look like anyone has requested to work on this yet. If it's still available, I'd love to give it a go. It would be my first contribution on here. I should be able to get it done tomorrow.

**Comment by PrashanthPuneriya** [comment]
Hey @LivesInRoom29 ! I have assigned you this issue. Happy coding :)
