### ISSUE TITLE
Use f-strings in mentorship_relation folder test files

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#742]
## Description
As a developer,
I need change strings interpolation in mentorship_relation folder test files,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `tests/mentorship_relation/*` file.

## Mocks
As an example, here:
https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/tests/mentorship_relation/test_api_cancel_relation.py#L50
We can use f-strings such as:
```
f"/mentorship_relation/{self.mentorship_relation.id}/cancel",
```
### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for all such files present in `tests/mentorship_relation` folder.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by ankanbose848** [comment]
@PrashanthPuneriya  I would love to work on this.

**Comment by PrashanthPuneriya** [comment]
Hey @ankanbose848! This issue is reserved for [Open Source Hack (OSH)](https://anitab-org.github.io/events/open-source-hack/) participants. If you are participating in it for sure I will assign you this issue. Please free to check out other issues :)

**Comment by BALaka-18** [comment]
Hi @PrashanthPuneriya, I am participating in Open Source Hack (OSH). Can I work on this issue ?

**Comment by PrashanthPuneriya** [comment]
@BALaka-18 I will assign this issue to you if @ankanbose848 isn't participating in OSH program. Otherwise it won't be fair. Hope you understand :)

**Comment by ankanbose848** [comment]
I am participating in it.

**Comment by BALaka-18** [comment]
> @BALaka-18 I will assign this issue to you if @ankanbose848 isn't participating in OSH program. Otherwise it won't be fair. Hope you understand :)

Yes I understand. No problem.

**Comment by priyanshuone6** [comment]
Hey can you assign this issue to me, I would like to work on it

**Comment by PrashanthPuneriya** [comment]
@priyanshuone6 You have been assigned to #736 issue. You can't claim this issue unless you create a PR for the prevs assigned issue.

**Comment by BALaka-18** [comment]
Hey @PrashanthPuneriya if no one's been assigned, could I work on this issue ?

**Comment by PrashanthPuneriya** [comment]
Sure @BALaka-18 !

**Comment by BALaka-18** [comment]
@PrashanthPuneriya I have made a PR (#808). Kindly review it once.
Thanks.
