### ISSUE TITLE
Use f-strings in users folder test files

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#743]
## Description
As a developer,
I need change strings interpolation in users folder test files,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `tests/users/*` files.

## Mocks
As an example, here:
https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/tests/users/test_api_resources.py#L49-L50
We can use f-strings such as:
```
f"POST /register failed to register Testing User! with error code = {response.status_code}" 
```
### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for all such files present in `tests/users` folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hour

**Comment by priyanshurohilla** [comment]
hey @PrashanthPuneriya  can i work on this?

**Comment by PrashanthPuneriya** [comment]
Hey @priyanshurohilla ! This issue is reserved for [Open Source Hack (OSH)](https://anitab-org.github.io/events/open-source-hack/) participants. If you are participating in it for sure I will assign you this issue. Please free to check out other issues :)

**Comment by BALaka-18** [comment]
Hi @PrashanthPuneriya I am participating in Open Source Hack (OSH). Can I work on this issue ?

**Comment by priyanshurohilla** [comment]
> Hey @priyanshurohilla ! This issue is reserved for [Open Source Hack (OSH)](https://anitab-org.github.io/events/open-source-hack/) participants. If you are participating in it for sure I will assign you this issue. Please free to check out other issues :)

I am participating in it. Thanks for acknowledging😊

**Comment by PrashanthPuneriya** [comment]
@priyanshurohilla I am assigning this issue to you since, you are participating in OSH and grabbed it first. But, remember that the PR for OSH will be valid only if you raised it during the OSH timeline.
