### ISSUE TITLE
Use f-strings in tasks folder test files

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#744]
## Description
As a developer,
I need change strings interpolation in tasks folder test files,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `tests/tasks/*` files.

## Mocks
As an example, here:
https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/tests/tasks/test_api_create_task.py#L32
We can use f-strings such as:
```
f"/mentorship_relation/{self.mentorship_relation_w_second_user.id}/task",
```
### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for all such files present in `tests/tasks` folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

**Comment by Nibba2018** [comment]
Hello @PrashanthPuneriya  can i work on this issue?

**Comment by ankanbose848** [comment]
@PrashanthPuneriya I would love to work on this issue.

**Comment by PrashanthPuneriya** [comment]
Hey @Nibba2018 @ankanbose848! This issue is reserved for [Open Source Hack (OSH)](https://anitab-org.github.io/events/open-source-hack/) participants. If you are participating in it for sure I will assign you this issue. Please free to check out other issues :)

**Comment by Nibba2018** [comment]
Sure @PrashanthPuneriya , I just wanted to know if someone else is already working on it to prevent duplicate work. Also I actually am participating for `OSH`.

**Comment by PrashanthPuneriya** [comment]
@Nibba2018 I am assigning this issue to you since, you are participating in OSH and grabbed it first. But, remember that the PR for OSH will be valid only if you raised it during the OSH timeline.

**Comment by Nibba2018** [comment]
Thank You @PrashanthPuneriya .
