### ISSUE TITLE
Search users based on both the username and name

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#745]
**Is your feature request related to a problem? Please describe.**
Currently, the search function finds the mentor/mentee based on `Name`. Sometimes, users are remembered by their username instead of their name. e.g. @Techno-Disaster :D

**Describe the solution you'd like**
Add a feature such that the users can be searched even by their username.

**Describe alternatives you've considered**
NA

**Additional context**
Refer [this](https://github.com/anitab-org/mentorship-backend/issues/644#issuecomment-661748664) comment for more details.

**Comment by brpowell** [comment]
Hi all 👋 . I was hoping to take this issue if it hasn't been claimed yet. Thanks!

**Comment by kritikaparmar-programmer** [comment]
Hey @PrashanthPuneriya  I want to work on this issue as a part of OSH.. Please assign me

**Comment by PrashanthPuneriya** [comment]
Sure @kritikaparmar-programmer! Since, this is a feature request it needs approval from other contributors as well :) 
@Techno-Disaster @isabelcosta @SanketDG @vj-codes Shall we proceed with this feature? As a reminder, earlier #644 issue was raised where most of the members confused the search functionality btw username and Name

**Comment by vj-codes** [comment]
@PrashanthPuneriya I would say we shall proceed!

**Comment by SanketDG** [comment]
@PrashanthPuneriya Looks fine by me, it's just that it should be explicity clear in the documentation that it searches by two fields.

**Comment by codesankalp** [comment]
@PrashanthPuneriya  I want to work on this issue.I am eagerly waiting to contribute to an issue.

**Comment by PrashanthPuneriya** [comment]
Are you still available to work on this issue @kritikaparmar-programmer?

**Comment by codesankalp** [comment]
@PrashanthPuneriya  I want to work on this issue.

**Comment by PrashanthPuneriya** [comment]
@codesankalp You are already assigned to #747. Do you want to work on this issue or the other?

**Comment by codesankalp** [comment]
Yes I want to work on this issue because I want to contribute in code part also.

If it is possible then assign me this issue otherwise I will try to complete that issue first and then move on to this issue.
@PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
I am more than happy to assign you this issue after you create a PR to #747 @codesankalp :) If I assign this issue right now then it means that you will be reserving this issue and others won't be able to take up this issue. I hope you understand.

**Comment by codesankalp** [comment]
Yes I will fix that issue soon.
And start working on this issue soon.
Thanks.

**Comment by aditya2499** [comment]
Is it available? I would like to work over this.

**Comment by abhinav72610** [comment]
If this is availablei will want to work on this

**Comment by PrashanthPuneriya** [comment]
Are you available to work on this issue @codesankalp ?

**Comment by codesankalp** [comment]
Yes I am available, I fixed the previous issue 🙂. You can check my pull request for that issue @PrashanthPuneriya .

You can assign me this issue.

**Comment by PrashanthPuneriya** [comment]
Assigning you @codesankalp! Happy coding :)

**Comment by codesankalp** [comment]
@PrashanthPuneriya Can you explain me more about this issue?
For example :- where to change the code?

**Comment by PrashanthPuneriya** [comment]
> For example :- where to change the code?

You need to find that on your own @codesankalp. The starting point would be to find the code for Searching by Names.

**Comment by PrashanthPuneriya** [comment]
Any progress @codesankalp ?

**Comment by codesankalp** [comment]
Working currently.

**Comment by codesankalp** [comment]
@PrashanthPuneriya @SanketDG 
Please Review this pull request.
