### ISSUE TITLE
Move docs from wiki to Docusaurus

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#747]
**Is your feature request related to a problem? Please describe.**
As of now, the whole documentation for mentorship-backend is in [the wiki](https://github.com/anitab-org/mentorship-backend/wiki).

**Describe the solution you'd like**
We will now move to Docusaurus.

**Describe alternatives you've considered** 
  Docusaurus

**Additional context**
**TODO:**

- [ ] Add a basic minimal scaffold in docs/ (use Tinysaurus)
- [ ] Remove the old files from docs/

**Comment by SanketDG** [comment]
We need to break each of the list items in separate issues for OSH, because this in itself is a pretty big issue.

**Comment by vaibhavarora102** [comment]
can I work on this in the open source hack

**Comment by nandini45** [comment]
yes @vaibhavarora102  do u want to work on it?

**Comment by vaibhavarora102** [comment]
Yes for sure

**Comment by gaurivn** [comment]
Hi @vaibhavarora102, the issues meant for open source hack will be assigned / can be claimed only when the program starts on September 1st, 2020 on a first come first serve basis. Do come back and comment here on 1st and will assign you.

**Comment by vaibhavarora102** [comment]
Can I take this at night 12 :00 of 31st

**Comment by vaibhavarora102** [comment]
Hi @gaurivn , can you pls assign this issue to me as its already 1st of September and I guess OSH has started
Thanks

**Comment by gaurivn** [comment]
> Hi @gaurivn , can you pls assign this issue to me as its already 1st of September and I guess OSH has started
> Thanks

Sure, assigned

**Comment by HeroicHitesh** [comment]
I would like to work on this issue under OSH. Please assign me this issue when it's free.

**Comment by Anmollenka** [comment]
I wolud like to work on this .Can you assign this to me when it's free??Thank You

**Comment by vj-codes** [comment]
@vaibhavarora102 how's the PR going?

**Comment by vaibhavarora102** [comment]
hi i am not getting the way to deal with docusaurus

**Comment by gaurivn** [comment]
Would you like to be unassigned from the issue?

**Comment by vaibhavarora102** [comment]
yes pls

**Comment by codesankalp** [comment]
I can do this work. So please assign me this work @SanketDG @gaurivn

**Comment by vj-codes** [comment]
Assigning you @codesankalp 
Happy documenting!

**Comment by codesankalp** [comment]
@vj-codes @PrashanthPuneriya 
should i remove all the old files from docs ?
I have solved this issue by using tinysauraus.

**Comment by PrashanthPuneriya** [comment]
@codesankalp I think we shouldn't remove anything from docs/...
We don't have access to remove wiki and the wiki has many docs linking to docs/.. folder files. It is better if we remove the docs/.. only if we remove wiki. So, let it be @codesankalp

**Comment by codesankalp** [comment]
@PrashanthPuneriya Please review my pull request. Thanks.
