### ISSUE TITLE
Remove the redundant link from README file

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#752]
## Description
As a contributor,
I don't need a link to the same page stating Mentorship System,
so that I won't be clicking on the link without knowing that it redirects to the same page.

## Mocks
![image](https://user-images.githubusercontent.com/42068010/91195882-0efdce80-e717-11ea-9091-bb6be2379fb0.png)
Here `Mentorship System` term points to the mentorship-backend repo which isn't required.

### Update [Required]
- [ ] Remove the link to Mentorship Backend for the term Mentorship System from [this](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md) file.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.25] hours

**Comment by Sommie09** [comment]
@PrashanthPuneriya I'm participating in the OSH program from 1st September. I am done with this task and would love to send in a PR on the 1st! I'm a first-timer in open source as well

**Comment by PrashanthPuneriya** [comment]
@Sommie09 I can assign you this issue on September 1st. Please free to checkout other issues in the mean time.

**Comment by Sommie09** [comment]
okay @PrashanthPuneriya would check in then! Thank you

**Comment by Hyper-Matrix** [comment]
I would like to work on this. Is there any chance I can work on it?

**Comment by PrashanthPuneriya** [comment]
@Hyper-Matrix This issue is for OSH program. Since, a participant has claimed the issue it won't be fair to remove this issue from OSH program. If you're participating in the program then it may be possible to assign this issue to you during OSH timeline.  If not then please feel free to checkout other issues :)

**Comment by nitish-awasthi** [comment]
Hi! @PrashanthPuneriya can I work on this issue for OSH?

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by Hyper-Matrix** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? I have already placed a PR regarding the same.

**Comment by Hyper-Matrix** [comment]
Hey can I be assigned?

**Comment by PrashanthPuneriya** [comment]
@Abjcodes This issue is only for first-timers. You have created #800. So, I can't assign you this issue.

**Comment by PrashanthPuneriya** [comment]
@Hyper-Matrix You shouldn't create a PR before the issue has been assigned to you. Please read the community-guidelines. I am assigning you this issue and considering your PR only for this time as you are new to this project. Please don't repeat it again :)

**Comment by Hyper-Matrix** [comment]
Thank you so much am sorry for the same..

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you please assign me this issue? I'm a first time contributor.

**Comment by PrashanthPuneriya** [comment]
Hey @96RadhikaJadhav! A PR has been created for this issue and will be merged most probably. Can you please look into other issues and work on them?
