### ISSUE TITLE
Add code quality badges to README file

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#754]
## Description
As a contributor,
I need to know the status of the code quality of major branches (develop and master).
So that I can be aware of the code quality as I land on the main page of the repository through README.

## Mocks
As done on mentorship-android's repository.
![mentorship-android](https://user-images.githubusercontent.com/46970368/91287854-e8d73d80-e7ad-11ea-8ed5-31299b590209.PNG)

### Update [Required]
- [ ] Add two badges (develop and master) to the Mentorship Backend [README file](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1-2] hours

**Comment by utkzas** [comment]
can you assign this to me please :)

**Comment by paritoshsinghrahar** [comment]
@utkzas 
This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. Please free to check out other issues in the meantime.

Program website: https://anitab-org.github.io/events/open-source-hack/

**Comment by swaraj961** [comment]
Hey Can you assign me this issue on 1st sept, also what if two persons conflict with Solving the same issue ?

**Comment by paritoshsinghrahar** [comment]
@swaraj961 Please refer to [Contributing Guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md):

- If you’re just getting started work on an issue labeled “First Timers Only” in any project. Additional resources are available on our website.
- In an active repository (not an archived one), choose an open issue from the issue list, claim it in the comments, and a maintainer will assign it to you.
- After approval, you must make continuous notes on your progress in the issue while working. If there is not at least one comment every 3 days, the maintainer can reassign the issue.

Additionally, we request you to get familiarized with the repository in the meantime.

**Comment by niyati-n** [comment]
I would like to work on this issue

**Comment by visthruth21** [comment]
Hi , I would like to work on this issue can you suggest me ways to get started?

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by Hyper-Matrix** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by priyanshuone6** [comment]
Hey can you assign this issue to me, I would like to work on it

**Comment by paritoshsinghrahar** [comment]
@Abjcodes You have been assigned to two issues.
@Hyper-Matrix @priyanshuone6 You have been assigned to an issue. 
#### This is a first-timers only issue.
 
@utkzas @swaraj961 @blackcrabb Since, we decided to not assign issues based on any comments before September 1 to make it fair for everyone. Please do tell me if you are interested, now.

Remember it's FCFS (First Come First Serve) starting September 1st.

**Comment by swaraj961** [comment]
> @Abjcodes You have been assigned to two issues.
> @Hyper-Matrix @priyanshuone6 You have been assigned to an issue.
> 
> #### This is a first-timers only issue.
> @utkzas @swaraj961 @blackcrabb Since, we decided to not assign issues based on any comments before September 1 to make it fair for everyone. Please do tell me if you are interested, now.
> 
> Remember it's FCFS (First Come First Serve) starting September 1st.

I've been assigned a issue already I'm working on it Thanks

**Comment by ankitwarbhe** [comment]
@paritoshsinghrahar  Can you assign this issue to me?

**Comment by paritoshsinghrahar** [comment]
@ankitwarbhe Sure!  I have assigned you. I hope you have set up the environment and read [community guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).

Happy Coding.  :smiley:

**Comment by ankitwarbhe** [comment]
Thank you @paritoshsinghrahar for assigning the issue looking forward to work on it.

**Comment by ankitwarbhe** [comment]
Hey, @paritoshsinghrahar  to add the codacy badge you need to add me to the organization! 

Note :- Seems like there are some contributions to this repository not being analyzed because these users don't belong to an organization.

kindly go through the concern @isabelcosta  @m-murad

**Comment by arjungarg07** [comment]
@paritoshsinghrahar Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by paritoshsinghrahar** [comment]
@arjungarg07 It's already assigned to someone.

**Comment by paritoshsinghrahar** [comment]
> Hey, @paritoshsinghrahar to add the codacy badge you need to add me to the organization!

@ankitwarbhe Can you work with Travis for now. The image is only for reference**.
A PR with Travis badge would be perfectly acceptable. 2 Badges as in status of master and develop branch. 

Not Travis and Codacy.

> Note :- Seems like there are some contributions to this repository not being analyzed because these users don't belong to an organization.

Yes, there will be contributors. Not everyone can be given write access. That's perfectly fine.

#### @ankitwarbhe  Please revert if any doubts.

**Comment by ankitwarbhe** [comment]
#829  Could you please guide further @paritoshsinghrahar @SanketDG  ?

**Comment by ankitwarbhe** [comment]
I have closed the PR @paritoshsinghrahar and unassigned myself with the issue.

**Comment by 17sushmita** [comment]
Hi I'm new to this community and participating in OSH. @paritoshsinghrahar  Can you assign this issue to me? I'd like to work on it.

**Comment by pallavisavant** [comment]
I have participated for OSH....if this is still available can i take up this one... as i haven't been assigned any under documentation...Thanks.

**Comment by alivabasa** [comment]
Can I take up this task for OSH?

**Comment by vj-codes** [comment]
Assigning you @17sushmita 
Happy documenting!

**Comment by 17sushmita** [comment]
Thank You @vj-codes  for assigning this to me.

**Comment by 17sushmita** [comment]
@vj-codes I've created the PR. Please review it.

**Comment by paritoshsinghrahar** [comment]
Closing this due to [following](https://github.com/anitab-org/mentorship-backend/pull/829#pullrequestreview-482125680).

**Comment by satyendra11111** [comment]
gf
