### ISSUE TITLE
Link essential files under /docs to Documentation section in README file

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#755]
## Description
As a contributor,
1. I need to know the [code organization](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/code_organization.md) within the repository. So that I can be aware of the code organization and basic architecture as I land on the main page of the repository through README.
2. Also, I need access to the internal workings of [user Authentication](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/user_authentication.md) which is JSON Web Token (JWT) based.
    
These can be found in docs but are not linked to the README file in the Documentation section.

### Update [Required]
- [ ] Add the two links to the Mentorship Backend's [README file](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md) under 'Documentation' section ONLY.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.5] hours

**Comment by SanketDG** [comment]
Great ideas!

This somewhat conflicts with #747, we need to have a proper discussion about what needs to be done here.

I'd personally favour creating one single docs, where any form of non-ephemeral documentation resides.

And then (following this issue) we obviously link that to the README, and then we can also link a couple of "frequently asked pages" to the README

**Comment by paritoshsinghrahar** [comment]
> Great ideas!
> 
> This somewhat conflicts with #747, we need to have a proper discussion about what needs to be done here.
> 
> I'd personally favour creating one single docs, where any form of non-ephemeral documentation resides.
> 
> And then (following this issue) we obviously link that to the README, and then we can also link a couple of "frequently asked pages" to the README

@SanketDG 
I think a possible solution can be that even when we move from docs to Docusaurus. 
This issue can be expanded to deal with linking all the pages of documentation to README, once movement to Docusaurus is completed. Additionally, it can also link "frequently asked pages" as you suggested.

This Issue can be broken into two issues.
1. Before moving to Docusaurus.
2. After moving to Docusaurus.

**Comment by SanketDG** [comment]
> This issue can be expanded to deal with linking all the pages of documentation to README

Wouldn't that create a lot of links?

**Comment by paritoshsinghrahar** [comment]
> Wouldn't that create a lot of links?

Yes, it would. Please guide what needs to be done here.

**Comment by faznan3nazer** [comment]
I would like to work on this issue...can you please assign this to me for Open-Source Hack?

**Comment by Aditiwebd** [comment]
I want to work on this issue..Please assign it to me.

**Comment by Poobalan1210** [comment]
can you assign me on this issue as part of OSH

**Comment by paritoshsinghrahar** [comment]
@faznan3nazer This is for first-timers only. @Poobalan1210 Sorry it's on the FCFS basis.

@Aditiwebd I have assigned you. I hope you have set up the environment and read [community guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).

Happy Coding.  :smiley:

**Comment by Aditiwebd** [comment]
Thank you :smile:
