### ISSUE TITLE
Design solution for push notifications in the app and submit as a markdown file under the “docs” folder.

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#756]
## Description
As a contributor, I need you to design a probable solution for supporting push notifications in the app. So that front-end developers can easily trigger an API call from backend sending notifications to the user's device.

Design a probable solution for push notifications in the app and submit as a markdown file under the “docs” folder.

### Update [Required]
- [ ] Submit as a markdown file under the “docs” folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
[4+] hours

**Comment by pavani-17** [comment]
Hey...! May I work on this?

**Comment by paritoshsinghrahar** [comment]
@pavani-17 
This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. You can then participate in the [program](https://anitab-org.github.io/events/open-source-hack/). Please free to check out other issues in the meantime.

**Comment by Aditiwebd** [comment]
I want to work on this issue.Please assign it to me -OSH

**Comment by Aditiwebd** [comment]
I want to work on this issue.Please assign it to me for OSH

**Comment by paritoshsinghrahar** [comment]
@pavani-17 @Aditiwebd You both have been currently assigned other issues. Check back when you are done with that.

**Comment by pavani-17** [comment]
I already sent a PR.... It is being reviewed

**Comment by paritoshsinghrahar** [comment]
@pavani-17 Ok. I'll assign this to you. Happy Coding.  :smiley:

**Comment by Anmollenka** [comment]
I would like to work on this issue.Can you please assign it to me when it's free??Thank You

**Comment by paritoshsinghrahar** [comment]
@Anmollenka It has currently been assigned to someone.

> [Contributing guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md)
> After approval you must make continuous notes on your progress in the issue while working. If there is not at least one comment every 3 days, the maintainer can reassign the issue.

@pavani-17 Please remember the contributing guidelines.

**Comment by pavani-17** [comment]
I have been working on it, I think I already got a solution. I will make a file soon.

**Comment by pavani-17** [comment]
What exactly should I write in the doc? Can someone please guide me on that?

**Comment by paritoshsinghrahar** [comment]
@pavani-17 It can be code snippets, algorithms, pseudo-code, or an in-depth explanation of how you aim to provide the facility of push notifications. How it fits with the present backend code. 

It's basically part of outreach/research. So that new contributors can work/code on the solution you design for the problem.

**Comment by khushishikhu** [comment]
may i work on this issue

**Comment by paritoshsinghrahar** [comment]
@khushishikhu It's already been assigned.

**Comment by devkapilbansal** [comment]
Removing `Status: Available` as there is already `Work in Progress` PR
