### ISSUE TITLE
Add link to quality assurance tables to Swagger UI docs.

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#762]
## Description
As a contributor,
I need to know about test cases for each feature implemented on the backend.
so that I can easily improve code by creating issues, PRs, etc.

You could add the link to the quality assurance test cases found [here](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md). So that contributors know about test cases each feature failed or passed.

#### Note: This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. Please free to check out other issues in the meantime. Program website: https://anitab-org.github.io/events/open-source-hack/

## Mocks
Currently, it looks like this:
![mentorship-backend-2](https://user-images.githubusercontent.com/46970368/91462270-a1cd7300-e8a7-11ea-8936-9019ab45885f.PNG)

### Update [Required]
- [ ] Add link to quality assurance tables.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hour

**Comment by anishghimire603** [comment]
Can a beginner in do this if yes then I will be attending QA open sessions on Tuesdays at 1pm EST and then learn from there and can contribute to this....?

**Comment by utkzas** [comment]
hey can you assign this issue to me?

**Comment by paritoshsinghrahar** [comment]
@anishghimire603 Yes it's for First-Timers only. These sessions help you clear doubts.
But I can guide you. You need to set up the environment refer: https://github.com/anitab-org/mentorship-backend -->README.
Then read [community guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).
If still have doubts ping me here.

@utkzas @anishghimire603 Since, we decided to not assign issues based on any comments before September 1 to make it fair for everyone. Please do tell me if you are interested, now.

Remember it's FCFS (First Come First Serve) starting September 1st.

**Comment by anishghimire603** [comment]
@paritoshsinghrahar assign this to me.

**Comment by paritoshsinghrahar** [comment]
@anishghimire603 yes! For sure!

Please setup up the dev environment and read community guidelines before proceeding.

**Comment by anishghimire603** [comment]
@paritoshsinghrahar haha sorry to ask is my task related to #763 and where can I find quality assurance tables?

**Comment by paritoshsinghrahar** [comment]
You could add the link to the quality assurance test cases found [here](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md). So that contributors know about test cases each feature failed or passed.

@anishghimire603 it's mentioned in Issue description.
--> https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md

**Comment by paritoshsinghrahar** [comment]
It's similar to an extent. @anishghimire603

**Comment by anishghimire603** [comment]
below this like this right??
For more information about the project here's a link to our wiki guide: https://github.com/anitab-org/mentorship-backend/wiki
The link to the quality assurance test cases found <a href="https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md">here</a>.

**Comment by anishghimire603** [comment]
@paritoshsinghrahar how to create virtual environment to run the app? in windows

**Comment by anishghimire603** [comment]
@paritoshsinghrahar do I need to delete the .env files which I have created for virtualenv? and I have created .bashrc files for virtualenvwrapper ? and then I need to push it?

**Comment by anishghimire603** [comment]
@paritoshsinghrahar I have just opened a PR #818  is that okay have a look please.

**Comment by paritoshsinghrahar** [comment]
@anishghimire603 I reviewed it. It would be great if you can add description to what are quality assurance tables.

**Comment by pallavisavant** [comment]
if still available can i take up this issue..Thanks.

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by paritoshsinghrahar** [comment]
@sujal111 @pallavisavant it's done.
