### ISSUE TITLE
Update the description of the app on the Swagger UI docs

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#763]
## Description
As a contributor,
I need some more description on Swagger docs,
so that I can easily understand what the app is about.

Currently, the Swagger docs don't mention:
1. [ios client repository](https://github.com/anitab-org/mentorship-ios) for the Mentorship System.
2. [flutter repository](https://github.com/anitab-org/mentorship-flutter) for the Mentorship System.
3. For new contributors, it would be helpful to link [Using Backend Swagger UI](https://github.com/anitab-org/mentorship-backend/wiki/Using-Backend-Swagger-UI) to Swagger docs.

4. Try to put all clients in one place like:
Clients: [android](https://github.com/anitab-org/mentorship-android) | [ios](https://github.com/anitab-org/mentorship-ios) | [flutter](https://github.com/anitab-org/mentorship-flutter)

#### Note: This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. Please free to check out other issues in the meantime. Program website: https://anitab-org.github.io/events/open-source-hack/

## Mocks
Currently, it looks like this:
![mentorship-backend-2](https://user-images.githubusercontent.com/46970368/91462270-a1cd7300-e8a7-11ea-8936-9019ab45885f.PNG)

### Update [Required]
- [ ] Add a link to ios client repository
- [ ] Add a link to flutter repository
- [ ] Add a link to Using Swagger UI
- [ ] Put all clients in one place

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hour

**Comment by SanketDG** [comment]
FYI, there is also https://github.com/anitab-org/mentorship-android

**Comment by paritoshsinghrahar** [comment]
> FYI, there is also https://github.com/anitab-org/mentorship-android

It's already mentioned in the mocks.

**Comment by SanketDG** [comment]
Let's try to put all clients under one place.

**Comment by rak108** [comment]
Hi! I would like to do this, could you please assign this task to me?

**Comment by paritoshsinghrahar** [comment]
> Let's try to put all clients under one place.

Sure.

**Comment by paritoshsinghrahar** [comment]
@rak108 I have assigned you. I hope you have set up the environment and read [community guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).

Happy Coding.  :smiley:

**Comment by yash2189** [comment]
Can I work on this @paritoshsinghrahar ?

**Comment by rak108** [comment]
> @rak108 I have assigned you. I hope you have set up the environment and read [community guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).
> 
> Happy Coding.

Thanks @paritoshsinghrahar ! When it comes to the issue at hand, I've put the links one after another in a similar format as the example given.
As in,
Clients:
Android: WWW
Flutter: XXX
ios: YYY

Is this fine?

**Comment by rak108** [comment]
> > @rak108 I have assigned you. I hope you have set up the environment and read [community guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).
> > Happy Coding.
> 
> Thanks! When it comes to the issue at hand, I've put the links one after another in a similar format as the example given.
> As in,
> Clients:
> Android: WWW
> Flutter: XXX
> ios: YYY
> 
> Is this fine?

@paritoshsinghrahar

**Comment by paritoshsinghrahar** [comment]
Ideally, instead of explicitly putting links to the repository. Try making hyperlinks.

Android: https://github.com/anitab-org/mentorship-android

try:
[Android](https://github.com/anitab-org/mentorship-android)

And put it under one topic. It's more readable.

**Comment by paritoshsinghrahar** [comment]
> Can I work on this @paritoshsinghrahar ?

Sorry, it has already been assigned.

**Comment by rak108** [comment]
> Ideally, instead of explicitly putting links to the repository. Try making hyperlinks.
> 
> Android: https://github.com/anitab-org/mentorship-android
> 
> try:
> [Android](https://github.com/anitab-org/mentorship-android)
> 
> And put it under one topic. It's more readable.

okay i'll try doing this and get back to you.

**Comment by rak108** [comment]
> Ideally, instead of explicitly putting links to the repository. Try making hyperlinks.
> 
> Android: https://github.com/anitab-org/mentorship-android
> 
> try:
> [Android](https://github.com/anitab-org/mentorship-android)
> 
> And put it under one topic. It's more readable.

@paritoshsinghrahar hey,
I did this, shall I do this for all the other links as well, such as main repo link, wiki link too?

**Comment by paritoshsinghrahar** [comment]
Umm, yes, and no.
The explanation is necessary like:

For additional information go to wiki guide: [wiki](https://github.com/anitab-org/mentorship-backend/wiki) 

#### Something like above. @rak108

**Comment by rak108** [comment]
> Umm, yes, and no.
> The explanation is necessary like:
> 
> For additional information go to wiki guide: [wiki](https://github.com/anitab-org/mentorship-backend/wiki)
> 
> #### Something like above. @rak108

Okay cool thanks! I've created a pull request, Kindly check the same.

**Comment by anishghimire603** [comment]
@rak108 your and my task looks similar can you help me on #762 I have to Add link to quality assurance tables to Swagger UI docs.

**Comment by rak108** [comment]
Hey! Kindly check out my latest PR for the same #817

**Comment by rak108** [comment]
> @rak108 your and my task looks similar can you help me on #762 I have to Add link to quality assurance tables to Swagger UI docs.

did you get it?

**Comment by anishghimire603** [comment]
> > @rak108 your and my task looks similar can you help me on #762 I have to Add link to quality assurance tables to Swagger UI docs.
> 
> did you get it?

yeah I opened my PR #818 thank you @rak108

**Comment by pallavisavant** [comment]
if this is still available can i take up this issue??

**Comment by paritoshsinghrahar** [comment]
It's done. @pallavisavant
