### ISSUE TITLE
Remove swagger.json from docs folder

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#764]
## Description
As a contributor,
I need an up-to-date [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file,
so that I can refer to the urls, responses and can search them easily. But, since this [link](http://mentorship-backend-temp.herokuapp.com/swagger.json) serves the purpose we no longer need to update [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) and can remove it.

## Mocks
The [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file isn't up-to-date and alternatively this [link](http://mentorship-backend-temp.herokuapp.com/swagger.json) serves the purpose if incase someone needs it.

### Update [Required]
- [ ] Delete the [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.1 hour

**Comment by SHITIZ-AGGARWAL** [comment]
hello ,I would like to work on this

**Comment by utkzas** [comment]
hey, can i work on this issue?

**Comment by SHITIZ-AGGARWAL** [comment]
Hello @PrashanthPuneriya  since OSH has begun ,i would like to work on this
I am new to open source so please guide me 
Really excited to work with the organisation

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by priyanshuone6** [comment]
Hey can you assign this issue to me, I would like to work on it

**Comment by PrashanthPuneriya** [comment]
@SHITIZ-AGGARWAL Assigning you! Happy coding :)

**Comment by PrashanthPuneriya** [comment]
@Abjcodes @priyanshuone6 Sorry! We assign on the basis of First-Come-First-Serve. If one fails to deliver a valid PR then others will be assigned this issue. Meanwhile checkout other issues :)

**Comment by SHITIZ-AGGARWAL** [comment]
@PrashanthPuneriya  thanks a lot for the opportunity
