### ISSUE TITLE
Perform manual testing and report PUT /user API

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#767]
## Description

As a tester,
I need to test PUT /user API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#update-user](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#update-user)

### Update [Required]
- [ ] Test PUT /user API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by ksraj123** [comment]
I would like to work on this for Open Source Hack. Thanks

**Comment by yash2189** [comment]
can I work on this @gaurivn ?

**Comment by yash2189** [comment]
@gaurivn  could you please tell me what is the term TBD mentioned under PUT /user in the Quality Assurance Test case?

Also should I test PUT /user/change password API as well?

**Comment by yash2189** [comment]
@gaurivn  Please review my PR related to the same, thanks.

**Comment by yash2189** [comment]
Can you please review my PR @gaurivn ?#809

**Comment by gaurivn** [comment]
Sure, will review, and get back to you in some time.

**Comment by yash2189** [comment]
Thanks @gaurivn

**Comment by yash2189** [comment]
@gaurivn I have some queries that I have asked on the PR #809. Will you please have a look at the same?
Thank you

**Comment by yash2189** [comment]
@gaurivn can you please have a look at my doubt I've mentioned on the PR #809

**Comment by gaurivn** [comment]
> @gaurivn can you please have a look at my doubt I've mentioned on the PR #809

@yash2189, no need to ping here, when you ping from the PR too, I'll see it... I'll get back to you in a while.

**Comment by yash2189** [comment]
@gaurivn Please review my new PR #850
