### ISSUE TITLE
Design UI for email confirmation

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#768]
## Description
As a developer,
I need to design a specific UI for email confirmation,
so that I can improve the current UI.

### Context
When a user registers they receive an email confirmation (account activation) link in the email ([current template](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_confirmation.html)). This UI should be designed following [AnitaB.org Branding Guidelines](https://drive.google.com/file/d/1QyQrNfGMa5e-3D0obDAGnkHZ1u7nhZ87/view).

## Mocks
Current confirmation email
![msemailconf](https://user-images.githubusercontent.com/48416306/91586688-c6d4eb00-e966-11ea-9bd4-815c60c3b907.png)

### Update [Required]
- [ ] Design a specific UI for email confirmation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by SHITIZ-AGGARWAL** [comment]
hello @gaurivn i would like to contribute once the event starts

**Comment by gaurivn** [comment]
Hi @SHITIZ-AGGARWAL, sure just comment here / claim the issue on Sept 1st and will assign you :)

**Comment by SHITIZ-AGGARWAL** [comment]
Hello @gaurivn ,since OSH has begun i would like to work on this issue,
I am new to Open Source so please guide
Really excited to work with the organisation

**Comment by SHITIZ-AGGARWAL** [comment]
Thanks for giving me this opportunity
I created a basic template please tell if any changes required 
_____________________________________

<p>Hi {{ user_name }},</p>
<br>
<p>Welcome to Mentorship System!</p>
<br>
<p>Thanks for signing up for Mentorship System account , We're thrilled to have you!</p>
<p>To get started, please click the link below to verify that we've got your correct email address.</p>
<br>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<p>The activation link will be active for {{ threshold // 86400 }} days.</p>
<br>
<p>If you have any trouble with your account, you can always email us at  </p>
<p><i>In Systerhood,</i></p>
<p>Systers Open Source</p>
<p><a href="http://systers.io/">http://systers.io/</a></p>

**Comment by SHITIZ-AGGARWAL** [comment]
@gaurivn Thanks for giving me this opportunity
I created a basic template please tell if any changes required 
* should I add email address for account related problems ,if yes can you please provide me the email address *
_____________________________________

<p>Hi {{ user_name }},</p>
<br>
<p>Welcome to Mentorship System!</p>
<br>
<p>Thanks for signing up for Mentorship System account , We're thrilled to have you!</p>
<p>To get started, please click the link below to verify that we've got your correct email address.</p>
<br>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<p>The activation link will be active for {{ threshold // 86400 }} days.</p>
<br>
<p>If you have any trouble with your account, you can always email us at  ____ </p>
<p><i>In Systerhood,</i></p>
<p>Systers Open Source</p>
<p><a href="http://systers.io/">http://systers.io/</a></p>

**Comment by jatinjain001** [comment]
i would like to work on  it please assign to me

**Comment by PriyanshuAgarwal27** [comment]
I would like to work on this issue. Can you assign me this issue?

**Comment by sanjibansg** [comment]
Do  assign the issue  to me if available.

**Comment by devkapilbansal** [comment]
@PrashanthPuneriya @SanketDG @vj-codes can this issue be assigned to multiple persons? If yes, do assign this to me

**Comment by PrashanthPuneriya** [comment]
A PR has been already created. So, I don't think this issue is available anymore
