### ISSUE TITLE
Design UI for Mentorship relation accepted

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#769]
## Description
As a developer,
I need to design a specific UI for Mentorship relation accepted,
so that I can improve the current UI.

### Context
When user B accepts a mentorship relation request from user A, the latter will receive an email stating Mentorship relation accepted by user B ([current template](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/mentorship_relation_accepted.html)). This UI should be designed following [AnitaB.org Branding Guidelines](https://drive.google.com/file/d/1QyQrNfGMa5e-3D0obDAGnkHZ1u7nhZ87/view).

## Mocks
Currently, Mentorship Relation accepted
![mrelationaccept](https://user-images.githubusercontent.com/48416306/91587662-241d6c00-e968-11ea-9090-d0c3da442e89.png)

### Update [Required]
- [ ] Design a specific UI for Mentorship relation accepted

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by vj-codes** [comment]
Heyy @gaurivn I would like to work on this for OSH!

**Comment by gaurivn** [comment]
Hi @vj-codes, glad to know you're interested in working on this issue. This issue is not made available / cannot be assigned yet for OSH, it will be made available once Open Source Hack starts on September 1st, 2020. Do come back here on Sept 1st and I'll be more than happy to assign you :)

**Comment by vj-codes** [comment]
@gaurivn ahh no I meant for OSH only and won't mind to be assigned after 1st.Just commented as issues are assigned on first come first serve right?

**Comment by gaurivn** [comment]
Yes, I meant please do comment here when the program starts on Sept 1st as the issues cannot be claimed beforehand.

**Comment by vj-codes** [comment]
@PrashanthPuneriya @anna4j @gaurivn I would like to work on this.

**Comment by gaurivn** [comment]
Here you go

**Comment by muskanvk** [comment]
@vj-codes there is no update from someone you assigned this issue to. Since, I already have worked on this, can you please let me know from gaurivn if she has worked on it. If not, then please assign it to me

**Comment by muskanvk** [comment]
My bad ! However I submitted a PR for this, it doesn't take much of time. 
 It's already the 3rd day. You can also work on it :)
Can anyone else look into it apart from the person who just closed it ? The solution's been proposed and I think it wont be good if the same adds up as a PR to someone else. 
The time bracket of 3 days is soon going to be over. :) @gaurivn

**Comment by vj-codes** [comment]
@muskanvk different contributors comeup with different ideas for UI issues and I assure that yours won't be 'copied' by someone.
The task is pretty simple , comment first get assigned and then send a PR.
Also this issue is about **redesigning** and not just changing format of current template.

**Comment by gaurivn** [comment]
> My bad ! However I submitted a PR for this, it doesn't take much of time.
> It's already the 3rd day. You can also work on it :)
> Can anyone else look into it apart from the person who just closed it ? The solution's been proposed and I think it wont be good if the same adds up as a PR to someone else.
> The time bracket of 3 days is soon going to be over. :) @gaurivn

Hi @muskanvk, since this issue is already assigned, it is not available at the moment for others to work on, only the assignee's PR will be considered for the time being, all other PRs if any won't be considered / will be closed. Regarding the plagiarism, yes it will be checked for all OSH issues.

**Comment by PrashanthPuneriya** [comment]
> It's already the 3rd day

We need to ask @vj-codes for an update. If @vj-codes is unable to deliver a valid PR then, we will consider assigning you and review your PR. Till then, your PR is not valid.
Please follow the community guidelines @muskanvk. Please feel free to grab other issues :)

**Comment by vj-codes** [comment]
@PrashanthPuneriya I made a PR already:)

**Comment by jatinjain001** [comment]
I want to work on this,please assign me to this ,Thank you

**Comment by gaurivn** [comment]
Hi @jatinjain001, this issue is already assigned and a PR has been sent for the same. Pls do check out for other issues, will assign.
