### ISSUE TITLE
Design UI for Mentorship relation request

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#770]
## Description
As a developer,
I need to design a specific UI for Mentorship request sent,
so that I can improve the current UI.

### Context
When user A sends a mentorship relation request to user B, the latter receives an email conveying the same ([current template](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_relation_request.html)). This UI should be designed following [AnitaB.org Branding Guidelines](https://drive.google.com/file/d/1QyQrNfGMa5e-3D0obDAGnkHZ1u7nhZ87/view).

## Mocks
Current mentorship relation request email
![mrelationreq](https://user-images.githubusercontent.com/48416306/91589292-85463f00-e96a-11ea-8c9f-62421f704a68.png)

### Update [Required]
- [ ] Design a specific UI for mentorship relation request

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by titiksha01** [comment]
@gaurivn hello, I would like to work on this issue

**Comment by gaurivn** [comment]
Hi @titiksha01, glad to know you're interested. Since OSH starts on September 1st, 2020, do comment here / claim the issue on that day and I'll assign you

**Comment by ksraj123** [comment]
I would like to work on this as a part of opensource hack if no one else is working on it already. Commenting as its 1 sep now so please assign this issue. Thanks

**Comment by titiksha01** [comment]
Hi, I would like to work on this issue. I was told to comment on 1st September. Thank you...

**Comment by gaurivn** [comment]
> I would like to work on this as a part of opensource hack if no one else is working on it already. Commenting as its 1 sep now so please assign this issue. Thanks

Assigning

**Comment by gaurivn** [comment]
> Hi, I would like to work on this issue. I was told to comment on 1st September. Thank you...

Sure, assigning

**Comment by titiksha01** [comment]
@gaurivn Thank you for the opportunity

**Comment by titiksha01** [comment]
#801 
@gaurivn Please review this.

**Comment by PrashanthPuneriya** [comment]
@ksraj123 Unassigning you from this issue. Since, you have been assigned to multiple issues and also since, @titiksha01 created a PR for it :)

**Comment by jatinjain001** [comment]
I would like to work on it,Thank you

**Comment by Rasikamurali** [comment]
I would like to work on it!

**Comment by titiksha01** [comment]
@gaurivn @PrashanthPuneriya Pls Review my pr and let me know if any changes are required.  Thank You

**Comment by titiksha01** [comment]
@gaurivn @SanketDG  Pls confirm this if i am supposed to edit the HTML file or just design the UI and submit png as pr or both.? Thank you...

**Comment by devkapilbansal** [comment]
@SanketDG @titiksha01 why there are two pull requests for same issue?

**Comment by titiksha01** [comment]
> @SanketDG @titiksha01 why there are two pull requests for same issue?

I was supposed to close the previous one. I have done it now.
