### ISSUE TITLE
Create a reporting_guidelines.md

### ISSUE THREAD

**Issue by sanchibansal340** [anitab-org/mentorship-backend#772]
## Description
As a user, I need to modify the reporting guidelines, so that I can seek for help when necessary.
1. The content should be consistent with [Reporting Guidelines](https://github.com/anitab-org/mentorship-flutter/blob/develop/.github/reporting_guidelines.md)
2. And then update the code of conduct link in **Readme.md**>>Contributing section.
3. Add the updated Reporting Guidelines file to doc folder.

## Acceptance Criteria
- [ ] Update [Required]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

## Note
This issue will be assigned from September 1, 2020.

**Comment by atharwa-24** [comment]
I would like to work on this!!!

**Comment by rutujadhanawade** [comment]
I would like to work on this

**Comment by niyati-n** [comment]
i would like to work on this

**Comment by sanchibansal340** [comment]
Comment on 1st September and I will assign it to you.

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by bhumikasharma29** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Hyper-Matrix** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by atharwa-24** [comment]
Would like to work on this one~ OSH

**Comment by sanchibansal340** [comment]
@Hyper-Matrix I am assigning this to you.

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you please assign me this issue? I'm a first time contributor.

**Comment by atharwa-24** [comment]
if the issue is not assigned yet i will like to get assigned!

**Comment by heyanurag** [comment]
Can I work on this issue? I am a first time contributor.

**Comment by anishghimire603** [comment]
@sanchibansal340  Will you assign me this issue please?

**Comment by heyanurag** [comment]
I would still like to try this.

**Comment by Tushika25** [comment]
I would like to work on this issue. Thank You!!!

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by vj-codes** [comment]
@Hyper-Matrix how's the PR going? Do update after every 3 days incase it's taking long otherwise issue will be assigned to person next

**Comment by sanchibansal340** [comment]
@atharwa-24 Would you like to work on this issue?

**Comment by rutujadhanawade** [comment]
I would like to work on this issue.

**Comment by dadheech-vartika** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by sanchibansal340** [comment]
@96RadhikaJadhav would you like to work on this issue?

**Comment by atharwa-24** [comment]
I would like to work @sanchibansal340

**Comment by atharwa-24** [comment]
if its not assigned to anyone yet

**Comment by sanchibansal340** [comment]
Okay I am assigning it to you @atharwa-24
