### ISSUE TITLE
Clean up the swagger to follow the same convention throughout the page

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#774]
## Description
As a contributor,
I need proper convention used in Swagger,
so that it doesn't appear oddly.

## Mocks
![image](https://user-images.githubusercontent.com/42068010/91643860-85226e00-ea54-11ea-8a5a-a5dbeb67b4e3.png)
As one can easily see that, capital letters are not used when required and full stops are redundant at few places. e.g. relations begin with small letter unlike others and the last two have full-stops whereas others don't.

### Update [Required]
- [ ] Start every sentence with capital.
- [ ] Remove full stops to follow same convention.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hour if you don't know where to look.
15 mins if you know where to look.

**Comment by vj-codes** [comment]
@PrashanthPuneriya there's inconsistency in the screen shot, relations begin with small letter unlike others and the last two have full-stops whereas others don't. 
As a first timer I would follow the ss exactly and to avoid confusion could you please update it.

**Comment by ksraj123** [comment]
I would like to work on this for open source hack. Thanks

**Comment by ksraj123** [comment]
I would like to work on this as a part of opensource hack. Commenting again as its 1 sep now so please assign this issue. Thanks

**Comment by gitpurva** [comment]
I would like to work on it. Can you assign me this issue.

**Comment by priyanshuone6** [comment]
Hey can you assign this issue to me, I would like to work on it

**Comment by PrashanthPuneriya** [comment]
Assigning you this issue @ksraj123 :)

**Comment by PrashanthPuneriya** [comment]
@gitpurva @priyanshuone6 We assign issues on the basis of First-Come-First-Serve. Hope you understand :)
@gitpurva Also, you have been assigned to #726 So, you can no longer claim this issue since it's first-timers only.

**Comment by PrashanthPuneriya** [comment]
@ksraj123 Please don't hijack all the issues. Work on one issue then claim other. Unassigning you from this issue @ksraj123. Which issue do you like to work on? #774 #787 #788

**Comment by priyanshuone6** [comment]
Can I work on it?

**Comment by PrashanthPuneriya** [comment]
This is a first-timers-issue @priyanshuone6. You have already created a PR for #736. Check other issues which aren't first-timer labelled.

**Comment by aditya2499** [comment]
Can I work on it?

**Comment by PrashanthPuneriya** [comment]
Sure @aditya2499. Assigning you this issue :)

**Comment by aditya2499** [comment]
@PrashanthPuneriya I have open a PR #813 .
