### ISSUE TITLE
Capturing Mobile Phone number and WhatsApp  number from User

### ISSUE THREAD

**Issue by pbgurav** [anitab-org/mentorship-backend#776]
So for such attributes we can have privacy settings like
1. Never - Dont display to 
**Is your feature request related to a problem? Please describe.**
In India, not everyone has an email id. Hence the reach will be limited.

Not everyone checks emails regularly, while sms and Whatsapp are checked more often.

**Describe the solution you'd like**

We need to capture mobile number for SMS and Whatsapp number for this.

1. It will help to reach a wider range of audience eg. users that dont use email.

2. SMS and Whats App messages are checked more regularly than emails.

Its possible that many users would like this setting to be governed by privacy
So for such attributes we can have privacy settings like,
1. Never - Dont display to anyone. Only use for personal notifications
2. Private- Display only to connected users after accepting of request
3. Public within the Mentorship system - i.e. only to registered users.
**Describe alternatives you've considered**

Push notifications. However, users can disable them.

**Additional context**

**Comment by vj-codes** [comment]
@pbgurav please follow the issue template and the issue will be reviewed/approved.Thanks!

**Comment by pbgurav** [comment]
> @pbgurav please follow the issue template and the issue will be reviewed/approved.Thanks!

Updated as per template

**Comment by abhinav72610** [comment]
@pbgurav Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by vj-codes** [comment]
@abhinav72610 This isn't an OSH issue, please look at issues with the label `Open Source Hack`

**Comment by abhinav72610** [comment]
@vj-codest thanks for the suggestion i forgot to check the label ..

**Comment by isabelcosta** [comment]
@pbgurav thank you for suggesting enhancements to this app.
However, this does not seem as a priority for an MVP that we are trying to work towards. So the idea would be, the first batch of people using this, such as Beta testers, they would require an email. And for example, everyone on Zulip has an email, for now, the email is mostly to login and confirm email. The email notifications are nice to have, that you can still check on the app.
I will close this for now :) Feel free to discuss more ideas if you wish through issues or [Zulip](https://anitab-org.zulipchat.com/).
