### ISSUE TITLE
Standalone Mentor/Mentee registration page instead of Google forms.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#779]
**Description**
As a contributor I want you to build a separate registration page instead of Google forms being used for registration.

**Acceptance Criteria**

- [ ] Update [Required]

Definition of Done

- [ ] Approval from 1 mentor.

- [ ] All of the required items are completed.

**Estimation**
   [2+] hours

**Note**
This issue will be assigned from September 1st 2020

**Comment by vj-codes** [comment]
@yashasvimisra2798 please follow the issue template and then the issue will be approved/reviewed.Thanks!

**Comment by bhumikasharma29** [comment]
What all should this registration page include?

**Comment by Meenalsolanki220397** [comment]
what are the mandatory labels for this form ?

**Comment by abhinav72610** [comment]
@yashasvimisra2798 Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by abhinav72610** [comment]
@yashasvimisra2798 can you help me with all the fields the registration page should include??

**Comment by vj-codes** [comment]
@yashasvimisra2798 @PrashanthPuneriya What is this issue about?I don't think mentorship-system deals with Gforms anywhere in app

**Comment by abhinav72610** [comment]
@vj-codes i too have the same doubt ..can you help me with current registration process ..Are we using flask-wtf forms or google forms or anything else for registration

**Comment by vj-codes** [comment]
@abhinav72610 for registration of mentorship-system, you need to sign up in the apk on your device and just confirm from the email . Do you have the apk?
@yashasvimisra2798 what is this abt exactly ?
@PrashanthPuneriya any idea?

**Comment by PrashanthPuneriya** [comment]
@yashasvimisra2798 @vj-codes @abhinav72610 
To my knowledge this issue is invalid. Even if we use google forms for registration (we don't) the issue should be raised in the frontend. This is the backend side of the project.

**Comment by yashasvimisra2798** [comment]
@vj-codes @abhinav72610 @PrashanthPuneriya My bad, I thought just like the other registrations for any activity in AnitaB.org there are google forms, here also some of them. So I thought of creating this issue.

**Comment by vj-codes** [comment]
Closing since issue is no longer relevent.
