### ISSUE TITLE
Spelling mistake in the subtitle of the documentation section.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#780]
**Description**
There is a spelling mistake in the Documentation section of the Readme it is in the first line itself, identify the word and correct the spelling.

**Acceptance** **Criteria**

- [ ] update required

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 1 mentor.

**Estimation**
   5 minutes.

**Note**
This issue will be assigned from September 1, 2020.

**Comment by vj-codes** [comment]
@yashasvimisra2798 please follow the issue template and then the issue will be approved/reviewed.Thanks!

**Comment by rutujadhanawade** [comment]
I would like to work on this. Please assign this to me on 1st September.

**Comment by yashasvimisra2798** [comment]
@rutujadhanawade please comment on September 1 so that I can assign the issue to you

**Comment by visthruth21** [comment]
Hi , I would like to work on this issue , can you suggest me ways to get started

**Comment by niyati-n** [comment]
@yashasvimisra2798 @vj-codes 
Please assign this issue to me.

**Comment by bhumikasharma29** [comment]
Please assign this to me for OSH.

**Comment by blackcrabb** [comment]
@yashasvimisra2798 please assign it to me

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by Hyper-Matrix** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue?

**Comment by vanditkhurana** [comment]
I would like to work on this issue as a part of OSH. Please assign me this issue. I will be highly thankful.

**Comment by niyati-n** [comment]
@vj-codes please assign it to me as it is a 5 minutes task, i know i am already assigned one .

**Comment by vj-codes** [comment]
@blackcrabb This is a `first timers only ` issue and you're already working on other issue thus no longer eligible.

**Comment by vj-codes** [comment]
@rutujadhanawade assigning you 
Happy documenting!

**Comment by 96RadhikaJadhav** [comment]
Please assign it to me as a part of OSH. Thanks!!

**Comment by Tushika25** [comment]
Please assign it to me as a part of OSH!!!

**Comment by jatinjain001** [comment]
Please assign to me I am  new In open source contribution

**Comment by rutujadhanawade** [comment]
#797  @vj-codes I have made a PR that will close this issue. Kindly review and merge it.

**Comment by sreelekha901** [comment]
Can you please assign this issue to me?

**Comment by Mahnoor123-Fatima** [comment]
Can you assign this issue to me?
