### ISSUE TITLE
In the Set Up and Run section write on how to set up for Linux and Windows separately.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#781]
**Description**
As a contributor, I need you to update the setup and run section and add two different sections on how to setup and run the project in  Windows and Linux respectively.  

**Acceptance Criteria**

- [ ] Update [Required]

**Definition of Done**

- [ ] All of the required items are completed.

- [ ]  Approval by 1 mentor.

**Estimation**
    1 hr

**Note**
This issue will be assigned from September 1, 2020.

**Comment by vj-codes** [comment]
@yashasvimisra2798 Please follow the issue template , and then this issue will be approved/reviewed.Thanks!

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by ksraj123** [comment]
I would like to work on this as a part of opensource hack if no one else is working on it already. Commenting as its 1 sep now so please assign this issue. Thanks

**Comment by Abjcodes** [comment]
I have submitted a PR. Kindly review it.

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Im a first time contributor. Could you please assign this issue to me?

**Comment by AparnaJuhi** [comment]
This is the first  time I am participating in any Open source. And I will be grateful if you assign me this issue!!

**Comment by yashasvimisra2798** [comment]
Currently, we are assigning each issue to one person only. @96RadhikaJadhav @AparnaJuhi I hope you understand :)
