### ISSUE TITLE
In the documentation add a section displaying versions of the frameworks and extensions use.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#782]
**Description**
In the Readme of the repository, in the documentation section add the versions of the frameworks and extensions used.

**Acceptance Criteria**

- [ ]  Update [Required]

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 2 mentors.

**Estimation**
   1 hr

**Note**
This issue will be assigned from September 1, 2020.

**Comment by vj-codes** [comment]
@yashasvimisra2798 please follow the issue template and then the issue will be approved/reviewed.Thanks!

**Comment by bhumikasharma29** [comment]
I would like to work on this. I am a first time contributor please guide me.

**Comment by bhumikasharma29** [comment]
Please assign this to me for OSH.

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by yashasvimisra2798** [comment]
@bhumikasharma29 I have assigned you the issue, as you can see that the Readme file does not contain the versions of frameworks used. I want you to add those version in front of their names. For further guidance you can join the zulip chat.
All the best for your first contribution.

**Comment by bhumikasharma29** [comment]
Thank you @yashasvimisra2798 .

**Comment by bhumikasharma29** [comment]
Please review this. @yashasvimisra2798

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part OSH. Could you please assign it to me?
I'm a first time contributor.

**Comment by yashasvimisra2798** [comment]
@bhumikasharma29 yes I will review it and get back to you

**Comment by yashasvimisra2798** [comment]
@96RadhikaJadhav we are assigning 1 issue per person right now.

**Comment by jatinjain001** [comment]
I would like to work on it.Could you assign it to me

**Comment by jatinjain001** [comment]
I haven't get any issue for solve I am new in OSH

**Comment by alivabasa** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by sanjibansg** [comment]
Do assign the issue to me if available.

**Comment by isabelcosta** [comment]
As discussed on weekly session w/ @vj-codes we'll close this since this information can be easily accessed from the `requirements.txt` file.
