### ISSUE TITLE
Fix the links for "Run tests" under "Setup and Run" in the Table of Contents of the Readme.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#784]
**Description**
The "Table of Contents" section in the Readme has the "Run Tests" link not working. It shows error 404.
As a contributor I want you to fix this issue.

**Acceptance Criteria**

- [ ] Update required

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 1 mentor.

**Estimation**
   atmost 30 minutes

**Note**
This issue will be assigned  September 1st, 2020 onwards.

**Comment by vj-codes** [comment]
@yashasvimisra2798 please follow the issue template and then the issue will be approved/reviewed.Thanks!

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by Abjcodes** [comment]
I have submitted a pull request. Kindly review it.

**Comment by 96RadhikaJadhav** [comment]
I would like to work on this issue as a part of OSH. Could you please assign it to me.

**Comment by HeroicHitesh** [comment]
I would like to work on this issue under OSH. Please assign me this issue when it's free.

**Comment by jatinjain001** [comment]
I would like to work on this issue under OSH assign it to me

**Comment by divyaaa123** [comment]
Can I work on this issue?

**Comment by PriyanshuAgarwal27** [comment]
I would like to work on this issue. Can you assign me this issue?

**Comment by alivabasa** [comment]
I would like to work on this. Can you please assign this to me?
