### ISSUE TITLE
A blog talking and/or teaching about Flask-SQAlchemy and how the Mentorship Backend uses it with example user models.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#786]
**Description**
As a contributor, I need you to come up with a blog or a file in .md teaching about Flask-SQAlchemy and how it is used in this project. An explanatory report will be appreciated not only teaching from the basics but also describing it's full usage here.

**Acceptance Criteria**

- [ ] Update required

- [ ] Submit as a markdown file

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 2 mentors.

**Estimation**
4 to 5 hours

**Note**
This issue is can be contributed to only from 1st September when Open Source Hack starts.

**Comment by ashwinijha6** [comment]
@yashasvimisra2798 I would like to work on this issue as an OSH participant

**Comment by gitpurva** [comment]
I would like to work on this issue. Can you assign me this issue?

**Comment by annu12340** [comment]
I am interested to work on this issue. Could you please assign it to me

**Comment by yashasvimisra2798** [comment]
Since it was on first come first serve basis, @ashwinijha6 has been assigned the issue

**Comment by yashasvimisra2798** [comment]
@ashwinijha6 any updates on your work?

**Comment by Aditiwebd** [comment]
I want to work on this issue please assign it to me for osh.

**Comment by yashasvimisra2798** [comment]
@ashwinijha6 any updates?

**Comment by ashwinijha6** [comment]
Sorry @yashasvimisra2798  I was working on an issue for the vms project could u give me some time pls?

**Comment by yashasvimisra2798** [comment]
@ashwinijha6 how much time do you require to complete this issue?

**Comment by ashwinijha6** [comment]
Atleast a day @yashasvimisra2798

**Comment by yashasvimisra2798** [comment]
Ok @ashwinijha6

**Comment by ashwinijha6** [comment]
Thanku @yashasvimisra2798

**Comment by pallavisavant** [comment]
can i work on issue,if not taken can you please assign it to me.

**Comment by ashwinijha6** [comment]
@yashasvimisra2798 should I make a .md file or use medium for blog writing ?

**Comment by yashasvimisra2798** [comment]
.md file @ashwinijha6

**Comment by vj-codes** [comment]
@ashwinijha6 how's the PR going?

**Comment by ashwinijha6** [comment]
@vj-codes working on it

**Comment by ashwinijha6** [comment]
> .md file @ashwinijha6

@yashasvimisra2798 I had some doubts related to this could we discuss on zulip?

**Comment by ashwinijha6** [comment]
> > .md file @ashwinijha6
> 
> @yashasvimisra2798 I had some doubts related to this could we discuss on zulip?

I see u are not subscribed to the #mentorship-system stream

**Comment by yashasvimisra2798** [comment]
Yes @ashwinijha6 I'll subscribe to it, however, you can tell me what problem you have here itself. You just have to see how Flask-SQLAlchemy has been used here and then write an article out of it.

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by ashwinijha6** [comment]
> Yes @ashwinijha6 I'll subscribe to it, however, you can tell me what problem you have here itself. You just have to see how Flask-SQLAlchemy has been used here and then write an article out of it.

Actually before making a pull request I just wanted to know certain things
This will be the Structure of the .md file
1. Flask-SQLalchemy
2. SqlAlchemy
3. Requirements
4. Create a minimal application
5. Usage in mentorship-backend
Should I mention the API part?
Is this ok? Should I also explain the installation of flask & flask-sqlalchemy separately ?
Or should **pip install -r requirements.txt** be enough?

**Comment by yashasvimisra2798** [comment]
@ashwinijha6 you can carry on with this. I think it would be better if you kind of give a brief introduction of flask-sqlalchemy and give the link of some article where the installation is explained. Then you can carry on with the rest of the things.

**Comment by ashwinijha6** [comment]
@yashasvimisra2798  I was thinking of including this code in the md file & explaining it but I'm getting an error can u help me out with it

Code
![1](https://user-images.githubusercontent.com/45794450/92622068-3f7e6480-f2e2-11ea-8c25-ddba832efd43.JPG)

Error (404 The requested url was not found on the server)
![2](https://user-images.githubusercontent.com/45794450/92622140-58871580-f2e2-11ea-89d2-b65b663e15f1.JPG)

**Comment by ashwinijha6** [comment]
I guess it's an error with **sqlite:///tmp/test.db** what do u think?

**Comment by ashwinijha6** [comment]
> I guess it's an error with **sqlite:///tmp/test.db** what do u think?

I got the error it must be //// instead of ///

**Comment by ashwinijha6** [comment]
@yashasvimisra2798  should I also mention the different sqlalchemy database uri being used for the different configurations?

**Comment by yashasvimisra2798** [comment]
Just, write briefly about them

**Comment by ashwinijha6** [comment]
> Just, write briefly about them

ok

**Comment by ashwinijha6** [comment]
application = create_app(get_env_config()) @yashasvimisra2798 what does this mean this is for the flask app configuration right?

**Comment by yashasvimisra2798** [comment]
Yes

**Comment by ashwinijha6** [comment]
@yashasvimisra2798  I have added the documentation #874 pls review it but my previous commits to mentorship-backend related to some other issue also got commited along with it. What can be done?

**Comment by ashwinijha6** [comment]
@yashasvimisra2798  actually I checked out a branch from the previous branch I was working on

**Comment by ashwinijha6** [comment]
@SanketDG & @yashasvimisra2798 I have created another pull request #894 for the issue #786
I have closed the previous pull request since I messed up with the branches
I have made the changes suggested by @SanketDG.
Pls review my pull request.

**Comment by vj-codes** [comment]
Closing as PR is closed as well
