### ISSUE TITLE
Fix the formats under Models section of the API Frontend 

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#787]
**Description**
![Capture2](https://user-images.githubusercontent.com/54177363/91689447-c49aa880-eb81-11ea-93cf-3861f0d8f550.PNG)
 You can see that Models has a format different from others. As a contributor I want you to fix the format of the Models section.

**Acceptance Criteria**

- [ ] Update [Required]

**Definition of Done**

- [ ] Approval from 1 mentor.

- [ ] All of the required items are completed.

**Estimation**
    30 min

**Note**
The issue will be assigned from 1st September 2020

**Comment by vj-codes** [comment]
@yashasvimisra2798 please follow the issue template and then the issue will be approved/reviewed.Thanks!

**Comment by ksraj123** [comment]
I would like to work on this as a part of opensource hack. Commenting as its 1 sep now so please assign this issue. Thanks

**Comment by gitpurva** [comment]
I would like to work on this . Can you assign me this issue?

**Comment by arjungarg07** [comment]
@yashasvimisra2798 Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by vj-codes** [comment]
@ksraj123 any updates?

**Comment by yashasvimisra2798** [comment]
@ksraj123 may I please have updates on this issue as well as #788

**Comment by pallavisavant** [comment]
Can i take this issue and work on the same if not taken

**Comment by yashasvimisra2798** [comment]
@arjungarg07 do keep me updated about your progress. All the best for your contribution :)

**Comment by Sanchit-Trivedi** [comment]
@yashasvimisra2798 Since arjungarg07 has dropped his assignment I would request you to assign me this issue as I want to take this up as a part of Open Source Hack

**Comment by yashasvimisra2798** [comment]
sure @Sanchit-Trivedi

**Comment by Sanchit-Trivedi** [comment]
@yashasvimisra2798 After 3 hours of investigation I find that this is the way that SWAGGER UI renders models. Attaching the example that I found on their website [https://petstore.swagger.io/](https://petstore.swagger.io/). Flask Restx generates the required swagger.json and could not find a way to make changes to this. Please help out. Thanks
