### ISSUE TITLE
Prettify the formats for all descriptions of JSON Responses under each endpoint in the API Frontend.

### ISSUE THREAD

**Issue by yashasvimisra2798** [anitab-org/mentorship-backend#788]
**Description**
As a contributor I want you to prettify the JSON responses which come under the endpoints in the API Frontend.

![Capture](https://user-images.githubusercontent.com/54177363/91688920-ba2bdf00-eb80-11ea-8b54-87d979383d92.PNG)

**Acceptance Criteria**

- [ ] Check for the prettified representation of JSON responses and then implement it here.

- [ ] update required

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 1 mentor.

**Estimation**
 1 hr approx

**Note**
Issue will be assigned from September 1st 2020

**Comment by vj-codes** [comment]
@yashasvimisra2798 please follow the issue template and then the issue will be approved/reviewed.Thanks!

**Comment by ksraj123** [comment]
I would like to work on this as a part of opensource hack. Commenting as its 1 sep now so please assign this issue. Thanks

**Comment by titiksha01** [comment]
Hello, I would like to work on this issue as a part of Open Source Hack.

**Comment by yashasvimisra2798** [comment]
@ksraj123 any updates?

**Comment by pallavisavant** [comment]
Is anyone working on this can i take this up

**Comment by yashasvimisra2798** [comment]
@ksraj123 you haven't been responding hence this issue is being assigned to @pallavisavant 
@pallavisavant do keep me updated about your progress. All the best for your contribution :)

**Comment by pallavisavant** [comment]
ok sure thank you

**Comment by pallavisavant** [comment]
@yashasvimisra2798 while setting environment variable for export DB_ENDPOINT=<database_endpoint> where will i find the .db file?? or how do i have to do this ,can you pls guide me on this thanks.

**Comment by pallavisavant** [comment]
@yashasvimisra2798 i have set the environment variables in .env file ,what do i have to do with the database variables ,r these also supposed to be .env and what should the values be???

**Comment by yashasvimisra2798** [comment]
https://github.com/anitab-org/mentorship-backend/wiki/Using-Backend-Swagger-UI
Mentorship Backend utilises Swagger UI. This the Documentation for it. Start here to get an idea.

**Comment by vaibhavarora102** [comment]
i would like to work on this

**Comment by pallavisavant** [comment]
@vaibhavarora102 i am already working on this,as it was me contributing for the first time it took time to set up the environment after solving the issue i was facing.Thanks

**Comment by pallavisavant** [comment]
@yashasvimisra2798 can you pls elaborate this in more detail for me...prettify the descriptions as in do you want me to change it or format it properly like all in small letter or how is it....Thanks

**Comment by vaibhavarora102** [comment]
No issues

**Comment by pallavisavant** [comment]
> @yashasvimisra2798 can you pls elaborate this in more detail for me...prettify the descriptions as in do you want me to change it or format it properly like all in small letter or how is it....Thanks

hey @yashasvimisra2798 i wanted to know what shall i change under all description...if told ..i can quickly do the required changes and raise PR.

**Comment by yashasvimisra2798** [comment]
@pallavisavant the time I created this issue the JSON format here was not correct, you can see in the screenshot itself. However, on reviewing the project again this fault has been fixed.

**Comment by pallavisavant** [comment]
@yashasvimisra2798 i feel its the same still....if i can do any required changes still can i pls....as i have participated in OSH i finished working on all category except UI and i am not finding any of the UI issue available...this is making me ineligible for OSH.
![Screenshot (108)](https://user-images.githubusercontent.com/43921225/92876118-5e3a4380-f427-11ea-83ef-c630c45e93f9.png)
