### ISSUE TITLE
Integrate pre-commit

### ISSUE THREAD

**Issue by SanketDG** [anitab-org/mentorship-backend#789]
**Is your feature request related to a problem? Please describe.**
As a developer, I want other developers sending PRs to this project follow basic conventions used in this project

There are a couple of ways that such conventions can be enforced, but the most preferrred way is to have
pre-commit hooks that run in git before code is committed.

**Describe the solution you'd like**
- [ ] Research `pre-commit` and report what hooks can be used
- [ ] Implement those hooks
- [ ] Write Documentation

**Describe alternatives you've considered**
- Checking those conventions as part of CI
- Manually put instructions in README

**Additional context**

**Comment by BALaka-18** [comment]
Hi @SanketDG , I would like to work on this issue.

**Comment by Abjcodes** [comment]
I would like to work on this issue as a part of OSH. Can you assign me this issue? Thank You.

**Comment by SanketDG** [comment]
@BALaka-18 I have assigned you, feel free to start working on this.

**Comment by SanketDG** [comment]
This issue is open again since @BALaka-18 is assigned to some other issue

**Comment by Abjcodes** [comment]
Is it possible to assign me this issue?

**Comment by SanketDG** [comment]
@Abjcodes You are already assigned to multiple issues

**Comment by shreyagupta30** [comment]
Hi @SanketDG, can I work on this?

**Comment by bhanvimenghani** [comment]
I have previously made an auto commit hook in git. I want to work on this issue. If no one is working on this , can you please assign it to me.

**Comment by SanketDG** [comment]
@bhanvimenghani You are assigned!

> can I work on this?

@shreyagupta30 You are already assigned to one issue in vms

**Comment by vj-codes** [comment]
How's the PR going? @bhanvimenghani

**Comment by bhanvimenghani** [comment]
@vj-codes Done with research and integration part. Just that should I add "Checking GitHub name and email set properly with a hook" or not as it would work only with my details. 
Also this is the [documentation link ](https://docs.google.com/document/d/15VbXVfhfeCkKz0OQX0HyD2oP6Wj2d9BGWM3yvtI9Xhg/edit) for any kind of suggestions ,if I am doing it as required for the project or not...

**Comment by vj-codes** [comment]
> @vj-codes Done with research and integration part. Just that should I add "Checking GitHub name and email set properly with a hook" or not as it would work only with my details.
> Also this is the [documentation link ](https://docs.google.com/document/d/15VbXVfhfeCkKz0OQX0HyD2oP6Wj2d9BGWM3yvtI9Xhg/edit) for any kind of suggestions ,if I am doing it as required for the project or not...

@SanketDG ^^

**Comment by SanketDG** [comment]
@bhanvimenghani Great, the documentation seems extensive. We did similar things in vms so you might want to take inspiration from there.

Here's what you have to do:

- Select a pre commit framework (I personally like https://github.com/pre-commit/pre-commit)
- Install all the required basic hooks along with black, flake8, isort.
- Add documentation for these hooks and how to integrate them.

**Comment by bhanvimenghani** [comment]
> @bhanvimenghani Great, the documentation seems extensive. We did similar things in vms so you might want to take inspiration from there.
> 
> Here's what you have to do:
> 
> * Select a pre commit framework (I personally like https://github.com/pre-commit/pre-commit)
> * Install all the required basic hooks along with black, flake8, isort.
> * Add documentation for these hooks and how to integrate them.

@SanketDG I have installed these hooks and updated the [doc. ](https://docs.google.com/document/d/15VbXVfhfeCkKz0OQX0HyD2oP6Wj2d9BGWM3yvtI9Xhg/edit#)can you see if there is something else required or should I make a pr?

**Comment by SanketDG** [comment]
Just make a PR @bhanvimenghani and then let's iterate from there

**Comment by KushalBeniwal** [comment]
@SanketDG I would like to work on this issue. Can you assign it to me?
