### ISSUE TITLE
Bug: Remove password hash from being returned on GET /user response

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/mentorship-backend#790]
**Describe the bug**
Currently user's password hash is returned on GET /user in the `full_user_api_model`. It should not be returned to frorntend UI since it is a sensitive information. 

**To Reproduce**

1. Login
2. send GET /user request
3. See pasword hash returned as part of user details

**Expected behavior**
The user data returned should not include password hash.

**Screenshots**
<img width="1247" alt="Screen Shot 2020-08-31 at 10 24 11 am" src="https://user-images.githubusercontent.com/29667122/91672842-23f1bc00-eb74-11ea-8ce7-c4c7dd90b53c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version ??

**Additional context**
This is a crross-project issue with BridgeInTech backend. The same issue was also raised on BIT backend repositorry with [issue#102](https://github.com/anitab-org/bridge-in-tech-backend/issues/102)

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers and @anitab-org/coding-team. This is a cross-project issue that also affecting BridgeInTech backend. This issue is open to anyone to work on as I am currently still tidying up BridgeInTech repositories.

**Comment by abhinav72610** [comment]
@mtreacy002 Hey I am new in this community and I am participating in OSH can I take this up?

**Comment by PrashanthPuneriya** [comment]
Sure @abhinav72610 ! Happy coding :)

**Comment by abhinav72610** [comment]
@mtreacy002 @PrashanthPuneriya why this pr is not getting merged ,,Are there any merge conflicts ??

**Comment by vj-codes** [comment]
@abhinav72610 the PR still needs to  be reviewed , tested and then it will be merged  mostly by the end of Sept. You may continue working on next issues for OSH.There's no condition of merging a PR and then proceeding for next issues :)
