### ISSUE TITLE
Set a timezone from the deployed server on the corn jobs

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#81]
## Description

As a developer,
I need have control over the timezone used on the cron job used to complete a mentorship relation,
so that I can be sure in what time the cron job does the work of completing the job.

Current deployed server is in eu-central-1 Amazon's region.

### Update
- [ ] Set a timezone to the cron job that completes the mentorship relations instead of using a default

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Conor0Callaghan** [comment]
I'd like to take this one, ill tidy up the PR and make a new one.

**Comment by isabelcosta** [comment]
@ivernus this issue is yours now. No need to create another PR. Now that you understand, next time I'm sure you'll follow our workflow.
