### ISSUE TITLE
Remove the Python versions contradiction in README file

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#820]
## Description
As a contributor,
I need no contradictions in the README file,
so that I won't be doubtful of the dependencies.

## Mocks
![image](https://user-images.githubusercontent.com/42068010/91970892-f6547080-ed35-11ea-94f1-1b0f2e31edf6.png)
Both the images (above and below) contradicts with the statement `Python3` and `Python3.6`
![image](https://user-images.githubusercontent.com/42068010/91970869-edfc3580-ed35-11ea-8ff3-244b75d8fd69.png)

### Update [Required]
- [ ] Update `Python 3.6` statement to `Python 3` 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.1 hour

**Comment by Surajv311** [comment]
Can I work on this issue ? @PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
Hey @Surajv311! If you don't mind, I am thinking to assign this specific issue to the person who doesn't have any Open Source contributions but is interested to get into it. Can you please look into other issues? Please let me know, if you are okay with it? I won't mind assigning you this issue :)

**Comment by PrashanthPuneriya** [comment]
Sure @Surajv311 :)

**Comment by soumyjain14** [comment]
How to start? I am new to open source, can anyone guide how to work? and what to do actually?

**Comment by PrashanthPuneriya** [comment]
> How to start? I am new to open source, can anyone guide how to work? and what to do actually?

Hey @soumyjain14 ! Setup the project locally by reading the README file. Once, you have done that look for first-timers-only labelled issues and start resolving it. Once you have resolved it create a Pull Request(PR) :tada:. You can then proceed further on your own :)

**Comment by sreelekha901** [comment]
Can I work on this issue?

**Comment by soumyjain14** [comment]
@PrashanthPuneriya  Thanks, can I work in this issue as well?

**Comment by divyaaa123** [comment]
@PrashanthPuneriya Can I work on this issue?

**Comment by chrpkorir** [comment]
I am new to open source, Can I work on this issue @PrashanthPuneriya

**Comment by Bhavani-Somanchi** [comment]
@PrashanthPuneriya  I'm new to open source and I am participating in the Open Source Hack. Can I work on this issue?

**Comment by PrashanthPuneriya** [comment]
Hey everyone! Since, this issue is already assigned to @Surajv311 and a valid PR has been created I can't assign others this issue. There are lot of other issues please feel free to fix them :)

**Comment by jatinjain001** [comment]
I want to take it up.I am new in Open source contribution . Can you please assign it to me
