### ISSUE TITLE
Add License shield to documentation 

### ISSUE THREAD

**Issue by muskanvk** [anitab-org/mentorship-backend#827]
Add a license shield to documentation to improve readability

**Comment by sreelekha901** [comment]
I want to work on it
Can you explain me this work in detail
I'm new to this

**Comment by muskanvk** [comment]
Hello @sreelekha901 This issue has already been resolved, See the linked PR for reference.
However, you can explore more issues in the issues section.

**Comment by vj-codes** [comment]
@muskanvk  an issue is first approved , then assigned to a contributor and then a PR is sent.I will be closing the PR for now , will be re-opened later.
Also this issue and PR won't be counted for OSH.Please look at issues labelled as Open Source Hack:)

**Comment by muskanvk** [comment]
Hii @vj-codes I am actually not looking out for OSH. I did this because I genuinely thought that there should be a license :)

**Comment by vj-codes** [comment]
@muskanvk I'll just assign you this after checking if license badges are added on other repos of the org!

**Comment by gaurivn** [comment]
@muskanvk, please do edit the issue you created following any of these [issue templates](https://github.com/anitab-org/mentorship-backend/tree/develop/.github/ISSUE_TEMPLATE), and if you want to create a PR for the same, do leave a comment (under the issue) asking to be assigned if it gets approved and if it gets approved by one of the maintainers, you can send a PR.

**Comment by jatinjain001** [comment]
I want to work on it please assign it to me

**Comment by vj-codes** [comment]
@gaurivn do we really need a license badge on readme? The other repos don't have and honestly no contributors will look for the license to begin their contributions rather will be aligned towards lang used and community etc

**Comment by muskanvk** [comment]
@vj-codes I really think you should not be rude to everyone and at every time. @gaurivn has already communicated the issue to me. The reason I am saying this is, previously also while working on some other issue, you got yourself assigned that issue, closed and marked the issues at your free will. Please give new comers also some chance. If it's not needed, it is okay, and yes contributors look for language and community accepted. But I really think that community is for everyone and I guess that's why all of us are here. This isn't really good. Please stop snubbing the people around and let them learn. Previously also, you weren't welcoming. If people keep on doing this, newcomers like me will get discouraged and I really don't think that this community promotes all that.

**Comment by vj-codes** [comment]
@muskanvk hey sorry if I seemed rude , was just following the community guidelines .The previous issue was assigned to me way before you created the PR without following the guidelines . I will be creating a few newcomer issues today for OSH , do comment on them I will make sure it's assigned to you .
And about not being welcoming , well others don't have any problem :)

**Comment by vj-codes** [comment]
And if you really want to work on this re-open this and I'll create same issues for other repos too
