### ISSUE TITLE
500 error when updating username to an already used username

### ISSUE THREAD

**Issue by bethanyr** [anitab-org/mentorship-backend#83]
**Describe the bug**
When I use the /PUT User api - and update a username to an already taken username, it returns a 500 Internal Server error

**To Reproduce**
1. Go to 'http://systers-mentorship-dev.eu-central-1.elasticbeanstalk.com/'
2. Click on 'PUT /user' Swagger entry
3. Enter your Bearer Token, and in the payload - include: "username": "isabel" - which is the name of an already created user

**Expected behavior**
return a more descriptive error message than: 500 
```
{
  "message": "Internal Server Error"
}
```

In the register user api call - if you use an existing username - you get a 400 error with this message: 
```
{
  "message": "A user with that username already exists"
}
```

That might be better than returning a 500 Internal Server Error

**Screenshots**
n/a

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
 n/a

**Additional context**
n/a

**Comment by isabelcosta** [comment]
Thank you @bethanyr for reporting this bug!
I just tested this now and it happens to me too.
I'll create an issue to solve this.
