### ISSUE TITLE
Update python badge in readme.md

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#830]
## Description
As a contributor,
I need no contradictions in the README file,
so that I won't be doubtful of the dependencies.
Update badge in readme from Python 3.6 to Python3 as it was decided in #820 to keep all versions same.

### Acceptance Criteria

- [ ] Update [Required]
- [ ]  Update Python 3.6 badge to Python 3 badge

### Definition of Done
 

- [ ] All of the required items are completed.
- [ ]  Approval by 1 mentor.

### Estimation
0.1 hour

**Comment by anishghimire603** [comment]
@vj-codes assign this to me.

**Comment by codesankalp** [comment]
@vj-codes  I want to solve this issue.

**Comment by PrashanthPuneriya** [comment]
> @vj-codes assign this to me.

This is a first-timers-only issue @anishghimire603. Assigning @codesankalp :)

**Comment by codesankalp** [comment]
@vj-codes  please review my pull request and if you want any other change then let me know. Thanks.

**Comment by jatinjain001** [comment]
I want to take it up please

**Comment by vj-codes** [comment]
@jatinjain001 After commenting on a issue please wait until it's assigned to you and then send a PR.
This issue is already assigned , please go through other available issues and comment to claim them:)

**Comment by jatinjain001** [comment]
Okk

**Comment by codesankalp** [comment]
@vj-codes if my pull request is correct then, please review it and if any other changes are required then please inform me.
In this meantime can I solve more issues?

**Comment by vj-codes** [comment]
@codesankalp You can proceed to solve other ones , just remember the guidelines.And about the review , it will be done soon:)

**Comment by sujal111** [comment]
I am willing to work and solve this issue. Please assign me the same

**Comment by jatinjain001** [comment]
I am willing to work on this please assign it to me

**Comment by vj-codes** [comment]
@jatinjain001 @sujal111 please don't hijack all issues that are already assigned
[Here's](https://github.com/anitab-org/mentorship-backend/issues?q=is%3Aopen+is%3Aissue+label%3A%22Status%3A+Available%22+label%3A%22Open+Source+Hack%22+no%3Aassignee) a list of some available issues for OSH.
Comment to claim , get assigned and then send a PR.Have a great start!

**Comment by sujal111** [comment]
🙂😑
Hmmm

**Comment by guruc-134** [comment]
@vj-codes  I'm new to open source contributions i would like work on it
please assign it to me
