### ISSUE TITLE
Beautify/Format Swagger.json

### ISSUE THREAD

**Issue by Shivansh2407** [anitab-org/mentorship-backend#840]
**Is your feature request related to a problem? Please describe.**
The Swagger.json page seems to be a bit congested. In order to make it look better we can try to beautify the json file, and present it in tree view format.
You can take a look at the idea in the link : https://codebeautify.org/jsonviewer

**Additional context**
Please comment below to get the issue assigned to you. This is a part of OSH and hence will be assigning it on First come first serve basis

**Comment by kritikaparmar-programmer** [comment]
I want to work on this issue.. Please assign me..

**Comment by Shivansh2407** [comment]
Go ahead @kritikaparmar-programmer 👍

**Comment by kritikaparmar-programmer** [comment]
![doc](https://user-images.githubusercontent.com/59971890/92327757-a1886100-f079-11ea-92c0-6e04ccdc2ca2.png)

Hey @Shivansh2407 , I looked for the Swagger.json file but it was deleted by someone 5 days ago..
Can you please take a look and correct me if I'm wrong..

**Comment by Shivansh2407** [comment]
But I guess, it is available at the heroku app at the /swagger.json endpoint. You need to just beautify it and display the formatted json view on the same endpoint.

**Comment by kritikaparmar-programmer** [comment]
Hey @Shivansh2407 , I setted up the project locally and when I run it I found the file on the webpage and even I know how to beautify it but I am having confusion on where and how to edit the file that in the project like how to display the formatted json view on the webpage.
Can you please help me with this..

**Comment by Shivansh2407** [comment]
Hi @kritikaparmar-programmer , you can create a template for the same and display it in the /swagger.json endpoint.

**Comment by SanketDG** [comment]
The `swagger.json` endpoint is generated by `flask-restx`, I am not sure how much it can be overridden.

**Comment by Anmollenka** [comment]
@Shivansh2407 Can I work on this issue?Thank You.

**Comment by Shivansh2407** [comment]
@Anmollenka this issue is assigned to @kritikaparmar-programmer . You can check out other issues as well.

**Comment by Anmollenka** [comment]
> @Anmollenka this issue is assigned to @kritikaparmar-programmer . You can check out other issues as well.

I would like to work on this when it is free.

**Comment by priyanshuone6** [comment]
Hey, can you please assign this issue to me when it's free

**Comment by khushishikhu** [comment]
may i work on this issue

**Comment by SanketDG** [comment]
Anyone who wants to work on this issue, please provide a little roadmap of what you want to achieve, I think this issue has a large scope of what can be done, and even can be done as its own mini project.

**Comment by khushishikhu** [comment]
@SanketDG  can you please give me a reference of how tree-view format looks like

**Comment by khushishikhu** [comment]
@SanketDG do we need to format json file also in tree view format, like this in screenshot
![s](https://user-images.githubusercontent.com/65439761/94180825-384b7f00-febc-11ea-94d9-1d5955e6f3a8.PNG)

**Comment by SanketDG** [comment]
@khushishikhu Yes. Not strictly, but I am guessing @Shivansh2407 has more views on this.

**Comment by khushishikhu** [comment]
@Shivansh2407 please give me your views about the json file sholud look like this in screenshot and also which do have to beautify?

**Comment by Shivansh2407** [comment]
Yes @khushishikhu , The screenshot you've attached is what I wanted the swagger.json to look like. But the main thing here is that we need to change/update the endpoint with this tree view to make it more readable, i.e. /swagger.json . For this you need to figure out on how it can be done as the endpoint is generated by flask-restx. If you need any help do let us know 👍

**Comment by khushishikhu** [comment]
@Shivansh2407 i guess we need to make changes in the files like [https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/resources/admin.py](this) for making swagger.json looks in a tree view format. plese let me know i am thinking right.

**Comment by khushishikhu** [comment]
@Shivansh2407 can you please give me some reference i can look for on how to make swagger.json in tree view format.
As i am completely new to this

**Comment by Shivansh2407** [comment]
Yeah Sure @khushishikhu , Please have a look at the links/resources : 
https://ourcodeworld.com/articles/read/753/creating-collapsible-tree-structures-from-json-into-html-in-javascript
https://www.cssscript.com/json-data-tree-view/
Assigning this issue to @khushishikhu , unassigning @kritikaparmar-programmer due to inactivity 👍

**Comment by khushishikhu** [comment]
![Capture](https://user-images.githubusercontent.com/65439761/94346731-44664680-004c-11eb-92d4-eb44be489b50.PNG)
@Shivansh2407 does it needs to be like this as i have just rendered the JSON data into HTML in javascript in the form of tree view. right now i have made changes in some of its part. just to make sure if i am doing right
please have a look

**Comment by khushishikhu** [comment]
hey @Shivansh2407  i guess i think that this issue has been resolved, because now i have checked swagger.json file it is showing me in tree format

**Comment by devkapilbansal** [comment]
@vj-codes @rpattath as `swagger.json` file has been removed now. Is the issue and linked PR valid?

**Comment by vj-codes** [comment]
@devkapilbansal although the file is deleted, the swagger.json endpoint is still there on the heroku link . If there is a need to beautiful that endpoint, a new issue cn be created and these could be closed. What say?

**Comment by devkapilbansal** [comment]
> @devkapilbansal although the file is deleted, the swagger.json endpoint is still there on the heroku link . If there is a need to beautiful that endpoint, a new issue cn be created and these could be closed. What say?

@vj-codes as far as I know, that endpoint is created by the `flask-restx` itself and it may be not be that easy too.
@SanketDG already had a discussion on it here :arrow_down: 
https://github.com/anitab-org/mentorship-backend/pull/847#issuecomment-691432446

**Comment by vj-codes** [comment]
@devkapilbansal it's best to close the PR and issue then:)
