### ISSUE TITLE
Perform manual testing and report PUT /user/change_password

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#845]
## Description

As a tester,
I need to test PUT /user/change_password,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#change-password](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#change-password)

### Update [Required]
- [ ] Test PUT /user/change_password API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by vj-codes** [comment]
@gaurivn hey I would like to work on this

**Comment by gaurivn** [comment]
@vj-codes, you're assigned issue #738 right, do open a PR for that and I'll assign you this one

**Comment by ankit-saraf** [comment]
@vj-codes I would like to work on it.

**Comment by ankit-saraf** [comment]
> @vj-codes I would like to work on it.

I had created the PR for my previous assigned issue.

**Comment by vj-codes** [comment]
@ankit-saraf assigning you:)
Setup up the repo locally or perform testing on the deployed link

**Comment by ankit-saraf** [comment]
> @ankit-saraf assigning you:)
> Setup up the repo locally or perform testing on the deployed link

Thank you, Vaishnavi :)  
I will try to complete it asap.

**Comment by ankit-saraf** [comment]
@vj-codes I have a doubt. This is the backend repo and is used by our ios and android app. So for performing the test, can I use the android app?

**Comment by vj-codes** [comment]
@ankit-saraf no you can't test using app , there's a repo deployed link to test or the other option is to set repo locally

**Comment by ankit-saraf** [comment]
@vj-codes https://mentorship-backend-temp.herokuapp.com/  U are talking about this link?

**Comment by vj-codes** [comment]
yes here's how to use swagger https://github.com/anitab-org/mentorship-backend/wiki/Using-Backend-Swagger-UI

**Comment by ankit-saraf** [comment]
Thank You!

**Comment by ankit-saraf** [comment]
I almost completed it. WIll create a pull request by evening.

**Comment by vj-codes** [comment]
Just make sure you don't add the screenshots/gifs in in form of binary files .

1.  Copy the image in a comment here , and when it is uploaded you will see a link
2.  Paste that link in your test_report.md file 

This is a preferred way of uploading images

**Comment by yash2189** [comment]
@gaurivn I have already included this in my PR #850

**Comment by ankit-saraf** [comment]
@vj-codes What I should do now?

**Comment by ankit-saraf** [comment]
@yash2189 I think you were not supposed to include it in your PR. That issue was related to PUT user/ API and not user/change_password

**Comment by yash2189** [comment]
@ankit-saraf apologies I just did all of that in a flow since I was going through the swagger. It was mentioned  PUT /user API so I thought it would include both.

**Comment by vj-codes** [comment]
@yash2189 thank you for letting us know but the issue you were assigned was dealing  ONLY with
1) `Change username to a username already being used by another User` and 
2) `Change username to a username  not  being used by another User`

Performing test report for change password deals with this issue which is currently assigned to @ankit-saraf 
I understand you did it with the flow , it happens to everyone but as we are currently following the **community guidelines**  for OSH, I request you to update your PR  or have a `Note :saying this PR also includes so and so test which I did out of curiosity `and let other contributors work on this
Sounds good ? @yash2189

**Comment by ankit-saraf** [comment]
@vj-codes Should I proceed with it?

**Comment by vj-codes** [comment]
@ankit-saraf you may continue your work on this but make sure your tests are 100% original

**Comment by ankit-saraf** [comment]
> @ankit-saraf you may continue your work on this but make sure your tests are 100% original

Yes definitely.

**Comment by yash2189** [comment]
@vj-codes I have mentioned it in my description I'll change  the commit message too

**Comment by vj-codes** [comment]
@yash2189 great thanks a lot :)

**Comment by yash2189** [comment]
@vj-codes I have done the required changes please check #850

**Comment by ankit-saraf** [comment]
@vj-codes Do you have any idea why some image links are working while some are not.
![error](https://user-images.githubusercontent.com/64194946/92592891-e00e5d80-f2bd-11ea-9b79-69509906a57e.png)

**Comment by ankit-saraf** [comment]
@vj-codes I created a PR. Please review. I also want to discuss an issue regarding the documentation with you. I want to open an issue for that. So pls tell me where we can discuss it.

**Comment by vj-codes** [comment]
@ankit-saraf the PR will be reviewed later tonight /tomr 
Anyone can open issues  ,so  feel free to create it .But make sure there is no issue about the same already and it isn't about adding badges in readme .
You can discuss it here or on zulip

**Comment by ankit-saraf** [comment]
@vj-codes
mentorship-backend/docs/quality-assurance-test-cases.md
In [Change Password](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#change-password) section I think we should have one more test. 

|  When the current password is wrong  | Fail |
 

Though it is obvious I think we should get it documented.

**Comment by vj-codes** [comment]
@ankit-saraf yes indeed. Was this the documentation issue you were speaking about? 
Adding a test case will be the QA team's decision though

**Comment by vj-codes** [comment]
> @vj-codes
> mentorship-backend/docs/quality-assurance-test-cases.md
> In [Change Password](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#change-password) section I think we should have one more test. 
> 
> |  When the current password is wrong  | Fail |
>  
> 
> Though it is obvious I think we should get it documented.

@rpattath your thoughts?
