### ISSUE TITLE
Updating Description in Readme.md

### ISSUE THREAD

**Issue by sharur7** [anitab-org/mentorship-backend#859]
## Description
As a contributor,
I need no contradictions in the README file,
so that I won't be doubtful of the dependencies.
Adding a description for Future-ideas for the project. 

## Mocks
I came up with this description.<br>
![Capture2](https://user-images.githubusercontent.com/57194200/92718595-a30a9f80-f37f-11ea-84b3-cfd93a731545.PNG)

### Update [Required]
- [ ] Adding a description for Future-ideas for the project. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

@vj-codes @isabelcosta  I want to take up this issue as part of OSH. Please add the appropriate labels to it. I want to work on this issue. Thank You.

**Comment by vj-codes** [comment]
@sharur7 thank you for creating this issue .Currently only issues which are labelled as Open Source Hack are open for OSH.
Your issue will be reviewed and validated in the mentorship session by mentors/maintainers and you will then be updated accordingly.
Please look at [ these available issues ](https://github.com/anitab-org/mentorship-backend/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22Open+Source+Hack%22+label%3A%22Status%3A+Available%22) and comment on any one to start contributing:)

**Comment by sharur7** [comment]
@vj-codes is this issue still not valid for OSH?

**Comment by vj-codes** [comment]
Closing since the current description in readme is accurate and to the point .
