### ISSUE TITLE
Skill fluency attribute for user  skill

### ISSUE THREAD

**Issue by pbgurav** [anitab-org/mentorship-backend#867]
**Is your feature request related to a problem? 

Currently there is no way to know the fluency of a mentor in a particular skill and hence not easy to to decide whether he is the right mentor for myself 
**Describe the solution you'd like

There should be a facility for the user to set his skill fluency for a skill which can be a self rating value in the range of 1 to 10. this will help other users to get a idea   of the  skill level while searching for a mentor.

**
<!-. -->

**Describe alternatives you've considered**

**Additional context**

**Comment by isabelcosta** [comment]
@pbgurav thank you for suggesting an improvement to the app 🤗 
At the moment, we have other features in higher priority, this issue if we choose to do it, would include some thought put into how to change the model for this. Right now skills is just a string, that can have any text on it.
I will put this with the potential future idea label and close this. cc @anitab-org/mentorship-maintainers
