### ISSUE TITLE
docs: Create Quality Assurance table for 'Returns all admin users' API

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#871]
## Description

As a developer,
I need to know what are the test cases for a certain API,
so that I can write new unit tests.

As a tester,
I need to know what are the test cases for a certain API,
so that I can perform manual tests on the API.

The task is to come up and add a quality assurance table for "Returns all admin users" API to the docs in the /docs folder.

## Mocks
As done under [docs/quality-assurance-test-cases.md](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md)

![mentorship-backend-3](https://user-images.githubusercontent.com/46970368/93278063-39f0b500-f7e1-11ea-977e-3d9f2bc4c678.PNG)

### Update [Required]
- [ ] Add test cases for List All Tasks API.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by rubyruins** [comment]
I would like to work on this but I've never made test cases for an API before, I will need some guidance!

**Comment by khushishikhu** [comment]
may i take this issue

**Comment by paritoshsinghrahar** [comment]
@khushishikhu Sure, I am assigning it to you,

**Comment by SHITIZ-AGGARWAL** [comment]
Can I also work on this issue??

**Comment by paritoshsinghrahar** [comment]
@SHITIZ-AGGARWAL Thanks for asking but I guess it's pretty much done.

**Comment by khushishikhu** [comment]
@paritoshsinghrahar  please review this PR

**Comment by devkapilbansal** [comment]
@paritoshsinghrahar it would be better to remove available status if the issue is assigned.

**Comment by khushishikhu** [comment]
@paritoshsinghrahar  please review my PR
