### ISSUE TITLE
Perform manual testing and report POST /user/resend_email API

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#875]
## Description

As a tester,
I need to test POST /user/resend_email API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#resend-verification-email](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#resend-verification-email)

### Update [Required]
- [ ] Test POST /user/resend_email API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by sreelekha901** [comment]
I'am interested to work on this

**Comment by gaurivn** [comment]
Assigned @sreelekha901

**Comment by sreelekha901** [comment]
Env setup is done 
Working from today

**Comment by sreelekha901** [comment]
still working on it
will update the progress soon

**Comment by devkapilbansal** [comment]
Is this issue available?? If yes, @gaurivn @SanketDG @PrashanthPuneriya @isabelcosta  please assign me for this

**Comment by PrashanthPuneriya** [comment]
@sreelekha901 Please update the progress.

**Comment by sreelekha901** [comment]
I'm facing problems in env setup in my new system 
Wont mind if issue is assigned to others

**Comment by devkapilbansal** [comment]
Okay, as both of my pull requests are complete now(or may need little modifications, if needed, I want to work on this. @PrashanthPuneriya please assign this to me

**Comment by PrashanthPuneriya** [comment]
Sure @devkapilbansal! Assigned you :)

**Comment by devkapilbansal** [comment]
@gaurivn  @isabelcosta  Please review pull request #897
