### ISSUE TITLE
Perform manual testing and report POST /user/refresh API

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/mentorship-backend#876]
## Description

As a tester,
I need to test POST /user/refresh API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#refresh-token](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#refresh-token)

### Update [Required]
- [ ] Test POST /user/refresh API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by rubyruins** [comment]
I would like to work on this, could you please explain a bit more?

**Comment by arkumari2000** [comment]
I would like to work on this issue. Can I do this? @gaurivn

**Comment by NarimaneHennouni** [comment]
Hi, can I try to solve this issue too?

**Comment by gaurivn** [comment]
> I would like to work on this, could you please explain a bit more?

Hi @rubyruins,  please refer to the links in the issue, you'll have to test the API on the backend locally and report on the same.

**Comment by gaurivn** [comment]
@arkumari2000, @NarimaneHennouni, issues are assigned on an FCFS basis...since this issue is assigned, can not assign again for time being as of now. 
In case this issue becomes available in the future, will surely assign you.

**Comment by rubyruins** [comment]
@gaurivn, thank you. I will try to set it up locally and let you know if I need any help with the same!

**Comment by rubyruins** [comment]
@gaurivn, I actually had a doubt - do I need to clone the repo and run it on my machine, or do I test the API in the browser itself on this link https://mentorship-backend-temp.herokuapp.com/?

**Comment by gaurivn** [comment]
@rubyruins, most preferred to run it and test locally.

**Comment by rubyruins** [comment]
@gaurivn, alright, thanks! I apologize for not having started working on this yet due to college tests, but I will start working on it today :)

**Comment by rubyruins** [comment]
@gaurivn, I am almost done testing but have 2 doubts, could you please help me out?

1. As per the guidelines (at least 1 positive and 1 negative test case), I have tested cases 1, 2 and 4 from the docs (2 failing, 1 successful.) However, I've been having some trouble testing the 3rd case - Refresh token in the Authorization field is expired. As per the docs, the token expires after a week. Should I wait that long for it to expire and test after a week, or will submitting a PR with the other 3 cases only be okay?

2. Out of curiosity, I also tested a case where I kept the Authorization field empty with just a single whitespace. It resulted in a status code "The authorization token is missing!" None of the cases in the POST/user/refresh documentation cover this case (single whitespace) or result in this status code - so could it be useful to include this test case as well? Should I add it to my PR, or just stick to the original cases?

**Comment by rubyruins** [comment]
@gaurivn, I have opened a PR for the issue! Kindly review it.

**Comment by isabelcosta** [comment]
@rubyruins those are great questions :)

1. You don't have to wait to long, there is a way to test is in shorter time. You would have to run the project locally and change the line of code that defines the 1 week, and switch to something like 30 seconds or 1 min. Basically change to something you can easily use it and get the error you want.

2. Feel free to add that to the PR :) its a good addition.

Thank you for such a thorough look at this API and testing :)

**Comment by rubyruins** [comment]
@isabelcosta, sure! I will try setting it up locally and update the PR soon. Thanks a lot for your suggestions :)

**Comment by rubyruins** [comment]
@isabelcosta, all done :) please review the PR and let me know if any more changes are needed!
