### ISSUE TITLE
Audit the dependencies and fix/upgrade/remove them.

### ISSUE THREAD

**Issue by PrashanthPuneriya** [anitab-org/mentorship-backend#881]
## Description
As a developer,
I need no unrequired dependencies, conflicts in the dependencies e.g. #713 ,
so that any upgrades to the dependencies doesn't break the project.

### Update [Required]
- [x] Remove unrequired dependencies
- [x] Fix the dependency issues

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
Can't estimate

**Comment by PrashanthPuneriya** [comment]
@SanketDG What category does this issue comes under? Also, can you suggest any changes to describe the issue more?

**Comment by GuruCharan-13** [comment]
I would like to work on this issue
please assign it to me
thank you

**Comment by PrashanthPuneriya** [comment]
Sure @GuruCharan-13. Assigning you :)

**Comment by SanketDG** [comment]
This looks good, everything is clear enough.

**Comment by PrashanthPuneriya** [comment]
@SanketDG What would be the suitable category? OSH participants needs the category label.

**Comment by devkapilbansal** [comment]
@GuruCharan-13 are you still working on this?

**Comment by sanjibansg** [comment]
I would like to work on this. Do assign if available.

**Comment by PrashanthPuneriya** [comment]
> @GuruCharan-13 are you still working on this?

@GuruCharan-13

**Comment by devkapilbansal** [comment]
@PrashanthPuneriya if @GuruCharan-13 is not then I would like to work on this.

**Comment by PrashanthPuneriya** [comment]
Yeah sure @KapilBansal320. Let's wait for sometime till @GuruCharan-13 responds. If he doesn't respond then I will assign you this issue :)

**Comment by GuruCharan-13** [comment]
i am extremely sorry I could not complete this we had an event in our college
assign it to any one else

**Comment by PrashanthPuneriya** [comment]
Happy coding @KapilBansal320 :)

**Comment by devkapilbansal** [comment]
@PrashanthPuneriya @SanketDG please review pull request #889

**Comment by devkapilbansal** [comment]
> @SanketDG What category does this issue comes under? Also, can you suggest any changes to describe the issue more?

@SanketDG @PrashanthPuneriya I don't think that this was related to coding. May be category should be **research** here.

**Comment by PrashanthPuneriya** [comment]
@SanketDG Is the outreach/research label appropriate for this issue?

**Comment by SanketDG** [comment]
I added the coding label and I think that's fair enough. Feel free to change anything though.

**Comment by devkapilbansal** [comment]
> @SanketDG Is the outreach/research label appropriate for this issue?

@PrashanthPuneriya, in my opinion, it has nothing to do with coding. Rest issue label may not matter

**Comment by PrashanthPuneriya** [comment]
> Rest issue label may not matter

What does this mean? I didn't get you.

**Comment by devkapilbansal** [comment]
> > Rest issue label may not matter
> 
> What does this mean? I didn't get you.

As this issue is already solved now.

**Comment by devkapilbansal** [comment]
@SanketDG @PrashanthPuneriya please review pull request #889

**Comment by codesankalp** [comment]
Yes, this issue is related to research.

**Comment by dixitaniket** [comment]
If possible can this issue be assigned to me if this is still open .

**Comment by devkapilbansal** [comment]
@dixitaniket there is already a pull request open that is ready to be merged
Search for other issues
