### ISSUE TITLE
Create Meetings between members or two users in a relation. Possibly integration with Google Calendar

### ISSUE THREAD

**Issue by rpattath** [anitab-org/mentorship-backend#899]
**Is your feature request related to a problem? Please describe.**
Create Meetings between members or two users in a relation. Possibly integration with Google Calendar

**Describe the solution you'd like**
Research about MVP feature for scheduling meetings between mentor and mentee: what database entities would we need; how would the workflow be; future integrations (not mvp) with 3rd parties that could improve this feature

**Outcome**
An md file describing how this can be implemented.

**Comment by sanjibansg** [comment]
I would like to work on this issue. Do assign. @rpattath

**Comment by rpattath** [comment]
@kahanikaar are you currently assigned to any issues for which you haven't created a PR yet?

**Comment by justdvnsh** [comment]
@rpattath I'd like to work on this. I have submitted all my pending PR's. Currently, I have no pending PR !

**Comment by justdvnsh** [comment]
@rpattath Unassigning myself. Took this issue by mistake. Thought it was in mentorship-android

**Comment by gitpurva** [comment]
@rpattath Can I take up this issue? I have submitted all my PR's .

**Comment by rpattath** [comment]
@gitpurva Are you assigned to any issues for which you haven't created a PR yet?

**Comment by faznan3nazer** [comment]
can I work on this issue?

**Comment by vj-codes** [comment]
@gitpurva any updates?

**Comment by gitpurva** [comment]
I have my college mid term exam .. So I will update within two to three
days:)

**Comment by sankha555** [comment]
Hello @rpattath , if there isn't anyone else working on this issue, can it be assigned to me. I would love to give it a shot with the ideation and possible development. Thanks!

**Comment by vj-codes** [comment]
@gitpurva how's the PR going? Any updates?

**Comment by sankha555** [comment]
@vj-codes can I take this up if there hasn't been much activity on it yet and can assign it to me? I can make a PR with the following roadmap:

1. Create a short md file showing what models I'll make, and related endpoints
2. Integration of Google calendar API with our API
3. After showing this initial ideation, I can also take up the task of implementing the idea if the idea seems good and integrate more suggestions with it

Thanks!

**Comment by vj-codes** [comment]
Assigning you @sankha555 
Happy documenting!

**Comment by vj-codes** [comment]
@gitpurva removing your assignment due to inactivity.
