### ISSUE TITLE
blog: OSH Experience

### ISSUE THREAD

**Issue by paritoshsinghrahar** [anitab-org/mentorship-backend#904]
## Description

I want you to write a blog about the OSH experience from a newcomer's point of view for the backend repo. So that it tells your experience about open source and also may serve as an intro to backend repo for prospective contributors.

Write a blog on Medium and share the link in a document called `outreach-work.md` in the “/docs” folder of mentorship-backend. So you need to create a post and add a new line to this document. 

#### Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium) at the end of your blog.
https://medium.com/anitab-org-open-source

### Update [Required]
- [ ] [Submit Blog. Add line to `outreach-work.md`]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1 Hour] hours

**Comment by paritoshsinghrahar** [comment]
I'll allow multiple contributors given they have worked on enough issues. * 
Also, while asking to be assigned, please give a brief intro/summary (1-2 lines) to your blog.


#### *Subject to the discussion.

**Comment by devkapilbansal** [comment]
@paritoshsinghrahar Do we need to use medium only for blog post or any blogging site will serve the purpose?

**Comment by SHITIZ-AGGARWAL** [comment]
@paritoshsinghrahar I would love to work on this issue since OSH helped me to make my first ever open source contribution and many more

**Comment by vj-codes** [comment]
Assigning you both @devkapilbansal @SHITIZ-AGGARWAL 
Happy documenting !

**Comment by vj-codes** [comment]
> @paritoshsinghrahar Do we need to use medium only for blog post or any blogging site will serve the purpose?

@devkapilbansal medium only as stated in the issue and mention AnitaB.org as a publication while publishing the blog/article (called: story on medium).

**Comment by decon-harsh** [comment]
I would love to share my experience , Can you assign me too?

My blog will focus mainly about the early problems i faced and the rise in my confidence after the first PR. I would love to mention how easy is to work in OSH when maintainers are giving their best to help you.

**Comment by paritoshsinghrahar** [comment]
> @paritoshsinghrahar Do we need to use medium only for a blog post or any blogging site will serve the purpose?

Yes, AnitaB.org has a publication there. I'll still check with the team.

**Comment by paritoshsinghrahar** [comment]
@decon-harsh I am assigning this to you as well. Happy writing!! 😄

**Comment by decon-harsh** [comment]
Sorry , I didn't see it. Is it specifically for the mentorship back-end repo? I had worked on vms!

**Comment by Anmollenka** [comment]
@paritoshsinghrahar Can I work on this???

**Comment by devkapilbansal** [comment]
Hi, @paritoshsinghrahar @isabelcosta @PrashanthPuneriya @SanketDG  when I try to add to publications it shows no publication available even after I follow AnitaB.org

**Comment by SHITIZ-AGGARWAL** [comment]
yes

**Comment by devkapilbansal** [comment]
> > @paritoshsinghrahar Do we need to use medium only for a blog post or any blogging site will serve the purpose?
> 
> Yes, AnitaB.org has a publication there. I'll still check with the team.

Please check and let me know.

**Comment by PrashanthPuneriya** [comment]
Pinging @isabelcosta @mtreacy002. Can you please guide them since you have already written few blogs?

**Comment by SanketDG** [comment]
Hey. please feel free to post on your own Medium (I'd say [avoid using Medium](https://florimond.dev/blog/articles/2019/05/why-i-dont-write-on-medium/) but it's your choice at the end of the day!) or your own blog. No need to wait for the org publication.

**Comment by ashwinijha6** [comment]
@paritoshsinghrahar I would like to work on this issue could u assign it to me I have written one for vms but as I have made 2 pull requests for the backend issue I would like to share my experience working on backend issues as well.

**Comment by paritoshsinghrahar** [comment]
@devkapilbansal @ashwinijha6 @decon-harsh
https://medium.com/anitab-org-open-source

did you try this?

**Comment by decon-harsh** [comment]
@paritoshsinghrahar I guess to add publication one must have editor or owner level permissions.

**Comment by ashwinijha6** [comment]
> @devkapilbansal @ashwinijha6 @decon-harsh
> https://medium.com/anitab-org-open-source
> 
> did you try this?

@paritoshsinghrahar I have just mentioned this at the bottom of my blog

**Comment by devkapilbansal** [comment]
> @paritoshsinghrahar I guess to add publication one must have editor or owner level permissions.

Yes, I tried to too @paritoshsinghrahar

**Comment by paritoshsinghrahar** [comment]
@decon-harsh Yes, but one can request for publication. It will help the article discovered in a better manner. And anyway blogging your experience on your page helps too.

@ashwinijha6 @devkapilbansal Oh, ok. Great.

**Comment by decon-harsh** [comment]
> @decon-harsh Yes, but one can request for publication. It will help the article discovered in a better manner. And anyway blogging your experience on your page helps too.
> 
> @ashwinijha6 @devkapilbansal Oh, ok. Great.

How can I?

**Comment by ashwinijha6** [comment]
@paritoshsinghrahar just had a question mentioning the publication & tagging them to your story are the same thing right?

**Comment by paritoshsinghrahar** [comment]
@decon-harsh https://help.medium.com/hc/en-us/articles/214035868-Leave-a-note
Actually, that happened in a vice-versa manner with me. When a publication left a note on my article. I see one cannot private message the other way round. 

#### I'll change the Issue description to not add as a publication.

**Comment by paritoshsinghrahar** [comment]
@ashwinijha6 It's fine.
