### ISSUE TITLE
Password accepting empty spaces. 

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#918]
**Describe the bug**

On the register endpoint the password accepts empty spaces. Where as on the Change password it does not.

**To Reproduce**

1. Go to 'register endpoint'
2. Click on 'create a new user with spaces in their password'
3. Scroll down to 'change password and try to change password to another password containing spaces'
4. See error saying no spaces allowed in the password

**Expected behavior**

Password validation should be same for both endpoints i.e. either allow spaces in both endpoints or for neither.

**Comment by beingrudraksh** [comment]
May I work on this issue?

**Comment by epicadk** [comment]
> May I work on this issue?

Try asking on zulip as no one has approved the issue yet

**Comment by devkapilbansal** [comment]
This issue seems valid for me, either password field should not accept spaces or change password should accept it too.

![ss](https://user-images.githubusercontent.com/42766576/98514676-d9856d80-228f-11eb-83b5-fd51f5cf041a.png)

Thanks @epicadk for opening this.
@vj-codes @PrashanthPuneriya what do you think?

**Comment by vj-codes** [comment]
Valid issue ✔️ 
@epicadk or @beingrudraksh anyone interested in fixing this ?

**Comment by epicadk** [comment]
> Valid issue ✔️
> @epicadk or @beingrudraksh anyone interested in fixing this ?

Don't we need to decide what needs to be done first?

**Comment by devkapilbansal** [comment]
Yes, @epicadk password field shouldn't accept spaces

**Comment by epicadk** [comment]
> Yes, @epicadk password field shouldn't accept spaces

Okay. @vj-codes please assign @beingrudraksh

**Comment by 17sushmita** [comment]
If the issue is available Can I work on it?

**Comment by rpattath** [comment]
@17sushmita are you still interested in working on this issue?

**Comment by 17sushmita** [comment]
Yes I'd like to work on this

**Comment by rpattath** [comment]
@17sushmita all your's ! Good luck :tada:
