### ISSUE TITLE
Use HTTP Status Codes instead of hard coded status codes

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#923]
**Describe the bug**

Some routes have hard coded status codes instead of HTTP Status 
**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Click on `User`
3. Scroll down to /user (Returns details of current user)

**Expected behavior**
HTTPStatus.XYZ should have been displayed instad of raw status codes

**Screenshots**
![error_code](https://user-images.githubusercontent.com/42766576/98860715-1b7a0380-248a-11eb-84f9-2bbef14a1208.png)

**Condition for Done**

- [ ]  All hard coded status codes are removed

**Estimated Time**
1 hour

**Comment by devkapilbansal** [comment]
Related to #846

**Comment by devkapilbansal** [comment]
@vj-codes @rpattath please update the labels

**Comment by 17sushmita** [comment]
Can I work on this issue?
