### ISSUE TITLE
Responses does not list username is invalid

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#927]
**Describe the bug**

Here username is invalid is returned but not documented in the responses.

https://github.com/anitab-org/mentorship-backend/blob/0cf4d9de952edac8569adfaa9c08ae7defdf5a26/app/api/validations/user.py#L123-L126
![ss](https://user-images.githubusercontent.com/42766576/99196751-6494c500-27b4-11eb-9ea2-d31a8b8184ad.png)

**To Reproduce**

1. Go to User
2. Scroll down to /user(updates user profile)
3. Add valid authorization token
4. Enter username as already used username
5. Click on execute
6. Scroll down to response

**Expected behavior**
The error messages should be included in the error responses

**Additional context**
Error mesaages for password, email and address should also be included

**Comment by devkapilbansal** [comment]
@PrashanthPuneriya add appropriate labels

**Comment by 17sushmita** [comment]
Can I work on this?

**Comment by msklarek** [comment]
Can I work on this?

**Comment by isabelcosta** [comment]
@msklarek I can assign it to you, since #918 is assigned to @17sushmita already :)

**Comment by msklarek** [comment]
Hello, just wanted to post an update that I am starting to work on this issue.

**Comment by msklarek** [comment]
The information in the bug does not seem to be correct. Below is my observation: 

The bug mentions that the /user(updates user profile) does not document the error responses which can be sent by the method [validate_user_registration_request_data](https://github.com/anitab-org/mentorship-backend/blob/1643e7e3f987aa418fb6477646fe685871eec8bf/app/api/validations/user.py#L33)

Although it should be noted that the method validate_user_registration_request_data is never called from /user(updates user profile). The /user(updates user profile) calls [validate_update_profile_request_data](https://github.com/anitab-org/mentorship-backend/blob/1643e7e3f987aa418fb6477646fe685871eec8bf/app/api/validations/user.py#L107) which does not do above checks and hence cannot return those errors. 

I have worked on updating the error response documentation to match the code for update_user_profile and register [here](https://github.com/msklarek/mentorship-backend/pull/3/files)

I still need to test for which I am waiting for some help on how to login into local mode without email verification. I have asked for this on Zulip just now. 

Happy Thanksgiving! :)

**Comment by devkapilbansal** [comment]
@msklarek just updated the comment. I saw that I link different lines above

**Comment by msklarek** [comment]
https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/Questions/near/218050274

**Comment by msklarek** [comment]
Update: I will be working further on this tomorrow. Thanks.

**Comment by msklarek** [comment]
Update: Opened a PR. Please help review.

**Comment by tichnas** [comment]
@msklarek Are you working on the merge conflicts in your PR?
If not, can I please work on this issue? @isabelcosta
