### ISSUE TITLE
Registration happens when name, username and password are empty

### ISSUE THREAD

**Issue by sviho** [anitab-org/mentorship-backend#93]
**Describe the bug**
The program doesn't return any error even though I don't fill in name, username and password. Registration also happens if only one of them is empty.

Related to issue #86 

**To Reproduce**
1. Go to /register
2. Set password to ""
3. Set username to ""
4. Set name to ""

**Expected behavior**
There should be an error saying that password/username/name is invalid

**Actual behavior**
User was created successfully. A confirmation email has been sent via email. After confirming your email you can login.

**Comment by isabelcosta** [comment]
Very interesting and valid test @sviho ! Thank you! That is a major bug. I'll create an issue to solve this, if you feel you can work on this tell me, otherwise I will fix this :)
