### ISSUE TITLE
Refresh Endpoint should mention Refresh token instead of access token

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#932]
**Describe the bug**

In refresh endpoint (to get new access token), it is mentioned to use in the `Authorization` field's input description, an access token, but it should mention refresh token.

**To Reproduce**

1. Go to 'Users' Section
2. Scroll down to refresh endpoint
3. See access token mentioned there instead of refresh token

**Expected behavior**

API endpoint should mention refresh token instead

**Screenshots**

![refresher](https://user-images.githubusercontent.com/42766576/100550531-9cb20280-32a0-11eb-9ff7-5663c68d31b8.png)

**Comment by JadeHayes** [comment]
Hello 👋 , if this issue is still available I'd love to work on this.

**Comment by devkapilbansal** [comment]
@JadeHayes You can ping someone on [zulip](https://anitab-org.zulipchat.com/) to assign this issue to you.

**Comment by tichnas** [comment]
Hi @devkapilbansal I'd love to work on this issue, can I please be assigned?
Thanks :)

**Comment by vj-codes** [comment]
@JadeHayes hey would you still like to work on this ?
@tichnas If there's no reply I'll assign it to you :)

**Comment by vj-codes** [comment]
Assigning you @tichnas 
Happy coding!

**Comment by tichnas** [comment]
Thanks @vj-codes for assigning me the issue.
I have a potential solution which I've pushed to my fork. Can you please take a look to make sure what I did is correct? Or should I open a PR directly?

**Comment by devkapilbansal** [comment]
@tichnas I was just looking to your fork. I will check if it is fine today. Although it would be better if you open a Work in Progress PR so that others may know about the work and can give their useful review

**Comment by tichnas** [comment]
@devkapilbansal I've opened a draft PR.

Can you please guide me on what exactly `Update Swagger documentation and the exported file at /docs folder` means? I've updated the swagger but have no idea about exporting it.

Thanks

**Comment by devkapilbansal** [comment]
@tichnas the `docs` folder contains some `manual_tests` too which needs to be updated.
In this [file](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/manual_tests/user_refresh_token.md) you can see that the screenshots too mention `access token` instead of refresh token which is incorrect, and you need to update that images too

**Comment by tichnas** [comment]
@devkapilbansal Ok, thanks for the nice explanation. I'll update the screenshots asap and will let you know.
