### ISSUE TITLE
Feature/bug: Decreasing the expiry time for access tokens. 

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#933]
**Is your feature request related to a problem? Please describe.**

The access tokens have an expiry set to one week. 

**Describe the solution you'd like**

Reduce the time to somewhere around 10 mins.

**Additional context**

This will ensure that even in the case where an access token is compromised it may be used only for a short period of time before it expires.

**Comment by devkapilbansal** [comment]
@epicadk probably expiry time is increased here only for testing purpose.

**Comment by epicadk** [comment]
> @epicadk probably expiry time is increased here only for testing purpose.

I spoke to @isabelcosta and that's not the case.

**Comment by marianayap** [comment]
@isabelcosta @epicadk Hello! is someone working in this bug?

**Comment by devkapilbansal** [comment]
@marianayap consider asking it on [zulip](https://anitab-org.zulipchat.com/)

**Comment by isabelcosta** [comment]
Ok, so thank you @epicadk and @vj-codes for your input at the Mentorship System sync up session! I now understand why this is an issue :) I will make it available then.

**Comment by isabelcosta** [comment]
@marianayap no one is working on this and this was now validated, do you still want to work on this?

**Comment by epicadk** [comment]
> @marianayap no one is working on this and this was now validated, do you still want to work on this?

I think we can also add first timers only.

**Comment by Debanitrkl** [comment]
@epicadk could I work on this issue

**Comment by devkapilbansal** [comment]
@Debanitrkl you already made a pull request. As this issue is `first timers only` we can't assign this issue to you. However you can look for other issues.

**Comment by kartikeysaran** [comment]
I would like to work on this issue

**Comment by epicadk** [comment]
@kartikeysaran just to make sure. Is this your first contribution on this repository?

**Comment by kartikeysaran** [comment]
Not made any contributions yet in this repo

**Comment by devkapilbansal** [comment]
@kartikeysaran assigning you. 👍

**Comment by epicadk** [comment]
@kartikeysaran any updates here?

**Comment by kartikeysaran** [comment]
> @kartikeysaran any updates here?
Sorry, was busy with other issues will work on this

**Comment by b-thebest** [comment]
@isabelcosta Can I work on this issue?

**Comment by kartikeysaran** [comment]
> @isabelcosta Can I work on this issue?

I am busy with other issues you can work on this ! 🍻 @b-thebest

**Comment by devkapilbansal** [comment]
> @isabelcosta Can I work on this issue?

Sure @b-thebest assigning you 👍

**Comment by b-thebest** [comment]
Do we need to limit expiry time of refresh token also ?

**Comment by epicadk** [comment]
> Do we need to limit expiry time of refresh token also ?

No.

**Comment by epicadk** [comment]
Unassigning @b-thebest as this is marked first timers only.

**Comment by devkapilbansal** [comment]
> Unassigning @b-thebest as this is marked first timers only.

Ohh, I didn't noticed that he already made a PR. Thanks for this @epicadk

**Comment by b-thebest** [comment]
Okay, no Worries, I will try to contribute other issues.

Thanks

**Comment by HeroicHitesh** [comment]
@epicadk @isabelcosta @devkapilbansal I would like to work on this

**Comment by epicadk** [comment]
> @epicadk @isabelcosta @devkapilbansal I would like to work on this

Would this be your first contribution to this repository?

**Comment by HeroicHitesh** [comment]
Yes @epicadk

**Comment by epicadk** [comment]
> Yes @epicadk

Assigning you. Happy coding : ).
