### ISSUE TITLE
Feat : Fix delete endpoint

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#934]
**Is your feature request related to a problem? Please describe.**

Currently User data like relations is not delete when a user deletes their account.

**Describe the solution you'd like**

User data should be deleted when they delete their account or can be replaced with some value that suggests the account was deleted.

**Additional context**

Alter tables

**Comment by marianayap** [comment]
Hello! Do you want the the whole user information to be deleted or just some information in specific and if that's the case which information should be deleted?

**Comment by epicadk** [comment]
> Hello! Do you want the the whole user information to be deleted or just some information in specific and if that's the case which information should be deleted?

I think everything should be deleted.

**Comment by marianayap** [comment]
@sanchibansal340 Hello! I'll like to work on this issue

**Comment by marianayap** [comment]
@isabelcosta Hello! I'm currently working on this issue, but I have some questions to continue. I enrolled in Zulip, but I don't have a clear in which channel to ask about this issue and tokens.

**Comment by gaurivn** [comment]
Hi @marianayap, you can ask questions pertaining to mentorship-backend [here](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/mentorship-backend).

**Comment by gaurivn** [comment]
> @isabelcosta Hello! I'm currently working on this issue, but I have some questions to continue. I enrolled in Zulip, but I don't have a clear in which channel to ask about this issue and tokens.

This issue is not yet approved and made available, for now, pls look for issues labeled available.

**Comment by marianayap** [comment]
> > @isabelcosta Hello! I'm currently working on this issue, but I have some questions to continue. I enrolled in Zulip, but I don't have a clear in which channel to ask about this issue and tokens.
> 
> This issue is not yet approved and made available, for now, pls look for issues labeled available.

Thank you!
