### ISSUE TITLE
Bug:Use HTTPStatus code values instead  of enum representation, in mentorship_relation API in Swagger UI

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/mentorship-backend#939]
**Describe the bug**

The values shown on Swagger UI of mentorship_relation API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK. 

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Scroll down to ```mentorship_relation```
3. See enum representation.
4. 
![image](https://user-images.githubusercontent.com/11148726/102997312-b1d72580-451c-11eb-8750-842078e7ff17.png)

**Expected behavior**
Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+
 - Browser FireFox Web Browser
 - Version --

**Comment by Aaishpra** [comment]
@isabelcosta can you have a look at the issue and assign this to me?
Thanks.

**Comment by isabelcosta** [comment]
Sounds good, I will assign it to you @Aaishpra

**Comment by Aaishpra** [comment]
> Sounds good, I will assign it to you @Aaishpra 

Thanks, will start working on this as soon as i setup the project 😄

**Comment by isabelcosta** [comment]
To enhance your issue, I added a screenshot of how it shows up now with enum representation

**Comment by Aaishpra** [comment]
> To enhance your issue, I added a screenshot of how it shows up now with enum representation

Thanks a lot 😊

**Comment by Aaishpra** [comment]
@isabelcosta @devkapilbansal @vj-codes I have some doubts, regarding how to proceed further in this issue. Since the swagger.json file was deleted by #804, I managed to find two links to find the swagger.json [this](http://mentorship-backend-temp.herokuapp.com/swagger.json) and after setting up the project locally [this](http://127.0.0.1:5000/swagger.json) after that I tried to save the swagger.json file (found from the link after local setup) under the docs section and editing it but nothing happens.
For example
If I edit something in mentorship_relation.py 
![image](https://user-images.githubusercontent.com/66299533/103076720-642dec00-45f4-11eb-9067-0f319a243e10.png)
I see a change on my local server
![image](https://user-images.githubusercontent.com/66299533/103076760-7b6cd980-45f4-11eb-8526-4c8c7e67f5f9.png)
But nothing happens if I change anything in swagger.json

This is my first time working with Swagger, so I might be completely wrong with my approaches. Can you people help me with this?

**Comment by Aaishpra** [comment]
Another thing, after some research I found [this](https://editor.swagger.io/) editor and copied the swagger.json there, editing here I can see the changes. But  I am still, not sure if this is the correct way to edit a swagger.
Or how can I save and push my changes after I finish editing in that editor?

**Comment by devkapilbansal** [comment]
@Aaishpra you should look into mentorship.py file
There you can see that it is returning HTTPStatus.Ok but it should return something like `HTTPStatus.OK.value`. To get better idea look into the existing PRs on hard coded status codes
Some of them are #924 #860

**Comment by Aaishpra** [comment]
> @Aaishpra you should look into mentorship.py file
> There you can see that it is returning HTTPStatus.Ok but it should return something like `HTTPStatus.OK.value`. To get better idea look into the existing PRs on hard coded status codes
> Some of them are #924 #860 

Ohh now i get it, so we have to make changes in mentorship_relation.py file only.
Not in the swagger.json

**Comment by devkapilbansal** [comment]
Yes, you need to make changes in UI only
Cc:- @isabelcosta

**Comment by Aaishpra** [comment]
@devkapilbansal @isabelcosta i changed all the ```HTTPStatus.x``` to ```HTTPStatus.x.value``` in mentorship_relation.py and I think this has worked correctly 
![image](https://user-images.githubusercontent.com/66299533/103087557-df4fcc00-460d-11eb-911e-ac1826f4fdc4.png)
Shall I submit PR if this looks right to you people?

**Comment by devkapilbansal** [comment]
@Aaishpra please open issues for other files too

**Comment by isabelcosta** [comment]
> @devkapilbansal @isabelcosta i changed all the `HTTPStatus.x` to `HTTPStatus.x.value` in mentorship_relation.py and I think this has worked correctly
> ![image](https://user-images.githubusercontent.com/66299533/103087557-df4fcc00-460d-11eb-911e-ac1826f4fdc4.png)
> Shall I submit PR if this looks right to you people?

@Aaishpra it looks nice :)
if you could do what @devkapilbansal said as well, that would be great 🙌

**Comment by Aaishpra** [comment]
Sure, I will open the issues for user and admin api @devkapilbansal @isabelcosta

**Comment by Aaishpra** [comment]
> > @devkapilbansal @isabelcosta i changed all the `HTTPStatus.x` to `HTTPStatus.x.value` in mentorship_relation.py and I think this has worked correctly
> > ![image](https://user-images.githubusercontent.com/66299533/103087557-df4fcc00-460d-11eb-911e-ac1826f4fdc4.png)
> > Shall I submit PR if this looks right to you people?
> 
> @Aaishpra it looks nice :)
> if you could do what @devkapilbansal said as well, that would be great raised_hands

Thanks.
