### ISSUE TITLE
Use HTTPStatus code values instead of enum representation, in Admins API in Swagger UI

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/mentorship-backend#946]
**Describe the bug**

The values shown on Swagger UI of Admins API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK.

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Click on Admins API
3. See enum representation
![image](https://user-images.githubusercontent.com/66299533/103191119-ad828200-48f9-11eb-86ab-dd9a369704f4.png)

**Expected behavior**
Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**

 

-    OS: Ubuntu 20+

  

-   Browser: Firefox Web Browser

   

-  Version --

**Additional context**
Similar to #939

**Comment by aakankshaagr** [comment]
Heyy @isabelcosta @Aaishpra Can you assign this issue to me? I would like to work on this issue. I have seen similar issues and I am confident l can  solve it.

**Comment by Aaishpra** [comment]
> Heyy @isabelcosta @Aaishpra Can you assign this issue to me? I would like to work on this issue. I have seen similar issues and I am confident l can  solve it.

You can ask on zulip someone might assign you.
As for me I don't have the authority to assign issues here.

**Comment by vj-codes** [comment]
Assigning you @aakankshaagr and welcome to the community!
Happy coding!

**Comment by aakankshaagr** [comment]
> 
> You can ask on zulip someone might assign you.
> As for me I don't have the authority to assign issues here.

Thank you @Aaishpra for guidance.

I can see these changes on my local server
Changes in (/admin​/new) section of admin
![task3](https://user-images.githubusercontent.com/71868375/103478823-54ca5200-4def-11eb-8f29-8086a9abc28c.jpg)

Changes in (/admin​/remove) section of admin
![task2](https://user-images.githubusercontent.com/71868375/103478839-6ca1d600-4def-11eb-8876-d912cd4f5a56.jpg)

@isabelcosta @Aaishpra I changed all the `HTTPStatus.x` to `HTTPStatus.x.value` in admin.py (api\resources\admin.py) and I think this has worked correctly. Shall I submit PR if this is correct??

**Comment by vj-codes** [comment]
@aakankshaagr you can submit a PR for review

**Comment by lavanaythakral** [comment]
Hi, Is this still open?

**Comment by Aaishpra** [comment]
> Thank you @Aaishpra for guidance.
> 
> I can see these changes on my local server
> Changes in (/admin​/new) section of admin
> ![task3](https://user-images.githubusercontent.com/71868375/103478823-54ca5200-4def-11eb-8f29-8086a9abc28c.jpg)
> 
> Changes in (/admin​/remove) section of admin
> ![task2](https://user-images.githubusercontent.com/71868375/103478839-6ca1d600-4def-11eb-8876-d912cd4f5a56.jpg)
> 
> @isabelcosta @Aaishpra I changed all the `HTTPStatus.x` to `HTTPStatus.x.value` in admin.py (api\resources\admin.py) and I think this has worked correctly. Shall I submit PR if this is correct??

Looks nice to me 😄@aakankshaagr Just remember not to add .value in the code with return statement as the codecov test fails because of it. You can Checkout the discussion [here](https://github.com/anitab-org/mentorship-backend/pull/952#discussion_r549875920)

**Comment by Aaishpra** [comment]
> Hi, Is this still open?

@lavanaythakral the issue has already been assigned to @aakankshaagr. You can check out  other issues :)

**Comment by anushka17agarwal** [comment]
Is this issue still open? I'd like to contribute to this.

**Comment by Aaishpra** [comment]
@isabelcosta the issue has already been solved by #956 but not closed (as the assignee did not mention the issue number in the PR correctly, so the PR has been merged but this issue is still open).

So, please close this, as it's creating confusion for newcomers.

**Comment by Aaishpra** [comment]
> Is this issue still open? I'd like to contribute to this.

This issue has been solved already, you can look for other issues.
Thanks

**Comment by vj-codes** [comment]
Closing the issue as PR has been merged as mentioned above. 
Thank you @Aaishpra for creating this issue xD 🚀
