### ISSUE TITLE
Use HTTPStatus code values instead of enum representation, in Users API in Swagger UI

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/mentorship-backend#947]
**Describe the bug**

The values shown on Swagger UI of Users API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK.

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Scroll down to Users API
3. See enum representation.
![image](https://user-images.githubusercontent.com/66299533/103191627-a8263700-48fb-11eb-9e00-c0576444777b.png)

**Expected behavior**

Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+ 
 - Browser: Firefox Web Browser
 - Version: --

**Comment by surbhigoel191** [comment]
Kindly assign this issue to me.

**Comment by isabelcosta** [comment]
Hi @surbhigoel191 sure :)

**Comment by isabelcosta** [comment]
@surbhigoel191 I will unassign until you solve the other issue you were assigned to :) #948
