### ISSUE TITLE
Update Readme.md with the instructions for running unittests

### ISSUE THREAD

**Issue by surbhigoel191** [anitab-org/mentorship-backend#954]
## Description
Mention commands for running the python unittests (missing '-v' tag as of now) along with installing and creating codecov report in the terminal.

### Update [Required]
- [ ] Correct commands for all the tasks.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by vj-codes** [comment]
@surbhigoel191 the command for running unittests is already present in readme and works good , can you share a resource as to why `-v tag` should be added in command ?

**Comment by surbhigoel191** [comment]
> @surbhigoel191 the command for running unittests is already present in readme and works good , can you share a resource as to why `-v tag` should be added in command ?

On adding -v tag it will be clearly visible which function of which file is running and giving the error. I found it useful so thought of adding it :)

**Comment by vj-codes** [comment]
@devkapilbansal what do you think about the validity of this issue ? 👀

**Comment by devkapilbansal** [comment]
@surbhigoel191 why should we know which function is running? If any test gives error then it is printed on console. Adding `-v` is irrelevant and it just increase noise. I would rather prefer to decrease the output printed.

**Comment by vj-codes** [comment]
@surbhigoel191 as discussed above by all , this issue is not really needed right now and will be closed .
Thank you for creating the issue :)
