### ISSUE TITLE
create CONTRIBUTING.md

### ISSUE THREAD

**Issue by ghost** [anitab-org/mentorship-backend#955]
**Is your feature request related to a problem? Please describe.**
It maybe difficult for beginners to figure out what to do so a clear guide will certainly be helpful.

**Describe the solution you'd like**
Add CONTRIBUTING.md describing  clearly what to do to contribute to open source.

**Describe alternatives you've considered**
The file can be like https://github.com/Tejas1510/Athavani/blob/master/CONTRIBUTING.md

**Additional context**

**Comment by diananova** [comment]
I think it already exists. Here: https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md. There's also a section Contributing in the README.

**Comment by ghost** [comment]
Ok sorry i missed it i am closing this issue.
