### ISSUE TITLE
Use HTTPStatus instead of hard-coded values in tests/users

### ISSUE THREAD

**Issue by tichnas** [anitab-org/mentorship-backend#957]
## Description
As a developer,
I need to avoid using hard-coded values wherever possible,
so that I can make code more readable and scalable.

### Update [Required]
- [ ] Use `HTTPStatus` instead of hard-coded response status codes (like in the API) in `tests/users`
 ## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by tichnas** [comment]
@isabelcosta Please review/accept this issue. Thanks

**Comment by isabelcosta** [comment]
@tichnas could you please follow one of the issue templates provided https://github.com/anitab-org/mentorship-backend/tree/develop/.github/ISSUE_TEMPLATE?
I would recommend the user-story one.

**Comment by tichnas** [comment]
@isabelcosta Sorry for the inconvenience, I was confused between which template to use.
I've updated the description, can you please check it once again? Thanks

**Comment by sankha555** [comment]
@isabelcosta @tichnas can I please work on this issue?  I can make a patch replacing all the hardcoded error codes with their corresponding HTTPStatus.response values if you could please assign it to me. Thanks!

**Comment by tichnas** [comment]
Hi @sankha555, thanks for your interest in the issue. I think this issue is simple, so why not keep it as the first-time issue to help newcomers get started? What do you suggest @isabelcosta?

**Comment by isabelcosta** [comment]
@tichnas this could be done in small PRs to avoid enormous PRs. So we could do this issue about one of the tests folders. For example, one issue could be about doing this for `tests/tasks` folder, and another issue for `tests/users`.

Could you make this issue about one of the folders please (by editing title and description)? Then If you can feel free to create the other issues or ask ion Zulip and other people can also do that (no need to be all you 😅 ). With that, we could make some only for first timers and other available to anyone 🤔 you are right that this would be nice for newcomers for sure.

What do you think @tichnas @vj-codes ?

**Comment by vj-codes** [comment]
@isabelcosta yes I agree :) 
@tichnas please spilt this issue with either tasks or users subpart and let us know if you are availableto create the other similarly or not

**Comment by vj-codes** [comment]
@tichnas hey since there was no update , the issues for other folder are created , can you please edit the description of this issue to `test/users` folder ?
Thank you for creating the issue :)

**Comment by tichnas** [comment]
@vj-codes Sorry, I got very busy in the last week and could not take out time.

**Comment by aakankshaagr** [comment]
@vj-codes  Can I take this issue?

**Comment by vj-codes** [comment]
Assigning you @aakankshaagr 
Happy documenting!

**Comment by vj-codes** [comment]
@aakankshaagr any updates?

**Comment by aakankshaagr** [comment]
@vj-codes  Sorry, I got very busy in  the last week due to health issues and  couldn't take out time. I am almost done. I will  submit it by tomorrow for sure

**Comment by vj-codes** [comment]
@aakankshaagr hey no problem , just remember to update your progress after every 3 days if it's taking long:)

**Comment by aakankshaagr** [comment]
I can see these changes on my local server.
@vj-codes @tichnas  I think this has worked correctly. Shall I submit PR if this is correct??
changes in POST/login (Login [user)

![tas2](https://user-images.githubusercontent.com/71868375/106356903-db0f8080-6328-11eb-9741-1665552797dd.jpg)

![task2](https://user-images.githubusercontent.com/71868375/106356893-cd59fb00-6328-11eb-8e61-cbda65c1af27.jpg)

**Comment by vj-codes** [comment]
@aakankshaagr you can create a PR , that'll be the best way to review instead of creating a new thread in comments !

**Comment by aakankshaagr** [comment]
There is an error in  **`tests\mentorship_relation\test_dao_creation.py`** which I got while running `python -m unittest discover tests` command.
I don't know why tests are failing and I don't know how to solve that. @vj-codes can you please guide me how to solve this problem?

**Comment by aakankshaagr** [comment]
I don't know how but all tests are passed now and I guess even that error in `tests\mentorship_relation\test_dao_creation.py` isn't there now.
