### ISSUE TITLE
Information in put /user can be updated to " "

### ISSUE THREAD

**Issue by sviho** [anitab-org/mentorship-backend#96]
**Describe the bug**
Everything in PUT /user can be set to " ", including username and name, which might be dangerous

**To Reproduce**
1. Go to put /user to update user's information
2. Set all the strings to " "
3. See "message": "User was updated successfully"
4. Go to get /user
5. See that everything is set to " "

**Expected behavior**
An error saying that a certain length of string is expected and a string can't be set to " "

**Actual behavior**
User was profile was updated successfully and now error message was returned.

**Comment by isabelcosta** [comment]
@sviho I updated the description of the issue to have the actual behavior and the "related to issue X" I understand there isn't any issue regarding updating the profile, so you can leave it out. I'll create the issue to solve this!

**Comment by isabelcosta** [comment]
Now that I checked the created user I see that you not only used an empty string but used empty string with length > 1. This is a mini bug that also needs to be fixed by stripping the string data. Very nice catch @sviho !

```
{
    "id": 1,
    "username": "  ",
    "name": "  ",
    "slack_username": " ",
    "bio": " ",
    "location": " ",
    "occupation": " ",
    "organization": " ",
    "interests": " ",
    "skills": " ",
    "need_mentoring": true,
    "available_to_mentor": true
  }
```
