### ISSUE TITLE
Use HTTPStatus instead of hardcoded values in tests/admin

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#966]
## Description
As a developer,
I need to avoid using hard-coded values wherever possible,
so that I can make code more readable and scalable.

### Update [Required]
- [ ]  Use HTTPStatus instead of hard-coded response status codes (like in the API) in` tests/admin`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by chinmaym07** [comment]
Hey @vj-codes can I try this issue .?

**Comment by chinmaym07** [comment]
Hey @vj-codes can I try this issue .?
```python
self.assertEqual(200, actual_response.status_code)
```
I think I need to change these values  .?

**Comment by vj-codes** [comment]
Assigning you @chinmaym07 
Happy coding !
And yes you need to change those values:)
