### ISSUE TITLE
Use HTTPStatus instead of hard-coded values in tests/mentorship_relation

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#967]
## Description
As a developer,
I need to avoid using hard-coded values wherever possible,
so that I can make code more readable and scalable.

### Update [Required]
- [ ] Use HTTPStatus instead of hard-coded response status codes (like in the API) in `tests/mentorship_relation`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by jalajcodes** [comment]
@vj-codes Hi there! Can you assign it to me?

**Comment by vj-codes** [comment]
Assigning you @jalajcodes 
Happy coding!
