### ISSUE TITLE
Use HTTPStatus instead of hardcoded values in tests/task_comments

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#968]
## Description
As a developer,
I need to avoid using hard-coded values wherever possible,
so that I can make code more readable and scalable.

### Update [Required]
- [ ] Use HTTPStatus instead of hard-coded response status codes (like in the API) in `tests/task_comments`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by cypherean** [comment]
Hello!
Can I take this issue?

**Comment by vj-codes** [comment]
Assigning you @cypherean 
Happy coding!
