### ISSUE TITLE
Use HTTPStatus instead of hardcoded values in tests/tasks and tests/user_journey

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#969]
## Description
As a developer,
I need to avoid using hard-coded values wherever possible,
so that I can make code more readable and scalable.

### Update [Required]
- [ ] Use HTTPStatus instead of hard-coded response status codes (like in the API) in `tests/tasks` and `tests/user_journey`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by chinmaym07** [comment]
Hey @vj-codes as this issue is available . Can I work upon this .?

**Comment by sankha555** [comment]
@vj-codes, may I take this up if it's open for contribution?

**Comment by vj-codes** [comment]
Assigning you @sankha555 
Happy documenting!
