### ISSUE TITLE
Create function to validate PUT /user request body data

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#97]
## Description
As a developer,
I need restrict character limit on fields that can be updated,
so that I can protect the backend from trying to save invalid data.

Solves bug reported on issue #96 

### Update
- [x] Add a validation function to app/api/validations/user.py file
- [x] Add tests to prove that the validation function is working properly. The test file can be called `test_validation_update_profile.py` inside folder  ` tests/users`
- [x] Use this validation function in `MyUserProfile` class, funtion `put()` from file `app/api/resources/user.py` to validate the request data sent by the client is being verified
- [x] **Warning!** make sure to strip strings before checking for the length!! fix this in the registration validation and add tests!

## Definition of Done
- [x] All of the required items are completed.
- [x] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by isabelcosta** [comment]
@sviho do you want to take on this issue and try to solve this? You can see in the **Update** section what you need to do. If you feel comfortable with python and this issue let me know, otherwise I can take of this.

**Comment by Dilu9218** [comment]
@isabelcosta you can do it. approved.
