### ISSUE TITLE
Add Bridge in Tech in Readme as a front end project using this api

### ISSUE THREAD

**Issue by Ayush23Dash** [anitab-org/mentorship-backend#973]
## Description
As a visitor,
I need to know that this API is also used by Bridge in Tech,
apart from mentorship apps.

## Mocks

![Mentorship](https://user-images.githubusercontent.com/40827680/104732865-d57c3d00-5763-11eb-872a-64c9f8402b37.png)

### Update [Required]
- [ ] Update Readme

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by Ayush23Dash** [comment]
@vj-codes , can you please check it out, I was setting up Bridge in Tech, and I found it to be a genuine concern. Moreover I would like to send a PR for this as my first PR in the org.

**Comment by vj-codes** [comment]
@Ayush23Dash hey thank you for creating the issue :tada
However, the frontend mentioned in readme are the ones using all APIs , in short this is the backend of Android iOS and flutter of mentorship system app. 
Bridge in tech partially uses the API, so I don't think it will be appropriate to mention it in frontend section also considering it is not completely implemented yet. 
What do you think?

**Comment by Ayush23Dash** [comment]
@vj-codes I get what you are trying to say, but when I was setting up Bridge in Tech, and I came to this repository , I was a bit confused on whether I am on the correct repo or not. 
If you say, instead of adding it directly beneath the mobile applications, we could add a new line that says ,that it is being partially used by BIT also. I think this could make a better experience for new guys setting up BIT. What say?

**Comment by vj-codes** [comment]
Closing the issue as discussed in BIT open session.
