### ISSUE TITLE
Bug : Threshold is initialized inside the for loop

### ISSUE THREAD

**Issue by epicadk** [anitab-org/mentorship-backend#978]
**Describe the bug**

Threshold is initialized multiple times.

**To Reproduce**

1. Go to https://github.com/anitab-org/mentorship-backend/blob/fffb4c39027b042f392d4edf0bb462e522cb7320/app/schedulers/delete_unverified_users_cron_job.py#L24

**Expected behavior**

Threshold can be initialized outside the for loop. 

**Additional context**

It would improve the performance.

**Comment by epicadk** [comment]
Can I work on this.

**Comment by epicadk** [comment]
@devkapilbansal can you confirm this.

**Comment by devkapilbansal** [comment]
Valid issue :heavy_check_mark:

**Comment by Aayush-hub** [comment]
@devkapilbansal @epicadk Can I work on this?

**Comment by epicadk** [comment]
@Aayush-hub Assigning you , Good luck : ).

**Comment by isabelcosta** [comment]
awesome leaders work here @devkapilbansal @epicadk 👏🏾
