### ISSUE TITLE
Password length to be checked when changing password as well

### ISSUE THREAD

**Issue by sammy1997** [anitab-org/mentorship-backend#98]
**Describe the bug**
The check on the length of the password is there while signing up but not for changing the password.

Related to Quality Assurance issue #101 

**To Reproduce**
1. Go to http://systers-mentorship-dev.eu-central-1.elasticbeanstalk.com/
2. Create your user by registering at /register
3. Try to change the password with another one which has a length lesser than 8
4. It get's changed

**Expected behavior**
It should have returned an error saying the min length of a password is 8.

**Screenshots**
-N.A.-

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Comment by isabelcosta** [comment]
Nice catch @sammy1997 ! I'll create an issue to solve this!
