### ISSUE TITLE
Problem in Readme Setup instructions for bash instructions

### ISSUE THREAD

**Issue by Ayush23Dash** [anitab-org/mentorship-backend#981]
**Describe the bug**

The setup instructions in the readme file for Git bash users has an error.

**To Reproduce**
The steps to activate the virtual environment for Git Bash users says:
`source /venv/Scripts/activate`

**Expected behavior**
The given command should activate the virtual environment, however it doesn't do so.

**Screenshots**
![mentorshipReadmeError](https://user-images.githubusercontent.com/40827680/105349531-dacc0280-5c0f-11eb-9bc6-bd1a48081818.png)

**Desktop (please complete the following information):**
 - OS: [Windows]

**Additional context**
I would like to add a PR for the correct command

**Comment by Ayush23Dash** [comment]
@vj-codes , can I submit a PR to resolve this?

**Comment by techno-disaster** [comment]
Looks like we missed a dot there. Assigning it to you @Ayush23Dash
