### ISSUE TITLE
Tests: Cover all tests in task_comments.py

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#989]
## Description
Some tests are missing in `app/api`dao/task_comments.py` file. Cover those to ensure any new change will not break existing changes.

## Test Cases
The test cases that should be cover are:-
- Unaccepted stale relation
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/task_comment.py#L21

- Task comment does not exist

https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/task_comment.py#L210

## Definition of Done
- [ ] At least one test case tested.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by devkapilbansal** [comment]
@isabelcosta please label this issue. Also, it would be better if this issue is made `first-timers-only` :thinking:

**Comment by isabelcosta** [comment]
Sounds good @devkapilbansal ! Thank you for thinking of `first timers only` issues 🙌 💯

**Comment by Carlos1729** [comment]
I would Like to work on this issue

**Comment by ashwinijha6** [comment]
Hey @devkapilbansal could I take up this issue.

**Comment by vj-codes** [comment]
Assigning you @GenRok1729 
Happy coding !
@ashwinijha6 you cannot be assigned as this a `first timers` only issue :)

**Comment by ashwinijha6** [comment]
> Assigning you @GenRok1729
> Happy coding !
> @ashwinijha6 you cannot be assigned as this a `first timers` only issue :)

ok @vj-codes

**Comment by devkapilbansal** [comment]
@GenRok1729 are you working on this??

**Comment by vj-codes** [comment]
@GenRok1729 hey any updates?

**Comment by devkapilbansal** [comment]
@vj-codes may be @GenRok1729 is not interested in this anymore. You should make this issue available again

**Comment by isabelcosta** [comment]
Thank you @devkapilbansal @vj-codes for helping to triage this issue 🙌🏾 You are soooo helpful 💯

**Comment by PratibhaShrivastav** [comment]
Hi! I would like to work on this issue

**Comment by devkapilbansal** [comment]
Sure @PratibhaShrivastav assigning you

**Comment by PratibhaShrivastav** [comment]
Hi @devkapilbansal, looks like the tests for ``Task comment does not exist`` are already present. I have added tests for ``Unaccepted stale relation`` and created a PR
