### ISSUE TITLE
Add validation to Change Password API request data

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/mentorship-backend#99]
## Description
As a developer,
I need password validation to be the same as in POST /register,
so that I can avoid users violating business rules.

Solves issue #98 

### Update
- [x] Add a validation function to app/api/validations/user.py file
- [x] Add tests to prove that the validation function is working properly. The test file can be called `test_validation_change_password.py` inside folder  ` tests/users`
- [x] Use this validation function in `ChangePassword` class, funtion `put()` from file `app/api/resources/user.py` to validate the request data sent by the client is being verified
- [x] **Warning!** make sure to strip strings before checking for the length!! fix this in the registration validation and add tests!

## Definition of Done
- [x] All of the required items are completed.
- [x] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Dilu9218** [comment]
approved

**Comment by isabelcosta** [comment]
I solved an issue similar to this in PR https://github.com/systers/mentorship-backend/pull/95

**Comment by isabelcosta** [comment]
@sammy1997 do you want to be assigned to this issue?

**Comment by sammy1997** [comment]
Yes sure @isabelcosta
