### ISSUE TITLE
Tests: Add missing tests in Mentorship Relation

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#990]
## Description
Some tests are missing in `app/api/dao/mentorship_relation.py` file. Cover those to ensure any new change will not break existing changes.

## Test Cases
The test cases that should be cover are:-
- Same id for relation
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L50

- Incorrect End Time
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L59

- Incorrect Mentor time
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L65

https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L68

- Mentor not available
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L77

- Mentee not available
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L86

- Uninvolve relation request
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L265-L268

## Definition of Done
- [ ] At least one test case tested.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by jalajcodes** [comment]
Are you working on it? If not, I'll take it. 😄

**Comment by devkapilbansal** [comment]
Are you a first timer?? If yes, ask this issue on zulip as this issue will be assigned to a `first-timer-only`

**Comment by devkapilbansal** [comment]
@isabelcosta @vj-codes please label this `first-timers-only` issue too

**Comment by jalajcodes** [comment]
> Are you a first timer?? If yes, ask this issue on zulip as this issue will be assigned to a `first-timer-only`

No I ain't and agreed, its a good issue for first timers.

**Comment by aakankshaagr** [comment]
I have generated 2 PRs  and I am still trying to understand codebase so I don't know if I come under first timers or not. I found this issue different from earlier issues I have worked on as they were very similar and this one is different and within my ability to solve. So, I really wanted to work on this issue. @vj-codes Can I work on it ?

**Comment by vj-codes** [comment]
@aakankshaagr hey no you cannot , this is for those who've never contributed to the repo before :)

**Comment by Sanika1999** [comment]
Hi @vj-codes I haven't contributed to this repo before can I work on this?

**Comment by Sanika1999** [comment]
Can someone guide me on how to get started with this. (I just realised I haven't worked on this before )

**Comment by devkapilbansal** [comment]
Sure @Sanika1999 
https://github.com/anitab-org/mentorship-backend/blob/2917a910ab34dd5b6f800e4eac08e8fa5ba3fa0f/app/api/dao/mentorship_relation.py#L50
For the case mentioned above, you will have to create a test in [mentorship test file](https://github.com/anitab-org/mentorship-backend/blob/develop/tests/mentorship_relation/test_dao_creation.py) and ensure it passed.

For help you can look at #988 (issue)  #989 (linked pr)

Hope it helps

**Comment by Sanika1999** [comment]
Thank you so much @devkapilbansal

**Comment by Sanika1999** [comment]
![image](https://user-images.githubusercontent.com/51399803/107731171-45f28b80-6d1b-11eb-9651-1f692e58122e.png)
Update - Created Test case for MENTOR_ID_SAME_AS_MENTEE_ID and tested it. Still working on the remaining test cases.

**Comment by vj-codes** [comment]
@Sanika1999 hey any updates with your progress?

**Comment by Sanika1999** [comment]
@vj-codes will complete this today or max tomorrow. Sorry took a bit long.

**Comment by Sanika1999** [comment]
Update- I am still working on this, I am still stuck on the 2nd test case for assigning time in the past, something keeps breaking. I have reached out about this on zulip and got some solutions will work on it and update again.

**Comment by devkapilbansal** [comment]
@Sanika1999 if you face difficulties, you can open a draft PR and keep working on it. This way other contributors will be able to help you too

**Comment by isabelcosta** [comment]
++1 to what @devkapilbansal said!
@Sanika1999 feel free to create the draft PR and we can suggest improvements on it

**Comment by Sanika1999** [comment]
Sure @isabelcosta and @devkapilbansal  will do that. Thanks

**Comment by Sanika1999** [comment]
I have created a draft pr for this and Iam constantly updating it. Please do check  Incorrect end time test case that is where Iam making some mistake. Thanks

**Comment by devkapilbansal** [comment]
> I have created a draft pr for this and Iam constantly updating it. Please do check Incorrect end time test case that is where Iam making some mistake. Thanks

Reviewed and asked for changes there.

P.S.:- Consider tagging me there once you made changes and needs any other help

**Comment by devkapilbansal** [comment]
Removing first timers only as it is an important issue.

@jalajcodes @aakankshaagr  are you interested in it?

**Comment by diananova** [comment]
Can I work on this?

**Comment by isabelcosta** [comment]
yes @diananova :)
