### ISSUE TITLE
Remove tests directory from test coverage

### ISSUE THREAD

**Issue by devkapilbansal** [anitab-org/mentorship-backend#993]
**Describe the bug**

At present, each directory and file is included in code coverage but tests directory should not be included there
https://github.com/anitab-org/mentorship-backend/blob/8f1906eb284cc7774cc7325a4fa519afa8a45f2a/.github/workflows/main.yml#L34

**Expected behavior**

Test directory should be excluded from the coverage

**Screenshots**

![qwe](https://user-images.githubusercontent.com/42766576/106648360-33a77d80-65b6-11eb-8f41-9c31401e7546.png)

**Comment by ashwinijha6** [comment]
Hey @devkapilbansal Can I take this up?
Also could you just let me know why the test directory should be excluded from the coverage?

**Comment by devkapilbansal** [comment]
Hi, @ashwinijha6 coverage is only calculated for the source code. Here all directories are included in report and hence sometimes gives wrong result when calculating coverage for the whole project.

**Comment by ashwinijha6** [comment]
ok I got your point @devkapilbansal

**Comment by isabelcosta** [comment]
I assume you don't want to work on this because you didn't mention it @devkapilbansal :)

Will assign to @ashwinijha6

**Comment by devkapilbansal** [comment]
Yes, it is an issue. Therefore anyone can work on it

**Comment by ashwinijha6** [comment]
@devkapilbansal I think the code coverage is not being calculated for the tests directory because when I run **coverage report** in the mentorship-backend directory it does not show me taking the tests directory into consideration but only app config & run
& then my venv files for which I got a total of 34%
![codecov](https://user-images.githubusercontent.com/45794450/107614965-53ebd200-6c71-11eb-9680-9d13acd38e5a.JPG)

**Comment by ashwinijha6** [comment]
Could u pls check with this also just let me know do u want to exclude the test directory from codecov ui then I'll have to make changes in codecov.yml

**Comment by devkapilbansal** [comment]
> @devkapilbansal I think the code coverage is not being calculated for the tests directory because when I run **coverage report** in the mentorship-backend directory it does not show me taking the tests directory into consideration but only app config & run
> & then my venv files for which I got a total of 34%
> ![codecov](https://user-images.githubusercontent.com/45794450/107614965-53ebd200-6c71-11eb-9680-9d13acd38e5a.JPG)

You have done something wrong for generating report. It is using venv too

**Comment by ashwinijha6** [comment]
ok I'll try without the venv & let u know

**Comment by ashwinijha6** [comment]
@devkapilbansal could you help me with a screenshot of your coverage report.

**Comment by ashwinijha6** [comment]
![test](https://user-images.githubusercontent.com/45794450/107881356-063dc680-6f0a-11eb-9eea-3c1880bf912d.JPG)
I got the correct coverage report I don't know how it was taking in the venv before

**Comment by vj-codes** [comment]
@ashwinijha6 any updates?

**Comment by ashwinijha6** [comment]
> @ashwinijha6 any updates?

Yes @vj-codes I'm working on it will try to make a pull request by tmr

**Comment by ashwinijha6** [comment]
@devkapilbansal I have created a  `.coveragerc`  which omits the `test/*` & on running the `coverage report`  I get 41% (as shown in the screenshot) but it takes in the virtual environment as well 
![venv1](https://user-images.githubusercontent.com/45794450/109323620-aa642d80-7879-11eb-8f99-56576b90d93c.JPG)

**Comment by devkapilbansal** [comment]
@ashwinijha6 create your virtualenv outside this directory. Go out of root directory and create virtualenv. Then cd in the directory and test the coverage.Also, you can omit `venv/*` too if you want

**Comment by ashwinijha6** [comment]
@devkapilbansal & @isabelcosta , could u'll pls review my pull request
