### ISSUE TITLE
Remove .elasticbeanstalk folder from the code

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/mentorship-backend#998]
**Is your feature request related to a problem? Please describe.**
Since the backend is now deployed on heroku , any references or files related to elastic beanstalk should be removed from the code

**Describe the solution you'd like**
Remove the folder and the config.yml file inside it.

**Comment by vj-codes** [comment]
@isabelcosta hey this can be a good first timers issue, what say?

**Comment by isabelcosta** [comment]
Yes :) I honestly do not know if we are using AWS any time soon. I will add the labels. thank you so much!

**Comment by Debanitrkl** [comment]
@isabelcosta I have just started exploring  this org and would like to take this issue and contribute

**Comment by vj-codes** [comment]
Assigning you @Debanitrkl 
Happy coding!
